### ISSUE TITLE
Default values for optional fields

### ISSUE THREAD

**Issue by eddieschoute** [lark-parser/lark#100]
Currently, an the optional presence of a token or rule will either appear or disappear from the parse tree. This makes transforming the tree unnecessarily difficult, because this has to be handled in a case-by-case basis.

## Example
Let us say we are defining some set of gates and optionally they could be inverted by appending a '*'
```
INVERSION   : "*" // Make sure the token does not get lost.
qgate       : "QGate[" string "]" INVERSION? "(" int ")" control_app
```
The parse tree would either include or not include the `INVERSION` token. To transform this to a nice format we can do the following
```python
    def qgate(self, t):
        if t[1] == "*":
            return QGate(name=t[0], inverted=True, wire=t[2], control=t[3])
        else:
            return QGate(name=t[0], inverted=False, wire=t[1], control=t[2])
```
but the process would be much simplified if one could assign a value to either case of the optional `?`.

## Example 2
Let us say we have a rule with two optional fields
```
foobar : foo? bar?
```
Now there are four possibilities this could parse to and it would require a fairly large if-elsif-else statement to transform to some standard class. In general the number of possibilities grows exponentially in the number of optional fields. And `Tree` children are only indexed by number instead of by some name such that each of these cases must be handled one-by-one so that you know how long the children list is and which items contains which child.

## Suggested change
Either allow the addition of a default or alternative value for the absence of the optional field, or add named parameters to the fields that would simplify transforming the tree (e.g. [Tatsu](https://github.com/neogeny/TatSu) has this possibility but it is very slow in parsing).

**Comment by erezsh** [comment]
I see your point, but I'm not sure how to add naming without making the syntax ugly. How does Tatsu handle it?

But regarding example 1, you could do:

    !inversion: "*"?       // ! means all tokens are preserved
    qgate       : "QGate[" string "]" inversion "(" int ")" control_app

    def qgate(self, t):
        return QGate(name=t[0], inverted=len(t[1]) > 0, wire=t[2], control=t[3])

**Comment by eddieschoute** [comment]
Let me expand on example two (foobar) to make clear how Tatsu handles it.

Let's say we want to write
```
foobar : "(" "foo"? "bar"? ")"
```
but keep the literals `foo` and `bar`. We could factor them out as in your example
```
!foo: "foo"?
!bar: "bar"?
foobar : "(" foo bar ")"
```
to create a consistent tree where the children are empty if either literal is missing. This does however, in the worst case, create an extra rule for each option. But what if `foo` and/or `bar` are rules (and not just one literal)?
```
foo: foo2 "literal" foo3 | foo1 "text" foo3
bar: "world" | "goodbye" etc
foobar : "(" foo? bar? ")"
```
It is hard for me to see how one could quickly refactor this to produce an empty tree node when either foo or bar is not matched.

Tatsu solved this by only keeping literals that are named, kind of like your aliases. In this example
```
foobar: "(" foo:["foo"] bar:["bar"] ")"
```
would parse to some dict-like object with a `foo` and `bar` key. E.g. `("foo")` would parse to `AST({'foo':'foo', 'bar': None})`.
Personally, I found that using named fields as indicators for what is retained was very intuitive.

**Comment by erezsh** [comment]
I agree that creating extra rules is not ideal. However, I don't like Tatsu's syntax either. Grammars are confusing enough, without adding names in the middle of rules.

Maybe a compromise could be to add a rule modifier, something like:

    @foobar: "(" foo? bar? TERM? ")"

Which will create a dictionary for foobar, with the keys "foo", "bar" and "TERM".

However, that still leaves three questions:

1) How to provide the dictionary in the transformer? Will it replace the list?

2) What about expanding rules (e.g. `foo ".." _bar`)?  Do we keep them and use their name? Or put them into a neutral key, such as "@"?

3) What about lists (i.e. `foo+  bar*`) and repetitive rules (i.e. `foo foo`)?.

So to put it all together, perhaps:

    @foobar: "(" foo? bar+ _bla TERM ")"

Will become

    {"foo": .., "bar": [ ... ], "@": ["bla1", "bla2"], "TERM": ...}

Any thoughts?

**Comment by eddieschoute** [comment]
I think automatically naming results will create conflicts (name repetition). If lark were to simply inline `_bar` then this might also introduce new conflicts in the local rule (e.g. if you have 2 `_bla`). So it would be necessary to find a way to disambiguate the name conflicts.
Furthermore what happens if you have `foo 'literal' foo* 'lit' foo+`, how does one extract the foos that were in the middle?

It seems this kind of change is quite major and needs to be considered carefully.

**Comment by eddieschoute** [comment]
I think it has the potential to clean up some initially confusing behavior. E.g. the tutorial has an example with `"true" -> true` and `"false" -> false` which could then be inlined if the user likes.

As an alternative you could also parse every element in a rule to a fixed index where missing elements are parsed to `None`. So that the AST node for foobar will be of length 2. E.g. `foo` would then parse to something like `("foo", None)` (for the rule `foobar: foo? bar?`). This would also necessitate grouping joins such as `*` and `+`.

**Comment by erezsh** [comment]
What's confusing about the tutorial?

Your alternative idea is nice, but it won't work. Consider:

    rule: a (one | two two) b

**Comment by eddieschoute** [comment]
The fact that `"true"` and `"false"` would be ignored (because they are tokens) but subrules aren't, such as `list` and `NUMBER`.

That example should parse to something of the type `(A, Either[One, Tuple[Two,Two]], B)` where the capitalised versions are the types of the individual rules plus [Either](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Either.html). One could then match on whether the OR is the `Left` or the `Right`

**Comment by drslump** [comment]
I really like @eddieschoute idea! Keeping the structure from the grammar on the sequence would greatly simplify processing it in many cases. It also maps naturally to python's datatypes None/rule (?), tuple (* and +). For alternation I think it should map it into a tuple too with each branch taking an index.

Also interesting the possibility of aliasing sub-expressions, that together with a decorator could map a rule into named parameters easily:

    # rule : ident "(" [ param ("," param  ])* -> extra ] ")"
    @patternmatch
    def rule(self, param=None, extra=()):
        assert param.name == 'param'
        assert type(extra) == tuple

    # rule: ident ( foo | bar )
    @patternmatching
    def rule(self, ident, foo=None, bar=None):
        assert foo.name = 'foo'
        assert bar is None

**Comment by typon** [comment]
I highly second this request. It's nearly impossible to write a complex grammar without optional values. I have to traverse the list in each token's transform function, find if the optionals are missing and create my custom representation of that token based on that. All that could easily be replaced by doing something like:

    @inline_args
    def rule(self, **kwargs):
        return RuleObj(**kwargs)

**Comment by erezsh** [comment]
Despite the many good suggestions in this issue, I've decided to take a slightly different route, which I believe is simpler, and still addresses many of the points raised.

It's described towards the end of issue #285 , and the best demonstration of it right now is in the unittests: https://github.com/lark-parser/lark/blob/master/tests/test_parser.py#L1251

If you're still following this issue, let me know what you think! Especially if you think it's not sufficient for your purposes.

**Comment by typon** [comment]
Seems nice at first glance. I'll have to play around with it to get a good feel for it.
Thanks @erezsh

**Comment by erezsh** [comment]
I consider this issue resolved. Feel free to continue the conversation, or request new changes, as you see fit.
