### ISSUE TITLE
v0.12.0 only published to PyPI as lark-parser

### ISSUE THREAD

**Issue by plannigan** [lark-parser/lark#1004]
The [v0.12.0 release](https://github.com/lark-parser/lark/releases/tag/0.12.0) can be found on PyPI as `lark-parser` ([history link](https://pypi.org/project/lark-parser/#history)). However, that version is not available on PyPI as `lark` ([history link](https://pypi.org/project/lark/#history)). Based on the [documentation](https://lark-parser.readthedocs.io/en/latest/index.html) and [this commit](https://github.com/lark-parser/lark/commit/fe488d1d4407f805ba19bd5348d1c2a8e7315271), it seems like `lark` is intended to be used as the canonical name for the package. If this is the case, can the new release be uploaded with the name `lark`? If this is not the case, it would be helpful if there were some documentation on the intended name with information about the transition plan.

**Comment by MegaIng** [comment]
Those commits and the changes in the docs are not part of `v0.12.0`, but only of the `v1.0.0` release (coming soon). For the moment `lark-parser` is still he "official" name.

**Comment by erezsh** [comment]
I agree it's a little confusing. Perhaps we should consider changing the default docs branch away from master, until we publish 1.0 officially.

**Comment by plannigan** [comment]
1.0 has been published & `lark` is now the official name.
