### ISSUE TITLE
Whitespace around word operators

### ISSUE THREAD

**Issue by roveo** [lark-parser/lark#1009]
Hi! I'm implementing a small Python-like expression grammar and got stuck with boolean operators. Previously I implemented a JavaScript-like grammar and it was simple, because then I could just ignore whitespace and be done with it.

So the gist of my problem is this. In Python, this is not a valid expression: `1and1`, but this is: `(1)and(1)`. So, spaces around `and` are required, but not in all circumstances.

Here's a relevant working subset of my grammar:

```lark
%import common.SIGNED_INT     -> INTEGER
?literal: INTEGER

IDENTIFIER: /[a-z_]\w*/i
?paren: "(" op ")"
?atom: IDENTIFIER | INTEGER | paren

?not_: atom | not
not: "not" atom

?and_: not_ | and
and: and_ "and" not_

?or_: and_ | or
or: or_ "or" and_

?op: or_

expr: op

%ignore /\s/
```

In this grammar, `1and1`, `1 and 1`, `(1)and(1)` are valid. I can force the spaces around keyword operators, e.g.
`and: and_ " and " not_`, but then `(1)and(1)` becomes invalid.

So my question is, how do I recreate the behaviour of Python parser?

**Comment by erezsh** [comment]
I can think of a few approaches.

1) Use lookahead on NUMBER to ensure it isn't followed by a character

2) Use regex lookahead/lookbehind to make sure "and" is surrounded by the right characters. Should work, but might have some tricky points.

3) Use a lexer_callback on the "and" (or NUMBER) token to verify against the original text.

**Comment by MegaIng** [comment]
You shouldn't force whitespace, but should force that `and1` is parsed as an `IDENTIFIER` (note: `1and(1)` is valid in python).

The easiest way to do that is to not use the contextual lexer, instead try to use the `standard` (in current master/future v1.0 renamed to basic).

Otherwise you can modify the `INTEGER` token to reject if directly in front of it is an word charterer. using a lookbehind.

**Comment by roveo** [comment]
@MegaIng thanks! This worked by just setting the lexer to `standard`.

Is there any documentation for lexers to get a feel of the differences between them? The only reference I found is in the API docs.
