### ISSUE TITLE
Trying to parse a soft keyword

### ISSUE THREAD

**Issue by evtn** [lark-parser/lark#1015]
**What is your question?**

I'm currently making a Python transpiler, using `lark/grammars/python.lark` for parsing.
The grammar is almost fine, but it lacks match..case support.

I've adapted grammar from [official docs](https://docs.python.org/3/reference/grammar.html), but now I encounter a new problem

**If you're having trouble with your code or grammar**
Here's a minimal example, with semicolons and braces added to drop indentation checks

```python
from lark import Lark

grammar = """
%ignore /[\t \f\n]+/x
NAME: /[a-zA-Z_]\w*/
MATCH: "match"
CASE: "case"
NUMBER: ("+" | "-")? "0".."9"

expr: NAME | NUMBER

agmt: NAME "=" expr
match: MATCH expr "{" case+ "}"
case: CASE expr block

block: "{" code "}"
code: stmt+

stmt: (expr | match | agmt) ";"
"""

parser = Lark(grammar, start="code", parser="lalr")

code = """match = 1;
case = 2;
match N {
    case Z {
        5;
    } 
};"""

parser.parse(code)
```
What happens is "match" in first line treated as the beginning of match rule and fails to parse.
Is there a way to resolve this while using LALR(1), not Earley?

**Comment by erezsh** [comment]
Hi, it is actually possible and easy to make it work. It's a bit of a trick, but a very simple one.

```python
from lark import Lark

grammar = """
%ignore /[\t \f\n]+/x
name: NAME | MATCH
NAME: /[a-zA-Z_]\w*/
MATCH: "match"
CASE: "case"
NUMBER: ("+" | "-")? "0".."9"

expr: name | NUMBER

agmt: name "=" expr
match: MATCH expr "{" case+ "}"
case: CASE expr block

block: "{" code "}"
code: stmt+

stmt: (expr | match | agmt) ";"
"""

parser = Lark(grammar, start="code", parser="lalr")

code = """match = 1;
case = 2;
match N {
    case Z {
        5;
    } 
};"""

parser.parse(code)
```

> There is a reason python3.10 does no longer use a lalr compatible parser/grammar

Yes, the reason is they never consulted me ;)

**Comment by evtn** [comment]
Seems legit, I'll take a look at it next time I'll be working on my project.
Thanks!

**Comment by MegaIng** [comment]
@erezsh I might be wrong, but since we only have one token lookahead, doesn't that mean that `match (a)` is still ambiguous? You need an arbitrary lookahead to detect the `:` at the end of the line (Also, I mistyped. It is still Context free of course)

**Comment by MegaIng** [comment]
@erezsh Yeah, you are correct it works.

@evtn #1016 should contain full support for parsing match statements.
