### ISSUE TITLE
[BUG] regexp works differently compared to the same lark pattern

### ISSUE THREAD

**Issue by 0dminnimda** [lark-parser/lark#1031]
This pattern
```lark
FLOAT_NUMBER.2: (DEC_NUMBER "." DEC_NUMBER? | "." DEC_NUMBER) (("E" | "e") ["+" | "-"] DEC_NUMBER)?
              | DEC_NUMBER (("E" | "e") ["+" | "-"] DEC_NUMBER)?
```
cannot parse `5.0_8e-6` it recognizes `5.0` as float, then sees `_` and tries to continue parsing new terminal(?)/rule but there's none that starts with `_`, so it fails

If I change it to
```lark
FLOAT_NUMBER.2: (DEC_NUMBER "." DEC_NUMBER? | "." DEC_NUMBER)
              | (DEC_NUMBER "." DEC_NUMBER? | "." DEC_NUMBER) (("E" | "e") ["+" | "-"] DEC_NUMBER)
              | DEC_NUMBER (("E" | "e") ["+" | "-"] DEC_NUMBER)?
```
then everything works fine.

I suppose that the reason is regexp, because if I use 
```lark
DIGIT: "0".."9"

DEC_NUMBER: DIGIT ("_"? DIGIT)*
```

instead of previously used
```lark
DEC_NUMBER: /\d(?:_?\d)*/i
```
than both patterns for `FLOAT_NUMBER` works as intended.

This seems unintentional and therefore worth investigation.

_Originally posted by @0dminnimda in https://github.com/lark-parser/lark/issues/1028#issuecomment-961278961_

**Comment by erezsh** [comment]
That's odd. Shouldn't both versions of `FLOAT_NUMBER` be equivalent?

**Comment by 0dminnimda** [comment]
I'm not sure what the order of the privilege should be in the first case when in the second it's obviously `(DEC_NUMBER "." DEC_NUMBER? | "." DEC_NUMBER)`

**Comment by erezsh** [comment]
I'm having some trouble understand what's the bug. The following code works for me: 

```python
from lark import Lark

base = """
start: FLOAT_NUMBER
DIGIT: "0".."9"
DEC_NUMBER: DIGIT ("_"? DIGIT)*
"""

p1 = Lark(base + """
FLOAT_NUMBER: (DEC_NUMBER "." DEC_NUMBER? | "." DEC_NUMBER) (("E" | "e") ["+" | "-"] DEC_NUMBER)?
 			| DEC_NUMBER (("E" | "e") ["+" | "-"] DEC_NUMBER)?	
""")

p2 = Lark(base + """
FLOAT_NUMBER: (DEC_NUMBER "." DEC_NUMBER? | "." DEC_NUMBER)
            | (DEC_NUMBER "." DEC_NUMBER? | "." DEC_NUMBER) (("E" | "e") ["+" | "-"] DEC_NUMBER)
            | DEC_NUMBER (("E" | "e") ["+" | "-"] DEC_NUMBER)?
""")


print( p1.parse('5.0_8e-6') )
print( p2.parse('5.0_8e-6') )
```

It also works if I use the regexp version of DEC_NUMBER.

**Comment by erezsh** [comment]
I find it's always a good idea to create a minimal reproducing example of a bug. It's useful both for proving to others that it exists, as well as to yourself :)

**Comment by 0dminnimda** [comment]
Here's the "issue"
```lark
start: FLOAT_NUMBER

DEC_NUMBER: /0|\d(?:_?\d)*/i
FLOAT_NUMBER.2: (DEC_NUMBER "." DEC_NUMBER? | "." DEC_NUMBER) (("E" | "e") ["+" | "-"] DEC_NUMBER)?
              | DEC_NUMBER (("E" | "e") ["+" | "-"] DEC_NUMBER)
```
and everything is fine, it prioritizes `0` over everything else, so `5.0` as `DEC_NUMBER "." DEC_NUMBER` is good enough, no need to include here the `_8` leftover.


Why I reported the `/\d(?:_?\d)*/i` and not `/0|\d(?:_?\d)*/i`?
It's is because while making #1028 I spotted this useless `0|` created conversation for this, MegaIng showed me that it was incorrect, so I fixed it in the pr as well in the comment that served as the origin for this issue, but I haven't checked that new version also produces this error, turns out that it fixed the "issue".

So this is a false alarm, I'm closing it.

**Comment by erezsh** [comment]
Entirely btw, mind if I ask what you're building with Lark?

**Comment by erezsh** [comment]
I see. I was also interested in the idea of passing expressions instead of values, i.e. lazy evaluation, because it allows the user to define complex constructs like functions that accept a live condition, similarly to while loops. Or 

In the end, I couldn't find a use-case that was compelling enough.

**Comment by 0dminnimda** [comment]
> In the end, I couldn't find a use-case that was compelling enough.

At least it's fun to play with the new concept :)
AFAICT such functionality just adds another way to do stuff

For example, you can have two functions that do one and another sort of behaviour, and you can pass them to a caller function, that'll decide what of those two functions is better to call now (those functions will not take in any arguments to keep it very dynamic, so arguments will be accessed from nonlocals - locals of the caller), or you can straight up pass funccall into caller function, funccall arguments will be looked up first from locals of the caller, and then in the outer scopes.
Here's an illustration of the second example:
```python
assign(try_to_ban, function(
    args(user, success_f, fail_f),
    assign(user_name, get_name(user)),
    if(there_is(user),
        exec(
            assign(user_id, get_id(user)),
            success_f,  # uses user_name and user_id),
        exec(fail_f)  # uses user_name
    )))

try_to_ban(
    user_from_command(),
    exec(ban(user_id), say("Banned", user_name)),
    say("Cannot ban, there's no user with name", user_name))
```
