### ISSUE TITLE
AssertionError when using declared symbols in terminal

### ISSUE THREAD

**Issue by SkryptX** [lark-parser/lark#1032]
I built a custom lexer which generates a custom token stream. I wanted to use the tokens which come from the token stream just like regular terminals in combination with other terminals, but then I encountered this error:
```
File "venv\lib\site-packages\lark\load_grammar.py", line 739, in resolve_term_references
    assert term_value is not None
AssertionError
```

As a minimal broken example I can modify two lines in the `custom_lexer.py` example:
```
from lark import Lark, Transformer, v_args
from lark.lexer import Lexer, Token

class TypeLexer(Lexer):
    def __init__(self, lexer_conf):
        pass

    def lex(self, data):
        for obj in data:
            if isinstance(obj, int):
                yield Token('INT', obj)
            elif isinstance(obj, (type(''), type(u''))):
                yield Token('STR', obj)
            else:
                raise TypeError(obj)

# HERE I CHANGED data_item: STR INT* to data_item: COMP and defined it below
parser = Lark("""
        start: data_item+
        data_item: COMP

        COMP: STR INT*

        %declare STR INT
        """, parser='lalr', lexer=TypeLexer)


class ParseToDict(Transformer):
    @v_args(inline=True)
    def data_item(self, name, *numbers):
        return name.value, [n.value for n in numbers]

    start = dict

def test():
    data = ['alice', 1, 27, 3, 'bob', 4, 'carrie', 'dan', 8, 6]

    print(data)

    tree = parser.parse(data)
    res = ParseToDict().transform(tree)

    print('-->')
    print(res) # prints {'alice': [1, 27, 3], 'bob': [4], 'carrie': [], 'dan': [8, 6]}

if __name__ == '__main__':
    test()
```

I don't see any reason why this should not be possible, but I am also absolutely no expert in this field. In any case, it would make my life so much easier.

**Comment by erezsh** [comment]
I consider it a bug that you got such a cryptic error message.

But Lark is works fine with the correct input. If you rename `COMP` to `_comp` it should work.

You're getting an error because the parser is trying to construct a terminal from the terminals you declared. But it can't because they are not defined yet. Change COMP to a rule bypasses this issue.

**Comment by SkryptX** [comment]
I kind of understand, but this seems to be a limitation of Lark. Declared terminals should just work like normal terminals even if it can't already construct them during the loading phase. During the parsing it just has to wait for the correct token instead of searching a particular string. Am I mistaken by that? Terminals as collection of atomic tokens and rules as aggregation of other rules and terminals. This `_comp` workaround feels wrong.

**Comment by MegaIng** [comment]
Terminals in lark are atomic. This means they are represented by a single regex. This now means that compound Terminals like the own you showed are joined together into a single regex. Of course if lark can't see the definition of the Terminals because they are `%declare`d lark can't do that.

It sounds like you are writing your own lexer. In that case you can do whatever you want. `%ignore` is not handled by the parse, but by the lexer.

**Comment by erezsh** [comment]
@SkryptX You might be a little confused about how parsers and lexers work.

The lexer's job is to transform text into a bunch of tokens (as defined by terminals). Those tokens are the API it provides the parser. So if you define `COMP`, the parser expects to see `COMP`, and not `INT` or `STR` which don't appear in any rule, so the parser doesn't know about them.

The job of a custom lexer is to provide the parser with terminal that it knows.

What you're looking for, perhaps, is another layer between you and the parser, that will be able to parse token fragments into whole tokens, before passing them to the parser.

It might be possible to write, but, what's the point? Just pass the fragments to the parser, it will be simpler and more efficient.

**Comment by erezsh** [comment]
@SkryptX I really have no idea why you would need more than Lark already provides. Can you explain it more clearly?

Why is it so important to lazy-compose terminals when you can use rules?

**Comment by erezsh** [comment]
P.S. %ignore simply throws away the tokens. i.e. not yield.
