### ISSUE TITLE
How to handle variable length arguments in a custom transformer?

### ISSUE THREAD

**Issue by ZachPerkitny** [lark-parser/lark#1037]
Using the following rule: `tag: identifier ["(" [attr ("," attr)*] ")"] [_NL | (":" block)]`, and a custom transformer, is there a good workaround to allow for something like this:
```
@v_args(inline=True)
    def tag(self, name, *attrs, body):
        return Tag(name, attrs, body)
```

The arguments name, attrs and body are no longer instances of Token, as they were transformed as well. It's important that attrs and body are seperated as they are handled differently.

The only solution (hack) I came up with is using `isinstance` but that's a sort of last resort method.

Has anyone else come across this sort of issue?

Thanks

**Comment by MegaIng** [comment]
There are multiple possible solutions:

Use an attr_list rule:
```
attrs_list: "(" [attr ("," attr)*] ")"
tag: identifier [attrs_list] [_NL | (":" block)]
```

Then you an do something like this:

```
    def attrs_list(self, children):
        return children

    @v_args(inline=True)
    def tag(self, name, attrs, body):
        return Tag(name, attrs, body)
```

Alternatively, you can do this:

```

    def tag(self, children):
        name, *attrs, body = children
        return Tag(name, attrs, body)
```

**Comment by erezsh** [comment]
Just to add on what @MegaIng said, you can use the following pattern:

```lark
attrs_list: "(" [attr ("," attr)*] ")"   -> as_list
tag: identifier [attrs_list] [_NL | (":" block)]
```

And then in the transformer:

```python
      def as_list(self, children):
        return children
```

Then you can re-use the `as_list` alias in any other rules that produce a list of items.

**Comment by ZachPerkitny** [comment]
Thanks for the responses :) it worked
