### ISSUE TITLE
Docs: JSON parser tutorial: keyword clash?

### ISSUE THREAD

**Issue by Nightblade** [lark-parser/lark#1040]
In the code below I think `list` and `dict` clash with reserved keywords?  Maybe use different names for clarity?

```python
from lark import Transformer

class TreeToJson(Transformer):
    def string(self, s):
        (s,) = s
        return s[1:-1]
    def number(self, n):
        (n,) = n
        return float(n)

    list = list
    pair = tuple
    dict = dict

    null = lambda self, _: None
    true = lambda self, _: True
    false = lambda self, _: False
```
https://lark-parser.readthedocs.io/en/latest/json_tutorial.html

**Comment by erezsh** [comment]
I think it's fine as it is. It's not much different than doing `transformer.list = list` or `transformer['list'] = list`. Just shorter syntax.
