### ISSUE TITLE
Necessary imports not included in Lark standalone parsers.

### ISSUE THREAD

**Issue by shiyunon** [lark-parser/lark#1059]
**Describe the bug**

To generate Lark standalone parsers for users (those users using `python -m lark.tools.standalone`), in `lark/tools/standalone.py`, necessary file sections are included in the final standalone parser. These necessary files are defined on line 56 in `lark/tools/standalone.py` in the Python list `EXTRACT_STANDALONE_FILES`. This list includes `visitors.py` (on line 61). The included section of `visitors.py` (in any standalone parsers) is from line 10 to line 518 (of `visitors.py`). However, on line 431 of `visitors.py`, `update_wrapper` function is used, but the import line `from functools import wraps, update_wrapper` is on line 3 of `visitors.py` and not in the included section (line 10-518 of `visitors.py`) in the generated standalone parser. Thus, a bug can be generated if line 431 is called in any standalone parsers.

**Comment by erezsh** [comment]
You're right. It will happen if you try to decorate a class with v_args, which I guess no one has tried with the standalone parser yet.

**Comment by erezsh** [comment]
Should be solved in `master`. I'll probably make a `v1.1` release in the coming weeks.
