### ISSUE TITLE
Are async transformer methods supported?

### ISSUE THREAD

**Issue by hf-kklein** [lark-parser/lark#1062]
## Question / tl;dr
Is is possible to use async user functions/methods in transformers?
If yes: How?
If no: What is the best workaround?

## Example Code
I modified [the minimal working example from the docs](https://lark-parser.readthedocs.io/en/latest/visitors.html#transformer) to be async:
```python
import asyncio

from lark import Tree, Transformer


class EvalExpressions(Transformer):
    async def expr(self, args):
        await asyncio.sleep(1)  # sleep is just a placeholder for something like an aiohttp request or an async db query
        return eval(args[0])


def main():
    t = Tree('a', [Tree('expr', ['1+2'])])
    loop = asyncio.get_event_loop()
    result = loop.run_until_complete(EvalExpressions().transform(t))
    print(result)


if __name__ == "__main__":
    main()
```

The code fails:
> Traceback (most recent call last):
...  
 line 15, in main
    result = loop.run_until_complete(EvalExpressions().transform(t))
  File "python\python39\lib\asyncio\base_events.py", line 621, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "python39\lib\asyncio\tasks.py", line 679, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
sys:1: RuntimeWarning: coroutine 'EvalExpressions.expr' was never awaited

This is behaviour obvious, because the transform function isn't async, so it cannot be awaited. Also internally lark doesn't seem to recognize the `expr` method to be async, hence the RuntimeWarning.

Is there any way to have/use async methods in a transformer? My use case would be for example:
- async http requests (using aiohttp)
- async access to a database or file system

I expect the transformer to be faster when there are many (async) leaves on the same hierarchy level of the tree.

My guess is that it might be possible to provide a wrapper using `v_args` and "hide" the async stuff there. Then it might not even be faster or truely concurrent but possible.

**Comment by erezsh** [comment]
It's not possible, and I don't think it's a good idea to have I/O functions inside a transformer, in terms of code design. It's better to use the transformer to create the tree you want, and perform I/O operations in a separate pass.

As for best workaround.. You can inherit from Transformer and rewrite the relevant functions as async, I suppose.

**Comment by hf-kklein** [comment]
Thanks for the fast answer :)

**Comment by hf-kklein** [comment]
> and perform I/O operations in a separate pass

I tried using `scan_values` and `ìter_subtrees`. I'm sure about the async part but not 100% familiar with the Lark/Tree API. Probably there's some easier way on how to replace the coroutines in `result` with their respective awaited return values. 

@erezsh Do you find any obvious mistakes or easy simplifications in here?

Thanks for any feedback :)

```python
import asyncio
from typing import Awaitable

from lark import Transformer, Tree


class EvalExpressions(Transformer):
    async def expr_async(self, args) -> str:
        await asyncio.sleep(1)
        return eval(args[0])

    def expr(self, args) -> Awaitable[str]:
        return self.expr_async(args)


def main():
    tree = Tree("a", [Tree("expr", ["1+2"]), Tree("expr", ["3+4"]), Tree("b", [Tree("expr", ["5+6"])])])
    result = EvalExpressions().transform(tree)
    loop = asyncio.get_event_loop()
    sub_results = loop.run_until_complete(asyncio.gather(*result.scan_values(asyncio.iscoroutine)))
    for coro, sub_result in zip(result.scan_values(asyncio.iscoroutine), sub_results):
        for sub_tree in result.iter_subtrees():
            for child_index, child in enumerate(sub_tree.children):
                if child == coro:
                    sub_tree.children[child_index] = sub_result
    print(result)
    # prints Tree('a', [3, 7, Tree('b', [11])])
    # takes << 3s


if __name__ == "__main__":
    main()

```

**Comment by erezsh** [comment]
I don't really know what you were going for, so hard to give a good input. I'm not sure why you're zipping what appears to be the same expression to itself.

But anyway, if the choice is between this and a transformer, maybe a transformer is better after all.
