### ISSUE TITLE
MyPy issue on Tree -> `data.value`

### ISSUE THREAD

**Issue by ernestoarbitrio** [lark-parser/lark#1063]
I'm a newbie to lark and while running mypy on my demo project i got a strange error:
`error: Incompatible types in assignment (expression has type "str", variable has type "Token")`

The class `Tree`
```
class Tree:
    """The main tree class.

    Creates a new tree, and stores "data" and "children" in attributes of the same name.
    Trees can be hashed and compared.

    Parameters:
        data: The name of the rule or alias
        children: List of matched sub-rules and terminals
        meta: Line & Column numbers (if ``propagate_positions`` is enabled).
            meta attributes: line, column, start_pos, end_line, end_column, end_pos
    """

    data: str
    children: 'List[Union[str, Tree]]'
    ```
    has `str` as type annotation, but when I get the `tree.data` I got always a `Token` and so I suppose that the data should be a `Token` or at least a `Union[str, Token]` 🤷🏽‍♂️

**Comment by erezsh** [comment]
We just merged a PR with fixes for tree typing.

Can you check the latest `master` and see if it's better now?
