### ISSUE TITLE
Lark.parse() sometimes returns tokens

### ISSUE THREAD

**Issue by robbrit** [lark-parser/lark#1067]
For certain input texts, calling the `parse()` method on my `Lark` object gives back `Token` objects instead of `Tree` objects.

Here's an example input that reproduces it using the v1.0.0 release from PyPI:

```python
import lark

# Grammar:
parser = lark.Lark(
    r"""
    ?block: value*

    ?value: cond
          | neg_cond
          | substitution -> substitution
          | comment
          | literal

    ?open_cond: _OPEN [_WS] _POUND [_WS] VARIABLE [_WS] _CLOSE
    ?open_neg_cond: _OPEN [_WS] _CARET [_WS] VARIABLE [_WS] _CLOSE
    ?close_cond: _OPEN [_WS] _SLASH [_WS] VARIABLE [_WS] _CLOSE

    ?cond: open_cond block close_cond
    ?neg_cond: open_neg_cond block close_cond

    ?substitution: _OPEN [_WS] VARIABLE [_WS] _CLOSE

    ?comment: _OPEN [_WS] _BANG [_WS] _COMMENT_TEXT _CLOSE

    ?literal: LITERAL

    _WS: /\s+/
    VARIABLE: /[a-z0-9_\-]+/i
    LITERAL: /(?:(?!{{).)+/s
    _COMMENT_TEXT: /(?:(?!}}).)+/s
    _OPEN: "{{"
    _CLOSE: "}}"
    _POUND: "#"
    _SLASH: "/"
    _CARET: "^"
    _BANG: "!"
""",
    start="block",
)

# Input that breaks it:
tree = parser.parse("this is text")
```
This gives back a `Token` object instead of a `Tree`, so our `Visitor` or `Transformer`s immediately break afterwards.

**Comment by MegaIng** [comment]
Well, that is exactly what you tell it to do. `block`, your start rule, has a `?`, so it will be inlined if it only has one child. Either make it not have that or create a second top level start rule that does not have a `?`

**Comment by robbrit** [comment]
Ah, my bad. I'll remove the `?` to keep the type system sane.

**Comment by erezsh** [comment]
Generally, the form

```lark
  ?a: b*
```

is a bit of a weird combination, because it will inline `a` if and only if there is just one `b`. I wonder if there's ever a situation where that's what you want.

**Comment by robbrit** [comment]
Yeah I didn't read the docs beyond the Getting Started tutorial, probably should have dove deeper in and discovered inlining.
