### ISSUE TITLE
Strangeness with 'expected' value from exception

### ISSUE THREAD

**Issue by snhirsch** [lark-parser/lark#1094]
This a cut-down example from a parser intended to accept disk format definitions.  I do not understand why it fails to report the 'libdisk' token in the expected list from the thrown exception.  The parse tree certainly looks reasonable, yet it insists on calling out an ANON token.  If there's a difference in the way the grammar is formed for that one terminal I'm not seeing it.

```
#!/usr/bin/python3

from lark.lark import Lark
from lark import Transformer, UnexpectedToken, UnexpectedCharacters, UnexpectedEOF
import pprint

GRAMMAR = r"""
start: diskdef+

diskdef: "diskdef" defname pair+ "end"

defname: CNAME

pair: intparm intval -> intparm
    | strparm strval -> strparm
    | osparm OSVAL -> osparm

intparm: "seclen" -> seclen
       | "tracks" -> tracks

strparm: "libdsk:format" -> libdisk

osparm: "os" -> os

?intval: INT

?strval: CNAME

OSVAL: "2.2"|"3"|"isx"|"p2dos"|"zsys"

%import common.WS
%ignore WS

%import common.INT
%import common.CNAME
%import common.LETTER
%import common.DIGIT
"""
parser = Lark(GRAMMAR, parser='lalr')

def do_parse(data):
    try:
        j = parser.parse(data)
        print(j.pretty())
    except UnexpectedToken as u:
        print("Unxpected token at line: %d, column: %d\n" % (u.line, u.column))
        txt = u.get_context(data)
        print(txt)
        print("Expected one of:")
        for tok in u.expected:
            print(tok)
    except UnexpectedCharacters as u:
        print(u)
    except UnexpectedEOF as u:
        print(u)

good_data = r"""
diskdef pcw
  seclen 512
  tracks 40
  os 3
  libdsk:format pcw180
end
"""
do_parse(good_data)

bad_data = r"""
diskdef pcw
  foobar 512
  tracks 40
  os 3
  libdsk:format pcw180
end
"""
do_parse(bad_data)
```

Parse Tree:
```
start
  diskdef
    defname     pcw
    intparm
      seclen
      512
    intparm
      tracks
      40
    osparm
      os
      3
    strparm
      libdisk
      pcw180
```
Error report:
```
Unxpected token at line: 3, column: 3

  foobar 512
  ^

Expected one of:
OS
SECLEN
TRACKS
__ANON_0  <----- Why?
```

**Comment by MegaIng** [comment]
The names displayed in the expected clause of the Exception are the internal names of the tokens. Those are derived from the string literals where possible, but only valid python identifiers are accepted here. `libdsk:format` is not a valid identifier, so it's not used. You can directly name the terminal to get a better display there.

**Comment by erezsh** [comment]
What you are seeing is the string ID for the token, which is auto-named when possible, for better usability, but it's not intended for the users of the parser.

You can use 1Lark.get_terminal1 to get its value, like:

```python
print( parser.get_terminal(tok).pattern )
```

**Comment by snhirsch** [comment]
> The names displayed in the expected clause of the Exception are the internal names of the tokens. Those are derived from the string literals where possible, but only valid python identifiers are accepted here. `libdsk:format` is not a valid identifier, so it's not used. You can directly name the terminal to get a better display there.

Perhaps I'm confused, but I thought I did name the terminal using '->'.  Can you clarify?

**Comment by snhirsch** [comment]
> What you are seeing is the string ID for the token, which is auto-named when possible, for better usability, but it's not intended to be displayed.
> 
> You can use `Lark.get_terminal` to get its value, like:
> 
> ```python
> print( parser.get_terminal(tok).pattern )
> ```

Thanks very much!  That is certainly more useful.  The only nit is that there's now a double-backslash escape in the string:  'libdisk\\:format'.  If that's expected I'll just strip it out myself.

**Comment by erezsh** [comment]
No, `->` aliases the subrule, not the terminal.

so you can do something like:

```lark
rule: "a" "b" "c" -> subrule1
      | "a" "b"  -> subrule2

**Comment by snhirsch** [comment]
So how do I name the terminal?  Sorry to be a pain, but I'm clearly missing something.

**Comment by erezsh** [comment]
Are you getting a backslash when doing

```python
print( parser.get_terminal(tok).pattern.value )
```

?

To name the terminal, you need to define it. Like

```lark
rule: NAMED
NAMED: "some_value"
```

**Comment by snhirsch** [comment]
> Are you getting a backslash when doing
> 
> ```python
> print( parser.get_terminal(tok).pattern.value )
> ```
> 
> ?

No - that works correctly.  

> 
> To name the terminal, you need to define it. Like
> 
> ```lark
> rule: NAMED_TERMINAL
> NAMED_TERMINAL: "some_value"
> ```

Thanks very much for the clarification!  Really appreciate the work you've done on this package.
