### ISSUE TITLE
What code style does Lark use?

### ISSUE THREAD

**Issue by hf-kklein** [lark-parser/lark#1103]
When opening #1102 I wondered why I stumbled upon these formatting things at all.
Does the lark code follow any specific code style (like f.e. black)?

**Comment by erezsh** [comment]
Lark doesn't follow a predefined code style.

We accept any code style that makes sense, as long as it's Pythonic and easy to read.

**Comment by erezsh** [comment]
(Added edit)

**Comment by hf-kklein** [comment]
yeah, the default line length of 100 (iirc in black) is pretty annoying sometimes

**Comment by erezsh** [comment]
I could live with a 100. I think Black's default is 88. Though I prefer 120.
