### ISSUE TITLE
Lark 1.1.0 does not provide a `py.typed` file

### ISSUE THREAD

**Issue by hf-kklein** [lark-parser/lark#1105]
**Describe the bug**

Dependabot proposed to upgrade from lark 1.0.0 to lark 1.1.0 in a library that uses lark.
But in the branch that with upgrade v1.1.0 the type checks with mypy break with the following error message for both lark and lark submodules:
> error: Skipping analyzing "lark": module is installed, but missing library stubs or py.typed marker  [import]

**To Reproduce**

See https://github.com/Hochfrequenz/ahbicht/pull/121

I think this can be fixed by adding a `py.typed` file and including it in the package.

**Comment by hf-kklein** [comment]
@erezsh Would you mind publishing something like a v1.1.1 that contains this fix?

**Comment by erezsh** [comment]
https://github.com/lark-parser/lark/releases/tag/1.1.1
