### ISSUE TITLE
regex \b flag is not working

### ISSUE THREAD

**Issue by wolyosung** [lark-parser/lark#1112]
**Describe the bug**

I use this type of regex, but it seems that \b flag is not working.

\b([-_]?[a-z]){2,}

**Comment by erezsh** [comment]
Are you using a raw string?

**Comment by wolyosung** [comment]
no i used /<regex>/ as guided in the document

**Comment by erezsh** [comment]
I mean for the grammar. You should use a `.lark` file for it. Or at least quote it using `r" ... "`

**Comment by wolyosung** [comment]
thank you!
