### ISSUE TITLE
is there any reason Visitors can't visit tokens while Transformers can?

### ISSUE THREAD

**Issue by ornariece** [lark-parser/lark#1113]
the ``visit_tokens`` parameter ("Should the transformer visit tokens in addition to rules") in ``Transformer`` is not a thing in ``Visitor``.

is that wanted? implementing it in ``Visitor`` is more-or-less a copy-paste matter from what i can see

**Comment by erezsh** [comment]
No reason, it's just that no one ever requested it.

**Comment by ornariece** [comment]
well, i'll probably do it at some point but not in the neaar future, you can expect a pull request

**Comment by erezsh** [comment]
Can't wait :)

**Comment by erezsh** [comment]
Closing for now. Feel free to reopen.
