### ISSUE TITLE
LALR templates not expanding

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#1131]
**Describe the bug**

Basically, [templates](https://lark-parser.readthedocs.io/en/latest/grammar.html#templates) don't work as well on the LALR parser. I have to manually expand the template in order for my grammar to work on LALR. This kind of defeats the purpose of templates.

**To Reproduce**

Grammar "A":

```lark
%import common.WORD
%import common.NEWLINE -> _NL
%ignore " "

start: _list{WORD}

_COMMA: "," _NL?
_list{x}: _sep{x, _COMMA} _COMMA?
_sep{x, sep}: x (sep x)*
```

Grammar "B" (this is equivalent to grammar A but I manually expanded one of the templates):

```lark
%import common.WORD
%import common.NEWLINE -> _NL
%ignore " "

start: _list{WORD}

_COMMA: "," _NL?
_list{x}:  x (_COMMA x)* _COMMA?
```

**Problem**

Earley can parse the following examples with either grammars
```yaml
Hello, world
```
```yaml
Hello, world,
```

LALR can only parse both inputs using grammar B (grammar A fails when trying to parse the second input)

**Comment by erezsh** [comment]
The problem isn't with templates, but with the resulting rules, which aren't ideal for prediction in LALR(1).

This could be solved by a new feature that inlines the templates, like `__sep{x, sep}: x (sep x)*`

But for now, I can't think of a simple solution.

**Comment by ThatXliner** [comment]
I thought templates were already inlined.

> Templates are expanded when preprocessing the grammar.
https://lark-parser.readthedocs.io/en/latest/grammar.html#templates

If not, what *does* happen?

**Comment by erezsh** [comment]
Each template is currently expanded into its own rule. Which is why you get a shift/reduce conflict.

I already opened an issue for this a year ago, but it didn't get any attention: https://github.com/lark-parser/lark/issues/822

**Comment by ThatXliner** [comment]
I have a feeling that when people are using templates, most of them are expecting it to be inlined. I don’t think anyone would use the templates as rule since (last time I checked) there’s no documented way on how to visited the rules generate by templates.

**Comment by erezsh** [comment]
Templates generate trees where `data` is the template name. It's very predictable.

Of course, you won't see those starting with underscore, because they get inlined during parsing.
