### ISSUE TITLE
grammar reference appears to be incomplete and other doc comments

### ISSUE THREAD

**Issue by julie777** [lark-parser/lark#1132]
**Describe the bug**

This is strictly a documentation issue.

1. I didn't see any information in the grammar documentation about rule name prefixes such as "?" and "!". 
The rule `?value: dict` is used in the JSON example and I had to search all the documentation to see why the "?" was there.

2. While I am at it
```
Grammars in Lark are based on [EBNF](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form) syntax, with several enhancements.
``` 
should either link to the list of enhancements to EBNF or list them right there. I read that sentence and immediately wondered what they are. I looked at the table of contents for the grammar reference and they didn't show up there either.
Also, (the same issue) the Features page has
```
EBNF-inspired grammar, with extra features (See: [Grammar Reference](https://lark-parser.readthedocs.io/en/latest/grammar.html))
```
which implies that the extra features can be found in the grammar reference, but in fact they are at the bottom of the Features page.

3. Given that many or most Lark users will already understand grammars in general, maybe put the definitions at the end of the grammar reference in a section listed in the TOC. Definitions could also be linked to in the earlier parts of the reference.

**To Reproduce**

N/A

**Comment by MegaIng** [comment]
A lot of this is covered in [Shaping the Tree](https://lark-parser.readthedocs.io/en/latest/tree_construction.html). You just want a few more links to that page?

**Comment by erezsh** [comment]
Closed due to lack of participation.
