### ISSUE TITLE
COBOL EBNF Grammar parsing

### ISSUE THREAD

**Issue by shrivatsahosabettu** [lark-parser/lark#1133]
**What is your question?**
Is Lark is capable of COBOL EBNF Grammar?
Try to be accurate and concise.
Cobol Program has normally 4 divisions and sections/paragraph/statements.
Below is the website which provide most of the COBOL-85 Grammar rules in EBNF format.
https://www.cs.vu.nl/grammarware/vs-cobol-ii/

**If you're having trouble with your code or grammar**

Provide a small script that encapsulates your issue.
The below statement I was trying to get the parser statement of as DISPLAY which is KEYWORD in cobol and TEST which is a user_defined variable.
```
from lark import Lark
import re

cobol_parser = Lark(r"""
            statement: display_statement  

            display_statement:	"DISPLAY"  identi | literal

            literal: SIGNED_NUMBER
            identi: string
            string: /[a-z0-9]([_a-z0-9\-]*[a-z0-9]+)?/            
           
            %import common.SIGNED_NUMBER
            %import common.ESCAPED_STRING
            %import common.WS
            %ignore WS

            """, start= 'statement')

text = "DISPLAY TEST."
print(cobol_parser.parse(text).pretty())
```
Explain what you're trying to do, and what is obstructing your progress.
Not sure if I am doing everything correct. But I wanted to get an idea from the community. I am sure it is possible as the documentation of the Lark says it is possible to even parse Java, Python and most of the languages. Need help or guidance on this.

**Comment by erezsh** [comment]
If COBOL can be expressed as EBNF, then Lark can parse it.

You might have better luck asking at our gitter: https://gitter.im/lark-parser/Lobby

**Comment by shrivatsahosabettu** [comment]
Thank you so much for your kind reply. I will definitely try something out and come to the gitter with specific example or challenges for solution.
