### ISSUE TITLE
Greediness of rules

### ISSUE THREAD

**Issue by ymeiron** [lark-parser/lark#1136]
Is it possible to adjust the greediness of rules with regex terminals?

My text to parse is this, for example:

    OTHER STATEMENT
    GO
    CREATE TABLE mytable (
        var1 float,
        var2 float
    )
    GO

Here `OTHER STATEMENT` is something I don't really care about, but it could have multiple tokens across lines, quotation marks, parentheses, etc. All we know that it terminates with the word `GO`. What I actually want to capture is this `CREATE TABLE` statement. My attempt of a Lark code is this:

    program: (statement "GO")* statement ["GO"]
    statement: create_table_statement | other_statement
    create_table_statement.1: "CREATE TABLE" table_name signature
    table_name: CNAME
    signature: "(" typed_variable ("," typed_variable)* ")"
    typed_variable: variable type
    variable: CNAME
    type: CNAME
    other_statement: /.+/s

    %import common.CNAME
    %import common.WS
    %ignore WS

The problem though is that the whole text matches the `other_statement`, because `/.+/s` consumes the `GO` keyword that is supposed to by the statement separator.

Is there a way within Lark to achieve what I want? I have a vague idea how to preprocess the text and remove the irrelevant statements before feeding it to Lark, but that may require some additional coding effort (making sure that "GO" appears not as a part of a quoted string).

**Comment by erezsh** [comment]
Are you aware of laziness in regular expressions?

```
>>> re.findall('.*?GO', 'dontGObabydontGO')
['dontGO', 'babydontGO']
```

**Comment by ymeiron** [comment]
Yeah, I didn't think it would be immediately helpful because that would require "GO" to be part of `other_statement` (right?). But trying a bit more I think I reached something satisfactory, that indeed captures "GO" with both `create_table_statement` and `other_statement`.

In my current version there are two minor problems, I wonder if there is an elegant solution, but I'm quite satisfied if not:

1. `other_statement` is not captured correctly if there is a "GO" in it. These are ignored anyway so not a big deal. Wherever there's a GO (as part of a word, or in between quotes), it's split into two `other_statement`s.

2. Now the text has to end with a "GO" (it should be possible to terminate the last statement just with EOF). Again not a big deal, it's easy just adding a "GO" to the end of the text.

Here is the new Lark:

    program: (statement)*
    statement: create_table_statement | other_statement
    create_table_statement.1: "CREATE TABLE" table_name signature "GO"
    table_name: CNAME
    signature: "(" typed_variable ("," typed_variable)* ")"
    typed_variable: variable type default?
    variable: CNAME
    type: CNAME
    default: "DEFAULT" "(" value ")"
    value: ESCAPED_STRING | NUMBER
    other_statement: /(.*?)GO/s

    %import common.CNAME
    %import common.ESCAPED_STRING
    %import common.NUMBER
    %import common.WS
    %ignore WS

The text:

    OTHER "HE REWE GO"
    GO
    CREATE TABLE mytable (
        var1 float DEFAULT("GO"),
        var2 float
    ) GO
    ANOTHER ~~~~~
    GO

gives basically the correct tree for the single `create_table_statement` I'm interested in parsing.

**Comment by erezsh** [comment]
> Yeah, I didn't think it would be immediately helpful because that would require "GO" to be part of other_statement 

So, regexps also support lookaheads. So you can do something like this:

>>> re.findall('.*?(?=\s*GO)', 'dont GO i said babydont GO')
['dont', '', ' ', '', 'GO i said babydont', '', ' ', '']

As for the other problems, there is no simple solution. In the ideal situation, you have a complete grammar of the entire text, and then you don't need to use `.*`, and can use "GO" as a separate token, which is how parsers are meant to be used.

**Comment by ymeiron** [comment]
`.?(?=\sGO)` however is a zero-width regexp, I'm not sure how it could be used.

I understand that it's best to have the complete grammar, but it's also useful to be able to parse a document partially. And it seems to mostly work fine when the separator is included in the statement.

**Comment by erezsh** [comment]
Oh, sorry, bad formatting. Something like `.+?(?=\sGO)` 

> it's also useful to be able to parse a document partially

Absolutely, although it's a less common use-case. We've been asked about it in the past, but I still haven't figured out a way for Lark to give a good answer for this. It might be best to skip to sections manually, and then only parse the structured parts.  (you can use `interactive_parse` to get even more control over the parsing mechanism)
