### ISSUE TITLE
Parsing behavior changes when install the latest version of lark-parser

### ISSUE THREAD

**Issue by alooba1** [lark-parser/lark#1139]
**Describe the bug**

I was using lark-parser 0.11.3 which is the latest version, I started a virtual environment today and installed lark, the parser version is still 0.11.3 but the behavior changed

**before with 0.11.3 it gives me:**
Tree('turtle_doc', [Tree('directive', [Tree('sparql_prefix', [Token('__ANON_2', 'PREFIX'), Token('PNAME_NS', ':'), Token('IRIREF', '<http://example/>')])]), Tree('triples', [Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':s')])]), Tree('predicate_object_list', [Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':p')])]), Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':o')])])])]), Tree('triples', [Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':a')])]), Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':q')])]), Tree('quotation', [Token('ANGLEBRACKETL', '<<'), Tree('triples', [Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':s')])]), Tree('predicate_object_list', [Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':p')])]), Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':o')])])])]), Token('ANGLEBRACKETR', '>>')])]), Tree('triples', [Tree('quotation', [Token('ANGLEBRACKETL', '<<'), Tree('triples', [Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':a')])]), Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':q')])]), Tree('quotation', [Token('ANGLEBRACKETL', '<<'), Tree('triples', [Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':s')])]), Tree('predicate_object_list', [Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':p')])]), Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':o')])])])]), Token('ANGLEBRACKETR', '>>')])]), Token('ANGLEBRACKETR', '>>')]), Tree('predicate_object_list', [Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':r')])]), Tree('iri', [Tree('prefixed_name', [Token('PNAME_LN', ':z')])])])])])

**When I used the venv today:**
Tree(Token('RULE', 'turtle_doc'), [Tree(Token('RULE', 'directive'), [Tree(Token('RULE', 'sparql_prefix'), [Token('__ANON_2', 'PREFIX'), Token('PNAME_NS', ':'), Token('IRIREF', '<http://example/>')])]), Tree(Token('RULE', 'triples'), [Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':s')])]), Tree(Token('RULE', 'predicate_object_list'), [Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':p')])]), Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':o')])])])]), Tree(Token('RULE', 'triples'), [Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':a')])]), Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':q')])]), Tree(Token('RULE', 'quotation'), [Token('ANGLEBRACKETL', '<<'), Tree(Token('RULE', 'triples'), [Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':s')])]), Tree(Token('RULE', 'predicate_object_list'), [Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':p')])]), Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':o')])])])]), Token('ANGLEBRACKETR', '>>')])]), Tree(Token('RULE', 'triples'), [Tree(Token('RULE', 'quotation'), [Token('ANGLEBRACKETL', '<<'), Tree(Token('RULE', 'triples'), [Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':a')])]), Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':q')])]), Tree(Token('RULE', 'quotation'), [Token('ANGLEBRACKETL', '<<'), Tree(Token('RULE', 'triples'), [Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':s')])]), Tree(Token('RULE', 'predicate_object_list'), [Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':p')])]), Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':o')])])])]), Token('ANGLEBRACKETR', '>>')])]), Token('ANGLEBRACKETR', '>>')]), Tree(Token('RULE', 'predicate_object_list'), [Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':r')])]), Tree(Token('RULE', 'iri'), [Tree(Token('RULE', 'prefixed_name'), [Token('PNAME_LN', ':z')])])])])])

**the node changed from string to Token('RULE', string), e.g. 'turtle_doc' to Token('RULE', 'turtle_doc') and when I called lark.reconstruct.Reconstructor to the new tree it throws AssertionError**

self = <lark.reconstruct.Reconstructor object at 0x0000019BF688D5F8>
parser = Lark(open('<string>'), parser='lalr', lexer='contextual', ...)

    def __init__(self, parser):
        # XXX TODO calling compile twice returns different results!
>       assert parser.options.maybe_placeholders == False
E       AssertionError

..\..\Anaconda3\lib\site-packages\lark\tree_matcher.py:91: AssertionError

I have to roll back to 0.11.2 to make it work

**Comment by erezsh** [comment]
`lark-parser` is the old package name. The new package name is `lark`. Perhaps another package installed it, and caused a version conflict that you weren't aware of.

You can tell which one is active if you do `import lark; lark` and look at the path. Also `lark.__version__` will tell you which version you're actually using.

**Comment by alooba1** [comment]
Thank you for your reply. I am just confused why the behavior changed. So the parsing result is supposed to be T**_ree(Token('RULE', 'turtle_doc'), [Tree(TokToken('RULE', 'turtle_doc'), [Tree(Tok_** ..... instead of **_Tree('turtle_doc', [Tree('directive', [Tr_** in the latest version? But this breaks the Reconstructor somehow

For the version issue, I print out lark.__version__ gives me 1.1.2. 

But when I do pip install lark -> it gives me Tree(Token('RULE', 'turtle_doc'), instead of Tree('turtle_doc' as it behaved before

I tried pip uninstall lark and pip install 'lark == 1.1.1', it gives me Tree(Token('RULE', 'turtle_doc')

I had to pip uninstall lark-parser and pip install 'lark-parser == 0.11.2' to roll back to previous behavior which is Tree('turtle_doc'

**Comment by alooba1** [comment]
and actually I never imported lark-parser in codes,
I did 

import lark

from lark import (
    Lark,
    Transformer,
    Tree,
)

from lark.visitors import Visitor

from lark.reconstruct import Reconstructor

from lark.lexer import (
    Token,
)

**Comment by erezsh** [comment]
I can't say from memory if this change is on purpose or not.

But keep in mind that `Token('RULE', 'turtle_doc') == 'turtle_doc`, and both would return `isinstance(x, str) == true`. So maybe it's not a big deal?

**Comment by alooba1** [comment]
Problem solved,
Sorry I didn't read the error carefully, the error is actually assert parser.options.maybe_placeholders == False, so when I add maybe_placeholders = False to parser it gives me no error now. I think the default setting of maybe_placeholders is turned to True in latest version somehow

**Comment by erezsh** [comment]
Yes, we changed it for version 1.0. You can read all the breaking changes here: https://github.com/lark-parser/lark/releases/tag/1.0.0
