### ISSUE TITLE
Dealing with nested comments

### ISSUE THREAD

**Issue by ColMcp** [lark-parser/lark#1143]
**What is your question?**

What is the recommended way to deal with (ie ignore) nested C-style comments (`/* ... /* ... */ ... */`) using Lark's LALR parser?

I tried defining a token for the start-of-comment (`/*`) and having a lexer_callback function manually scan the following text and replace inner `/*` and `*/` with spaces. It then constructed and returned a Token instance covering the whole of the outer comment but I think it was ignored - understandable, I suppose, since I was using a `%ignore` directive.

**Comment by erezsh** [comment]
I think your best bet is to do it by writing a postlexer.

**Comment by ColMcp** [comment]
Thank you! I had missed this when reading the documentation.
