### ISSUE TITLE
Nested Transformers

### ISSUE THREAD

**Issue by jhallqvist** [lark-parser/lark#1144]
Hi,

I am attempting to build a parser that transforms ISC Bind into json and have run into a wall. 
In the text I am parsing there can be several instances of a certain clause but these clauses does not have a piece of text that I can use as a parent so I wish to inject a parent key and add these clauses as entries in a list that acts as the value to the parent key.

I am utilising nesting of both transformers and grammars to keep things neater. If I assign the main_transformer to use the AclTransformer and call it it does produce the desired result but that would of course break the intent of gathering all transformers under the Storage transformer (as per the example of grammar composition). Would really appreciate any help.

my code:

main.py
```
from pathlib import Path
from lark import Lark
from lark.visitors import Transformer, merge_transformers
from transformers.acl import AclTransformer

__dir__ = Path(__file__).parent

class Storage(Transformer):
    def start(self, children):
        return children

main_transformer = merge_transformers(
                            Storage(),
                            acl=AclTransformer())


text = '''
acl "test" {
    !1.1.1.0/24;
    2.2.2.2;
    none;
    {
        !2001:af:3546::1/64;
        "Test String";
    }; 
    !{
        key MyKey;
        4.4.4.4; 
    };
};
acl "test2" { 4.4.4.4; };
'''

parser = Lark.open(__dir__ / 'grammars/main.lark')

tree = parser.parse(text)

print(tree.pretty())

transformed_tree = main_transformer.transform(tree)
# transformed_tree = AclTransformer().transform(tree)
```

transformers/acl.py
```
from lark.visitors import Transformer, merge_transformers
from .aml import AmlTransformer

class AclBaseTransformer(Transformer):

    def start(self, items):
        return {"name": items[0], "entries": items[1]}

    def name(self, items):
        return str(items[0])

class AclComposer(Transformer):

    def start(self, items):
        return {"acls": items}

middle_transformer = merge_transformers(
                            AclBaseTransformer(),
                            aml=AmlTransformer())

AclTransformer = merge_transformers(
                            AclComposer,
                            acl=middle_transformer())
```
transformers/aml.py
```
from lark import Transformer

class AmlTransformer(Transformer):

    def ip_prefix(self, items):
        if None in items:
            items.remove(None)
        return ("".join(items))

    def ip_addr(self, items):
        if None in items:
            items.remove(None)
        return ("".join(items))

    def key(self, items):
        if None in items:
            items.remove(None)
        return ("".join(items))

    def acl(self, items):
        if None in items:
            items.remove(None)
        return ("".join(items))

    def predefined(self, items):
        if None in items:
            items.remove(None)
        return ("".join(items))

    def list(self, items):
        result = {"negated": False, "entries": []}
        negated, items = items
        if negated is not None:
            result["negated"] = True
        for item in items:
            result["entries"].append(item)
        return result

    def start(self, items):
        return list(items)
```

Current output:
```
[
    {
        'acls': [
            Tree('acl__name', [Token('acl__QUOTED_STRING', '"test"')]),
            Tree('acl__aml__start', [Tree('acl__aml__ip_prefix', [Token('acl__aml__NEGATED', '!'), Token('acl__aml__IP_PREFIX', '1.1.1.0/24')]), Tree('acl__aml__ip_addr', [None, Token('acl__aml__IP_ADDR', '2.2.2.2')]), Tree('acl__aml__predefined', [None, Token('acl__aml__AML_PREDEFINED', 'none')]), Tree('acl__aml__list', [None, Tree('acl__aml__start', [Tree('acl__aml__ip_prefix', [Token('acl__aml__NEGATED', '!'), Token('acl__aml__IP_PREFIX', '2001:af:3546::1/64')]), Tree('acl__aml__acl', [None, Token('acl__aml__QUOTED_STRING', '"Test String"')])])]), Tree('acl__aml__list', [Token('acl__aml__NEGATED', '!'), Tree('acl__aml__start', [Tree('acl__aml__key', [None, Token('acl__aml__KEY_ID', 'key MyKey')]), Tree('acl__aml__ip_addr', [None, Token('acl__aml__IP_ADDR', '4.4.4.4')])])])])
        ]
    },
    {
        'acls': [
            Tree('acl__name', [Token('acl__QUOTED_STRING', '"test2"')]),
            Tree('acl__aml__start', [Tree('acl__aml__ip_addr', [None, Token('acl__aml__IP_ADDR', '4.4.4.4')])])
        ]
    }
]
```

Desired output would look like this:
```
{
    'acls': [
        {
            'name': '"test"',
            'entries': [
                '!1.1.1.0/24',
                '2.2.2.2',
                'none',
                {
                    'negated': False,
                    'entries': [
                        '!2001:af:3546::1/64',
                        '"Test String"'
                    ]
                },
                {
                    'negated': True,
                    'entries': [
                        'key MyKey',
                        '4.4.4.4'
                    ]
                }
            ]
        },
        {
            'name': '"test2"',
            'entries': [
                '4.4.4.4'
            ]
        }
    ]
}
```

**Comment by erezsh** [comment]
It's a little hard to understand what exactly is the problem that you're facing

**Comment by jhallqvist** [comment]
certainly:

>>> dir(AclTransformer)
['__abstractmethods__', '__class__', '__class_getitem__', '__default__', '__default_token__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__visit_tokens__', '__weakref__', '_abc_impl', '_apply_v_args', '_call_userfunc', '_call_userfunc_token', '_transform_children', '_transform_tree', 'acl__aml__acl', 'acl__aml__ip_addr', 'acl__aml__ip_prefix', 'acl__aml__key', 'acl__aml__list', 'acl__aml__predefined', 'acl__aml__start', 'acl__name', 'acl__start', 'start', 'transform']

**Comment by erezsh** [comment]
Oh, but you're running `main_transformer`... which probably renames everything to the acl namespace.

Notice how you have two `acl=`, which means `acl__name` gets renamed to `acl__acl__name`

**Comment by erezsh** [comment]
(But the grammar only has one level of `acl` namespace)

**Comment by jhallqvist** [comment]
I figured it might be something like that and thanks for confirming it. The thing is I could not (and still can't) figure out how to do it any other way. Do I need another level of grammar just to tie this up or is there another option?

**Comment by erezsh** [comment]
The question for me, is first of all, why do you have this

```python
middle_transformer = merge_transformers(
                            AclBaseTransformer(),
                            aml=AmlTransformer())

AclTransformer = merge_transformers(
                            AclComposer,
                            acl=middle_transformer())
```

instead of this

```
AclTransformer = merge_transformers(
                            AclBaseTransformer,
                            aml=AmlTransformer())

```
?

**Comment by jhallqvist** [comment]
I tried with just the AclTransformer first and tried to modify the start method to add children to the parent key of "acls". But I could not get it to work so I assumed that the AclTransformer was per matched clause and I might need another transformer one level higher so to speak to handle the parent key. 

But should I be able to do this in the AclTransformer?

**Comment by erezsh** [comment]
Well, I don't see your grammar, so I can't say for sure. But if you should be able to do it either in AclTransformer or in Storage.

**Comment by jhallqvist** [comment]
I did try to modify the Storage class first but the issue was that I could not access children based on what transformer produced them or by namespace which led to an unsuccessful attempt to loop the children and take ones that matches certain criteria. It did not work as I had hoped. 
The issue being that only some children of the Storage class will be acls, there will be other types there so I can't just place all children in a parent key of "acls".

I could not get the AclTransformer to add all the acl parent key but perhaps I did not modify the grammar correctly.

I added the code to a public git repo so that you can see the grammar used as well.
https://github.com/jhallqvist/isc_lark

**Comment by jhallqvist** [comment]
It finally clicked what you said about the grammar. I got it working the way I wanted by doing some minor changes.

acl.lark
```
start: "acl" name "{" aml__start "}" ";"
```

became

```
start: acl+

acl: "acl" name "{" aml__start "}" ";"
```

and the transformer in acl.py
```
class AclBaseTransformer(Transformer):

    def start(self, items):
        return {"name": items[0], "entries": items[1]}

    def name(self, items):
        return str(items[0])
```
became
```
class AclBaseTransformer(Transformer):

    def start(self, items):
        return {"acls": items}

    def acl(self, items):
        return {"name": items[0], "entries": items[1]}

    def name(self, items):
        return str(items[0])
```


And presto! It turned out just like I wanted. Thanks so much for your help and thanks for a great project.

**Comment by erezsh** [comment]
Glad to hear it worked out!
