### ISSUE TITLE
Support error handling for custom errors

### ISSUE THREAD

**Issue by DecrepitHuman** [lark-parser/lark#1145]
**Suggestion**
Support catching raised errors through the `<Lark>.parse("...", on_error=...)` function.
Specifically in the `on_error` callback.

**Describe alternatives you've considered**
Considered [this](https://lark-parser.readthedocs.io/en/latest/examples/advanced/error_reporting_earley.html) example, however this becomes nasty on a complex grammar

**Additional context**
Would like to raise a custom error extending the `UnexpectedInput` class or other alternative in a `Interpreter`-like class method

**Comment by DecrepitHuman** [comment]
```python
class SomeCustomError(UnexpectedInput):
    pass

def handler(e) -> bool | None:
    # Function catches the raised SomeCustomError

lark.parse("...", on_error=handler)
```
This wouldn't work as shown here since errors raised in a Interpreter class are different to errors raised while parsing, but I would like something similar for those raised errors.

**Comment by DecrepitHuman** [comment]
This wouldn't be necessary if there were some way to get the current line and column, something similar to `UnexpectedToken`'s `get_context` function (I think it was that, can't reference my code at the moment). As I've said above I do not at the moment require the `interactive_parser` so I don't think it's necessary to support that in this context

**Comment by erezsh** [comment]
So if I understand correctly, you want to throw exceptions while walking the tree with `Interpreter`, and you want those exceptions to have the line/column info, the same Lark's exceptions do?

**Comment by DecrepitHuman** [comment]
Yes, that way It's rather easy to implement good looking errors with enough information to be considered an actual error. Even if there is no handling or anything, I would definitely appreciate easy support for such systems

**Comment by erezsh** [comment]
If you use `propagate_positions=True`, the line information will be in each `tree.meta` attributes.

You can use the line information to create `UnexpectedInput` yourself, or subclass from it and throw that, and then you'll have get_context.

(just set state to None)

Maybe I'll add a function to utils that helps with that, but it will be very short, because it's simple logic.

**Comment by erezsh** [comment]
Yes, I'll just close it. You can keep commenting if you run into trouble.

**Comment by DecrepitHuman** [comment]
Running into difficulty, I would like to re-propose the idea something similar to `<Lark>.parse("...", on_error=...)` for the `Interpreter` class. There are often times where the class might hold a list or dictionary in which it becomes extremely tedious to check for lengths, and keys before accessing.

I'm currently handling this with a try/except on both `KeyError` and `IndexError`, however reporting on such errors in a nice way becomes extremely difficult without some context to the situation.
