### ISSUE TITLE
Release an old wheel please?

### ISSUE THREAD

**Issue by skieffer** [lark-parser/lark#1153]
Hello, and thank you for Lark! Great project!

I am wondering if you would be willing to please make a wheel available for version 0.6.7 on PyPI.

I have some old code that needs this version, and deployment would be much smoother if PyPI hosted a `.py3-none-any.whl` file.

I looked up how to add files to an existing release (maybe you already know how to do it, but to me it was not obvious), and it doesn't seem to be too hard. Apparently you can use the `--skip-existing` switch with `twine upload`.

Something like this would probably do it:

```shell
git checkout 0.6.7
python setup.py bdist_wheel  # or however you usually build
twine upload --skip-existing dist/lark_parser-0.6.7-py2.py3-none-any.whl
```

See:
* https://stackoverflow.com/a/52130985
* https://twine.readthedocs.io/en/latest/#twine-upload

**Comment by erezsh** [comment]
Done. Hope that helped.

**Comment by skieffer** [comment]
Thanks very much for your response!

The wheel file is not showing up at <https://pypi.org/project/lark-parser/0.6.7/#files>, and attempts to install from it are failing...

**Comment by erezsh** [comment]
Tried again, I'm getting `400 File already exists`.

Perhaps it would be best if you created your own fork for 0.6.7, and uploaded it to pypi as `lark-skieffer` (or similar)

**Comment by chanicpanic** [comment]
Looks like @erezsh uploaded it to PyPI under `lark`, not `lark-parser`.
https://pypi.org/project/lark/#files

**Comment by erezsh** [comment]
Oh, haha... my bad. Thanks for pointing it out.

**Comment by erezsh** [comment]
@skieffer Do you want it in `lark-parser`, or is `lark` good enough?

**Comment by skieffer** [comment]
Ah, I was actually not aware there was now a project called just `lark`. Looks like `lark` started at version `0.10.1`, so I guess the `0.6.7` wheel would make most sense under the old `lark-parser` project.

Now I'm worried about the 0.6.7 wheel appearing under lark 1.1.2. There must be some way to delete that...

**Comment by erezsh** [comment]
No worries, I deleted the file from 1.1.2.

But I'm not sure how to upload to 0.6.7, maybe it's not even possible.
