### ISSUE TITLE
Standalone does not include `load_grammar`

### ISSUE THREAD

**Issue by BlueDrink9** [lark-parser/lark#1155]
**Describe the bug**

Lark 1.1.2, installed via pip, creates a standalone without the function `load_grammar` defined.

**To Reproduce**

Create a grammar 
```
start: "a"
```

Build in cmd.exe with `python -m lark.tools.standalone grammar.lark > standalone.py`

Opening the file, there is one call to `load_grammar`, and no definition

**Comment by BlueDrink9** [comment]
This has been a bug since 0.7.1 😰 a bit disheartening that no-one has reported it before this - standalone is such a great feature I would have expected it to get used a lot!

**Comment by MegaIng** [comment]
But does `load_grammar` actually get called? Yes, the call to it is in the file, but a call that doesn't get executed is irrelevant (unless you insist of putting it though a linter in which case just don't). standalone generation is part of our test suite, so it works for sure. What python error are you getting for what python code using the generated parser?

**Comment by BlueDrink9** [comment]
Bisected to one of 3c64c56, 94e15fb, or d13ebb9

**Comment by BlueDrink9** [comment]
I'm getting "name 'load_grammar' is not defined"

**Comment by BlueDrink9** [comment]
Very pleased to hear the standalone is in the test suite. Hoping that means it's a problem I can fix at my end

**Comment by MegaIng** [comment]
With what python code? It's hard to fix a bug that we can't reproduce.

**Comment by BlueDrink9** [comment]
Nope, minimal reproduction also fails.

```python
import standalone as lark
Parser = lark.Lark('start: "a"')
Parser.parse("B")
```

**Comment by BlueDrink9** [comment]
Could it be to do with being on Windows? Assuming dev and tests are Nix?

**Comment by MegaIng** [comment]
Yes, because that is not how you are supposed to be using the standalone parser. You are supposed to call `Lark_StandAlone` without an argument for the grammar, the grammar is part of the standalone after all.

**Comment by BlueDrink9** [comment]
Ah, thank you. The docs said it was the same interface, and I assumed that extended to init

**Comment by BlueDrink9** [comment]
Sorry, one other question if I may: is it possible to specify the parser (`parser='lalr'` or default) with the standalone?

**Comment by erezsh** [comment]
The standalone *must* be LALR, it doesn't support other parsers.

**Comment by BlueDrink9** [comment]
That's quite important, I think. But I couldn't find it documented anywhere. If it is, and I missed it, perhaps it should be made more prominent. Unless I'm wrong, the default without standalone is Earley? So I think it is very important to note that the standalone must be compatible with the non-default option.

**Comment by erezsh** [comment]
https://lark-parser.readthedocs.io/en/latest/tools.html

First line in the page

**Comment by BlueDrink9** [comment]
I see, thank you. I still think you should highlight that that is different to the default - it's entirely plausible someone might not bother to understand the difference if they get a working parser without thinking about whether they're using LALR or Earley.

Personally, I followed the blog post to set mine up, which I believe was written before Earley became the default, and doesn't mention the difference.

Thanks for your time addressing this. I hope I'm not coming across as just another ignorant user - I read almost every page of the docs, but the subtle differences have escaped me.

**Comment by erezsh** [comment]
No worries, thanks for your input. I think it's natural to miss things when reading so many pages of docs (it also says lalr only in the main [README](https://github.com/lark-parser/lark#lark---a-parsing-toolkit-for-python). I can't say how common that confusion is, or what's the best way to address it. Either way, I'm open to suggestions.

(Earley was always the default parser.)

**Comment by BlueDrink9** [comment]
I think it would be sufficient, or at least better, to explicitly mention that the default parsing method is not supported by the Standalone - perhaps with advice that users test their grammar to ensure it is parsable with `parser='lalr'` before using the standalone
