### ISSUE TITLE
Changing file-extension for standalone grammar definitions from .g?

### ISSUE THREAD

**Issue by RobRoseKnows** [lark-parser/lark#116]
Currently standalone files like [common](https://github.com/erezsh/lark/blob/master/lark/grammars/common.g) and the example [json](https://github.com/erezsh/lark/blob/master/examples/standalone/json.g) use the file extension `.g`. However, it looks like `g` is [already associated](http://filext.com/file-extension/G) with the [ANTLR](http://www.antlr.org/) parser. While I suppose it's possible to make Lark compatible with ANTLR, in the meantime it's probably best to use a different file extension. I would propose the extension `lrk` as it [doesn't seem](http://filext.com/file-extension/lrk) to be used by anything currently. 

I'm about to submit a pull request to change the file extensions to `.lrk` in the relevant file names and in the code referencing the `.g` extension. It's on a separate branch so if you want to use a different extension that should be easy enough to change.

**Comment by erezsh** [comment]
I appreciate your intention to improve Lark, but I'm strongly against your suggestion to change the file extension for grammars.

1) Lark's grammar syntax is similar enough to ANTLR's, that the default syntax highlighting mostly works out of the box in vim and other editors. That includes comments, strings, most operators, and differentiation between rules and terminals.

2)  .g stands for grammar. Just because ANTLR used it first, doesn't mean Lark has to avoid it. Also, fileext.com is an [outdated](https://www.fileext.com/file-extension/md.html) site, to say the least. You shouldn't take it too seriously.

**Comment by RobRoseKnows** [comment]
I see your point regarding fileext.com, but that was just the first google result, there are other sites that show .lrk as not used by any similar programs. Regarding your first point though, if ANTLR grammars are similar but not cross-compatible with Lark, that seems to me to be _more_ of a reason to change the extension, that way people won't try to use a Lark grammar in ANTLR or an ANTLR grammar in Lark expecting them to work.

Additionally, it means that if someone wrote a syntax highlighter specific to Lark for Vim, Sublime, etc. it wouldn't be able to work automatically for Lark files, especially since [ANTLR highlighting](https://github.com/dylon/vim-antlr/blob/master/syntax/antlr3.vim#L75) triggers based on file extension. 

I also don't think ANTLR3/4 highlighting works out of the box in Sublime or Vim anyway. When loading `common.g` and using `:echo b:current_syntax`, it returns `pccts` which is [an older version](http://www.antlr2.org/pccts133.html) of ANTLR, and the syntax file was last modified in 1999, which isn't up-to-date with ANTLR3 or 4 which are the most recent versions. And it doesn't change anything at all when using Sublime 3.

It's up to you, but I think it's worthwhile changing the file extension, especially since new syntax highlighting files should be easy enough to write using what currently exists for ANTLR.

**Comment by erezsh** [comment]
If and when someone writes syntax highlighting for Lark for popular editors, I'll reconsider my position.

**Comment by dirk-thomas** [comment]
I am using Atom with the [language-antlr](https://github.com/dbrabera/language-antlr) for highlighting `.g` files. One of my Lark grammar files contains something like this:

```
_SINGLE_QUOTE: "'"
```

After that point in the file the highlighting is broken since the language package considers the single quote as the start of a string. Reading a bit about ANTLR I found the [following definition](https://github.com/antlr/antlr4/blob/master/doc/lexicon.md#literals) about the grammar format:

> All literal strings one or more characters in length are enclosed in single quotes such as `’;’`, `’if’`, `’>=’`, and `’\’` (refers to the one-character string containing the single quote character).

On the other hand Lark uses double quotes for string literals (as decribed in the [wiki](https://github.com/erezsh/lark/wiki/Grammar-Reference#terminals)). I have tried to use single quotes instead but that doesn't seem to be supported.

So currently ANTLR and Lark seem to use a different character for quoting string literals. In order to use the same highlighter:
* the highlighers written for ANTLR would need to be changed to also allow double quotes (not sure how likely that is since they target ANTLR and comply with their format)
* Lark could support single quotes as an alternative to double quotes

Otherwise a separate highlighter might be necessary to handle these differences.

**Comment by erezsh** [comment]
Seems like I was misinformed. Vim uses the pccts syntax for .g files. It is antlr's predecessor, and it does indeed use double-quotes for strings (it's such a vaporware that it took some digging to confirm this). But you're right, antlr's grammar is different than lark's.

So, maybe changing the file extension is a good idea after all. I'm thinking `.lark` or `.lr` could work.

@RobRoseKnows @dirk-thomas  Would any of you like to help me create a syntax file for your favorite editor if I do? (My guess is that together we might have vim, atom & sublime covered)

Meanwhile,  I just want to make sure that you know, you can use whatever file extension you like, lark will still work :)

**Comment by erezsh** [comment]
Also, sorry @RobRoseKnows, just realized that you wrote about pccts in your comment. I didn't know it's that different from antlr.

**Comment by RobRoseKnows** [comment]
@erezsh That's alright. I can take a look at Vim and Sublime. Since ANTLR is similar enough to Lark, it shouldn't be terribly hard to modify. It looks like my PR to change the file extension is still mergeable, which is good. It may also be a good idea to keep `.g` extensions valid at least until the `0.6.0` release, and add in a warning that they'll be deprecated in the future for `0.5.7`.

**Comment by erezsh** [comment]
@dirk-thomas @RobRoseKnows 
Fantastic! If you have these 3 covered, I can do vscode. And I don't mind bumping to 0.6.0 soon. There are other breaking changes I'm looking to make, so it could be a good opportunity.

Also, I noticed that although the grammar is similar to ANTLR, It's also very similar.. to Perl !

* Perl has both "strings" and /regexps/i

* Perl also differentiates between lowercase and UPPERCASE

And all editors have it. So perhaps you can use the perl syntax file for some quick-and-easy copy pastes.

Anyway, write them in your free time, and I'll add them to the README. When they're all done, I'll bump the version and update the docs.

P.S. I gave it some thought, and I think `.lark` is the best choice. It's clear, simple, and google-able.

Cheers,
Erez

**Comment by erezsh** [comment]
@RobRoseKnows  I feel like an organization might be an overkill for Lark at the moment. Unless you think it has important features? And won't moving the repo break existing links from blogs?

> I can edit my PR as well

Sure, that would be nice.

Thanks!

**Comment by RobRoseKnows** [comment]
@erezsh Hey, wanted to give you an update. I'm working on the Sublime package first. I have a few questions regarding the Lark grammar though, have you written a standalone `.g`/`.lark` grammar to define the grammar? 

Also I'm not quite sure what lines starting with question marks are supposed to be. EBNF defines question marks as starting/ending special sequences but that doesn't really make sense here and I can't find it defined in the documentation page @dirk-thomas posted earlier.

**Comment by erezsh** [comment]
@RobRoseKnows 

Lines starting with question marks are a prefix for tree construction, meaning that the rule will be expanded if it has only 1 child.

The only grammar definition is here: https://github.com/erezsh/lark/blob/master/lark/load_grammar.py#L64

But you can also find this information here:

* https://github.com/erezsh/lark/wiki/Grammar-Reference

* https://github.com/erezsh/lark/wiki/Tree-Construction

Perhaps it would be useful if I made a cheatsheet containing all the features in a condensed format?

**Comment by RobRoseKnows** [comment]
@erezsh Ah thanks. Yes a cheatsheet could help, I also think since Lark is adopting a separate file type now, a potentially useful example grammar definition could be a grammar defining Lark itself. I would assume that it is probably possible to write something like that given that you define it in `load_grammar.py`. I know Nearley now [bootstraps itself](https://github.com/kach/nearley/blob/master/lib/nearley-language-bootstrapped.ne), but I don't really know if that would be useful for Lark.

I've also looked at the syntax highlighting that was written for Nearley.js for ST3 and it's possible I may be over-engineering the highlighter. It seems like many of Sublime's syntax features aren't strictly necessary. So I may end up simplifying the definition by quite a bit.

**Comment by dirk-thomas** [comment]
> I am happy to create a language package for Atom.

I might have to revise my previous offer. I have started evaluating VSCode since then and it seem to address some of my issues with Atom. So it is likely that I will switch all the way and not put any more effort into Atom packages.

@erezsh Do you still want to work on an extension for `code`? If not I could give that one a try. I just ported my `empy` package from `Atom` to `code` and it seemed pretty straight forward...

**Comment by erezsh** [comment]
@RobRoseKnows  I'm not a big fan of Nearley's bootstraping. Iirc they use a compiled version of the grammar to parse the grammar, which I find a bit opaque and inflexible. But it's shouldn't take long to create a grammar definition for lark in lark, just for the heck of it.

@dirk-thomas  Sure that's fine, go ahead and do vscode. I don't mind doing whatever is left.

**Comment by RobRoseKnows** [comment]
@erezsh Yeah, I understand what you mean regarding bootstrapping. But a Lark grammar in Lark would definitely be a worthwhile example IMO. I also may change up how I'm doing the syntax highlighting, as I'm not sure if it's necessary to use all of ST3's features to highlight the syntax.

**Comment by dirk-thomas** [comment]
I created a first version for language support of Lark in VSCode: https://github.com/dirk-thomas/vscode-lark I always find it difficult to choose the scope selectors though...

**Comment by Danmou** [comment]
Hey I just created Sublime Text syntax for Lark grammars which can be found here: [https://github.com/Danmou/lark_syntax](url), or on package control once they approve my PR.

I based it off another EBNF syntax, although I had to modify it quite a bit to work without semicolons and with regexes. It's a bit hacky in places but it works with all the official Lark examples.

**Comment by erezsh** [comment]
Very nice!
Would you be interested in moving it to the lark-parser organization?
@RobRoseKnows What do you think, perhaps you could code-review it?

**Comment by Danmou** [comment]
> Would you be interested in moving it to the lark-parser organization?

Sure! How do we proceed?

Also, can you point me to some more examples of complex Lark grammars, so I can check that it highlights them correctly?

**Comment by RobRoseKnows** [comment]
@erezsh I took a quick look and it looks like it should work fine. It's using an older (but still supported) version of Sublime's highlighting, so I'll continue working on the version I was making because I think using the new version also adds stuff auto-complete wise. Only thing is I would remove the `.g` file type since that's associated with ANTLR. I submitted a PR to do that.

@Danmou You should be able to use some of the examples in this repo under examples to test. The Python grammar isn't complete AFAIK, but it should be syntactically correct, so you can test it on that.

As for moving the repo to the lark-parser, if you go to the settings tab, in the danger zone it should let you change the owner.

**Comment by erezsh** [comment]
I'm going to change the file extension in 0.6.0, which should happen soon enough. You can assume it's `.lark` for your highlighter.

**Comment by erezsh** [comment]
Hey guys, how are the highlighters coming along? Anything I can help with?

On my end, the 0.6.0 release is almost done, with redesigned transformers and a few bugfixes.

@dirk-thomas Would you like to move the vscode highlighter to the lark-parser organization?

@RobRoseKnows Do you still intend to write the highlighter for vim?

(There's no hurry, I'm just checking where we're at.)

**Comment by erezsh** [comment]
@RobRoseKnows 
Not sure if you still need it, but I made a cheatsheet: https://github.com/lark-parser/lark/blob/master/docs/lark_cheatsheet.pdf

**Comment by dirk-thomas** [comment]
I moved the repo to https://github.com/lark-parser/vscode-lark.

**Comment by erezsh** [comment]
@RobRoseKnows Yes, the 0.6.0 update is practically ready. I'm going to merge it soon.

**Comment by erezsh** [comment]
Merged.
