### ISSUE TITLE
ambiguity and whitespace with lalr

### ISSUE THREAD

**Issue by gitshub** [lark-parser/lark#1161]
Hi,
I am trying to understand ambiguity and whitespace in an lalr(1) parser.  The first program works as I would expect, but the second fails on input "a ".  Could anyone tell me why?   By the way, they both work as I would expect under Earley (not lalr(1)) in the Lark IDE https://www.lark-parser.org/ide/.  Also, this probably should have been a discussion, not an issue, but I don't think I can move it to "discussions" myself, so if someone else can, that's fine with me.  Thanks.

This program works as expected:

```python
from lark import Lark

grammar = '''

start:  alternative_1  | alternative_2 

!alternative_1: "a"  WS

!alternative_2: "a"  WS "b" WS

%import common.WS
'''
text = "a "    #returns Tree(Token('RULE', 'start'), [Tree(Token('RULE', 'alternative_1'), [Token('A', 'a'), Token('WS', ' ')])])
	
#text = "a b " #returns Tree(Token('RULE', 'start'), [Tree(Token('RULE', 'alternative_2'), [Token('A', 'a'), Token('WS', ' '), Token('B', 'b'), Token('WS', ' ')])])

parser = Lark(grammar,parser='lalr')
print(parser.parse(text))
```
This program fails on input "a ":

```python
from lark import Lark

grammar = """

start: alternative WS

!alternative: "a"  | "a" WS  "b"        // fails on input  "a ",           works on "a b " 

%import common.WS
"""

text = "a " 
''' returns 
				KeyError: '$END'
				Expected one of:
				   * B
'''

#text = "a b " # returns Tree(Token('RULE', 'start'), [Tree(Token('RULE', 'alternative'), [Token('A', 'a'), Token('WS', ' '), Token('B', 'b')]), Token('WS', ' ')])

parser = Lark(grammar,parser='lalr')
print(parser.parse(text))
```

**Comment by erezsh** [comment]
In your second example, there is a shift/reduce conflict. There is a way to see it:

```python
import logging
from lark import Lark, logger
logger.setLevel(logging.DEBUG)
...
parser = Lark(grammar,parser='lalr', debug=True)
```

It will output:

```
Shift/Reduce conflict for terminal WS: (resolving as shift)
 * <alternative : A>
```

By default, Lark chooses shift, same as PLY. You can change it using priority. But better to avoid if you can.

**Comment by erezsh** [comment]
Try raw strings:

grammar = r"""

**Comment by gitshub** [comment]
I  managed to rewrite my main application's grammar so that the conflict disappeared, but someday I intend to study LALR parsing so I can actually understand your answer, which I'm sure is very helpful.  I found this site https://mdaines.github.io/grammophone/ which looks pretty neat. You can close this if you like, and thanks for your great parsing software.
