### ISSUE TITLE
LALR parser Reduce/Reduce collision in an unambiguous grammar

### ISSUE THREAD

**Issue by IsaacBreen** [lark-parser/lark#1166]
First, my sincere thanks to the contributors for sharing this excellent library with the community.

I'm raising this as a question rather than a bug, because I think it's more likely that I'm misunderstanding some important point about the LALR parser.

Consider the following unambiguous grammar:

```py
Lark(
  r"""
     start: x
     x: "a" | x "b" | y "," y
     y: "a" | y "b"
  """,
  parser='lalr'
)
```

This raises

```
GrammarError: Reduce/Reduce collision in Terminal('B') between the following rules:
	- <y : A>
	- <x : A>
```

I understand I could easily rewrite this trivial grammar in such a way that it doesn't raise the above. The trouble is that when I encounter this in a more complex grammar, it's not so easy for me to see how I could rewrite it in a valid way, perhaps because that I don't really understand the cause.

Where am I going wrong? Is this grammar ambiguous?

**Comment by IsaacBreen** [comment]
Welp, right after I wrote this up I realised this grammar _is_ ambiguous after all 🤦

**Comment by erezsh** [comment]
Yes, and the error is even relatively informative :)

But yeah, parsing is confusing!
