### ISSUE TITLE
Check expression in condition with Lark

### ISSUE THREAD

**Issue by ldevyataykina** [lark-parser/lark#118]
I try to check satisfied expression to condition

    from lark import Lark
    json_parser = Lark(r""" ?start: value
                        ?value: dict
                              | condition
                              | array
                              | STRING
                              | VARIABLE
                              | operator
                              | action_operator
                              | SIGNED_NUMBER      -> number
                              | "true"             -> true
                              | "false"            -> false
                              | "null"             -> null
                        
                        condition: "if" statement "then" result
                                |  "if" statement "then" result "except" statement result
                                |  "if" statement "then" result "elseif" statement ":" result
                                |  "if" statement "then" result "elseif" statement ":" result "else" result
                                |  "if" [statement "then" result ("elseif" statement ":" result)*]
                                |  "if" [statement "then" result ("elseif" statement ":" result)*] "else" result
                                
                        statement: expression == true
                        expression: VARIABLE action_operator (VARIABLE | SIGNED_NUMBER)
                        result: STRING | condition
                        array: "[" [value ("," value)*] "]"
                        dict: "{" [pair ("," pair)*] "}"
                        pair: STRING ":" value
               
                        VARIABLE: /[a-zA-Zа-яА-Я0-9_.-]+/
                        STRING: /[a-zA-Zа-яА-Я0-9_.-]+/
                        
                        ?operator: OPERATOR
                        OPERATOR: "+:"|":"
                        
                        ?action_operator: ACTION_OPERATOR
                        ACTION_OPERATOR: "<"|">"|"="|"=="|">="|"<="|"!="|"in"

                       
                        %import common.ESCAPED_STRING
                        %import common.SIGNED_NUMBER
                        %import common.WS
                        %ignore WS""", start='value')`

But it returns 
`GrammarError: Unexpected input '== tr' at line 21 column 46 in <string>`

Without expression' verification it returns strange tree to text `text = 'if a > 5 then if b > 10 then do elseif b < 5: do1 else do2 else false'`

**Comment by erezsh** [comment]
Just to make sure, you understand that the `[ .. ]` operator means everything inside is optional, right?

So something like:

                                |  "if" [statement "then" result ("elseif" statement ":" result)*]

Means that it can match just the "if" keyword.

**Comment by ldevyataykina** [comment]
@erezsh and can you say, how can I do this code executable? 
`if a > 5:
    if b > 10:
        print('do')
    elif b < 5:
        print('do1')
    else:
        print('False')`

**Comment by erezsh** [comment]
You mean, how to write an interpreter?

Maybe my blog post will be helpful: http://blog.erezsh.com/how-to-write-a-dsl-in-python-with-lark/
