### ISSUE TITLE
Unexpected input [tbnrf\"']

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [lark-parser/lark#1188]
Hi!

I am getting an error with the following terminal: `ECHAR : "\" [tbnrf\"']`

which is giving me an unexpected input error, but I do not see why.

What am I doing wrong?

Thanks,
Julián

**Comment by erezsh** [comment]
You could be doing a lot of things wrong :)

My guess is that you forgot to make your grammar a raw string (e.g. `r"start: ..."` )

**Comment by ArenasGuerreroJulian** [comment]
Thanks @erezsh 

My grammar is in a raw string. I think that the problem is with the `\`. The following is working:

`ECHAR  : "\"" /[tbnrf\"']]/`, that is, without the `\` it works.

Any idea of why `\` is producing this error?

**Comment by MegaIng** [comment]
What you have in your second comment is something else than what you have in your first post. The difference is the first string literal `"\""` vs `"\"`. The second one isn't correct I assume

**Comment by ArenasGuerreroJulian** [comment]
You are right, sorry I am new to lark.

Thanks,
Julián

**Comment by erezsh** [comment]
No worries! Glad to help.
