### ISSUE TITLE
How to cite Lark?

### ISSUE THREAD

**Issue by elichad** [lark-parser/lark#1195]
Is there an established way to cite the Lark project? Ideally a BibTeX snippet if you have one. I haven't been able to find any paper or references to how to cite Lark in the docs.

In case you haven't come across it, you might like to look into the [Citation File Format](https://citation-file-format.github.io) to help people to cite the code correctly (even if there's no accompanying paper).

**Comment by erezsh** [comment]
Lark is cited in this paper, maybe it will help: https://joss.theoj.org/papers/10.21105/joss.03497
