### ISSUE TITLE
Macroses support. Dynamic grammar

### ISSUE THREAD

**Issue by xor2003** [lark-parser/lark#1231]
I want to implement Macroses support for my masm parser. So is it possible to have kind of Dynamic grammar so I could add tokens at runtime?
Or check if token match with my handler? (If macros was defined several lines before)
It also might called custom matcher

**Comment by xor2003** [comment]
Probably postlex will help
https://stackoverflow.com/questions/68813599/lark-matching-custom-delimiter-multiline-strings

**Comment by erezsh** [comment]
@xor2003 Can you give an example of the new tokens you would like to create?

**Comment by xor2003** [comment]
LABEL: /[A-Z]+/
structdir: LABEL "struct"i structitem+ structend
structitem: LABEL TYPE VALUE
structusage: LABEL STRUCTNAME
%declare STRUCTNAME

Example:
abc STRUCT
      qwe DB 0
abc ENDS

Struct usage:
zxc abc

"abc" is a struct name defined above.      
I mean I need to dynamically update grammar at runtime like:
STRUCTNAME: "abc"
If I define new structure:
newone STRUCT
      somevar DB 0
newone ENDS
need to update:
STRUCTNAME: "abc" | "newone"

**Comment by erezsh** [comment]
There is no API for something like that, and I don't think it would be super simple to add.

But if you use the interactive parser, you can "pause" at each point, collect the structs as they get defined, and try to match STRUCTNAME yourself.

Here's a real-world example of how something like that might look: https://github.com/geographika/mappyfile/blob/master/mappyfile/parser.py#L235

**Comment by xor2003** [comment]
I tried like you suggested and but lexer raises exception 
"unexpected character"  before I got to parser. 
Trying to do it with postlex. Will put result here later
