### ISSUE TITLE
Can I display progress status of Lark().parse()?

### ISSUE THREAD

**Issue by quag-cactus** [lark-parser/lark#1237]
I have implemented a JSON converter for a unique format of text with a CLI using Lark. 
When I run `Lark().parse()` on a large file, I have to wait for several tens of seconds. 

Is there a way to get a progress status -- for example, by returning a generator that can be passed to tqdm? 

I am not having any issues with the speed of Lark. I just want to be able to inform the user that the program is running👍.

**Comment by erezsh** [comment]
Yes, see https://lark-parser.readthedocs.io/en/latest/classes.html#lark.Lark.parse_interactive

Your loop can look something like this:

```python
parser = Lark(..., parser="lalr")
ip = parser.parse_interactive(text)
for t in tqdm(ip.iter_parse()):
    pass

tree = ip.resume_parse()
```

**Comment by quag-cactus** [comment]
It's work fine. Thank you for the code!

Unfortunately, I could not find this useful function in the guide (it can be found in the more advanced case of Eerror handling).

How about adding it to the tutorial?

**Comment by quag-cactus** [comment]
Thanks for adding the tag.
It seems that a good answer has already been added to `doc/recipe.md` regarding this issue.

I am happy with the answers here and the documentation. Thank you!
