### ISSUE TITLE
Storing and/or passing data

### ISSUE THREAD

**Issue by vsraptor** [lark-parser/lark#1238]
In Lark parser how do I pass out of bound data to the Transformer, so I can process the text differently based on the value of the argument f.e.. lets say I **can** modify the Parser,  then i want a behavior as if ...

    parser.parse(txt, my_arg='blah')
    
    class Parser :
    
         def parse(self, txt, my_arg):
                ............
                self.transformer.my_arg = my_arg

    class T(Transformer):

         def block(self,items):
            if self.my_arg == 'blah' : ....
            else: ...

**Comment by erezsh** [comment]
Sorry I missed this question. Hopefully you figured out that you can give the Transformer any __init__ function you want :)
