### ISSUE TITLE
ignore.WS but still use it in some rules

### ISSUE THREAD

**Issue by vsraptor** [lark-parser/lark#1239]
Is there a way to in general ignore white space but use it for parsing in some rules ... f.e. i want to distinguish between sentence/s and a block of sentences

```

sentence : words+ "."
sentences : sentence+
block : NL NL sentences NL NL 

%ignore.WS
```

**Comment by erezsh** [comment]
Did you try giving NL a higher priority?

**Comment by vsraptor** [comment]
it worked, thanks
