### ISSUE TITLE
Match token only at the beginning of a line when %ignore.WS is in effect

### ISSUE THREAD

**Issue by vsraptor** [lark-parser/lark#1240]
How do you match token only at the beginning or the end of a **line** when %ignore.WS is in effect ?

      begin:  ^b ...
      end: ..... e$

???

Another quick one : 

     integer : /\d+/
     item: integer |  /\w[a-zA-Z0-9]*/

how to force Transformer:integer() to be called when the item is a number.
It seems that the 2 regexes are fused, so only item() is called !!

**Comment by MaxOstrowski** [comment]
I had to use `m` after the regular expression to get a line start working.
```
COMMENT: /^\*/m /[^\n]*/
%ignore COMMENT
```

**Comment by erezsh** [comment]
> It seems that the 2 regexes are fused

It only fuses them if you define item as ITEM (i.e. a terminal)
