### ISSUE TITLE
Q: using whitespace as an operator?

### ISSUE THREAD

**Issue by jnikula** [lark-parser/lark#126]
I'm trying to write a query language with boolean algebra. It seems to work as I intend, but I'd like to expand it to support whitespace as an implicit AND. For example, `foo bar OR baz` would mean `foo AND bar OR baz`. My attempts always seem to end up in some corner case blowing up spectacularly. My current working baseline grammar is:

```
query_grammar = '''
?sum: product
| sum _or product -> op_or

?product: term
| product _and term -> op_and

?term: query
| _not term -> op_not
| "(" sum ")"

_and: _WHITESPACE "and"i _WHITESPACE

_or: _WHITESPACE "or"i _WHITESPACE

_not: "not"i _WHITESPACE

?query: string -> op_query
| prefix ":" string -> op_prefix_query

?prefix: /[a-zA-Z0-9-]+/

?string: quoted_string | plain_string

?quoted_string: ESCAPED_STRING

?plain_string: /[a-zA-Z0-9.@_-]+/

%import common.ESCAPED_STRING
%import common.WS_INLINE -> _WHITESPACE
'''
```

Any suggestions?

**Comment by erezsh** [comment]
My impression is that using `%ignore` will solve all your problems.
Perhaps if you provide more examples of your query language, I will better understand your issue.

**Comment by jnikula** [comment]
Thanks for the prompt reply; I'm afraid that didn't help though. I think the problem is one of precedence. `foo OR bar baz` should be parsed as `foo OR (bar AND baz)` i.e. the implicit-AND should have more precedence than OR. But that leads to `foo OR bar` being interpreted as `(foo AND OR) AND bar`. Feels like I should prevent `plain_string` from matching any of AND, OR, NOT, but I'm not quite sure how, as a newbie to Lark grammar.

I'll provide more examples once I have a moment to extract some minimal reproducers from the bigger program.

**Comment by erezsh** [comment]
Well, the grammar isn't written correctly for this precedence to work. Try something like:

    ?or_expr:  [or_expr OR] and_expr

    ?and_expr:  expr+

**Comment by jnikula** [comment]
I solved this in the end, but it's not as pretty as I was hoping for. The relevant bits are:

```
?start: or_expr

?or_expr: [or_expr _OR] and_expr

?and_expr: [and_expr _AND] term

_AND: [_WHITESPACE "and"i] _WHITESPACE
```
i.e. you can leave out "and" if you like. But due to precedence this would make terms match the operators, so I had to add the IMO ugly bit:

```
?plain_string: /(?!(or|and|not))[a-z0-9.@_-]+/i
```

i.e. negative lookahead regex to not match the operators as terms. (Unless quoted, of course.)

**Comment by jnikula** [comment]
PS. I also struggled with why I originally couldn't make `_and` and friends proper uppercase terminals. The reason was, I couldn't combine case-insensitive `"string"i` with the "case-sensitive" `common.WS_INLINE`. I forget the error message, but it was less than helpful. I solved it by defining my own "case-insensitive" whitespace with `_WHITESPACE: /[ \t]+/i`.

**Comment by erezsh** [comment]
I appreciate your input, there's definitely room to improvement when it comes to error messages and handling of regex flags.

But I still don't understand why the negative lookahead is necessary. I'm pretty sure `"and"i` would take precedence over `plain_string`.

See for example this grammar, inspired by yours:

    >>> p = Lark("""start: expr ("and"i expr)*
    ...             expr: /[a-z0-9]+/i
    ...             %ignore " "
    ...          """)

    >>> print(p.parse("Hello and goodbye AND whatever").pretty())
    start
      expr	Hello
      expr	goodbye
      expr	whatever

**Comment by jnikula** [comment]
Here's a self-contained example as a python unittest: [space-as-and.txt](https://github.com/erezsh/lark/files/1934530/space-as-and.txt). It does what I need now, but suggestions for improvement are welcome. Feel free to close the issue.

I first looked at [boolean.py](https://github.com/bastikr/boolean.py) but found Lark much nicer (more than I need, to be honest, but it's not as limiting either). I use this to do boolean operations on python sets. I think a cleaned up version of the grammar here could be turned into a useful Lark example.

**Comment by erezsh** [comment]
I gave it a short try and couldn't get rid of the negative lookahead. I'll need to look deeper into it, perhaps it's a bug in the early prioritization.

Meanwhile, I did manage to make the grammar slightly simpler:

    ?start: or_expr

    ?or_expr: [or_expr "or"i] and_expr

    ?and_expr: [and_expr ("and"i|_WHITESPACE)] term

    ?term: query
    | "not"i term -> not_expr
    | "(" or_expr ")"

    ?query: string -> op_query
    | prefix ":" string -> op_prefix_query

    ?prefix: /[a-zA-Z0-9-]+/

    ?string: quoted_string | plain_string

    quoted_string: ESCAPED_STRING

    ?plain_string: /(?!(or|and|not))[a-z0-9.@_-]+/i

    _WHITESPACE: /[ \t]+/

    %import common.ESCAPED_STRING
    %ignore _WHITESPACE
