### ISSUE TITLE
UnexpectedToken when there should be no error

### ISSUE THREAD

**Issue by aha79** [lark-parser/lark#1284]
**Describe the bug**

Identical grammar gives "UnexpectedToken" error.

**To Reproduce**

Consider the following code
```python
    import lark

    grammar = r"""
    main: char*
        | "[" atom* "]"
    
    atom: SETCHAR
        | null_escape

    char: PATTCHAR
        | null_escape
        
    null_escape: "\\" "0"
    null_escape2: "\\" "0"

    SETCHAR: /[^\-\]\\]/                         // all except for  "]"   "-"  or "\" 
    PATTCHAR: /[^\^\$\\\.\+\?\*\(\)\[\]\{\}\|]/
    """
    parser = lark.Lark(grammar, start='main', parser="lalr")
    parser.parse("[\\0a]")
```

Raises error
```
lark.exceptions.UnexpectedToken: Unexpected token Token('PATTCHAR', 'a') at line 1, column 4.
Expected one of: 
	* SETCHAR
	* BACKSLASH
	* RSQB
```

However when I change to
```
    char: PATTCHAR
        | null_escape2   // note the "2" differently named but identical rule otherwise
```
no exception is generated.

Also when I omit the star in first rule, i.e. `main: char` no error is generated. However this changes the grammar of course.

I have no idea why this is the case, but I suspect this must be some kind of bug.

I use version 1.1.5.

**Comment by aha79** [comment]
Thank you for your prompt response.

I was (perhaps incorrectly) assuming that inside the ` "[" atom* "]" ` only the SETCHAR terminal is expected and hence only this token generated by the lexer. 

I solved it this way
```
    XCHAR: /[^\^\$\\\.\+\?\*\(\)\[\]\{\}\|\-]/
    
    pattchar: XCHAR
        | "-"
    setchar: XCHAR
        | /[\^\$\.\+\?\*\(\)\[\{\}\|]/
```
which is perfectly fine for me.

**Comment by erezsh** [comment]
> inside the "[" atom* "]" only the SETCHAR terminal is expected 

Lark can do that to some degree with LALR, but not perfectly. I think that they're both included because they are both in the FOLLOW set of `null_escape`.
