### ISSUE TITLE
Grammar Composition docs incorrectly rendered

### ISSUE THREAD

**Issue by wermos** [lark-parser/lark#1287]
**Describe the bug**

In the [Grammar Composition](https://lark-parser.readthedocs.io/en/latest/examples/index.html#grammar-composition) section of the Lark Examples, the text and subsections and everything looks like it didn't get rendered correctly. Here is a screenshot:
<img width="634" alt="image" src="https://github.com/lark-parser/lark/assets/63574588/c710706f-286a-4527-94d6-0345a5a2c2c0">

**To Reproduce**

Not applicable.

**Comment by erezsh** [comment]
Thanks for letting us know.

I fixed some of the issues. It's still not perfect, but I'm not sure how to fix the rest.

**Comment by erezsh** [comment]
There are still some CSS issues but I think it's probably good enough. If anyone wants to PR a fix for those, they are welcome to :)
