### ISSUE TITLE
propagate_positions isn't well documented

### ISSUE THREAD

**Issue by ningit** [lark-parser/lark#1293]
**Describe the bug**

The keyword argument `propagate_positions` of [Lark](https://lark-parser.readthedocs.io/en/latest/classes.html#lark.Lark) constructor is not obeyed. The attributes `line`, `column`, `end_line`, and `end_column` are not available in the `Tree` objects returned by `Lark.parse`.

**To Reproduce**

In the following code, the last two lines produce an `AttributeError: 'Tree' object has no attribute 'line'`, while they should return 1.

```python
import lark

grammar = '''
	%import common.WS
	%ignore WS

	%import common.INT -> NUMBER

	start: expr

	expr: NUMBER
	    | NUMBER "+" NUMBER
'''

parser = lark.Lark(grammar, parser='lalr', propagate_positions=True)
tree = parser.parse('1 + 2')

print(tree.children[0].children[0].line)
print(tree.children[0].line)
print(tree.line)
```

**Comment by erezsh** [comment]
It's tree.meta

**Comment by ningit** [comment]
Many thanks and sorry. Now I see this is mentioned in the documentation for the constructor of the [`Tree`](https://lark-parser.readthedocs.io/en/latest/classes.html#lark.Tree) class.

Anyhow, making explicit that these attributes are available through `meta` in the documentation of the `propagate_positions` option itself may avoid confusion and help users.

**Comment by erezsh** [comment]
@ningit  I added a PR https://github.com/lark-parser/lark/pull/1294

**Comment by ningit** [comment]
Great, it is now clearer. I think the PR solves the issue.

**Comment by erezsh** [comment]
Great! Added even more explanations too.
