### ISSUE TITLE
Grammar is case sensitive?

### ISSUE THREAD

**Issue by Michael0x2a** [lark-parser/lark#13]
I'm currently experimenting with `lark`, and am attempting to run the following code:

```python
from lark import Lark

grammar = '''
    Stmt: "foo"
'''

parser = Lark(grammar, start='Stmt')
```

This results in the following exception:

```
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\lark\parsers\lalr_parser.py", line 31, in get_action
    return states_idx[state][key]
KeyError: 'RULE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tester.py", line 81, in <module>
    parser = construct_parser(grammar, root)
  File "tester.py", line 77, in construct_parser
    return Lark(lark_grammar, start=root)
  File "C:\Python35\lib\site-packages\lark\lark.py", line 143, in __init__
    self.grammar = load_grammar(grammar, source)
  File "C:\Python35\lib\site-packages\lark\load_grammar.py", line 537, in load_grammar
    tree = self.simplify_tree.transform( self.parser.parse(grammar_text+'\n') )
  File "C:\Python35\lib\site-packages\lark\parser_frontends.py", line 31, in parse
    return self.parser.parse(tokens)
  File "C:\Python35\lib\site-packages\lark\parsers\lalr_parser.py", line 60, in parse
    action, arg = get_action(token.type)
  File "C:\Python35\lib\site-packages\lark\parsers\lalr_parser.py", line 35, in get_action
    raise UnexpectedToken(token, expected, seq, i)
lark.common.UnexpectedToken: Unexpected token Token(RULE, 'tmt') at line 2, column 6.
Expected: dict_keys(['_COLON'])
Context: <no context>
```

However, when I convert the phrase `Stmt` to `stmt`, the grammar starts working.

Is this behavior intentional? I didn't see anything in the documentation about this (unless I missed it?) and as far as I'm aware, both grammars are valid EBNF grammars -- the casing of the non-terminals and terminals should be irrelevant (at least, according to the EBNF specification on [wikipedia](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form#Examples)).

**Comment by erezsh** [comment]
Yes, the grammar is case sensitive.
Rules consist lowercase letters (such as stmt)
Terminals consist of uppercase letters (such as STMT)
This distinction is used in many parsers (such as yacc), and it affects the lexing stage (if any) and the resulting parse tree.
This is also explained in the json tutorial (https://github.com/erezsh/lark/blob/master/docs/json_tutorial.md)

**Comment by bjourne** [comment]
Can the tokens themselves in the grammar be case insensitive? It doesn't look like Lark can handle that.

**Comment by erezsh** [comment]
If you mean the terminal values, then yes, of course. You do it by adding "i" to the end of the string or regexp.

Examples:

    HELLO: "hello"i   // Match HELLO, Hello, hello, etc.
    REGEXP: /this is [also] case? insensitive/i

You can mix them too:

    some_rule: "Case Sensitive"  "insensitive"i  "Sensitive again"

Does that answer you question?

**Comment by bjourne** [comment]
thankyoU!

**Comment by rdeoliveira** [comment]
is there a global flag to set all terminals to be case insensitive?

**Comment by erezsh** [comment]
No. You can open an issue with that feature request.

**Comment by rdeoliveira** [comment]
Let me know please if [this issue](https://github.com/lark-parser/lark/issues/541) is not the right place/format for a feature request.

**Comment by erezsh** [comment]
Looks good.

**Comment by ctrlcctrlv** [comment]
This is the only thing I don't like about Lark.

Today I implemented a grammar described in the Unicode standard.

```yacc
// Grammar based on grammar in The Unicode Standard v13.0 (2020)
// ch. 18, sec. 2, "Ideographic Description Characters
//
// See http://www.unicode.org/versions/Unicode13.0.0/ch18.pdf p. 733

// Also, FYI, this library differentiates terminals/non-terminals by
// whether or not they're capitalized. ugh

?start              : icds*
icds                : UNICODE_CLASS
                    | IDS_BINARYOPERATOR icds icds
                    | IDS_TRINARYOPERATOR icds icds icds

UNICODE_CLASS       : IDEOGRAPHIC | RADICAL | CJK_STROKE | PRIVATE_USE | "\uFF1F"
IDEOGRAPHIC         : /[\p{Ideo}]/
RADICAL             : /[\p{Radical}]/
PRIVATE_USE         : /[\p{Private_Use}]/
CJK_STROKE          : "\u31C0" .. "\u31E3"

IDS_BINARYOPERATOR  : "\u2FF0" | "\u2FF1" | "\u2FF4" .. "\u2FFB"
IDS_TRINARYOPERATOR : "\u2FF2" | "\u2FF3"
```

It triggers my OCD big time that `icds` has to be like that. Not even trying to alias it with `-> IDS` works... 😖 

This is a great little library, but yeah, this part bites.

**Comment by MegaIng** [comment]
@ctrlcctrlv And what is your suggestion? Terminals are by definition regex. If you can't parse it with a regex, it can't be a terminal.

**Comment by ctrlcctrlv** [comment]
@MegaIng I suggest that aliases be allowed to go to a name of any casing.

**Comment by MegaIng** [comment]
@ctrlcctrlv @erezsh It might be interesting to consider this meaning 'combine everything into a single Token'.

this would mean: Just take all children, fully expand all sub trees, then join all tokens in a single token of name `IDS`. I will see if I manage to implement that.

Is backwards compatible, since the syntax was not allowed previously.

**Comment by erezsh** [comment]
@ctrlcctrlv I don't really understand the complaint. Using lowercase/uppercse for rules and terminals is a standard practice in many (if not most) parsing tools. Also, rules and terminals behave different, so it makes sense to differentiate between them somehow.

And actually, I think you're using too many terminals. For example, it makes more sense that `UNICODE_CLASS` will actually be a rule, because you would want to process the result afterwards, and to be able to know which of the terminals it consists of was actually matched.

@MegaIng  Not sure about your solution. Sounds a bit strange. If anything, it makes more sense to me that everything should be rules only, and we will automatically turn what we can into terminals. (ofc, that's not necessarily so simple to do)

**Comment by ctrlcctrlv** [comment]
I would prefer if the standard and my parser used the same names, is all. Also, with all due respect, you're wrong for this use case, I do want this many terminals, and each ideograph to be its own node on the tree. :-)
