### ISSUE TITLE
Possible bug in PropagatePositions class

### ISSUE THREAD

**Issue by stellabelin** [lark-parser/lark#1304]
Hi, thanks for your work with this library! When updating to lark 1.1.6 we started getting issues with our parser, and after digging I noticed that it's possible this line inputs the wrong variable: https://github.com/lark-parser/lark/blob/e4df0249c489d20c64222fd293b5cca4c3be4f27/lark/parse_tree_builder.py#L65
It should use `last_meta` instead of `first_meta`, right? When I tried changing it our parser worked as expected.

**Comment by erezsh** [comment]
Hi Stella! I believe you're right. Very embarrassing. Thanks for letting me
know!

**Comment by erezsh** [comment]
Fixed and released 1.1.7

Thanks again!

**Comment by stellabelin** [comment]
Great, thank you the fix and the quick response!
