### ISSUE TITLE
How to turn "RBRACE", "__ANON_n" into "{"?

### ISSUE THREAD

**Issue by aspizu** [lark-parser/lark#1316]
I want to get the value of the terminal from UnexpectedInput errors.

**Comment by erezsh** [comment]
I think you mean `UnexpectedToken`. Did you try `e.token.value`?

**Comment by aspizu** [comment]
```py
if isinstance(err, UnexpectedCharacters):
    expected = ", ".join(err.allowed)
    return Diagnostic(
        range,
        f"Expected one of: {expected}",
        DiagnosticSeverity.Error,
        "UnexpectedCharacters",
    )
```

`err.allowed` is `Set[str]`

I want to get the string which was defined in the grammar file from this list.

**Comment by erezsh** [comment]
Did you try `lark_instance.terminals` ?
