### ISSUE TITLE
Syntax breaks after escaped double quotes "\""

### ISSUE THREAD

**Issue by Fxztam** [lark-parser/lark#1318]
I am trying to define the double  quotes

DOUBLE_QUOTE: "\"" 

but the Syntax breaks after this escaped double quotes.

What can I do here?

Thanks, Fried

**Comment by MegaIng** [comment]
Please don't just duplicate an issue. Can you show a full example of what is going wrong? The syntax @erezsh showed you in your last issue does work. So why doesn't that syntax work for you? Make sure you are inside a `r""` raw string literal.

**Comment by Fxztam** [comment]
Please excuse my ignorance and the duplicate issue, the syntax works of course with the  `r''' .. '''`  raw string literal now.

Thanks again, Fried
