### ISSUE TITLE
Invalid document link.

### ISSUE THREAD

**Issue by cocolato** [lark-parser/lark#1335]
**Describe the bug**

The link in [Grammar Composition](https://lark-parser.readthedocs.io/en/latest/examples/index.html#grammar-composition) and  [example-grammars](https://lark-parser.readthedocs.io/en/latest/examples/index.html#example-grammars) will now report a 404 error.

![image](https://github.com/lark-parser/lark/assets/35182391/f450648a-eb0c-4976-ac0e-ca48eb21a258)

![image](https://github.com/lark-parser/lark/assets/35182391/b6b34fdd-86b3-4aed-8135-e0bf6bf7b825)

**To Reproduce**

https://lark-parser.readthedocs.io/en/latest/examples/index.html#grammar-composition

https://lark-parser.readthedocs.io/en/latest/examples/index.html#example-grammars

**Comment by erezsh** [comment]
Merged.
