### ISSUE TITLE
String definition from Python 3 issue with parse string '\' 

### ISSUE THREAD

**Issue by Fxztam** [lark-parser/lark#1336]
Hi,

I just encountered a problem with Lark's Python 3 string definition::

`string : /([ubf]?r?|r[ubf])('(?!'').*?(?<!\\)(\\\\)*?')/i
`

-> the parse string `'\'` does not work:

`lark.exceptions.UnexpectedCharacters: No terminal matches ''' in the current parser context, at line 9 col 25
`

                `   x := '\';`
                        ^
 ```
 Expected one of: 
	* /([ubf]?r?|r[ubf])('(?!'').*?(?<!\\)(\\\\)*?')/i
	* ...
```
I'm afraid I have an understanding problem with escaped strings.?

Here is an [example](https://www.fmatz.com/lark_example_02.txt)

Thanks,
Fried

**Comment by MegaIng** [comment]
Yes, `'\'` is not a valid string in python. This is the correct behavior.

**Comment by Fxztam** [comment]
It's nice to know.
Maybe there's a suggestion for the solution when parsing a non-Python language here, please?

**Comment by Fxztam** [comment]
I tied with [this](https://regex-vis.com/?r=%28%5Bubf%5D%3Fr%3F%7Cr%5Bubf%5D%29%28%27%28%3F%21%27%27%29.*%3F%28%5C%5C%5C%5C%29*%3F%27%29l)

`([ubf]?r?|r[ubf])('(?!'').*?(\\\\)*?'`

and it seems that works.

Thanks, 
Fried
