### ISSUE TITLE
Grammar reference is missing some details

### ISSUE THREAD

**Issue by Danmou** [lark-parser/lark#136]
Comparing the [Grammar Reference](https://github.com/lark-parser/lark/wiki/Grammar-Reference) in the wiki to the [reference grammar implementation](https://github.com/lark-parser/lark/blob/master/examples/lark.g), it looks like a few details are missing from the wiki:
* The last part of `?expr: atom [OP | "~" NUMBER [".." NUMBER]]` (I assume this is analogous to the regex `{1,2}` syntax)
* `STRING ".." STRING -> literal_range` (not sure how that works)

**Comment by erezsh** [comment]
Thanks, I added it now.
