### ISSUE TITLE
Partial parsing

### ISSUE THREAD

**Issue by Daniel63656** [lark-parser/lark#1367]
Is it possible to parse one token at a time, building a parse tree incrementally in the process? One could then also run a custom interpreter at each step. I know there is parser.parse_interactive() but it does not build the parse tree incrementally for some reason and therefore needs the type for each token as well.

**Comment by erezsh** [comment]
It does build the parse-tree incrementally. You can find it at `ip.parser_state.value_stack`, where `ip: InteractiveParser`. But it might be a bit tricky to use it effectively.

**Comment by Daniel63656** [comment]
I am a bit confused about this incremental parsing. I want to feed it one token at a time but it requires a Token class that also has a type. This type is the current production rule I guess? Why is this necessary when the parse tree is constructed incrementally? The current rule should be obvious then or not?

**Comment by erezsh** [comment]
Like you said, tokens have a type and a value. The value is the actual bit of text being parsed, and the type is the category of that text. The parser doesn't look at the value at all. It only looks at the type, in order to choose how to update the state-machine.

value_stack is a stack, of course.. it's a stack of trees (or tokens).

**Comment by Daniel63656** [comment]
Yes but I don't know the type. I just want to add tokens (values). I thought at first type have something to do with the rules they are used in but it's just another string that the parser uses instead of the actual (value) string. Seems kind of unnecessary. How would I even get these types?

**Comment by MegaIng** [comment]
You define them. In the grammar. In the above grammar, it's the `A`, `B`, `C`, i.e. the left side of the `:`. What exactly the token types are depends on your grammar. If you use literals directly in your grammar, lark with automatically choose names. If you print `parser.terminals`, you can see a list of all defined terminals. This isn't unnecessary: The parser doesn't care about the original text *at all*, it only cares about the token types. One token type can represent an infinite number of actual text strings. If you want to skip the lexer step, you need to do the step of the lexer and provide the token types.

**Comment by MegaIng** [comment]
> If a terminal only appears on the right side of productions like ".", "grace", or "flag" then they get their own new type like
DOT: "." or GRACE:"grace" ?

Yes, lark automatically gives names, as I mentioned before.

> Should I define them myself ?

That makes the names more predicable, but it's not necessary.

> does every non-terminal need a production rule like nonterminal:terminal to cover them

Not sure what you mean. Are you sure you are using the terms nonterminal and terminal correctly?

In lark, everything in uppercase is a terminal, everything in lowercase is a nonterminal.

> You said a lexer would typically do this. Can I then also partially lex one token at a time to get the type?

Sure, you can try use `parser.lex` for that.

**Comment by Daniel63656** [comment]
> Not sure what you mean. Are you sure you are using the terms nonterminal and terminal correctly?

I accidentally swapped the terms in that sentence

> Because lark couldn't find a better name. Every terminal needs a name.

But I defined a name: digit. That's kind of my point, if lark switches these names around then I can't reliably provide them myself. I didn't think of the Lexer. I thought a Lexer only breaks a string of tokens into individual tokens tbh. Is generating these types also part of lexing and will they then be the same as parsers?

**Comment by MegaIng** [comment]
> But I defined a name: digit

You defined a name for the *nonterminal*, not for the *terminal*. You need to define a name for the terminal, in uppercase.

**Comment by Daniel63656** [comment]
After searching the source code for a while I figured it is probably easiest to do this myself:

```
import re

class DynamicLexer:
    def __init__(self, terminals):
        self.terminals = [(terminals.name, terminals.pattern.to_regexp()) for terminals in terminals]

    def lex_token(self, token_string):
        for name, pattern_str in self.terminals:
            if re.fullmatch(pattern_str, token_string):
                return Token(name, token_string)
        raise ValueError(f"Token '{token_string}' could not be matched.")
        
        
        
# example usage
lexer = DynamicLexer(parser.terminals)
print(lexer.lex_token('bos'))
print(lexer.lex_token('bb'))
# expect this to raise error
print(lexer.lex_token('bbt'))
```

This very simple class uses the terminals from the parser (so they are always same as your defined grammar) and returns a correct token with type if and only if the token can be fully matched. No clue if this is redundant or something but I don't see how to make it work wit lark directly
