### ISSUE TITLE
custom importer ?

### ISSUE THREAD

**Issue by asmodehn** [lark-parser/lark#137]
I recently started working on a [lark grammar file importer](https://github.com/asmodehn/lark_import).
It's already working, but I was wondering : 

- if someone think it would be useful
- if anyone care at all about python2
- if it would be suitable (or not) to integrate with lark itself. If the interface becoming not a class but a module (cached) might be problematic ?
- if there were some usecase, to help drive the "language developer" features, so that the import actually helps experimenting with PEGs (instead of confusing anyone not deeply into python internals)
- if it would be better instead to have a way for lark users to load files in their own language, defined by a lark grammar...

Let me know your thoughts... and feel free to report/ask anything in issues.
Thanks !

**Comment by erezsh** [comment]
It's a neat trick, but I'm not sure how useful it is.

Not sure what you mean by PEGs? Lark doesn't support those.

> load files in their own language

What do you mean?

I think a possible direction for your project is to make it a general file-loading library, which can then be used by anyone who uses a non-python file. Then it could still be applicable to Lark, if anyone wanted:

```python
    import anyport
    lark_importer = anyport.importer('lark', Lark)

    with lark_importer(parser='lalr'):
        from . import calc
```

**Comment by asmodehn** [comment]
> Not sure what you mean by PEGs? Lark doesn't support those.

Sorry, I just began my travel in parser territory, reading different materials around. I am not familiar with the surroundings yet, and I used the wrong term. I meant **grammars**.

It might make sense indeed to make the importer work for ultimately _any_ python parser...

> > load files in their own language

> What do you mean?

This is related to what I am trying to achieve... It still is quite hypothetical but let's suppose : 
- I define a grammar in a .lark file. Lets say it s a lambda based programming language...

- I define a Transformer in python. For example something that interpret lambda expressions to python. Note, there could also be multiple layers of it, one reducing from s-expr to normal form ("compilation") and second translating from normal-form to python for interpretation...

- Then I would like to, somehow, be able to : 
```python
import anyport.lark_importer
with anyport.lark_importer(
    grammar='mylang',
    module_extension='mylang',
    parser='lalr',
    transformer=TransformChain()
):
    from . import module
```
It should find both `mylang.lark` and `module.mylang` from the current directory.
And upon import my `module.mylang` will be executed, by python (via the chain of transformers).

I think this would make it quite easy to embed DSLs into python...

While writing this it seems the importer behavior might somehow be linked to what the TransformChain is trying to achieve (compilation to bytecode, rewriting of file, etc.).
So probably the interface of the importer will be quite different in the end, and match more the interface of [importlib's SourceLoader](https://docs.python.org/3/library/importlib.html#importlib.abc.SourceLoader).

**Comment by erezsh** [comment]
> It might make sense indeed to make the importer work for ultimately any python parser...
I meant making it work for any python program, not just parsers.

I do think it has some potential as a general loader for project files. But it's a bit too complex and "edgy" to be part Lark.

I'm closing this issue. But if you ever do make it into a separate project, I might add it as an optional dependency to Lark and provide the api.

**Comment by asmodehn** [comment]
I did a little something over there : https://github.com/asmodehn/palimport

It gives the idea of what I "would like to have" when developing DSLs in python.
I tangled Lark and the import protocol together, and I could get an DSL module importable in python (grammar parsed by lark).

Have a look in the tests when you get the chance, and let me know what you think about all that... how much would be better in/out of lark.

It could be a part of lark, or it could be a project on its own, but I have little knowledge in parsers, and more interests in language semantics than parsing, so a very low probability of finding motivation to develop/maintain/advocate it.

**Comment by asmodehn** [comment]
The importer() method does nothing special. Just a [few lines](https://github.com/asmodehn/palimport/blob/master/palimport/lark/__init__.py#L22), all part of [documented way](https://www.python.org/dev/peps/pep-0302/#specification-part-2-registering-hooks) to customise your import system.

There is also potential simplification I could do in the finder/loader structure...

So, I understand I can start working on a PR for a lark grammar importer in lark repo. We will discuss more in details regarding the implementation there. I ll also add a few tests for it (using calc). It should be quite simple. How it will interface with the code will likely depend on how and for what aim people using lark will want to use it...
