### ISSUE TITLE
lark.exceptions.UnexpectedCharacters: No terminal matches ',' in the current parser context, at line 1 col 8

### ISSUE THREAD

**Issue by CanIbeyourdog** [lark-parser/lark#1383]
I get the following error when I run the self-query function in langchain，which relis on lark.

1.lark.exceptions.UnexpectedCharacters: No terminal matches ',' in the current parser context, at line 1 col 8

eq(year, '1928年') and eq(day, '1月')
       ^
Expected one of: 
        * LPAR

Previous tokens: Token('CNAME', 'year')

2‘lark.exceptions.UnexpectedToken: Unexpected token Token('COMMA', ',') at line 1, column 8.
Expected one of: 
        * LPAR
Previous tokens: [Token('CNAME', 'year')]

**Comment by MegaIng** [comment]
And have you already reported this with langchain? Why do you think this is a lark bug?
