### ISSUE TITLE
Parser error messages are not deterministic

### ISSUE THREAD

**Issue by RobertCraigie** [lark-parser/lark#1386]
**Describe the bug**

When a parse error occurs, the "Expected one of" part of the error message is not deterministic and changes order from time to time.

**To Reproduce**

My grammar is pretty small so I'm just including that as-is, this could likely be reproduced with a smaller grammar.

```py
parser = Lark(
    """
    start: "@" NAME "(" argument_list ")"

    argument_list: [argument ("," argument)* ","?]

    argument: key ":" value

    key: CNAME
    value: ESCAPED_STRING | CNAME

    NAME: /[A-Za-z_][A-Za-z0-9_]*/
    CNAME: /[A-Za-z_][A-Za-z0-9_]*/

    %import common.ESCAPED_STRING
    %import common.WS
    %ignore WS
    """,
)
parser.parse("""@Python(foo: 1)""")
```
It will sometimes output:

```
lark.exceptions.UnexpectedCharacters: No terminal matches '1' in the current parser context, at line 1 col 14

@Python(foo: 1)
             ^
Expected one of:
	* ESCAPED_STRING
	* CNAME
```

And other times output:
```
lark.exceptions.UnexpectedCharacters: No terminal matches '1' in the current parser context, at line 1 col 14

@Python(foo: 1)
             ^
Expected one of:
	* CNAME
	* ESCAPED_STRING
```

Would be great for this to be deterministic out of the box so I can write tests for the error messages my parser raises.

**Comment by erezsh** [comment]
Did you try choosing a fixed PYTHONHASHSEED ?

**Comment by RobertCraigie** [comment]
Ah that does fix it, thanks!
