### ISSUE TITLE
lalr parser transformers

### ISSUE THREAD

**Issue by asmodehn** [lark-parser/lark#140]
Is it possible to add the transformer after the creation of the Lark instance ?
And is it possible to combine multiple transform ?

Some code to make this sentence a bit clearer : 

Currently I do : 
```python
parser = Lark(grammar=mygrammar, parser='lalr', transformer=MyTransform())
```

I would like to do something along the lines of : 

```python
parser = Lark(grammar=mygrammar, parser='lalr')  # parses into AST
translater =  parser.transform(MyTransformer())  # transform AST into AST'
interpreter = translater.transform(MyInterpreter())  # transform AST' into python code
```

_OR_ I am going at this the wrong way and should do my transformation/interpretation of the AST outside of any Lark interface ? Is this at all in the scope of lark ?

**Comment by asmodehn** [comment]
I eventually saw the Transform objects in the wiki.
Thanks for the info, good to know that the parameter in the Lark instance is not a major difference.

Are there currently any possibility of combining different Transformers ?
One use case I am thinking about is translating between languages, and be able to compose them : 
T1 : LangA to LangB
T2 : LangB to LangC
T1.T2 : LangA to LangC
Potential practical application is combining simple transformers to get potentially very complex ones
It would make testing also much more efficient.

But I am not really familiar with what is theoritically possible there...

**Comment by erezsh** [comment]
The transformer is a very simple class, you can probably follow its implementation very easily.

You can combine transformers using `T1 * T2`.

**Comment by asmodehn** [comment]
Oh thanks.
I'll close this issue and go back to reading the docs and source :-)
