### ISSUE TITLE
Add `outlines` in the list of projects using Lark

### ISSUE THREAD

**Issue by rlouf** [lark-parser/lark#1407]
I am a maintainer of the [Outlines library](https://github.com/outlines-dev/outlines/tree/main), and we use Lark to help Large Language Models generate text in the language of any formal grammars. The repository is fairly popular in the LLM world, and I was wondering if you would accept a PR that add the project to the README in the section on libraries that use Lark.

Thank you for the great work!

**Comment by erezsh** [comment]
Sure, I would be happy to.

Btw, it looks like you're accessing and overriding a lot of Lark's internal implementation. I wonder why that was necessary, and if perhaps there is a less invasive way of doing that?

Anyway, as long as you do, I suggest pinning to a specific lark version. I can't guarantee that internal details won't change in the future.

**Comment by rlouf** [comment]
> Btw, it looks like you're accessing and overriding a lot of Lark's internal implementation. I wonder why that was necessary, and if perhaps there is a less invasive way of doing that?

You would have to ask @brandonwillard.

> Anyway, as long as you do, I suggest pinning to a specific lark version. I can't guarantee that internal details won't change in the future.

That's a good idea!
