### ISSUE TITLE
Attribute Grammar

### ISSUE THREAD

**Issue by azarezade** [lark-parser/lark#141]
I want to write a date-time parser with lark, and evaluate (calculate) the parsed tree to find the date (given a reference time).
For example "next Wednesday" expression will be parse and then should evaluates to `2018-05-23`.

I want to know if Lark has a way to write an [Attribute Grammar](https://en.m.wikipedia.org/wiki/Attribute_grammar) to easily parse and evaluate an expression.

**Comment by erezsh** [comment]
Yes, it's possible, but in Lark the code isn't part of the grammar. Instead, we use transformers to do the same thing.

See the JSON parser example: https://github.com/lark-parser/lark/blob/master/examples/json_parser.py

I believe you'll find that using transformers is about the same amount of code as Attributes in the grammar, but it's cleaner and more flexible.

**Comment by azarezade** [comment]
Thanks @erezsh, I will try the transformers.
It would be appreciated if you could add more doc on transformers.
