### ISSUE TITLE
Lark.open_from_package() does not support namespace packages

### ISSUE THREAD

**Issue by michaeltryby** [lark-parser/lark#1410]
**Describe the bug**

Lark.open_from_package() cannot load grammars located in namespace packages.

**To Reproduce**

Place a grammar in a namespace package and then try to load it using open_from_package(). Lark issues the following exception when it can't find the grammar file:
lark.exceptions.GrammarError: Using an undefined rule: NonTerminal('start')

P.S. I love Lark!

**Comment by MegaIng** [comment]
The fact that it mange to raise this errors means it did find the grammar file, or it found a different grammar file. What does the grammar file contain?

**Comment by michaeltryby** [comment]
Thanks for the insight @MegaIng. Happy to report that I set up the namespace wrong. Lark.open_from_package() is working great now. 

Closing the issue accordingly.
