### ISSUE TITLE
Issue of installing lark in Python

### ISSUE THREAD

**Issue by EmersttaCreations** [lark-parser/lark#1413]
**What is your question?**

Where can I Install `lark` in Python.

**If you're having trouble with your code or grammar**

![image_2024-05-12_210640552](https://github.com/lark-parser/lark/assets/169614988/28aac657-c195-41c2-8cdd-a251cbd7d175)

I was about to install `lark` in Python 3.11.5, but it won't install it. I don't know where to install it.

**Comment by erezsh** [comment]
You're supposed to run pip from the command-line or shell.

This isn't a Lark specific question. Read more about pip.
