### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by MohammedShokr** [lark-parser/lark#1417]
I am getting the following deprecation warnings while I am using the latest version of lark `1.1.9`
```
.venv/lib/python3.11/site-packages/lark/utils.py:163: DeprecationWarning: module 'sre_parse' is deprecated
  import sre_parse
```
```
.venv/lib/python3.11/site-packages/lark/utils.py:164: DeprecationWarning: module 'sre_constants' is deprecated
  import sre_constants`
```

**Comment by MohammedShokr** [comment]
Yes, I am using version `1.1.9`
Here's a snap shot from my poetry.lock file
![image](https://github.com/lark-parser/lark/assets/63115488/9a1f73bf-0e0f-47f0-819d-34dd2303a833)

And here are the lines causing the issue
![image](https://github.com/lark-parser/lark/assets/63115488/5bb26c5d-05aa-4689-b424-2e8670105a89)

**Comment by MegaIng** [comment]
What does `import lark; print(lark.__version__)` show? There is a reason I asked for the imported version, not what you have installed.

Clearly, the file you have does not come from our `1.1.9` distribution, you can check that manually by opening of the `tar.gz`/`.whl` files yourself and checking the `utils.py` file: https://pypi.org/project/lark/#files

**Comment by MegaIng** [comment]
You probably have `lark-parser` installed as well. That's the old install name of this package.

**Comment by MohammedShokr** [comment]
Yes, I had lark-parser with version `0.12.0` and that what caused the confusion.
Thanks for the clarification,
Closing the issue.
