### ISSUE TITLE
accepts() vs choices() in InteractiveParser

### ISSUE THREAD

**Issue by Daniel63656** [lark-parser/lark#1418]
I am using the InteractiveParser to feed tokens one at a time. I noticed this to be comparatively slow. After profiling it, I saw that a lot of copying is done. After checking the class, I noticed that accepts() (which I use in each step to query next allowed terminals) loops over all terminals returned from choices(), **copies the parser state** and then checks if feeding the terminal causes an UnexpectedToken exception.
Why is this even necessary? The docs of choices() say: "only returns token types that are accepted by the current state" so why doing the very expensive copying of the entire parser state to verify this?
Can I just use choices() and filter out the terminals?

**Comment by MegaIng** [comment]
`choices()` returns the terminals that have a transition in the state machine from the current state. But following that transition might lead to errors further down the line, see #646

Whether `choices()` is enough for you depends on what you are trying to do.

**Comment by Daniel63656** [comment]
I am trying to get all terminal at the step that conform to the grammar. According to the issue, I would need to use accepts() then I guess but the copying overhead is way too much. Maybe there is another solution to verify the tokens?

**Comment by MegaIng** [comment]
I don't think there is a fundamentally different approach that avoids copying the parser state.

But it might be possible to avoid deep-copying the `value_stack`, which I suspect is the majority of the cost of copying, since everything else should be quite cheap to copy.

**Comment by Daniel63656** [comment]
Is there no way to "peek" and check if a token would be accepted without advancing the state (thus making copying of any kind obsolete)?

**Comment by erezsh** [comment]
I agree that the deepcopy is the most likely candidate / suspect. I think the deepcopy is there because the callbacks (i.e. transformer) might change the objects they are given. But actually in this use-case we don't care about the values. We can even tell the parser not to compute anything in the value_stack, which will cause it to run faster, and avoid the risk of side-effects from the callbacks.

Another optimizations for this particular scenario: If the action is a SHIFT (which is quite probable), unwinding the stack only requires a pop, and no copy is needed.

**Comment by Daniel63656** [comment]
@erezsh yes I can confirm that. Replacing accepts() with choices() reduced the percentage of compute time taken by lark from 50% to almost 0% in my case. Would be nice if this would still provide only acceptable tokens though

**Comment by erezsh** [comment]
Sorry, my message was to @MegaIng .

Anyway, I think we can make accepts() pretty fast if we do those things.

**Comment by erezsh** [comment]
@Daniel63656 I created a PR that might solve your performance problems.

Can you give it a try and let me know if it helped?

https://github.com/lark-parser/lark/pull/1419

**Comment by Daniel63656** [comment]
yes, this helps a lot. The copying now only takes a few percentage points in my case instead of the 50% it used to be.

**Comment by erezsh** [comment]
There could be more optimizations done, but sounds like it's good enough right now, so I'm closing the issue.
