### ISSUE TITLE
Inconsistent parse results from simple ambiguous grammar

### ISSUE THREAD

**Issue by mcarpenter** [lark-parser/lark#1434]
**Describe the bug**

I have a small grammar that is a starting point to parse regular expressions. When run repeatedly on the same input Lark produces two different parse trees.

There is an ambiguity in my toy grammar because a RE `quantifier` (`*`, `+`, `?`) can also be interpreted as a `printable_char` (ASCII values between space and tilde). However my reading previous issues (#81, #83) indicates inconsistent parse results should be treated as a bug (and it was certainly a surprise).

**To Reproduce**

Lark 1.1.9, Python 3.10.12.

```python
#!/usr/bin/env python

from lark import Lark

parser = Lark('''
start: factor+

?factor: atom quantifier?

quantifier: "*" | "+" | "?"

?atom: DOT | printable_char

printable_char: /[ -~]/

DOT: "."
''')

regex = r'a.?'
tree = parser.parse(regex)
print(tree.pretty())
```

**Sample results**

```
start
  printable_char	a
  .
  printable_char	?
```

```
start
  printable_char	a
  factor
    .
    quantifier
```

**Comment by MegaIng** [comment]
Does this still happen with the latest master? (`pip install git+https://github.com/lark-parser/lark`)

**Comment by mcarpenter** [comment]
Yes, it does still happen. (`pip list` reports 1.2.0, I still get two different results).

I also see discussion https://github.com/lark-parser/lark/discussions/1288 and setting environment variable `PYTHONHASHSEED=0` does indeed yield consistent results (the second of those presented above). Similarly increasing the priority to `quantifier.2` also fixes it for me.

**Comment by erezsh** [comment]
@mcarpenter Try the latest master again. (you might need to uninstall lark first)

**Comment by mcarpenter** [comment]
That got it, thanks.
