### ISSUE TITLE
Lexer matches shorter literals before longer literals 

### ISSUE THREAD

**Issue by tom-huntington** [lark-parser/lark#1440]
<strike>I'd appreciate if you could suggest a work around please? Edit: using `lexer="basic"` fixes by MRE below but not my actual solution</strike> (Turns out my grammar was wrong).

**Describe the bug**

The lexer is not matching longer literals before shorter ones when the literals are in different terminals.

> #### Notes for when using a lexer:[](https://lark-parser.readthedocs.io/en/latest/grammar.html#notes-for-when-using-a-lexer)
> When using a lexer (basic or contextual), it is the grammar-author’s responsibility to make sure the literals don’t collide, or that if they do, they are matched in the desired order. **Literals are matched according to the following precedence**:
> - Highest priority first (priority is specified as: TERM.number: …)
> - Length of match (for regexps, the longest theoretical match is used)
> - **Length of literal / pattern definition**
> - Name

**To Reproduce**

The problem is the lexer seperates `idiv` into two tokens `i` and `div`. I just want it in one token `idiv`.

```python
from lark import Lark


grammar=f"""
?start: monad
monad: builtin? builtin
builtin: BUILTIN_DYAD | BUILTIN_MONAD
BUILTIN_DYAD: "i" | "div"
BUILTIN_MONAD: "idiv"

%import common.WS
%ignore WS

"""

parser = Lark(grammar, start='start')
print(parser.parse('idiv')) 
```

```shell
✦ ❯ python3 test.py
Tree(Token('RULE', 'monad'), [Tree(Token('RULE', 'builtin'), [Token('BUILTIN_DYAD', 'i')]), Tree(Token('RULE', 'builtin'), [Token('BUILTIN_DYAD', 'div')])])
```

**Comment by erezsh** [comment]
So do you still need help or not?
