### ISSUE TITLE
Confusing Error on simple example.

### ISSUE THREAD

**Issue by Shuraken007** [lark-parser/lark#1455]
Hello. I worked with grammar and can't understand what's wrong:

```py
from lark import Lark

grammar = r"""
  query: TEST1 TEST2
  TEST1: "x"
  TEST2: "y"

  %import common.WS
  %ignore WS  
"""

search_parser = Lark(grammar, start="query", debug='True',  parser='lalr')
search_parser .parse("x y")
```

This works as expected.
But if I use additional terminal `EXPR`- it can't recognize
```py
grammar = r"""
  query: EXPR
  EXPR: TEST1 TEST2
  TEST1: "x"
  TEST2: "y"

  %import common.WS
  %ignore WS  
"""
```

Getting error
```
No terminal matches 'x' in the current parser context, at line 1 col 1

x y
^
Expected one of: 
    * EXPR
```

On practice founded this problem, when want to parse smth like : `EXPR & EXPR & EXPR`
```
query: EXPR (AND EXPR)*
```

**Comment by erezsh** [comment]
`%ignore WS` doesn't work inside terminals.. When you define `EXPR` it is without spaces.

**Comment by Shuraken007** [comment]
> `%ignore WS` doesn't work inside terminals.. When you define `EXPR` it is without spaces.

Haha, it was not obvious.

`EXPR` -> `expr`
and everything works

Thanks
