### ISSUE TITLE
import local grammar file

### ISSUE THREAD

**Issue by azarezade** [lark-parser/lark#146]
I there a way to import grammar from local files other that common?
It seems a very useful feature to write large grammars in a neat and clean way.

**Comment by azarezade** [comment]
Thanks, the concatenation of rules seems a good idea!

Both of them, especially the rules. For example, I want to write a datetime parser and it need to parse numbers, so like to import numbers grammar that I wrote previously.

**Comment by erezsh** [comment]
Sure, it's a desirable feature. I plan to support this in the future.
