### ISSUE TITLE
Quick question - am I using Lark correctly?

### ISSUE THREAD

**Issue by FruitfulApproach** [lark-parser/lark#1462]
So to get data from the parse tree when transforming, I'm using str, list, ''.join, etc.

Just wanting to make sure that use of str(tree) is appropriate.  Since there's no obvious "get_data()" method..

Thanks!

**Comment by erezsh** [comment]
This isn't Java. Just use `tree.data`

**Comment by FruitfulApproach** [comment]
Cool, will do from now on!

**Comment by FruitfulApproach** [comment]
@erezsh 

And what do I do for Tokens?

```
lark.exceptions.VisitError: Error trying to process rule "LATIN":
'Token' object has no attribute 'data'
```

Thanks!  And what about tree[0].  Is it better to use tree.data[0]?

Thanks.  Documentation doesn't cover this afaik.

**Comment by FruitfulApproach** [comment]
> This isn't Java. Just use `tree.data` and `tree.children`

What is the difference between these two?
