### ISSUE TITLE
Regex wildcard too greedy

### ISSUE THREAD

**Issue by jbogar** [lark-parser/lark#1464]
Here is a minimal code example of grammar that I think should parse the given string, but it doesn't:
```
grammar="""
        start: any " " carrot
        carrot: "carrot"
        any: /.+/
        """

lark.Lark(grammar).parse("blue carrot")
```

This raises an exception:

```
UnexpectedEOF: Unexpected end-of-input. Expected one of: 
	* SPACE
```

It works if I reverse the order (i.e. the grammar has  `start: carrot " " any` and the parsed string is `carrot blue`), so I assume that the reason this grammar doesn't parse this string is because the `any` rule greedily eats up the whole string, and nothing is left.

The expected behavior is that this doesn't happen, and the above grammar would parse the string "blue carrot".
Thanks for looking into it!

The lark version:
1.2.2

Python version:
3.9.19

**Comment by erezsh** [comment]
This is the correct behavior. Use a non-greedy regex (like `.+?`) or use `[^ ]+`.

**Comment by erezsh** [comment]
Or use `lexer=”dynamic_complete”`

See: https://lark-parser.readthedocs.io/en/latest/parsers.html
