### ISSUE TITLE
Extend %import functionality: Relative import

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#147]

**Comment by julienmalard** [comment]
Hello,

I'm new to using Lark but expect to depend heavily on it (and especially the newest/experimental features, such as reconstructing and line numbers) for a new project of mine, and was thinking that contributing to a "good first issue" could be a good way for me to get familiar with the code.

Would you like me to try to implement this and send a pull request? And if so, could you post an example of what syntax a relative import would be expected to look like?

Many thanks,
Julien Malard

**Comment by erezsh** [comment]
Hi Julien,

Sure, I'll be happy to accept a PR regarding this issue. I'm rather particular about code structure and style, but I can guide you through it.

I'm open to suggestions regarding the syntax and usage.

My idea is to use idioms that are similar to python, or javascript. So either

```python
%from . import grammar_file.TERMINAL
```
Or
```python
%import ./grammar_file.TERMINAL
```
I think the first is probably the better one, but I'm interested to hear your thoughts.

**Comment by julienmalard** [comment]
Thanks! How about allowing both? (Python allows syntax similar to both, for example, "from x import y.z" and "import x.y.z")
I made a fork and will start working on this soon.

**Comment by erezsh** [comment]
Like in python, `import x.y.z` is a global import (more precisely, a global-path based import), and `from .. import` is a local import (relative-path import).

We may choose to mirror this functionality.

**Comment by erezsh** [comment]
Could we say this issue is now resolved?

**Comment by julienmalard** [comment]
I think so! Perhaps we should update the lark.lark grammar in the examples as well?

**Comment by erezsh** [comment]
Yes, we definitely should :)
