### ISSUE TITLE
`strict` option mentioned in documentation does not seem to exist

### ISSUE THREAD

**Issue by kpet** [lark-parser/lark#1470]
**Describe the bug**

The documentation (https://lark-parser.readthedocs.io/en/latest/classes.html) refers to a `strict` option to `Lark` that does not seem to exist.

**To Reproduce**

```
parser = Lark(grammar, strict=True)
```

results in the following exception

```
lark.exceptions.ConfigurationError: Unknown options: dict_keys(['strict'])
```

**Comment by MegaIng** [comment]
What version of `lark` are you using? `print(lark.__version__)`

**Comment by kpet** [comment]
I thought I was using 1.2.2 but also had 1.1.1 on my system that was being picked up. PEBKAC. Sorry for the noise.
