### ISSUE TITLE
Quickly identify cause of UnexpectedEOF exception thrown parsing a very large file?

### ISSUE THREAD

**Issue by byerun** [lark-parser/lark#1474]
I'm using Lark to parse rather large (~40K lines) structured text files using Earley. Today I started to parse a file but got an UnexpectedEOF exception:

```
Unexpected end-of-input. Expected one of: 
	* _NEWLINE
	* _FOOTNOTE
```
Since in this case there's no line number provided, I can't immediately jump to the offending line and fix it. I suppose I could do a bisect search to isolate the cause, but I was wondering if some other strategy available to more quickly determine what the cause of the problem is.

Thank you.

**Comment by MegaIng** [comment]
Unexpected EOF does not have a line number because it's location is obvious: At the end of the file. Based on the fact that `_NEWLINE` is exepcted, I suspect that your grammar is written in a style where the file has to end with an empty line.

**Comment by byerun** [comment]
My bad. I thought there _was_ a `_NEWLINE` at the EOF (which I forgot to mention in my original comment), but I was looking at a similarly named file in my editor that has the expected newline. Sure enough, the offending file was missing the newline.
