### ISSUE TITLE
`lark.grammar.Symbol.__eq__` raises an `AssertionError` when checking if `None == Symbol(...)`

### ISSUE THREAD

**Issue by weaversam8** [lark-parser/lark#1476]
**Describe the bug**

When attempting to compare a variable set to `None` with a Symbol, Lark's implementation of `__eq__` within the `Symbol` class raises an `AssertionError`.

**To Reproduce**

```python
from lark.grammar import Symbol
a = None
b = Symbol("abc")

# this throws an error:
a == b
```

The error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/venv/lib/python3.8/site-packages/lark/grammar.py", line 19, in __eq__
    assert isinstance(other, Symbol), other
AssertionError: None
```

**Comment by erezsh** [comment]
This class is mainly for internal use, but I will accept a PR that returns False if the other object is None.
