### ISSUE TITLE
Async methods in transformers are not working

### ISSUE THREAD

**Issue by vignesh14052002** [lark-parser/lark#1477]
**Describe the bug**

In our project while making a transformation, for some nodes we will make an api call to get the desired results, for that the method needs to be async

**To Reproduce**

Add an `async` method in a sub_class of `Transformer`

**Suggested Solution**
in the `transform` method
- parse the tree
- collect all async methods
- execute them and gather results
- parse the tree in the same order as the previous
- place the results

**Comment by erezsh** [comment]
Can you explain why it needs to be async?

**Comment by MegaIng** [comment]
I would suggest you implement your own async transformer implementation. You can e.g. copy the code. I don't think there are going to be many/any other users of this, and getting async right is not trivially, and we wont have an need for it internally.

We also can't just add it to the existing `Transformer` class - that is not how async can be used, it must be a new class `AsyncTransformer`.

**Comment by vignesh14052002** [comment]
Thanks for the info, we will inherit and customize the transformer
