### ISSUE TITLE
Extend %import functionality: Allow to import rules

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#148]
Requires recursive import of dependent rules and terminals.

Could cause collisions, at least in LALR. Do we merge or throw an error?

**Comment by erezsh** [comment]
An experimental implementation was added at commit 21bbf9b.

There's no support yet for collisions caused by importing the same file from two or more different imported files.

**Comment by Rogdham** [comment]
Hello, I would also be interested in importing rules. My use case is to split the grammar into several files, but maybe there is some easier way to achieve that?

Anyway, I would expect:
 * rule names to belong to one file only (for example they could be renamed to avoid collisions)
 * `%ignore` to apply to a file only

---

Example:

 * `a.lark`
```
start: expr

expr: "ab"
    | "a" expr "b"

%ignore "_"
```
 * `b.lark`
```
start: expr

expr: "X"
    | "[" inner "]"

%import a.start -> inner
```

The grammar defined in `b.lark` should match: `X`, `[aabb]` and `[aab_b__]` but not `_[ab]_` (`_` not ignored in `b.lark`) nor `[aXb]` (the scope of the `expr` rule should be restricted to each file)

---

@erezsh you mention having written an experimental implementation.

I see that  `import_from_grammar_into_namespace` is in `master`, but I'm not sure how to use it.

**Comment by erezsh** [comment]
@Rogdham 

> * rule names to belong to one file only (for example they could be renamed to avoid collisions)

If I understand you correct, that's already implemented

> * `%ignore` to apply to a file only

`%ignore` isn't imported, because it can't be scoped. At least, it would be complicated to implement.

> I'm not sure how to use it.

I'm pretty sure it's already in `0.6.6`.

**Comment by Rogdham** [comment]
> > * `%ignore` to apply to a file only
> 
> `%ignore` isn't imported, because it can't be scoped. At least, it would be complicated to implement.

Fair enough!

> > * rule names to belong to one file only (for example they could be renamed to avoid collisions)
> 
> If I understand you correct, that's already implemented

It seems that you are right indeed! :+1: 

However, I was not able to "rename" an imported rule… I am able to do `%import .a.expr`, but say I already have a rule `expr` defined in the file I am importing into, I would like to either do `%import .a.expr -> foobar`, or something like `%import .a` and then use `.a.expr` as a rule name (maybe it needs its own syntax).

Btw, I belive [the lark.lark grammar](https://github.com/lark-parser/lark/blob/master/examples/lark.lark) does not recognise the syntax `%import .foo.bar`.

**Comment by erezsh** [comment]
> I would like to either do `%import .a.expr -> foobar`

Makes sense. Do you feel like making a PR? :)

> I belive [the lark.lark grammar](https://github.com/lark-parser/lark/blob/master/examples/lark.lark) does not recognise the syntax `%import .foo.bar`.

You seem to be correct. That needs fixing. How did you spot it, btw?

**Comment by Rogdham** [comment]
> Makes sense. Do you feel like making a PR? :)

Took me a while as I encountered a bug in the process… see #325 

> You seem to be correct. That needs fixing. How did you spot it, btw?

I was looking into the documentation as well as the examples to see how to use rule importing, but could not find really anything about it (only terminal importing).

Btw, I tried improving doc & examples as well in my PR :smiley:

**Comment by erezsh** [comment]
Lark supports importing rules

**Comment by evandrocoan** [comment]
Link for Syntax?

**Comment by erezsh** [comment]
https://lark-parser.readthedocs.io/en/latest/grammar/

Look at `%import`

**Comment by piermarcobarbe** [comment]
> https://lark-parser.readthedocs.io/en/latest/grammar/
> 
> Look at `%import`

Updated URL here: https://lark-parser.readthedocs.io/en/latest/grammar.html?highlight=import#import
