### ISSUE TITLE
Porting from pyparsing: counted_array

### ISSUE THREAD

**Issue by gerlero** [lark-parser/lark#1485]
**What is your question?**

How would one port code that uses [pyparsing's `counted_array` helper](https://pyparsing-docs.readthedocs.io/en/latest/pyparsing.html#pyparsing.counted_array)?

FWIW, I need to parse a sequence of bytes in a file that looks somewhat like this:

```
array <count> <sequence of 'count' bytes>
```

and can appear anywhere inside a file whose other contents also need parsing.

I'll appreciate any pointers.

**Comment by erezsh** [comment]
There is no direct feature for it, but you could use the interactive parser to parse until the point of COUNT, then read as many bytes as you need, and resume the parse.

**Comment by gerlero** [comment]
@erezsh Thanks! I wonder, would using the interactive parser imply any significant slowdown over using the default `Lark` class? After all, my reason for considering moving from pyparsing is parsing performance with these files.

**Comment by MegaIng** [comment]
The reason that lark doesn't have this feature is that it's not context free. Only supporting (a subset of) CFG is what allows lalr to be so fast. You might be able to implement this with the interactive parser or with a postlexer, but I am honestly not quite sure what exactly erezsh has in mind.

**Comment by erezsh** [comment]
The interactive parser is about as fast as the main-loop, I don't think you'll notice any difference.

There might not be a convenient API to do exactly what you need, but I think it should be possible. Let me know if you get stuck.

**Comment by gerlero** [comment]
@erezsh @MegaIng Thanks for the responses!
