### ISSUE TITLE
synthesis : generate language from parse tree ?

### ISSUE THREAD

**Issue by asmodehn** [lark-parser/lark#151]
I realize this is not the main usage of lark.
However I was curious to know if it would be possible to do the opposite of parsing. That is generating a "program" in the defined (via a lark grammar) language, given the parsed tree.
This would basically mean inverting the control flow...

This could be useful in program synthesis, and when translating between languages, to be able to translate changes both ways.

It naively seems it would be doable, if the grammar is not ambiguous. Is it suitable for lark ? If feasible, where should one start to implement such a feature ?

Any other thought on this topic ?

**Comment by erezsh** [comment]
That actually exists in Lark: https://github.com/lark-parser/lark/blob/master/lark/reconstruct.py
And here's an example of reconstructing JSON with it: https://github.com/lark-parser/lark/blob/master/examples/reconstruct_json.py

But before you get too excited, it's very experimental, and I haven't got it to work with more complex grammars yet. I'll keep working on it though, when I have the time.

**Comment by FRidh** [comment]
This is a very interesting feature and I would like to use this to remove unused objects. I gave it a go with our grammar, but it seemed to fail. Should the parser be made using `keep_all_tokens` or not?

**Comment by erezsh** [comment]
@FRidh  No, `keep_all_tokens` is unrelated. If you get an error you should post it, and perhaps I'll be able to help. But since it's a complicated and experimental feature, I can't guarantee it.
