### ISSUE TITLE
pygments lexer ?

### ISSUE THREAD

**Issue by asmodehn** [lark-parser/lark#154]
Feature request : a pygments' lexer.
See : http://pygments.org/docs/lexerdevelopment/

This would help with syntax highlighting when writing REPLs and editors dealing with lark grammars.

**Comment by erezsh** [comment]
There's already a syntax highlighter for qscintilla: https://github.com/lark-parser/lark/blob/master/examples/qscintilla_json.py

If you want to add one for pygments, I'll be happy to add it to examples
