### ISSUE TITLE
Datetime parser

### ISSUE THREAD

**Issue by azarezade** [lark-parser/lark#156]
Given that I have a datetime grammar that can parse queries like:
```
next Monday
Tuesday at 8 PM
```
Is it possibile to detect and parse datetime substring from queries like:
```
I will be there on next Monday, is it ok?
```
I was thinking of adding a rule like `datetime_expr : TOKEN datetime TOKEN` in top of datetime grammar, but in this way earley parser returns the first matched parse tree, which most of the time is not true.
Dose anyone have any idea!?

**Comment by azarezade** [comment]
Thanks @erezsh for the quick reply!
Good idea!
I think among the two approach that you proposed, the second one would be better, since for a sentence with n token I think the number of substring (with consecutive tokens) is of order O(n^2).
With `ambiguity="explicit"` one can search for a tree with the minimum number of tokens!

**Comment by erezsh** [comment]
Glad I could help. Regarding complexity, you can try to construct the grammar in such a way that it will fail early if the parse is incorrect.
