### ISSUE TITLE
persian STRING

### ISSUE THREAD

**Issue by AbolfazlDalily** [lark-parser/lark#161]
how to parse a persian srting in lark-parser

**Comment by erezsh** [comment]
I don't know what is a "persian string"

**Comment by AbolfazlDalily** [comment]
"رشته فارسی"

**Comment by AbolfazlDalily** [comment]
in grammer i define 
rule: "rule add" NUMBER  "msg_contains" STRING "then" rule_action        ->    rule_add

**Comment by brupelo** [comment]
This subject could become quite interesting but the way it's been asked it is quite lazy without any relevant code/details/information at all. Let's try to make this post a little bit more interesting with some related questions:

0) Is it a possible using EBNF grammar to parse natural language words like persian or it's better using more suitable tools like [ntlk](https://www.nltk.org/)?
1) Can EBNF grammars cover natural languages like persian/english/...? EBNF accepts grammars type 2, that means neither context-sensitive grammar nor unrestricted grammars can be parsed by it...
2) Let's consider the simplistic assumption than a valid `persian string` is just 1 or more persian alphabets letters.

        from lark import Lark


        if __name__ == "__main__":
            grammar = r"""
                start: persian_word+
                persian_word: LETTER+
                LETTER: "U+0621"
                    | "U+0622"
                    | "U+0623"
                    | "U+0624"
                    | "U+0626"
                    | "U+0627"
                    | "U+0628"
                    | "U+062A"
                    | "U+062B"
                    | "U+062C"
                    | "U+062D"
                    | "U+062E"
                    | "U+062F"
                    | "U+0630"
                    | "U+0631"
                    | "U+0632"
                    | "U+0633"
                    | "U+0634"
                    | "U+0635"
                    | "U+0636"
                    | "U+0637"
                    | "U+0638"
                    | "U+0639"
                    | "U+063A"
                    | "U+0641"
                    | "U+0642"
                    | "U+0643"
                    | "U+0644"
                    | "U+0645"
                    | "U+0646"
                    | "U+0647"
                    | "U+0648"
                    | "U+0649"
                    | "U+064A"
                    | "U+064B"
                    | "U+064E"
                    | "U+064F"
                    | "U+0650"
                    | "U+0652"
                    | "U+0653"
                    | "U+067E"
                    | "U+0686"
                    | "U+0698"
                    | "U+06A9"
                    | "U+06AF"
                    | "U+06CC"

                %import common.WS
                %ignore WS
            """

            parser = Lark(grammar, start='start', parser='lalr')
            tree = parser.parse("رشته فارسی")
            print(tree)

The above snippet will raise `lark.lexer.UnexpectedInput: No token defined for: 'ر' in 'رشته ' at line 1 col 0`. So, how do you recognize unicode letters on lark grammars?

---

The way this question has been asked and then defined what a "persian string" won't give you too many good answers. Please take a look to [mcve](https://stackoverflow.com/help/mcve) or [sscce](http://sscce.org) links, it contains few hints that can help to bring up better questions to the table that can be useful for everybody ;)

That said, welcome to the still young but growing up lark community :'D

You can find more info about lark on:

 - [Google groups](https://groups.google.com/forum/#!forum/lark-parser)
 - [Stackoverflow](https://stackoverflow.com/unanswered/tagged/lark-parser)
 - [Docs](https://github.com/lark-parser/lark/tree/master/docs)
 - [Examples](https://github.com/lark-parser/lark/tree/master/examples)
 - IRC: It'd be great having as well some lark channel on freenode, #lark, #lark-parser, ##lark, ##lark-parser name are free atm. Of course, if there were enough people interested...

**Comment by brupelo** [comment]
Interesting reading: [http://cs.haifa.ac.il/~shuly/teaching/08/nlp/complexity.pdf](http://cs.haifa.ac.il/~shuly/teaching/08/nlp/complexity.pdf)

**Comment by brupelo** [comment]
Fixed above example:

    from lark import Lark


    if __name__ == "__main__":
        grammar = r"""
            start: persian_word+
            persian_word: LETTER+
            LETTER: "\u0621"
                | "\u0622"
                | "\u0623"
                | "\u0624"
                | "\u0626"
                | "\u0627"
                | "\u0628"
                | "\u062A"
                | "\u062B"
                | "\u062C"
                | "\u062D"
                | "\u062E"
                | "\u062F"
                | "\u0630"
                | "\u0631"
                | "\u0632"
                | "\u0633"
                | "\u0634"
                | "\u0635"
                | "\u0636"
                | "\u0637"
                | "\u0638"
                | "\u0639"
                | "\u063A"
                | "\u0641"
                | "\u0642"
                | "\u0643"
                | "\u0644"
                | "\u0645"
                | "\u0646"
                | "\u0647"
                | "\u0648"
                | "\u0649"
                | "\u064A"
                | "\u064B"
                | "\u064E"
                | "\u064F"
                | "\u0650"
                | "\u0652"
                | "\u0653"
                | "\u067E"
                | "\u0686"
                | "\u0698"
                | "\u06A9"
                | "\u06AF"
                | "\u06CC"

            %import common.WS
            %ignore WS
        """

        parser = Lark(grammar, start='start', parser='lalr')

        tests = [
            "رشته فارسی   ",
            "hello world",
            "hola mundo"
        ]

        for t in tests:
            try:
                tree = parser.parse(t)
                print(f"=> OK: {t} parsed correctly")
            except Exception as e:
                print(f"=> FAIL: {e} -> Is {t} a persian word?")

**Comment by erezsh** [comment]
@brupelo Please fix code by editing it, instead of posting a new version.

**Comment by brupelo** [comment]
@erezsh Good idea, that will keep the thread shorter, done. I'd added a new version as I'm not sure if the thread's participants will receive notifications about editing comments who've already read
