### ISSUE TITLE
migration instructions missing

### ISSUE THREAD

**Issue by erickeller** [lark-parser/lark#165]
Hi all,

I did use the lark-parser some time ago with the version `0.3.6`
I now understand that some work was done :) since the last release points to: `0.5.6`

Unfortunately it seems that the code working with this older version does not work anymore today...
I did not find any migration hints since this repository seems to have been moved here without the previous tags oldest is `0.5.1`.

could someone help out and give a short summary about what changed between 0.3.x and 0.5.x ?

**Comment by erezsh** [comment]
That's a long list. Perhaps if you write the error you're getting, I can help you solve it.

**Comment by erickeller** [comment]
Yep I can imagine :)
so I did a bit of debugging and found out that removing `ambiguity='explicit'` did result in only one variant of the tree.

As explained in your example:

```
Lark can automatically resolve ambiguity by choosing the simplest solution. Or, you can ask it to return all the possible parse trees, wrapped in a meta "_ambig" node.
```

It returned all the possible trees decomposing each and every word like the following:
```
remind Mini Mouse on 24-Dec-2018 at 18:00 about Christmas dinner with Mickey Mouse
Tree(_ambig, [Tree(meet, [Tree(remind, [Token(NAME, 'Mini'), Token(NAME, 'Mouse')]), Tree(on, [Token(DATE, '24-Dec-2018')]), Tree(at, [Token(TIME, '18:00')]), Tree(about, [Token(EVENT, 'Christmas'), Token(EVENT, 'dinner')]), Tree(with, [Token(NAME, 'Mickey'), Token(NAME, 'Mouse')])]), Tree(meet, [Tree(remind, [Token(NAME, 'Mini'), Token(NAME, 'Mouse')]), Tree(on, [Token(DATE, '24-Dec-2018')]), Tree(at, [Token(TIME, '18:00')]), Tree(about, [Token(EVENT, 'Christmas'), Token(EVENT, 'dinner')]), Tree(with, [Token(NAME, 'M'), Token(NAME, 'ickey'), Token(NAME, 'Mouse')])]),...
```

I do not know why a word is decomposed as a character + another word...
```
Tree(with, [Token(NAME, 'M'), Token(NAME, 'ickey'), Token(NAME, 'Mouse')])]
```
the grammar looks like:
```
meet: remind on at about with (repeat)?
remind: "remind" NAME+
on: "on" DATE
at: "at" TIME
about: "about" EVENT+
with: "with" NAME+
repeat: "repeat" RECURENCE

// tokens
NAME: WORD
DATE: /\d+\-\w+(-\d+)?/
TIME: /\d+:\d+/
EVENT: WORD
RECURENCE: WORD
YESNO: /([y](es)?)|([n]o?)/

%import common.WORD
%import common.WS
%ignore WS
```

**Comment by erezsh** [comment]
Yes, this is a known bug with the dynamic earley mode, that we're currently working on fixing.

Meanwhile, since your grammar appears pretty simple, I can suggest that you try using contextual lalr instead: `Lark(..., parser="lalr", lexer="contextual")`

If you must use Earley, you can fix this by requiring a space between the words, for example:

    with: "with" NAME (" " NAME)*

One of these *should* do the trick, but if they don't, let me know and I'll make other suggestions (don't want to unnecessarily overload you with hacks :)

**Comment by erickeller** [comment]
Thanks I will try these out in the upcoming day when I am in reach of my laptop.

**Comment by erezsh** [comment]
So, how did it work out?

I forgot to mention a simple solution for words cutting out in the middle: the `\b` modifier.

You can use it like this:

    NAME: /\b/ WORD /\b/

To make `NAME` only match whole words, instead of fragments.
