### ISSUE TITLE
Error parsing 'mañana' word which include 'ñ' letter with LARL parser

### ISSUE THREAD

**Issue by victorcordero** [lark-parser/lark#169]
Hi,

i changed my parser from **early** to **lalr** and then the words what contains **'ñ'** letter in spanish alphabet raise the next exception:

__File "/opt/lib/python3.6/site-packages/lark/lexer.py", line 116, in lex
    raise UnexpectedInput(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column)
lark.lexer.UnexpectedInput: No token defined for: 'ñ' in 'ñana' at line 1 col 2__

How I can include the 'ñ' letter in my grammar with 'lalr' parsing?

Thanks for all and very good job with this lark-parser project!!

**Comment by victorcordero** [comment]
I can see that this happens when the **lexer='standard'**

**Comment by erezsh** [comment]
Hi,
I think the problem isn't with the letter `ñ`, but that your grammar isn't correct.
Perhaps you can include your grammar, so I'll see for myself?

**Comment by victorcordero** [comment]
Thanks for your reply! 
Your are right, I had a problem in the grammar but I don't know how solve it.

An example of my grammar and code is:

```python
json_grammar = """
        ?test : example1
            | example2

        !example1 : "mañana" | "hoy"
        example2 : "maño" | "madrugada"
        """

spanish_grammar = Lark(json_grammar, start='test', lexer='standard')
text = 'mañana'
tree = spanish_grammar.parse(text)
print(tree.pretty())
```
This grammar and Lark constructor works.
Now, if I add the following import at the end:

```python            
        %import common.WORD
```
the code fails.

How can use that import and get this to work?

**Comment by erezsh** [comment]
Is there a particular reason you're using the standard lexer? It's not that good, and mostly there because it's a little faster.

**Comment by erezsh** [comment]
Well, right now `common.WORD` only accepts `a..z`. That causes a collision when using the standard lexer.

If you want to support unicode characters, you should define it yourself. Maybe then the standard lexer will work. Really depends on your grammar.
