### ISSUE TITLE
Evaluate list of trees

### ISSUE THREAD

**Issue by azarezade** [lark-parser/lark#172]
How can I transform tree, when using `ambiguity="explicit"` in the parser.
```
    parser = Lark(grammar, start="start", parser="earley", ambiguity="explicit")
    query = u"bla bla bla..."
    trees = parser.parse(query)
    print(Evaluate().transform(trees))
```
I have also tried to iterate over subtrees then `Evaluate()` them, but it also returns error!
```
for tree in trees.iter_subtrees():
    print(Evaluate().transform(tree))
```
It return `TypeError: 'Tree' object is not subscriptable`.

**Comment by erezsh** [comment]
It looks like the issue is with your implementation of the `Evaluate` class.

**Comment by azarezade** [comment]
I don't think so, since my `Evaluate` class works perfectly when the parser and tree are:
```
    parser = Lark(grammar, start="start", parser="earley")
   tree = parser.parse(query)
``` 
but when I use:
```
    parser = Lark(grammar, start="start", parser="earley", ambiguity="explicit")
    trees = parser.parse(query)
```
which returns a list of trees, then the Evaluate dos not work. 
Should I use `Evaluate` on the `trees` or iterate over subtrees of `trees` then Evaluate. I tried both and it doesn't works.

**Comment by erezsh** [comment]
@azarezade 

The parser never returns a list of trees. It always returns a single `Tree` instance. When there is an ambiguity, it's signified by an `_ambig` node. i.e. `tree.data == '_ambig'`

If you fail to account for this situation, it might cause the error you reported.

**Comment by azarezade** [comment]
Thanks @erezsh.

Yes, I know that! This is why I used `iter_subtrees()` method to iterate over the different subtrees that resulted because of the ambiguity.

Maybe my question is not clear enough. I am seeking for a way to choose the best parse tree (subtree) when there is an ambiguity. For this means, first I need a way to `Evaluate` all subtrees, then I choose the best one based on the evaluation result.

How can I `Evaluate` each subtree when there is ambiguity?

**Comment by erezsh** [comment]
@azarezade 

I think we're going in circles a bit. Perhaps you can write the full exception you're getting?

**Comment by erezsh** [comment]
So, the reason you get this error is because in
```python
hour = args[0]['hour']
```
The value of `args[0]` is a Tree instance, probably an `_ambig` node. You'll have to **handle it yourself**.

> How can I Evaluate each subtree when there is ambiguity?

That is how.

**Comment by erezsh** [comment]
P.S. You can do
```python
print( args[0].pretty() )
```
To see what you're dealing with. You can also handle the `_ambig` nodes even before you transform, by doing:
```python
for ambig_node in tree.find_data('_ambig'):
    do_something()
```

**Comment by azarezade** [comment]
Thanks!
