### ISSUE TITLE
Possible to use grammar file read by PlyPlus ?

### ISSUE THREAD

**Issue by bemichel** [lark-parser/lark#173]
[fortran.txt](https://github.com/lark-parser/lark/files/2149744/fortran.txt)
Hi, 
I use PlyPlus to read the file attach to this issue and I want to know if it is possible to read it with Lark ?
This file coming from the project [F2X](https://github.com/DLR-SC/F2x).

If it is not possible to read this kind of file, it is possible to give me an idea of the rules to convert this file into a syntax readable by Lark. 

For example :  How to translate (%unless ..) ?
T_DEFINED_OP : '\.[a-zA-Z]+\.' (%unless
    T_EQ            : '\.EQ\.' ;
    T_NE            : '\.NE\.' ;
    ...)
or (%newline)
CONTINUE_CHAR
    : '&[ \r\t\u000C]*(![^\n\r]*)?\r?\n([ \t\u000C]*&)?' (%newline) (%ignore)

Thanks !
Bertrand M.

**Comment by erezsh** [comment]
Hi,

Lark cannot read PlyPlus grammar files, but converting them should be relatively straight-forward.

The `%unless` keywords isn't necessary in Lark, it detects these collisions automatically

So:
```python
T_DEFINED_OP : /.[a-zA-Z]+./
T_EQ : ".EQ."
T_NE : ".NE."
```
etc.

Likewise, `%newline` is also unnecessary. Lark detects it automatically.

I hope that helps. Let me know if you have any more questions.

**Comment by bemichel** [comment]
Thanks a lot !
I just start the convertion yesterday so it seems that i  will  need help
in a very short time.
Bertrand.


Le sam. 30 juin 2018 à 09:32, Erez Shinan <notifications@github.com> a
écrit :

**Comment by bemichel** [comment]
Could you help me to convert this notation : 
```
language_binding_spec
    :   T_BIND T_LPAREN T_IDENT /* 'C' */   (T_COMMA name T_EQUALS expr)? T_RPAREN
```
especially the special character  /* 'C' */
Thanks a lot.

**Comment by erezsh** [comment]
What do you mean by special character? It's just a comment, no?
