### ISSUE TITLE
Fail to create parser using a big grammar (memory increase infinitely)

### ISSUE THREAD

**Issue by someoneusinglark** [lark-parser/lark#175]
Hello,

I'm trying to parse a text in python 3.5, using the 0.5.6 release of lark.
I have a very long grammar in this format :

```
start: title  field+

field: rule1 -> alias1
	| rule2 -> alias2
	[…]
	| rule386 -> alias386

//AUXILIARY TERMS
title: ...
term1: ...
[...]
term90:

//RULES GROUP 1
rule1: ...
[...]
rule276: ...

//RULES GROUP2
rule277: ...
[...]
rule386: ...

//TERMINALS
[...]
```

Here are some examples of the syntax of rules and terms : 
 ```
//AUXILIARY TERMS
adexpmsg: CHARACTER*
aidequipment: (("N"|"S") [equipmentcode])|equipmentcode
aircraftid: ALPHANUM~2..7

//PRIMARY FIELDS
aatot: _HYPHEN _sep "AATOT" _sep timehhmm
ad: _HYPHEN _sep "AD" _sep adid [_sep (fl|flblock)] [_sep eto] [_sep to] [_sep cto] [_sep sto] [_sep ptstay] [_sep ptrfl] [_sep ptrulchg] [_sep (ptspeed|ptmach)]
ada: _HYPHEN _sep "ADA" _sep date

//SUBFIELDS
addrinfo: _HYPHEN _sep "ADDRINFO" _sep networktype _sep fac
adid: _HYPHEN _sep "ADID" _sep (icaoaerodrome | "ZZZZ")
adname: _HYPHEN _sep "ADNAME" _sep (LIM_CHAR)~1..50

//TERMINALS
_sep: SEP*
ALPHA: /[A-Z]{1}/
DIGIT: /[0-9]{1}/
ALPHANUM: ALPHA|DIGIT
SPACE: " "
_HYPHEN: "-"
FEF: "\n"|"\r"
SEP: (SPACE|FEF)
SPECIAL: SPACE
	|"("
	|")"
	|"?"
	|":"
	|"."
	|","
	|"'"
	|"="
	|"+"
	|"/"
CHARACTER: ALPHA|DIGIT|SPECIAL|FEF|_HYPHEN
LIM_CHAR: ALPHA|DIGIT|SPECIAL|FEF
START_OF_FIELD: _HYPHEN
%import common.WS
```

The text format I'm trying to parse is the ADEXP format, which is a succession of fields, all of them beginning by a "-", followed by a name of field, and one or more values, which can also be a new field.
The first field is "-TITLE".
Here is an example of an ADEXP message :

```
-TITLE BFD -REFDATA -SENDER -FAC BORD -RECVR -FAC A -SEQNUM 001 -ARCID RYR743D -SSRCODE A1122 -NBARC 1 
-ARCTYP B738 -ADEP EDDH -ROUTE N0441F370 OLRAK DEGOL LAPRO PPG ALBER  -BEGIN RTEPTS -PT -PTID OLRAK -PT 
-PTID DEGOL -PT -PTID LAPRO -PT -PTID PPG -PT -PTID ALBER -END RTEPTS -ADES LEBL -BEGIN EQCST -EQPT Y/EQ 
-EQPT W/EQ -EQPT R/EQ -END EQCST -RFL F370 -SPEED N0441 -EOBT 2359 -WKTRC M
```

This format allow separators between almost every fields, but some fields have to be directly one after the other, without any separator, so i had to explicit all separators in all rules.
You can find in details the complete syntax of all fields [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwjP_Ijkw4DcAhUCesAKHeUhBSUQFgg0MAE&url=https%3A%2F%2Fwww.eurocontrol.int%2Fdownload%2Fpublication%2Fnode-field_download-4907-0&usg=AOvVaw0xAxaodfoVbtJ10MvjN0E7).

I tested some rules individually and I'm able to parse a text with this rules.

But when I try to parse the entire grammar above (~900 lines), lark can't create the parser:

When I execute the code :

```
[...]
print("Creating parser")
parser = Lark(grammar, parser='earley')
print("Parser created")
tree_res = parser.parse(text)
print("Text parsed")
```

The program displays "Creating parser", and processes to create it. The RAM is increasing progressively, until it reaches 12-13GO of RAM and get killed by the system (after 15-20 minutes).

I also tried to use different parser with different lexers, but it doesn't change anything.
I obtained the same result when I used a different python interpreter (Pypy).

I would like to know if you have any idea why it's taking this time to finally get killed ? Is it my grammar which is too big ? Or maybe too ambiguous ?
Tell me if you need any more details about the grammar or anything else.

Thank you in advance for your answer.

**Comment by erezsh** [comment]
Hi, 

A grammar of 900 lines doesn't sound that big, and definitely shouldn't exhibit the behavior you're describing.

Can you please paste the exception you're getting?

**Comment by erezsh** [comment]
On a second look, expressions such as `(LIM_CHAR)~1..50`, especially if used repeatedly, could cause what you're describing.

See issue #108 

Also, if you can, I recommend that you replace the fixed ranges with `+` or `*`, as they are much faster and lighter.

**Comment by someoneusinglark** [comment]
I don't have any exception, the program never stop, and if I stop it manually, I get this : 

```
Traceback (most recent call last):
  File "/home/testsLark/parsingADEXP.py", line 102, in <module>
    arbre = analyse_texte(texte, grammaire)
  File "/home/testsLark/parsingADEXP.py", line 85, in analyse_texte
    parser = Lark(gram, parser='lalr')
  File "/home/venv/lib64/python3.5/site-packages/lark/lark.py", line 156, in __init__
    tokens, self.rules, self.ignore_tokens = self.grammar.compile(lexer=bool(lexer), start=self.options.start)
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 519, in compile
    simplify_rule.visit(tree)
  File "/home/venv/lib64/python3.5/site-packages/lark/tree.py", line 156, in visit
    self.visit(child)
  File "/home/venv/lib64/python3.5/site-packages/lark/tree.py", line 156, in visit
    self.visit(child)
  File "/home/venv/lib64/python3.5/site-packages/lark/tree.py", line 156, in visit
    self.visit(child)
  File "/home/venv/lib64/python3.5/site-packages/lark/tree.py", line 159, in visit
    f(tree)
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 210, in expansion
    for option in set(child.children)]
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 210, in <listcomp>
    for option in set(child.children)]
  File "/home/venv/lib64/python3.5/site-packages/lark/tree.py", line 159, in visit
    f(tree)
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 210, in expansion
    for option in set(child.children)]
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 210, in <listcomp>
    for option in set(child.children)]
  File "/home/venv/lib64/python3.5/site-packages/lark/tree.py", line 159, in visit
    f(tree)
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 210, in expansion
    for option in set(child.children)]
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 210, in <listcomp>
    for option in set(child.children)]
  File "/home/venv/lib64/python3.5/site-packages/lark/tree.py", line 159, in visit
    f(tree)
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 210, in expansion
    for option in set(child.children)]
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 210, in <listcomp>
    for option in set(child.children)]
  File "/home/venv/lib64/python3.5/site-packages/lark/tree.py", line 156, in visit
    self.visit(child)
  File "/home/venv/lib64/python3.5/site-packages/lark/tree.py", line 159, in visit
    f(tree)
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 203, in expansion
    self._flatten(tree)
  File "/home/venv/lib64/python3.5/site-packages/lark/load_grammar.py", line 185, in _flatten
    to_expand = [i for i, child in enumerate(tree.children)
KeyboardInterrupt
```

**Comment by someoneusinglark** [comment]
And replacing the fixed ranges with `+` or `*` is complicated in my case as the ADEXP syntax require precise repetitions of rules. I'm going to try to replace them just to see if it changes something.

**Comment by erezsh** [comment]
Interesting. I think I may have some idea as to why this happens (that is not related to repetitions).

Any chance you can share the full grammar with me? I'll run some tests on it.

**Comment by erezsh** [comment]
Well, turns out this was what I thought at first..

The offending line is:
```ruby
pbncode: ("a1"|"b1"|"b2"|"b3"|"b4"|"b5"|"b6"|"c1"|"c2"|"c3"|"c4"|"d1"|"d2"|"d3"|"d4"|"l1"|"o1"|"o2"|"o3"|"o4"|"s1"|"s2"|"t1"|"t2")~1..8
```

**Comment by erezsh** [comment]
Well, it's not the only offending line.. I should find a way to print a proper error, or at least something that will help debugging this kind of cpu drain.

**Comment by someoneusinglark** [comment]
Effectively it finally ends when I comment this rule ! I reach 1min40sec to create the parser and between 3 and 4 seconds to parse the text.

Thanks a lot for your help.

**Comment by erezsh** [comment]
That's great. I have an idea on how to significantly improve the speed of creating ranges. I'll give it a try when I get the time.

**Comment by erezsh** [comment]
Oh, btw, instead of 
```ruby
fields:  aatot -> aatot
       |  cobd -> cobd
       ...
```
You can just write
```ruby
?fields: aaot
          | cobd
          ...
```
It's a little cleaner, I suppose.

**Comment by someoneusinglark** [comment]
Oh ok I'll change that, thanks.

And I was wondering if you plan to implement the concatenation operator ? Because I actually don't see any other solution than spelling out all the separators to resolve the problem of rules directly followed by an other rule, without any separator between them.

**Comment by erezsh** [comment]
What do you mean by a concatenation operator?

**Comment by erezsh** [comment]
I see, you want an operator to negate the `%ignore` directive in a specific location.

I would consider such an operator, but I'm not sure how useful it is, especially since there is a workaround using regexps, by using lookback and lookahead.

Can you give a concrete example of why you need it?

**Comment by someoneusinglark** [comment]
Ok, so in fact the grammar I wrote is traduced from a BNF grammar in which there are 2 types of rules : 
`rule1: "-" "FIELD" X` meaning `"-" (SEP)* "FIELD" (SEP)* X` where SEP is a whitespace or \n or \r
`rule2: day ! month` meaning `day (SEP){0} month` where day and month are a 2 digit number.

So for the first rule, "- FIELD X", "-  (10 whitespace here)   FIELD (30 here)        X" and "-FIELD   \n   X" should match,
and for the second one, "0107" matches, but not "01 07".

If I ignore whitespaces in my grammar, the second rule fails, and if I don't ignore them, I have to write every separators in rules like the first one (`"-" SEP "FIELD" SEP X`) and don't write them in rules like the second one (`day month`).

Writing every separator is slowing a lot the grammar and is absolutely not readable.
I may be mistaken but I don't see how to do this without a concatenation operator.

Do you see what I mean?

**Comment by erezsh** [comment]
I can suggest two possible solutions, though I'm aware that they have their own downsides and limitations:

1) Create a single terminal DAY_MONTH, and parse it later (say, using a transformer)

2) Use lookahead/lookback in day/month to disallow whitespace. Something like `DAY: /\d\d(?!\s)/`

Is there a reason that these won't apply to your case?

The reason I'm suggesting these, is that the `!` operator (or whatever symbol) is very different from the other operators that Lark currently supports, so it won't be simple to add it. Having said that, it *is* possible, so I'll consider it if there seems to be a really good reason.

**Comment by someoneusinglark** [comment]
Also, do you have any ideas on how to optimize my grammar ? 

It's actually really slow : 
With python3.5 it takes ~20 minutes to create the parser and ~45 seconds to analyse the text.
With pypy it takes 1 minute 40 seconds to create the parser and ~3 seconds to analyse the text.

If I try to remove separators and ignore them, it's a bit faster with pypy (1 minute 15 seconds), and not tested with python3.5

**Comment by erezsh** [comment]
The reason it's slow is, as I said before, because of the fixed-amount operators.

Try to separate them from the rest of the rules, and use them as little as possible. One thing that would make them a lot faster, is fragmenting them. For example, `a: b~50` would be a lot faster as

```ruby
a: b10 ~ 5
b10: b ~ 10
```

This kind of fragmentation, except automatic, is essentially the way I want to solve this issue. If you think you can implement this on your own, be my guest. Otherwise, fragmenting manually, especially the big repetitions, should improve the speed by a lot.

**Comment by someoneusinglark** [comment]
I did what you proposed to improve the generation speed of the parser.

I replaced in the grammar with ignored separator all rules that does not accept separators by regexp like you said (`day: /\d\d(?!\s/`) and it worked well.
I also fragmented rules like `rule: x~50`.

I now have a working grammar without spaces; but even with fragmented rules, the time didn't improve and it's still taking ~1minute15seconds to generate the parser (like my previous grammar with ignored whitespaces).

I'll try to change things in main generation rules (start/field) and some other things to see if there is a difference . I will report my results here as soon as I get interesting results.

Thanks again.

**Comment by erezsh** [comment]
What do you mean by conflicting?

Btw you should really avoid things like ` (hexadecimal~36 | hexadecimal~38)`

**Comment by someoneusinglark** [comment]
I just can't parse the grammar so I guess it's because of one (or some) rules that are problematical.

**Comment by someoneusinglark** [comment]
And about rules with `~x`, I fragmented them as you said previously but it didn't change anything, and avoiding them is complicated as the ADEXP syntax require them.

**Comment by erezsh** [comment]
There problem can be seen in the following grammar:
```ruby
start: a? b? c? d? e? f? g? h? i? j? k? l?

a: "A"
b: "B"
c: "C"
d: "D"
e: "E"
f: "F"
g: "G"
h: "H"
i: "I"
j: "J"
k: "K"
l: "L"
```

Right now, Lark compiles the grammar into BNF so that each option is either taken or not taken. When bunched together, the effect is combinatorical. If I only had a..i, it wouldn't be noticeable, but once it's long enough, it can take a long while.

This obviously happen due to the simplicity of Lark's grammar compilation, and perhaps I should implement something a bit smarter (basically, it's the same issue as the `~` operator, and the solution should be similar).

So if, instead, I'll write

```ruby 
start: a b c d ...

a: "A"?
b: "B"?
c: "C"?
d: "D"?
...
```

The grammar will load instantly.

So until the compilation is improved, I suggest that you take this approach.

**Comment by someoneusinglark** [comment]
That's it ! 
Effectively, if I just keep the rule `pt: _HYPHEN  "PT"  ptid [( fl |  flblock)] [sfl] [eto] [to] [ cto] [ sto] [ ptrte] [ ptstay] [ ptrfl] [ ptrulchg] [( ptspeed |  ptmach)] [ ptcrsclim] [ ptdle]` as start without all the rules, the parser takes 75sec to be generated. When I removed the rule `[sfl]` (for example), it passes to 4sec ! And if I add an optional one, it's infinite..

Thanks a lot, I wouldn't have found this without you.

**Comment by erezsh** [comment]
Nor should you. This is what maintainers are for :)

Let me know if you run into any more issues.

**Comment by someoneusinglark** [comment]
I'll do what I can if it can help you with Lark !
