### ISSUE TITLE
Issues with the Python 3 grammar

### ISSUE THREAD

**Issue by julienmalard** [lark-parser/lark#176]
Hello,

I am having difficulties with the Python 3 parser example. It seems that any code with an indent breaks, for example, as in:

"""
def a(x):
    pass
"""

If parses the first line well, after which I get "no token for "p" (from "pass"). Similar results occur with "return" (no token for "r"), arithmetic expressions (e.g., "x*3"; no token for "x"), or anything else within the function definition, for that matter. Similar problems arise when defining classes as well. I was using the lalr parser with the contextual lexer.

If you have any general pointers as to what could be the mistake (e.g., the grammar, lark itself, or me) I would be happy to try to submit a pull request! (In case you are curious, I am using Lark as the backend for a new tool called Lassi, which will allow people to code Python with keywords in their own natural language, before transpiling behind the scenes to regular Python keywords right before execution.)

Many thanks,
Julien Malard

**Comment by erezsh** [comment]
Hi,

Did you see `examples/python_parser.py` ?

It successfully parses Python3 code. I suggest you build on that (or copy-paste from there)
