### ISSUE TITLE
Misinterpreted tree?

### ISSUE THREAD

**Issue by rezemika** [lark-parser/lark#183]
I'm developping a Python module to parse `opening_hours` fields from OpenStreetMap ([repo](https://github.com/rezemika/humanized_opening_hours)), and I use Lark to parse them (with Earley). However, I have a problem I don't understand. A field can contain one or many `rules` (indications of opening periods, separated from others by semicolons), containing mainly a `selector_sequence`.

Here are the first lines of the EBNF:

```
time_domain : rule_sequence ("; " rule_sequence)*

rule_sequence : selector_sequence [rule_modifier]
              | rule_modifier

rule_modifier : OPEN -> rule_modifier_open
              | CLOSED -> rule_modifier_closed

selector_sequence : ALWAYS_OPEN -> always_open
                  | range_selectors [" " time_selector]
                  | time_selector
```

When I parse `Mo-Fr 10:00-12:00`, I get the following tree.

```
time_domain
  rule_sequence
    selector_sequence
      range_selectors
        weekday_or_holiday_sequence_selector
          weekday_sequence
            weekday_range
              Mo
              Fr
      time_selector
        timespan
          time
            hour_minutes
              10
              00
          time
            hour_minutes
              12
              00
```

But when I parse `10:00-12:00`, I get the following one:

```
time_domain
  selector_sequence
    time_selector
      timespan
        time
          hour_minutes
            10
            00
        time
          hour_minutes
            12
            00
```

There is no `rule_sequence`, but `time_domain` is called in the Transformer I use next (I put some prints).

But when I parse `sunrise-sunset`, I get the following tree and the transformer method are called.

```
time_domain
  rule_sequence
    selector_sequence
      time_selector
        timespan
          time
            variable_time	sunrise
          time
            variable_time	sunset
```

Does this problem come from my grammar, or is it a bug somewhere?

Thank you so much for your work on Lark!

**Comment by erezsh** [comment]
Here's what I'm getting:

```bash
$ python -c "from lark import Lark; x=Lark.open('field.ebnf', start='time_domain');print(x.parse('10:00-12:00').pretty())"

time_domain
  rule_sequence
    selector_sequence
      time_selector
        timespan
          time
            hour_minutes
              10
              00
          time
            hour_minutes
              12
              00
```

I advise that you upgrade Lark to the latest version (0.6.1) and try again.

**Comment by rezemika** [comment]
I tried to update but without success. However, after a look in the `git blame`, it seem this problem appear after I modified some lines in one of the methods of the transformer ([here](https://github.com/rezemika/humanized_opening_hours/commit/a9c7cf6f9784a2fb5bf4cffd3f23abc24a0f8904)), so the problem probably come from me, sorry.

Anyway, thank you for your fast response! :)

**Comment by erezsh** [comment]
Okay, happy to help.

Let me know if you want help updating to 0.6.1, it shouldn't be difficult.
