### ISSUE TITLE
Edit the Expecting string

### ISSUE THREAD

**Issue by petermlm** [lark-parser/lark#184]
With the given grammar:

```
from lark import Lark

grammer = """
    value: dict
         | list
         | ESCAPED_STRING
         | SIGNED_NUMBER
         | "true" | "false" | "null"

    list : "[" [value ("," value)*] "]"

    dict : "{" [pair ("," pair)*] "}"
    pair : ESCAPED_STRING ":" value

    %import common.ESCAPED_STRING
    %import common.SIGNED_NUMBER
    %import common.WS
    %ignore WS
"""

parser = Lark(grammer, start='value')
parsed = parser.parse('{"key": $"value", "list": [1, 2, 3, 4]}')
```

And the given wrong string, I get the following expected exception:

```
    lark.lexer.UnexpectedInput: No token defined for: '$' in '$"val' at line 1 col 8

    Expecting: {'__LSQB', 'SIGNED_NUMBER', '__FALSE1', '__TRUE0', '__LBRACE', '__NULL2', 'ESCAPED_STRING'}
```

Can I edit the token strings '__LSQB', 'SIGNED_NUMBER', '__TRUE0', etc? So I can actually have a message saying: "Expecting: '[', 'signed number', 'false', ..."?

If so, how?

**Comment by erezsh** [comment]
What would you like the result to be?

Perhaps you'll find this example useful: https://github.com/lark-parser/lark/blob/master/examples/error_reporting_lalr.py

**Comment by erezsh** [comment]
Oh, btw, update to version 0.6.1. The strings are different there!

**Comment by petermlm** [comment]
Oh! I cannot believe I overlooked this example. This is exactly what I needed.

Thank you very much! And by the way, Lark is an awesome lib!
