### ISSUE TITLE
Usage of assert statements in optimized mode

### ISSUE THREAD

**Issue by petermlm** [lark-parser/lark#185]
I've noticed that Lark uses assert statements in some places outside of tests. Just by doing `git grep assert` in the lark directory we can see a big list of these.

Assert statements are ignored when Python is running in optimized mode. Optimize mode is used in some projects when Python is deployed and/or distributed. I did a quick experiment, and running the following like of code fails in both normal and optimized mode:

```
lark.Lark(grammar='start: "my_token"', parser='not_a_parser')
```

But the yielded exception is different. Normal mode is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/my_user/opensource/lark/lark/lark.py", line 108, in __init__
    self.options = LarkOptions(options)
  File "/home/my_user/opensource/lark/lark/lark.py", line 68, in __init__
    assert self.parser in ('earley', 'lalr', 'cyk', None)
AssertionError
```

And optimized is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/my_user/opensource/lark/lark/lark.py", line 165, in __init__
    self.parser = self._build_parser()
  File "/home/my_user/opensource/lark/lark/lark.py", line 177, in _build_parser
    self.parser_class = get_frontend(self.options.parser, self.options.lexer)
  File "/home/my_user/opensource/lark/lark/parser_frontends.py", line 187, in get_frontend
    raise ValueError('Unknown parser: %s' % parser)
ValueError: Unknown parser: not_a_parser
```

This particular example might not be too problematic, but might the usage of asserts became problematic for people running lark in optimized mode?

**Comment by erezsh** [comment]
In general, I use asserts to test for conditions that

a) Will certainly fail later on

b) The user can avoid, so there's no need to catch them.

So, I don't see any downside to using them.

If you find any specific asserts that don't apply to this rule of thumb, or you think might be problematic for any other reason, feel free to point them out.

The example you gave is a little contrived, and as you said, not really a problem.

**Comment by petermlm** [comment]
Ah that makes sense.

Thanks.
