### ISSUE TITLE
Parsing strings containing variable expansion

### ISSUE THREAD

**Issue by oprypin** [lark-parser/lark#187]
Hi,
I'm having difficulties with parsing strings that contain variable expansions like in Bash. `"Hello, $name!"`.
(So this is either a newbie question, or a feature request.)

When I run this example, each character in the string is processed as a separate terminal. It makes sense why it happens but I don't want it to happen. It also seems to decimate performance on a larger input.

```python
import lark

parser = lark.Lark(r'''
IDENTIFIER: /[A-Za-z_][A-Za-z_0-9]*/
string    : "\"" ( CHAR | ESCAPE | expansion ) * "\""
ESCAPE    : "\\" ( "$" | "\"" | CHAR )
expansion : "$" IDENTIFIER
CHAR      : /[^$"\n]/
''', start='string')

tree = parser.parse('"Hello, $name! That will be \$9.95"')
print(tree.pretty())
```
```
string
  H
  e
  l
  l
  o
  ,

  $name
  !

  T
  h
  a
  t

  w
  i
  l
  l

  b
  e

  \$
  9
  .
  9
  5
```

I've tried changing `/[^$"\n]/` to `/[^$"\n]+/` but that causes an error.

Existing suboptimal options I have:

* Accept the poor performance and concatenate characters
* Call a separate string parser recursively during traversal

Note that this is the simplest possible scenario. What about expressions nested in a string, like Ruby's `"Hello, #{arbitrary + expression}!"` or Python's new `f'Hello, {arbitrary + expression}!'`? *python3.lark* doesn't seem to have these, anyway...

**Comment by erezsh** [comment]
That happens because you've defined `string` as a rule, and not a terminal.

Try this:

```ruby
STRING    : "\"" ( CHAR | ESCAPE | expansion ) * "\""
```

**Comment by oprypin** [comment]
A terminal cannot contain a rule, last I checked.

**Comment by erezsh** [comment]
See the edit

**Comment by erezsh** [comment]
Also, if you want to keep it as a rule, so that you can observe the escape / expansion in the tree, try changing it to:

```ruby
string    : "\"" ( WORD | ESCAPE | expansion ) * "\""

WORD: CHAR+
```

**Comment by oprypin** [comment]
I cannot just change everything to terminals, my actual rules are more complicated with expressions nested in them. (see also the bottom of my original post)

About keeping as a rule:

```python
import lark

parser = lark.Lark(r'''
IDENTIFIER: ("A" .. "Z" | "a" .. "z") ("A" .. "Z" | "a" .. "z" | "0" .. "9") *
string    : "\"" ( WORD | ESCAPE | expansion ) * "\""
ESCAPE    : "\\" ( "$" | "\"" | CHAR )
expansion : "$" IDENTIFIER
CHAR      : /[^$"\n]/
WORD      : CHAR +
''', start='string')

tree = parser.parse('"Hello, $name! That will be \\$9.95"')
print(tree.pretty())
```

```
lark.exceptions.UnexpectedCharacters: No terminal defined for '9' at line 1 col 31

"Hello, $name! That will be \$9.95"
                              ^

Expecting: {Terminal('IDENTIFIER')}
```

**Comment by erezsh** [comment]
You make it sound like your bug is my fault.

Try excluding `\` from `CHAR`:

```ruby
CHAR      : /[^$"\n\\]/
```

**Comment by oprypin** [comment]
Sorry about that, and thanks.

That really was the reason why everything I tried  failed.

```python
import lark

parser = lark.Lark(r'''
IDENTIFIER: ("A" .. "Z" | "a" .. "z") ("A" .. "Z" | "a" .. "z" | "0" .. "9") *
string    : "\"" ( WORD | ESCAPE | expansion ) * "\""
ESCAPE    : "\\" ( "$" | "\"" | CHAR )
expansion : "$" IDENTIFIER
CHAR      : /[^$"\n\\]/
WORD      : CHAR +
''', start='string')

tree = parser.parse('"Hello, $name! That will be \\$9.95"')
print(tree.pretty())
```
```
string
  Hello, 
  expansion	name
  ! That will be 
  \$
  9.95
```
