### ISSUE TITLE
Transformer interface and behavior change in 0.6.0

### ISSUE THREAD

**Issue by achedeuzot** [lark-parser/lark#192]
Hi !

I was wondering: why did the interface for `Transformer` methods change ?

I used to have:
```
class MyTransformer(Transformer_NoRecuse):
    def some_rule(self, tree: Tree):
        tree.children = [...]    # Some changes on children + access to tree class
        return tree
```
Now, when converting to `Transformer_InPlace)`, I'm bothered by the fact that a function rule will delete the tree. e.g.
```
class MyTransformer(Transformer_InPlace):
    def some_rule(self, values: List):
        values = [...]    # Some changes on values + no access to tree class :(
        return values   # <- In the final tree, the `some_rule` node has disappeared !
```

I can update my code to the new `Transformer_InPlace` with many changes but having access to the tree and a way to rewrite portions and/or delete the tree element gave more flexibility in the usage. What is the rationale behind removing `tree`s in arguments to transformer functions ? Is there a way to have access to the `tree` in each transformer functions ?

Thanks for the wonderful work you're doing on lark :)

**Comment by erezsh** [comment]
I changed the transformers so the interface will be simpler and cleaner, and to allow future improvements.

> I'm bothered by the fact that a function rule will delete the tree
It won't delete the tree, that's what InPlace means..

But yes, you can still get the tree, it's just not the default anymore.

Do:
```python
class MyTransformer(Transformer_InPlace):
    @v_args(tree=True)
    def some_rule(self, tree: Tree):
        tree.children = [...]
        return tree
```
Or
```python
@v_args(tree=True)
class MyTransformer(Transformer_InPlace):
    def some_rule(self, tree: Tree):
        tree.children = [...]
        return tree
```

**Comment by achedeuzot** [comment]
Great, thanks soooo much for the tip !

I couldn't find this information in the documentation wiki, thus the issue/question. Would it be possible to host the documentation for all versions on a separate service ? Not being able to use the wiki when using an old version is a bit cumbersome.

Thanks again for your really cool lib. Keep up the good work 👍

**Comment by erezsh** [comment]
> I couldn't find this information in the documentation wiki

You're right, this is a new feature, and I hadn't had time to document it yet. I know documentation isn't one of my best skills, so I'm open to any suggestion!

I like the idea of having version-based documentation. Any idea how to set it up?

**Comment by erezsh** [comment]
> I'd be happy to lend you a hand to set it up if you want.
Thanks, I'll appreciate that.
It seems that I have to make a choice between either Sphinx and MkDocs. Do you have any insight into which one is better? Or perhaps there's a better way?

**Comment by achedeuzot** [comment]
I've used Sphinx in the past and it was straightforward to set up and use.

There's good documentation here: http://dont-be-afraid-to-commit.readthedocs.io/en/latest/documentation.html 

Would you want me to suggest a pull-request for this ?

**Comment by erezsh** [comment]
Actually, having looked at both, I think MkDocs is probably better for Lark, because

1. It uses Markdown, which is what the existing documentation uses

2. It has nicer default themes
