### ISSUE TITLE
Regex syntax and flags docs

### ISSUE THREAD

**Issue by dkrikun** [lark-parser/lark#193]
It is mentioned regex can have flags to it, where could I find info about it?
Also, any info on regex syntax itself would be useful too

**Comment by erezsh** [comment]
Take a look at the cheatsheet: https://github.com/lark-parser/lark/blob/master/docs/lark_cheatsheet.pdf

Other than that, the syntax is the same as Python's regex

**Comment by dkrikun** [comment]
Thanks, what does it mean "imslux" after the regex?

**Comment by erezsh** [comment]
These are the flags. Read about Python's regular expressions, and you will get it.
