### ISSUE TITLE
UnexpectedCharacters is misleading

### ISSUE THREAD

**Issue by Vesuvium** [lark-parser/lark#194]
I run into a weird situation. Lark is raising an UnexpectedCharacters error with this message:

```
lark.exceptions.UnexpectedCharacters: No terminal defined for '*' at line 3 col 3
```

That terminal is defined in my grammar, and if I change

```
3 * 3
```

to

```
3*3
```
it gets parsed correctly.

For reference, the grammar file being used is:

```
start: _NL? block+
line: values | operation | comment | assignment | imports | return_statement | block
number: INT | FLOAT
string: SINGLE_QUOTED | DOUBLE_QUOTED
boolean: TRUE | FALSE
list: _OSB (_NL _INDENT)? (values (_COMMA (_WS|_NL)? values)*)? (_NL _DEDENT)? _CSB
key_value: string _COLON values
objects: _OCB (key_value (_COMMA key_value)*)? _CCB
mutation: _WS NAME arguments*
values: (number | string | boolean | FILEPATH | list | objects) mutation?
comparisons: GREATER | GREATER_EQUAL | LESSER | LESSER_EQUAL | NOT | EQUAL
path_fragment: _DOT NAME | _OSB INT _CSB | _OSB string _CSB
path: NAME (path_fragment)*
assignment_fragment: EQUALS _WS? (values|path|service)
assignment: path _WS? assignment_fragment
return_statement: _RETURN _WS (path|values)
operator: PLUS | DASH | MULTIPLIER | BSLASH
operation: values _WS operator _WS values | values operator values
path_value: path | values
if_statement: _IF _WS path_value (_WS comparisons _WS path_value)?
nested_block: _INDENT block+ _DEDENT
elseif_statement: _ELSE _WS? _IF _WS path_value (_WS comparisons _WS path_value)?
elseif_block: elseif_statement _NL nested_block
else_statement: _ELSE
else_block: else_statement _NL nested_block
if_block: if_statement _NL nested_block elseif_block* else_block?
foreach_statement: _FOREACH _WS NAME output
foreach_block: foreach_statement _NL nested_block
typed_argument: NAME _COLON types
function_argument: _WS typed_argument
function_output: _WS _ARROW _WS types
function_statement: FUNCTION_TYPE _WS NAME function_argument* function_output?
function_block: function_statement _NL nested_block
inline_expression: _OP service _CP
arguments: _WS? NAME? _COLON (values|path|inline_expression)
command: _WS NAME
output: (_WS _AS _WS NAME (_COMMA _WS? NAME)*)
service_fragment: (command arguments*|arguments+) output?
service: path service_fragment
service_block: service _NL (nested_block)?
when_block: _WHEN _WS (path output|service) _NL nested_block
block: line _NL|if_block|foreach_block|function_block|arguments|service_block|when_block
imports: _IMPORT _WS string _WS _AS _WS NAME
types: INT_TYPE | FLOAT_TYPE | STRING_TYPE | LIST_TYPE | OBJECT_TYPE | REGEXP_TYPE | FUNCTION_TYPE
comment: COMMENT+

_WS: (" ")+
_NL: /(\r?\n[\t ]*)+/
_INDENT: "<INDENT>"
_DEDENT: "<DEDENT>"
INT.2: "0".."9"+
FLOAT.2: INT "." INT? | "." INT
SINGLE_QUOTED: /'([^']*)'/
DOUBLE_QUOTED: /"([^"]*)"/
TRUE: "true"
FALSE: "false"
FILEPATH: /`([^"]*)`/
_COMMA: ","
_OSB: "["
_CSB: "]"
_COLON: ":"
_OCB: "{"
_CCB: "}"
GREATER: ">"
GREATER_EQUAL: ">="
LESSER: "<"
LESSER_EQUAL: "<="
NOT: "!="
EQUAL: "=="
NAME.1: /[a-zA-Z-\/_0-9]+/
_DOT: "."
EQUALS: "="
_RETURN: "return"
PLUS: "+"
DASH: "-"
MULTIPLIER: "*"
BSLASH: "/"
_IF: "if"
_ELSE: "else"
_FOREACH: "foreach"
_AS: "as"
_ARROW.2: DASH GREATER
_OP: "("
_CP: ")"
_WHEN: "when"
_IMPORT: "import"
INT_TYPE: "int"
FLOAT_TYPE: "float"
NUMBER_TYPE: "number"
STRING_TYPE: "string"
LIST_TYPE: "list"
OBJECT_TYPE: "object"
REGEXP_TYPE: "regexp"
FUNCTION_TYPE: "function"
COMMENT: /(?<=###)\s(.*|\n)+(?=\s###)|#(.*)/
```

**Comment by erezsh** [comment]
Please provide the full exception, and the output of the correct parse.

**Comment by Vesuvium** [comment]
I have fixed that specific one, so I don't have the full exception. I have been encoutering this error from time to time however, so I will come back with the full traceback. 

The error is misleading because it should be an UnexpectedToken instead of UnexpectedCharacters

**Comment by erezsh** [comment]
If the token is not syntactically valid at that point, the characters won't be tokenized, even if it's defined in the grammar. That why you get this error. It's possible to provide the error you expect, but I'm not sure if it's the correct behavior.

**Comment by erezsh** [comment]
If the token is not syntactically valid at that point, the characters won't be tokenized, even if it's defined in the grammar. That why you get this error. It's possible to provide the error you expect, but I'm not sure if it's the correct behavior.

**Comment by Vesuvium** [comment]
I am closing since the issue has been clarified

**Comment by erezsh** [comment]
Okay. I kept it open because I think you have a point, but I wasn't sure how to correct the error message without making it confusing, or complicating the implementation. However, if you have any ideas I'm interested in hearing them.

**Comment by JohnCC330** [comment]
Not sure, but I think I have a similar problem. As is, it produces the following error:
```
lark.exceptions.UnexpectedCharacters: No terminal defined for 'c' at line 1 col 33

box { <-1, -1, -1>, <1, 1, 1> } cylinder {<1, 2, 3>, <3, 4, 5>, 2}
```
When uncommenting the two #~ commented lines in main(), and commenting the next line, all is fine..I.e. changing the main() to:
```
    l = Lark(GRAMMAR, start = "finite_solid_object")
    print( l.parse("box { <-1, -1, -1>, <1, 1, 1> } ") )
    print( l.parse("cylinder {<1, 2, 3>, <3, 4, 5>, 2}") )
    #~ print( l.parse("box { <-1, -1, -1>, <1, 1, 1> } cylinder {<1, 2, 3>, <3, 4, 5>, 2}") )
```

This is a simplified version of my test program:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  test_lark.py
#
#  Copyright 2019 John Coppens <john@jcoppens.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#

from lark import Lark

GRAMMAR = """
SIGN                : "+"|"-"
DIGIT               : "0".."9"
NON_ZERO_DIGIT      : "1".."9"
UNSIGNED_INT        : NON_ZERO_DIGIT DIGIT*
SIGNED_INT          : [SIGN] UNSIGNED_INT
EXPONENT            : ["e"|"E"] SIGNED_INT
FLOAT               : SIGNED_INT ["." UNSIGNED_INT] [EXPONENT]

vector_literal      : "<" FLOAT "," FLOAT "," FLOAT ">"
vector              : vector_literal

box                 : "box" "{" vector "," vector "}"
cylinder            : "cylinder" "{" vector "," vector "," FLOAT "}"
finite_solid_object : box
                    | cylinder

%ignore " "
"""

def main(args):
    # Test finite objects
    l = Lark(GRAMMAR, start = "finite_solid_object")
    #~ print( l.parse("box { <-1, -1, -1>, <1, 1, 1> } ") )
    #~ print( l.parse("cylinder {<1, 2, 3>, <3, 4, 5>, 2}") )
    print( l.parse("box { <-1, -1, -1>, <1, 1, 1> } cylinder {<1, 2, 3>, <3, 4, 5>, 2}") )

    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
```

**Comment by evandrocoan** [comment]
This problem is because your start symbol `finite_solid_object` either accepts `box` or `cylinder`, but not both at the same time. Now, you need to define how your grammar should accept them. One quick solution is to use:
```regex
finite_solid_object : box
                    | cylinder
-->
finite_solid_object : ( box
                    | cylinder )+
```

Or:
```regex
finite_solid_object : finite_solid_object box
                    | finite_solid_object cylinder
                    | box
                    | cylinder
```

**Comment by JohnCC330** [comment]
You're right, of course. In fact it was working all along, but because of debugging I had changed the start symbol temporarily to `finite_solid_object`. The repetition was higher up in the syntax:
```
scene_item          : camera
                    | light_source
                    | finite_solid_object
                    | infinite_solid_object

scene               : scene_item*
```
Thanks a lot for the prompt reply! Sorry for the noise...

**Comment by erezsh** [comment]
Even though this is closed, the notifications reminded me of it, and in a small burst of inspiration I managed to fix the error with a few lines.

If anyone here feels like checking the new error and telling me their opinion, that would be helpful

**Comment by evandrocoan** [comment]
I am comparing the stacktraces after the change. 
1. ![image](https://user-images.githubusercontent.com/5332158/65821581-c17a9800-e20d-11e9-99b7-40679530e743.png)

With your change, the old information was preserved, while the new information was added:
1. ![image](https://user-images.githubusercontent.com/5332158/65821574-a7d95080-e20d-11e9-86a8-590312f61bc8.png)

Just a note, I had to add `parser="lalr"` to the @JohnCC330 example, because lark was using early by default.

The only thing I think is strange is this `Expecting: {'__IGNORE_0'}`. May be it could have a better name like `Expecting: {'END_OF_PROGRAM'}`?

**Comment by erezsh** [comment]
> With your change, the old information was preserved, while the new information was added

Yes, that's how exceptions in Python3 work. I think it's fine, but if users find it confusing I'll find a way to suppress the original exception.

> May be it could have a better name like Expecting: {'END_OF_PROGRAM'}?

Thanks, that's a good note! I added a fix for that.

**Comment by evandrocoan** [comment]
> Yes, that's how exceptions in Python3 work.

I was not complaining, just emphasizing we did not lose any information with this change.


> I think it's fine, but if users find it confusing I'll find a way to suppress the original exception.

The double exception is fine. No need to suppress as it make easier to understand how lark works internally, then, new developers can easier add contributions/pull requests to its source code.

There are some times (like this: https://github.com/SublimeTextIssues/Core/issues/2930), you need to suppress the exception because the first and the second exception are very close and the first is useless.

**Comment by evandrocoan** [comment]
Actually, you could do this to show everything in a single exception:
```python
raise UnexpectedToken(t, e.allowed)
# -->
first_exception = "".join( traceback.format_exception( *sys.exc_info() ) )
raise UnexpectedToken( t, e.allowed, first_exception ) from None 
```
On this case, the constructor of UnexpectedToken would have to be changed to handle the new parameter.

The problem is that `raise ... from None` was added after Python 3.3:
> Changed in version 3.3: None is now permitted as Y in raise X from Y

1. https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement
1. https://stackoverflow.com/questions/24752395/python-raise-from-usage/24752607#24752607
