### ISSUE TITLE
NEWLINE

### ISSUE THREAD

**Issue by justinse0** [lark-parser/lark#200]
Hi, I am trying to write a parsing script for vsif/vsof to python objects but I am running into a small issue. I am using "<text>" /(.|\\n|\\r)*/ /(NEWLINE)*/ "</text>" in my grammar to store text tokens but it seems to have trouble when things are written in new lines. If the whole "<text>" /(.|\\n|\\r)*/ /(NEWLINE)*/ "</text>"  is written in a single line the grammar parsing correctly but when there are new lines I get: Expecting: {'__SEMICOLON', 'NON_RESERVED_CHARACTER_TOKEN', 'BLANK'}. Is there anything I can change to make this work? Thanks.

**Comment by erezsh** [comment]
Please upgrade to the latest version of Lark, and post this again with proper `formatting`

**Comment by justinse0** [comment]
Hi, I believe I have the latest version installed. Requirement already satisfied: lark-parser in /data/data800/spbu_essd/utils/pyenv/lib/python3.6/site-packages (0.5.6)

The following is my grammar and when I have newlines in between my <text></text> the parser does not work properly. 

`grammar = r"""
	_entity_list : _entity
				| _entity_list _entity
	!_entity : container
				| attribute ";"
				| ";"
	!container : container_type BLANK container_name "{" _entity_list "}"
	container_type : IDENTIFIER
	container_name : IDENTIFIER
				| NON_RESERVED_CHARACTER_TOKEN
				| STRING
	!attribute : attribute_name ":" attribute_value
	attribute_name : IDENTIFIER
	attribute_value : TEXT
				| STRING
				| _data
	_data : NON_RESERVED_CHARACTER_TOKEN
				| _data BLANK NON_RESERVED_CHARACTER_TOKEN
	IDENTIFIER : /[_a-zA-Z][0-9_a-zA-Z]*/
	STRING : /'[^'\n]*'/
			| /"[^"\n]*"/
	TEXT : "<text>" /(.|\\n|\\r)*/ /(NEWLINE)*/ "</text>"
			| "<text>" /(.|\n)+/ "</text>"
	BLANK : /[ \n\t\r]+/
	NON_RESERVED_CHARACTER_TOKEN : /[^ \n\;:{}'\"]+/
	%import common.NEWLINE
	%import common.WS
	%ignore WS
	%ignore " "
	COMMENT : "//" /(.|\\n|\\r)*/ NEWLINE
			| "//" /(.|\\n|\\r)*/
	%ignore COMMENT
"""`
My input file is:
`failure F0 {
                description : <text>Complimentary Scanning was disabled!!! Note that complimentary scanning was disabled earlier, by using the '-disable' switch: vm_scan.pl /tools/cadence/incisiv_15.10.010/vmanager/bin/ovm_sv_lib.flt 
                /tools/cadence/incisiv_15.10.010/vmanager/bin/vm.flt /tools/cadence/incisiv_15.10.010/vmanager/bin/shell.flt -disable -notextvsof -vsofdir ./.vm_scan.sjlxi50.4781.2</text>;
                failure_id : <text>F0</text>;
                kind : <text>scan_disable</text>;
                severity : <text>warning</text>;
                tool : <text>scan_script</text>;
        }` 
And my script takes a vsif file, converts it into a python object and then I turn that python object back into a vsif file. But in the parsing stage I keep getting this error: Expecting: {'NON_RESERVED_CHARACTER_TOKEN', '__SEMICOLON', 'BLANK'}. When I added this: "<text>" /(.|\n)+/ "</text>", after | the parser parses without error but it ignores the whole thing entirely. Please help!

**Comment by erezsh** [comment]
Latest version is 0.6.2 ;)

Use `pip install --upgrade lark-parser`

**Comment by erezsh** [comment]
Sorry, but you will have to find a small example that produces this error.

Also, please provide the full exception.

**Comment by justinse0** [comment]
Sorry, I don't think it was a lark problem actually! It turned out that my input file had duplicate functions with the same name so in my reverse operation, the newer function with the same name overrides the older function. I believe it is not a problem from larks end. Thank you for the help!

**Comment by erezsh** [comment]
Oh, I knew it wasn't a Lark problem :)

Glad it helped.
