### ISSUE TITLE
Missing error error

### ISSUE THREAD

**Issue by henryiii** [lark-parser/lark#202]
If you set a 0 length token, you can break lalr with the wrong error, a `LexError` not defined error:

```python
Lark(r'''
start : EMPTY_LINE
EMPTY_LINE: /^[ \t]*$/
%ignore EMPTY_LINE
''', debug=True, parser='lalr', lexer='standard')
```

output

```
~/anaconda/lib/python3.6/site-packages/lark/lexer.py in __init__(self, tokens, ignore, user_callbacks)
    193 
    194             if t.pattern.min_width == 0:
--> 195                 raise LexError("Lexer does not allow zero-width tokens. (%s: %s)" % (t.name, t.pattern))
    196 
    197         assert set(ignore) <= {t.name for t in tokens}

NameError: name 'LexError' is not defined
```

By the way, is there a good way to "ignore all empty lines" but not ignore all new lines in rules?  That is, 

```
Line part
# empty line

Line part
```

but not allowing
```
Line
part
```

?

**Comment by erezsh** [comment]
Thanks for the bug report!

Regarding your question, you can use the same trick I use for the Python grammar: https://github.com/lark-parser/lark/blob/master/examples/python3.lark#L170

Basically, keep the newlines explicit, and allow them to match multiple lines, so they eat up the empty lines, if such exist.

**Comment by henryiii** [comment]
Thanks, that's basically what I'm doing, so glad that is recommended. That's about where I found it, too...

**Comment by erezsh** [comment]
Your version is slightly slower, and more likely to cause collisions/ambiguity.

**Comment by henryiii** [comment]
Moving to the lalr parser changed the parse time from 20+ seconds to a little over 1 second; the times fluctuate enough that I can't tell if this is faster, but is a little cleaner and nicer so I like it (I hadn't noticed the multiple whitespace line match before). Why do comments have to be included if they are already ignored?
