### ISSUE TITLE
Request for a chat room for Lark

### ISSUE THREAD

**Issue by henryiii** [lark-parser/lark#206]
I think this would be a good way to quickly ask a question or plan a PR. Probably using gitter room and badge would be sufficient.

**Comment by erezsh** [comment]
What's a "gitter room" and "badge"?

**Comment by eltrhn** [comment]
I assume they're requesting the creation of a lark-parser room on https://gitter.im/ and the addition of a "chat on gitter" badge to the README, like the [sanic](/channelcat/sanic/#sanic) project has.

I'm on board myself with having a chatroom to discuss Lark off of GitHub, although I must say I'd find Discord a touch more accessible than Gitter.

**Comment by henryiii** [comment]
[PyBind11](https://github.com/pybind/pybind11/tree/master)'s [gitter room](
https://gitter.im/pybind/Lobby) is extremely successful, that's where I got the idea for Gitter from. But any chatroom would be fine.

**Comment by Vesuvium** [comment]
I agree with both @henryiii  and @eltrhn: a chat room would be nice, but I find gitter weird to use

**Comment by eltrhn** [comment]
@erezsh, anything? This really would be useful for design discussion, or for the odd question that may not deserve a whole GH issue.

**Comment by erezsh** [comment]
I created a gitter chatroom. Let's see how this goes.

(Discord feels a bit like an overkill, and I like gitter's github integration)

**Comment by erezsh** [comment]
It's at https://gitter.im/lark-parser/

**Comment by henryiii** [comment]
Great! A link on the front page would be nice. You should see me there in 1-2 weeks, overloaded at the moment, but would love to get back into some discussion about Lark.
