### ISSUE TITLE
Is it possible to include the source code in Tree nodes?

### ISSUE THREAD

**Issue by emiapwil** [lark-parser/lark#216]
Hello lark developers,

Thanks very much for providing this wonderful tool. I am wondering if it is possible to attach the original source code to each Tree node.

My current use case is to raise error messages for certain Tree node. Even though we can reconstruct the source code by recursively visit a Tree node, it would be much easier if there is a way to access the original source code.

~~~
==========grammer.lark=============
start: first "," second
first: ...
second: ... (a very complex definition)

===========parse.py===============
def interpret(t):
    if t.data == 'start':
        interpret(t.children[0])
        interpret(t.children[1])
    elif t.data =='first':
        # do something
       ...
    elif t.data =='second':
        print(t.source) <- Is this possible?
~~~

**Comment by erezsh** [comment]
I just pushed a patch to the `master` branch, that causes the `propagate_positions` flag to report `start_pos` and `end_pos` for each tree. Then, you can simply do the following for each node:

    source_code = text[tree.start_pos: tree.end_pos]

I didn't really test is properly, so let me know how it works out :)

**Comment by emiapwil** [comment]
Sounds good. I will give it a try. Thanks!

**Comment by erezsh** [comment]
Let me know if anything comes of it, or if you have more questions.
