### ISSUE TITLE
Non-deterministic parser state for ambiguous example with priorities

### ISSUE THREAD

**Issue by rikardn** [lark-parser/lark#217]
I have a very small example of an ambiguity in a parser:
```python
from lark import Lark

l = Lark(
'''start: GENERIC | SPECIFIC
GENERIC.2: /\w+/
SPECIFIC.1: "HelloWorld"
''', parser="earley", lexer="dynamic", ambiguity="resolve"
)

for i in range(1, 101):
    print(l.parse("HelloWorld"))
```

Both GENERIC and SPECIFIC matches, but I have set a priority forcing GENERIC to match. This is not always the result though. If running this program multiple times it will match either GENERIC or SPECIFIC seemingly random. All matches for one run will be the same, but not between runs. This signals that a state in the parser is different between the runs.

**Comment by erezsh** [comment]
Can you test it with the `earley_sppf` branch?

**Comment by rikardn** [comment]
Testing with the  ``earley_sppf`` branch gives a fully deterministic result. The ``GENERIC`` will always match. However another problem arise: if I swap the priorities around the ``GENERIC`` still always matches although I would expect ``SPECIFIC`` to match in that case.

**Comment by rikardn** [comment]
Yes, I tested the following three versions of my terminals (now on the ``earley_sppf`` branch):
```
GENERIC.2: /\w+/
SPECIFIC.1: "HelloWorld"
```
```
GENERIC.1: /\w+/
SPECIFIC.2: "HelloWorld"
```
```
GENERIC: /\w+/
SPECIFIC: "HelloWorld"
```

and they all gave the same result
```
Tree(start, [Token(GENERIC, 'HelloWorld')])
```

**Comment by erezsh** [comment]
Sorry, I should have noticed earlier.

Earley currently doesn't support priority on terminals. If you rewrite it as rules it should work.

```python
l = Lark(
'''start: generic | specific
generic.2: /\w+/
specific.1: "HelloWorld"
''', parser="earley", lexer="dynamic", ambiguity="resolve"
)
```

**Comment by rikardn** [comment]
I have tested your new example and it works with lark 0.6.3.  Thanks!

Is this fact reflected in the documentation? (or perhaps an error should be given for priorities on terminals when using earley)

Please feel free to close this issue.

**Comment by erezsh** [comment]
You're right, this is a usability pitfall. I've started some restructuring to allow support for priorities in terminals (no real reason that it shouldn't work, except for lack of foresight on my part). Let's keep this issue open as a reminder.

**Comment by yngman** [comment]
Thanks for the quick replies!

I'm in a project with @rikardn, and we *did* try a lot of variants with rules instead of terminals. However, the use case was of course a bit more involved. It concerns separate grammars for specific key-val pairs (with restricted form) from a generic key-val pair as fallback.

So I sat down and tried to construct a minimal example out of that mess, and this is what I ended up with:

```python
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from lark import Lark

data = "HELLO=WORLD KEY=VAL"
nparse = 100
grammars = ("""
    start : item (WS item*)

    WS : /\s+/

    ?item : generic | specific
    specific.2 : HELLO ["="] WORLD
    generic.1 : KEY "=" VAL
              | VAL

    HELLO : "HELLO"|"HELL"|"HEL"
    WORLD : "WORLD"|"WORL"|"WOR"

    KEY : /\w+/
    VAL : /[^\s=]+/
""",)

print('data = %r' % data)
for grammar in grammars:
    print('\ngrammar = """%s"""' % grammar)
    for i in range(10):
        lark = Lark(grammar, parser="earley", lexer="dynamic",
                    ambiguity="resolve", keep_all_tokens=True)

        alternatives = set()
        for j in range(nparse):
            alternatives.add(lark.parse(data))
        print('run %2d (%d parses): %s' % (1+i, nparse, alternatives))
```

For me (0.6.4), this outputs:
```
data = 'HELLO=WORLD KEY=VAL'

grammar = """
    start : item (WS item*)

    WS : /\s+/

    ?item : generic | specific
    specific.2 : HELLO ["="] WORLD
    generic.1 : KEY "=" VAL
              | VAL

    HELLO : "HELLO"|"HELL"|"HEL"
    WORLD : "WORLD"|"WORL"|"WOR"

    KEY : /\w+/
    VAL : /[^\s=]+/
"""
run  1 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  2 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  3 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  4 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  5 (100 parses): {Tree(start, [Tree(generic, [Token(KEY, 'HELLO'), Token(EQUAL, '='), Token(VAL, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  6 (100 parses): {Tree(start, [Tree(generic, [Token(KEY, 'HELLO'), Token(EQUAL, '='), Token(VAL, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  7 (100 parses): {Tree(start, [Tree(generic, [Token(KEY, 'HELLO'), Token(EQUAL, '='), Token(VAL, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  8 (100 parses): {Tree(start, [Tree(generic, [Token(KEY, 'HELLO'), Token(EQUAL, '='), Token(VAL, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  9 (100 parses): {Tree(start, [Tree(generic, [Token(KEY, 'HELLO'), Token(EQUAL, '='), Token(VAL, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run 10 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
```

At the moment, we have the issue "resolved" with negative lookaheads:

```
KEY   : /(?!(HEL|WOR))\w+/
VALUE : /(?!(HEL|WOR))[^\s=]+/
```

But would rather not generate blacklists, of course.

Thank you again!

**Comment by erezsh** [comment]
Hi, did you try that with the `earley_sppf` branch?

The current Earley implementation has known issues with determinism. The plan is to replace it with the sppf implementation (probably for version 0.7)

**Comment by yngman** [comment]
> Hi, did you try that with the `earley_sppf` branch?
> 
> The current Earley implementation has known issues with determinism. The plan is to replace it with the sppf implementation (probably for version 0.7)

Nope. I had not. Now I have:

```
run  1 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  2 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  3 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  4 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  5 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  6 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  7 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  8 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run  9 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
run 10 (100 parses): {Tree(start, [Tree(specific, [Token(HELLO, 'HELLO'), Token(EQUAL, '='), Token(WORLD, 'WORLD')]), Token(WS, ' '), Tree(generic, [Token(KEY, 'KEY'), Token(EQUAL, '='), Token(VAL, 'VAL')])])}
```

Clearly a success. I tried to patch it into our more complex grammar, and as far as I'm willing to go now... I can't detect any issues anymore!

Some other things do change however (apparently implicit priorities I had relied on unknowingly), breaking my unit tests and rather quick and dirty spec, so I'll pretend it's all fine and wait with integrating this `earley_sppf` behaviour until release.

Looking forward to 0.7 then!

Thank you.

**Comment by jbowen7** [comment]
Version: 0.6.4
parser=earley
lexer=dynamic
*not yet tested on branch -> earley_sppf

Thanks for opening this issue. I"m experiencing the same. 
I wanted to add my observations. I notice a disparity whether or not my text is multi-line or not.

The following always returns the expected token: Token(BOOL, 'True')
```
parser = Lark.open('grammar-bug.lark')
for i in range(25):
    print(parser.parse("""a = True"""))

```
But when I do the following, I get a seemingly random token of (BOOL|NAME)
```
TEXT = """
a = True
a = True
a = True
a = True
a = True
"""
parser = Lark.open('grammar-bug.lark')
print(parser.parse(TEXT))
```
One, perhaps, coincidence is that the last token of my multi-line text is ALWAYS Token(BOOL, 'True')


Grammer: 
```
%import common.CNAME
%import common.SIGNED_INT
%import common.SIGNED_FLOAT
%import common.ESCAPED_STRING
%import common.WS
%import common.WS_INLINE

// Ignore
%ignore WS
%ignore WS_INLINE

// INIT
start: instruction+
 
instruction: assign_stmt
 
assign_stmt: CNAME "=" atom


int: SIGNED_INT
float: SIGNED_FLOAT
str: ESCAPED_STRING
bool.2: BOOL
name.1: CNAME

BOOL: "True" | "False"

atom: bool
     | name
     | int 
     | float
     | str 
```

**Comment by jbowen7** [comment]
Update (branch-> earley_sppf) 
The branch "earley_sppf" appears to fix my issue and resolve the noted disparity.

**Comment by yngman** [comment]
> Thanks for opening this issue. I'm experiencing the same.
> I wanted to add my observations. I notice a disparity whether or not my text is multi-line or not.

Yes, I saw something similar but did not formally define the finding. I believe that if I changed

```
?item : generic | specific
specific.2 : HELLO ["="] WORLD
generic.1 : KEY "=" VAL
                | VAL
```

To

```
?item : generic | specific
specific.2 : HELLO ["="] WORLD
generic.1 : KEY "=" VAL
```



The problem disappeared.

In the complicated grammar, the problem was only discovered once *another* unrelated `generic`-type rule was matched *after* the ambiguity, not before. Maybe this is valuable somehow?

I've also seen hints that many optional `WS`-matching constructs can trigger weird behavior, probably because I have let `WS` match in rather promiscuously on different rules/terminals. I.e. ambiguity on *which* node will integrate the `WS`-token.

> Update (branch-> earley_sppf)
> The branch "earley_sppf" appears to fix my issue and resolve the noted disparity.

Cool! Then we're in the same boat!

**Really looking forward to the 0.7 release.**

**Comment by dirk-thomas** [comment]
> the earley_sppf branch also fixed problems with this grammar.

So does the `0.7` as well as the `0.7b` branch. @erezsh Do you have a rough timeline for the 0.7 release? Until then which of the two branches would you consider more recent - either seems to contain a change the other doesn't?

**Comment by erezsh** [comment]
@dirk-thomas  `0.7b` is the latest candidate. I hope to merge it to master in the next couple of weeks.

An official release might take a little longer, because I'll want to make sure the documentation reflects all the changes.

**Comment by erezsh** [comment]
0.7 published
