### ISSUE TITLE
[standalone.py] The behavior of Lark_StandAlone is different from that of lark.Lark(parser='lalr')

### ISSUE THREAD

**Issue by ForceBru** [lark-parser/lark#222]
__Code-breaking.__

In [lark's Wiki](https://github.com/lark-parser/lark/wiki/Tree-Construction) it's said that terminals enclosed in double quotes are _not_ included in the parse tree. This works as expected with `lark.Lark`, but the standalone parser does include these terminals for some reason.

This happens, for example, with the very first simple example from the link above:

```
// Untitled.txt
?start: expr

expr: "(" expr ")" | NAME+

NAME: /\w+/

%ignore " "
```

Then build the standalone parser: `python3 -m lark.tools.standalone Untitled.txt > Untitled_parse.py`

Here's a script hat shows the difference:

```
# Untitled.py
import lark
import Untitled_parse


def non_standalone(code):
    with open('Untitled.txt') as f:
        return lark.Lark(f.read(), parser='lalr').parse(code)
        
def standalone(code):
    return Untitled_parse.Lark_StandAlone().parse(code)
    

code = '((hello world))'  # the example from the docs

ns = non_standalone(code)
s = standalone(code)

print(ns.pretty())
print(s.pretty())
```

This outputs the following:

```
expr
  expr
    expr
      hello
      world

expr
  (
  expr
    (
    expr
      hello
      world
    )
  )
```

According to the wiki, the parentheses shouldn't be present in the tree.

## Installation info
* Python 3.6.1 (default, Aug 24 2017, 16:16:10) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
* `lark.__version__ == '0.6.4'`

**Comment by erezsh** [comment]
Thanks for the bug report! It should work now as expected.

**Comment by ForceBru** [comment]
Yes, now everything works great, thank you!
