### ISSUE TITLE
[standalone.py] Impossible to use `lark.visitors.Interpreter`

### ISSUE THREAD

**Issue by ForceBru** [lark-parser/lark#223]
Consider this simple grammar:

```
// G1.txt

?start: expr
?expr: expr (OP_ADD | OP_SUB) high_precedence | high_precedence

high_precedence: INT

INT: /\d+/
OP_ADD: "+"
OP_SUB: "-"
```

Then generate standalone: `python3 -m lark.tools.standalone G1.txt > G1_parse.py`

Here's the Python code that attempts to evaluate the expression `expr`:

```
# G1.py

import operator

from lark.visitors import Interpreter
import G1_parse


# this can be done with a bottom-up traversal, but I need a top-down one for my actual code
class Do_Stuff(Interpreter):
    def high_precedence(self, tree):
        number, *_ = self.visit_children(tree)

        tree.val = int(number.value)

        return tree

    def expr(self, tree):
        left, op, right = self.visit_children(tree)

        tree.val = {
            'OP_ADD': operator.add,
            'OP_SUB': operator.sub
        }[op.type](left.value, right.value)

        return tree


code = '1+2-3+4-5'

root = G1_parse.Lark_StandAlone().parse(code)
print(root.pretty())

print(Do_Stuff().visit(root).val)
```

However, this throws an exception:

```
Traceback (most recent call last):
  File "G1.py", line 33, in <module>
    print(Do_Stuff().visit(root).val)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lark_parser-0.6.4-py3.6.egg/lark/visitors.py", line 181, in visit
    return getattr(self, tree.data)(tree)
  File "G1.py", line 23, in expr
    }[op.type](left.value, right.value)
AttributeError: 'Tree' object has no attribute 'value'
```

--------

This happens because _both_ `left` and `right` are instances of `Tree`, which means that `visit_children` failed to visit them. To be precise, both `left` and `right` are instances of `G1_parse.Tree`, and that's a problem, because in `lark/visitors.py` we have this:

```
...
from .tree import Tree
...

class Interpreter:
    ...
    def visit_children(self, tree):
        return [self.visit(child) if isinstance(child, Tree) else child
                for child in tree.children]
    ...
```

So, the `Tree` here is actually `lark.tree.Tree`, but the standalone version works with `G1_parse.Tree`, so `isinstance(child, Tree)` returns `False` and __unvisited children__ are returned.

This can easily be fixed by copying the contents of `lark.visitors.Interpreter` into `G1.py`, which is kinda ugly, or into the standalone parser.

## System info:
 * Python 3.6.3
 * Lark version: 0.6.4 (
https://github.com/lark-parser/lark/commit/737d750b6b296bc05917e17a43e2f699e62de637)

**Comment by ForceBru** [comment]
Well, that's obviously not critical at all, and not even an actual bug, but I think that code generated by Lark should still be able to work with its own basic tree-traversal techniques. `Transformer` and `Interpreter` are, as far as I understand, the two main means of traversing the tree from the bottom and the top respectively, and it would be _nice_ (not obligatory or anything, just very nice) to have both (not only `Interpreter`) in the standalone version.

I think `Interpreter` may even be more powerful than `Transformer`. For example, the Dragon book says the following in _section 5.3_<sup>1</sup>:

> We consider two SDD's for constructing syntax trees for expressions. The first, an S-attributed definition, is suitable for use during bottom-up parsing. The second, L-attributed, is suitable for use during _top-down parsing_.

L-attributed definitions are a superset of S-attributed ones (see section 5.2.4), so a top-down traversal should be able to do everything as bottom-up one can. Thus, only `Interpreter` should be sufficient, but it's neater to have both, to my mind.

Right now, it's impossible to traverse a tree generated by the standalone version at all, and one has to write their own routine to do that, which is just inconvenient. Not critical, but inconvenient.

However, I agree that the standalone parser (and also a lexer, which is awesome!) shouldn't be too crowded.

------
<sup>1</sup> a free (but maybe slightly illegal) copy of the Dragon book, a.k.a "Compilers: Principles, Techniques, & Tools" can br found [here](http://www.informatik.uni-bremen.de/agbkb/lehre/ccfl/Material/ALSUdragonbook.pdf).

**Comment by erezsh** [comment]
Okay, I'm convinced. I added Interpreter and the rest of the transformers/visitors to the standalone.

Don't get used to it, I'm usually more stubborn :)

**Comment by ForceBru** [comment]
Great, now the `standalone` tool generates truly standalone code, and it has become much easier (at least for me) to get a new grammar up and running. Thank you!
