### ISSUE TITLE
Error recovery: Can I add some error recovery strategy?

### ISSUE THREAD

**Issue by evandrocoan** [lark-parser/lark#227]
I see parsers like ANTLR offer some extension support for it: [ANTLRErrorStrategy](https://www.antlr.org/api/Java/org/antlr/v4/runtime/ANTLRErrorStrategy.html) and [Error Reporting and Recovery](http://media.pragprog.com/titles/tpantlr/errors.pdf)

I looked into the [error_reporting_lalr.py](https://github.com/lark-parser/lark/blob/master/examples/error_reporting_lalr.py), and these examples, Lark just bail out parsing upon the first syntax error. It seem to correspond to the ANTLR [BailErrorStrategy](https://www.antlr.org/api/Java/org/antlr/v4/runtime/BailErrorStrategy.html).

I found this thesis from 2005, [lark.pdf](http://www.cocolab.com/products/cocktail/doc.pdf/lark.pdf), there, they talk about error recovering. Is that thesis related with this Lark, or it is some other project with the same name?

**Comment by erezsh** [comment]
I would like Lark to have support for error recovery. If you want to contribute to the code base, that's great. Let me know what you plan to do, and we can discuss it.

> Is that thesis related with this Lark

No, it's just a happy coincidence. That paper is on my to-read list, it seems pretty interesting.

**Comment by evandrocoan** [comment]
I am using lark to build a DSL (Domain-specific language) Parser for my thesis, i.e., I am using lark to build compiler's compiler. Then, it would be nice for the users to have some error recovering on lark, so they can get a better/complete message when they write a bad grammar for my parser.
![image](https://user-images.githubusercontent.com/5332158/45237983-92b61a80-b2b6-11e8-9fe6-b7e77f16265f.png)
Right now I do not have much time available for working on lark for the error recovering feature. I will try to poke around the lark code and see if I can do something simple. Depending on how good my thesis becomes after I publish it next year, I think I can work harder understanding the lark code base and implement some nice error recovering strategy, because when the user's input grammar has errors, they will see the lark parser errors, at least for the lexical and syntactic aspects of the grammar's language they are inputting. This only excludes the semantic aspects from lark because they are handled by me after I get the derivation tree out of lark.

**Comment by erezsh** [comment]
I see. Sounds interesting!

What sort of interface / behavior do you imagine? It will help me make suggestions, and tell you if it's even possible with the current algorithms.

**Comment by evandrocoan** [comment]
> What sort of interface do you imagine?

I am not sure I understood correctly, but I think the interfacing is simple, because the usage of lark would just be like usual/common usage. The difference is only conceptual. Instead of entering my program's grammar into lark, I enter my grammar's grammar, then lark would just output another parser's parser instead of a end-user parser. Then, the users of my parser's parser, would enter their program's grammar and my parser's parser would output their parser. On this context, I would call the usage of lark as a back-end program:
1. The users' of my parser's parser generated from lark, would deal directly with lark, if they input a grammar with lexical/syntactic errors. On this case, the usage of lark would be direct (explicit) for the users using the my generated parser's parser from lark.
1. The users' of generated parser from my parser's parser, would deal directly with my parser's parser, if they input a program with lexical/syntactic errors. On this last case, usage of lark would be transparent (hidden) for the users using the generated parser from my parser's parser.

Resuming this, I am using a Parser's Generator (Lark) to build another Parser's Generator:
![image](https://user-images.githubusercontent.com/5332158/45257905-10942780-b384-11e8-9726-4d33cf618e8a.png)

This new Parser's Generator is Domain Specific Parser Generator, which means it only generates limited Parsers, i.e., you could not use it to generate another Parser's Parser because as Domain Specific Languages, they are limited and are not as general programming languages.

Now, looking over, this contextual lexer seems curious thing. Since I am new to this and I am planing to implement error recovering into lark source code, I am trying to understand how it works by comparing the generated code before and after your fix, by using your unit test grammar example `ABAB`:
![image](https://user-images.githubusercontent.com/5332158/45249528-29ef9200-b2f8-11e8-8c51-b2ff152848bc.png)

The parse table is a little different, and there are few new cool things in between. I think it will not be easy to add good error recovering for LALR(), after researching on few new links. I probably will have to study more new things, like these articles and other thesis listed bellow. I see YACC is a LALR with error recovering, I will also try to give a look into how it does things. These links/references should be my to read list:
1. [specific error recovery in bison/yacc](https://stackoverflow.com/questions/37421213/specific-error-recovery-in-bison-yacc)
1. [Error recovery in an LALR(1) grammar](https://stackoverflow.com/questions/11870125/error-recovery-in-an-lalr1-grammar)
1. [Can parser error recovery be guided automatically by the grammar?](https://stackoverflow.com/questions/21806955/can-parser-error-recovery-be-guided-automatically-by-the-grammar)
1. [specific error recovery in bison/yacc](https://stackoverflow.com/questions/37421213/specific-error-recovery-in-bison-yacc)
1. [REPORT No. 73 Error Recovery for Yacc Parsers by Julia Dain](http://wrap.warwick.ac.uk/60772/7/WRAP_cs-rr-073.pdf)
1. [Practical error recovery in LR parsing by Seppo Sippu](https://doi.org/10.1145/582153.582173)
1. [LR(1) Parser Generation System: LR(1) Error Recovery, Oracles, and Generic Tokens by Arthur Sorkin](https://arxiv.org/pdf/1010.1234.pdf)
1. [Lark - An LALR(2) Parser Generator With Backtracking by J. Grosch](http://www.cocolab.com/products/cocktail/doc.pdf/lark.pdf)

___


> What sort of behavior do you imagine?

In a optimal implementation, the error recovering for lark would allow its users to implement their favorite error recovering strategy as the several ones which can be found on the literature, thesis and articles as the ones listed just above. But I am not sure how this would be possible exactly. First I have to implement a hard coded way of simple error recovering directly into lark source code. Then after that, with more experience and understanding of lark internal workflow, I could look forward into a general extensible error recovering strategy.

The most simple thing I can think right now about error recovering would be changing this part of the lark's source code:
https://github.com/lark-parser/lark/blob/4487bf65c1c8fa3f81ff5a8b77886c2cf69ac79f/lark/parsers/lalr_parser.py#L44-L50

Then instead of raise a exception, I would:
1. Randomly take one of the expected tokens, as the first token and return it.
1. Annotate there was an parsing error in a global list of syntax errors.
1. Then, proceed the parsing as nothing wrong happened.

Therefore, at the end of the parsing, if the global error's list of syntax errors was not empty, I would raise an exception within all the parsing errors. Perhaps, the problem with this strategy could be the parser not recovering correctly and keep throwing a bunch of non-existent syntax errors until the end of the program. This is why I say I would have to study much more about other implementation's strategy for error recovering with LALR parsers.

**Comment by erezsh** [comment]
Lark now supports error recovery! 

Example is here: https://github.com/lark-parser/lark/blob/master/examples/error_puppet.py
