### ISSUE TITLE
Standard lexer failing in simple example

### ISSUE THREAD

**Issue by dsd** [lark-parser/lark#229]
Thanks for lark - seems like a highly complete solution, and I see this as a good option for my project because of the automatic tracking of line/column info.

In order to use `end_line` and `end_column` I see I need to avoid using the "dynamic" lexer which is the default.

However I'm having a hard time with the standard lexer. For example this fails (unless switched back to dynamic):
```
from lark import Lark

l = Lark(r'''start: field+
            name: /[a-zA-Z]+/
            value: /[^\n]+/
            _WS: /[ \t]+/
            field: name ":" _WS? value
         ''', lexer='standard')

print( l.parse("Foo: bar") )
```
Am I doing something wrong, or is there a bug here?

**Comment by whitten** [comment]
Can you get each lexer to give you a stream of tokens for this case?
I mean, just call the lexer repeatedly on the text, but do NOT send it on the parser,
just send it to a "fake" parser that prints it out so we can look at the sequence.
Perhaps after we compare the tokens, we'll see where the mistake is being introduced.

**Comment by erezsh** [comment]
Hi @dsd,
You're right, the dynamic lexer right now doesn't provide `end_line` or `end_input`, but you do need it for the grammar you've specified. The 'standard' lexer is not really that good.

But it's quite easy to calculate them on your own. Here's the pseudo-code :+1: 

            newlines = token.count('\n')
            token.end_line = token.line + newlines
            if newlines:
                token.end_column = len(token) - token.rindex('\n')
            else:
                token.end_column = token.column + len(token)

Don't mind if there are off-by-1 errors here, but that's the gist of it.

@whitten  Lark.lex() does exactly that (only works for the standard lexer tho)

**Comment by erezsh** [comment]
You can also try LALR+contextual lexer, which do provide `end_line` and `end_column`, and might work with your grammar.

**Comment by dsd** [comment]
Thanks, I'm managing to get some initial results that suggest LALR+contextual will work for me.

BTW if you have time in future it might be useful to have some documentation about the pros/limitations of the different parsers and lexers and how to choose between them. It would make lark more accessible for beginners and those of us who have forgotten the intricacies of parser/lexer theory. (still not sure if this is a bug in the standard lexer or just something to be expected?)

Back to the standard lexer, `print list(l.lex('Foo: bar'))` shows:
```[Token(__ANON_0, 'Foo'), Token(__ANON_1, ': bar')]```

**Comment by erezsh** [comment]
The "standard lexer" is just a clone of how yacc's lexer works. So, it's not very good at all, but on some rare occasions it might be useful.

There is some information here: https://lark-parser.readthedocs.io/en/latest/features/

What information or topic do you think are missing?

Anyway, I might add `end_line` and `end_column` to the dynamic earley parser as well. It would be a little tricky but it's possible.

**Comment by dsd** [comment]
You've probably got to draw a line somewhere and require *some* underlying knowledge of parser theory in order for people to be successful with lark. That new doc site looks like a great improvement, although I am still not totally clear. Maybe a good compromise would be adding carefully selected links to help people get up to speed.

For example: If the standard lexer is just a copy from yacc, does that mean that what I've found here is a yacc bug? If I recreate this experiment with yacc, would I get a more informative message that points me to what I've done wrong? Is there a good resource that I could read that explains the limitations of yacc that would let me understand why it can't work with my example?

And adding end_line and end_column to the default parser sounds great if you can make that happen!

**Comment by erezsh** [comment]
The error happens because `name` and `value` can match the same text.

            name: /[a-zA-Z]+/
            value: /[^\n]+/

Yacc was never meant to handle lexical ambiguities such as this. Lark can handle it, and it is rather unique this regard, but not using the standard lexer.

**Comment by dsd** [comment]
Hmm, OK, thanks for clarifying.
Maybe you could mention in the docs under "Note on ambiguity" something like: "The `standard` lexer is a clone of yacc's lexer, and does not handle lexical ambiguities".

For newbies like me it would be good to go deeper, but I haven't found a good way to define/explain the ambiguity above. As a human it seems unambiguous to me (how can it struggle to choose between name and value when it can use the colon to know which one is which?)...

You're saying that there can't be any overlap whatsoever between what is accepted by `name` and `value`? That makes it sound like yacc would be extremely restrictive on the kinds of grammars it could work with.

I searched around a bit and read resources like https://docs.oracle.com/cd/E19504-01/802-5880/6i9k05dh2/index.html and https://en.wikipedia.org/wiki/Ambiguous_grammar but don't really grasp how these issues apply to my grammar. Or would it become unambigious only if `value` is modified to disallow further ":" characters?

Anyway for now I'm closing in some kind of success with lalr+contextual so feel free to close this issue!

**Comment by erezsh** [comment]
It's mentioned here: https://lark-parser.readthedocs.io/en/latest/features/

If you think there's a clearer way to write it, or a better category, feel free to be specific.

> As a human it seems unambiguous to me

That's the first notion from which every programmer has to disabuse himself :)

> That makes it sound like yacc would be extremely restrictive on the kinds of grammars it could work with.

Yes, it probably would be. Good thing there are better parsers nowadays!

I'm not sure I can explain it better, but the point to remember is that the LALR parser, for performance reasons, only sees the past, and one token into the future, at each point. It has to use this limited knowledge to figure out which path to choose, and unlike you, it can't backtrack and try again (again, for performance reasons). It's a reasonable limitation, but it does mean you have to be a little more aware on how you write your grammar.

Or use Earley + dynamic lexer, which will handle all ambiguity.
