### ISSUE TITLE
Document regex flags

### ISSUE THREAD

**Issue by ealter** [lark-parser/lark#230]
I saw in the cheatsheet that lark supports regex flags `imslux`. However, I couldn't find any documentation in lark for what these meant. After reading the lark sourcecode, I realized that these are documented in the python `re` module docs (https://docs.python.org/3/library/re.html) under the heading `(?aiLmsux)`.

I'm not sure the best place to put this in the lark documentation. There's no anchor tag on that section of the python docs to directly link to.

**Comment by erezsh** [comment]
Hi, if you'd like to add this to the documentation, then probably the best place is ./docs/grammar.md (https://lark-parser.readthedocs.io/en/latest/grammar/)

I'll be happy to accept a PR for it.

Do note that the `a` flag only exists in Python3, so similarly Lark will only support it for Python3

**Comment by Valt25** [comment]
I have missed it right now, because there is no "imslux" in re docs module. Only "aiLmsux". Maybe link directly to python docs or using alternatives(aiLmsux) is better?
