### ISSUE TITLE
Can I created a indentation block based language with the contextual lexer?

### ISSUE THREAD

**Issue by evandrocoan** [lark-parser/lark#231]
The documentation says:
https://github.com/lark-parser/lark/blob/04db90b72e558e8ac374243b346f71e96caac0c8/lark/lark.py#L43

* https://github.com/lark-parser/lark/issues/48 Python example grammars are broken

But the example for the python 3 grammar uses the postlex:
https://github.com/lark-parser/lark/blob/04db90b72e558e8ac374243b346f71e96caac0c8/examples/python_parser.py#L23-L27

**Comment by erezsh** [comment]
Yes, you can use the contextual lexer as well!

I should update the docstring.
