### ISSUE TITLE
No EOL on last line of file

### ISSUE THREAD

**Issue by timofurrer** [lark-parser/lark#233]
I have some grammer with does something like this:

```ebnf
_NEWLINE: ( /\r\n[\t ]*/ | /\n[\t ]*/ | COMMENT )+
_INDENT: "<INDENT>"
_DEDENT: "<DEDENT>"

foo_compound_stmt: "FOO _NEWLINE (_INDENT bar_stmt+ _DEDENT)?
bar_stmt: "BAR" STRING_NO_WS _NEWLINE
```

And a code sample might look like this:

```
FOO
    BAR something
```

This work perfectly fine unless the `BAR something` is the last line in the file without an EOL character at the end. This happens if the file is in dos format and saved under Windows ...
In this case a `_NEWLINE` is expected so that `_DEDENT` matches.

Do you have any solution for this problem?

**Comment by erezsh** [comment]
The quick and easy solution is to add `'\n'` to the input.

There is a plan to add an EOF symbol to Lark for conceptual completeness, but I think it's not necessary for your use-case.

**Comment by timofurrer** [comment]
> The quick and easy solution is to add `'\n'` to the input.

That's what I ended up doing. 

> There is a plan to add an EOF symbol to Lark for conceptual completeness

Is this coming any time soon?

**Comment by erezsh** [comment]
> Is this coming any time soon?

Probably not, since there are many other features that are more important. 

You can follow #237 to get notified on its progress.
