### ISSUE TITLE
Ambiguity error for simple grammar

### ISSUE THREAD

**Issue by carstenlipka** [lark-parser/lark#238]
Hi,

I recently stumbled upon an error, where ``lark`` is missing some ambiguous solutions. I tried to create a minimal example to make the problem easier to understand. The code is the following:

#### Code

```python
import lark

simple_string = 'aaab'
simple_grammar = '''
    s: as? as? b
    as: a a?

    ?a: /a/
    ?b: /b/
    '''
simple_parser = lark.Lark(simple_grammar, start='s', ambiguity='explicit')
print(simple_parser.parse(simple_string).pretty())
```

There is an ambiguity in the first rule for matching **aaab**. Either the first non-terminal ``as`` is resolved to the terminals **aa** or the second non-terminal ``as`` is, leaving the other one to be resolved to a single **a** and resulting in two solutions for this string-grammar combination. However, the output of ``lark`` is the following indicating that there is no ambiguity:

#### Output

```
s
  as
    a
  as
    a
    a
  b
```

Whereas the expected output is the following:

#### Expected Output

```
_ambig
  s
    as
      a
    as
      a
      a
    b
  s
    as
      a
      a
    as
      a
    b
```

I verified the ambiguity of this simple example using a different parser. Finally, if I change the ``b`` in the first rule from a non-terminal to the corresponding terminal, I get the right output.

**Comment by erezsh** [comment]
Thanks, I'll look into it.

What's interesting is that the cyk parser misses out on this ambiguity as well. @uriva any thoughts?

**Comment by uriva** [comment]
IIRC the CYK implementation only returns a single result, that can be manipulated by the rule weights.

It can probably be tweaked to return all of them, but it requires more knowledge of the lark API which is why we didn't do it.

@ehudt might know more.

**Comment by erezsh** [comment]
Thanks, I forgot to add him too. My bad.
