### ISSUE TITLE
Unexpected end_line/end_column values

### ISSUE THREAD

**Issue by dsd** [lark-parser/lark#240]
Take this test app:

```python
from lark import Lark

parser = Lark(r"""
%import common.LF -> _NL

start: line+
line: /[^\n]+/ _NL

COMMENT: "#" /[^\n]/* _NL
%ignore COMMENT
""", parser='lalr', propagate_positions=True)

text=\
    "line1\n" \
    "line2\n" \
    "# a comment\n" \
    "# another comment\n" \
    "line3\n"

def print_pos(node, name):
    print "%s start=%d,%d end=%d,%d" % (name, node.line, node.column, node.end_line, node.end_column)

result = parser.parse(text)
print_pos(result.children[0], "line1")
print_pos(result.children[1], "line2")
```

The first line printed is:
```line1 start=1,1 end=2,1```

The documentation says that end_line and end_column are the line/column "where the token ends". Personally I would have interpreted that to suggest that the end should be reported as line 1, column 6 (the newline character at the end of the line). I would instead describe the reported values as "the character after the end of the token". Maybe the documentation could be made a bit clearer here.

The second line printed is:
```line2 start=2,1 end=5,1```

and I find that unexpected and hard to work with. It appears that the end line/column info reported actually is the position of the start of the next parsed token. And in this case it's unfortunate that it has included the ignored comments when calculating this. Is this a bug?

I'm hoping to use this start/end information to carefully modify specific portions of the original file, but I don't want to trample on other parts of the file such as comments.

**Comment by erezsh** [comment]
Yes, it appears to be a bug. I'll push a fix soon.

**Comment by erezsh** [comment]
This seems to be working correctly with the latest `master`. Please verify.

**Comment by dsd** [comment]
Do you  have a recommended approach for how to install master? `pip install lark-parser` shows that I'm already on the latest release 0.6.4

**Comment by geographika** [comment]
@dsd you can install from Git directly. The following works for me:

`pip install git+git://github.com/lark-parser/lark@master -U`

**Comment by erezsh** [comment]
Cool! I wasn't aware of this shortcut. 

Usually I `git clone` and then `python setup.py install`

**Comment by dsd** [comment]
Thanks. It's working on master and I propose this doc clarification: https://github.com/lark-parser/lark/pull/241

**Comment by erezsh** [comment]
Thanks, I merged it in. It should be intuitive tho, imho, because that's how Python indexes arrays.
