### ISSUE TITLE
v_args-decoration of Transformer breaks staticmethods

### ISSUE THREAD

**Issue by altvod** [lark-parser/lark#246]
If callback methods are defined as staticmethods, and the Transformer is decorated with `v_args`, e.g.:
```
@v_args()
class MyTransformer(Transformer):
    @staticmethod
    def integer(args):
        pass # some code here
```
Then all the `staticmethod`s break - they start receiving a `MyTransformer` instance as the first argument. Removing `@staticmethod` and adding `self` as the first argument works as a workaround

**Comment by erezsh** [comment]
Fixed in `master` and version 0.6.5
