### ISSUE TITLE
How to walk the tree top-down?

### ISSUE THREAD

**Issue by dongli** [lark-parser/lark#252]
I would like to write a parser to parse some configuration file (see #251), change some items in it and write them back into a new configuration file. I have written a transformer to walk the tree, but it is from bottom to up, which is not right for rewriting.

**Comment by erezsh** [comment]
See the Interpreter class:

https://github.com/lark-parser/lark/blob/master/lark/visitors.py#L172

**Comment by dongli** [comment]
Thanks for quick guide!

**Comment by dongli** [comment]
@erezsh I try to import `Interpreter` class as:

```
from lark import Lark, Transformer, Interpreter
```

but encounter the following error:

```
Traceback (most recent call last):
  File "./parse_met_config.py", line 3, in <module>
    from lark import Lark, Transformer, Interpreter
ImportError: cannot import name 'Interpreter' from 'lark' (/usr/local/lib/python3.7/site-packages/lark/__init__.py)
```

**Comment by dongli** [comment]
I have fixed the import error by:

```
from lark import Lark
from lark.visitors import Transformer, Interpreter
```

but found no clue how to write a rewriter by visiting each node.

**Comment by erezsh** [comment]
Perhaps these tests will help you (taken from test_tree.py):

        t = Tree('a', [Tree('b', []), Tree('c', []), 'd'])

        class Interp1(Interpreter):
            def a(self, tree):
                return self.visit_children(tree) + ['e']

            def b(self, tree):
                return 'B'

            def c(self, tree):
                return 'C'

        self.assertEqual(Interp1().visit(t), list('BCde'))

        class Interp2(Interpreter):
            @visit_children_decor
            def a(self, values):
                return values + ['e']

            def b(self, tree):
                return 'B'

            def c(self, tree):
                return 'C'

        self.assertEqual(Interp2().visit(t), list('BCde'))

        class Interp3(Interpreter):
            def b(self, tree):
                return 'B'

            def c(self, tree):
                return 'C'

        self.assertEqual(Interp3().visit(t), list('BCd'))

**Comment by dongli** [comment]
Thanks for the hint! I finally managed to rewrite the parsed file.
