### ISSUE TITLE
Order of nodes in iter_subtrees()

### ISSUE THREAD

**Issue by worldmind** [lark-parser/lark#259]
Hi, thanks for your project.
I make some [experiment ](https://github.com/worldmind/scripts/blob/master/parsers/test_lark.py) and have question - why `iter_subtrees()` did not return nodes in same order like `pretty()` does?
I want to convert from one format to another and need to process nodes in order of source file, I can write own walk function (or just copy [pretty](https://github.com/lark-parser/lark/blob/master/lark/tree.py#L30)), but maybe such function will be useful not just for me?

**Comment by erezsh** [comment]
`iter_subtrees()` iterates nodes bottom-up, while `pretty()` iterates from the top down. Feel free to contribute a `iter_subtrees_topdown`, it should be simpler to implement than the former.

**Comment by worldmind** [comment]
[PR-260](https://github.com/lark-parser/lark/pull/260)
