### ISSUE TITLE
Nearley macros not supported

### ISSUE THREAD

**Issue by kasbah** [lark-parser/lark#26]
I had a go at [converting my nearley grammar](https://github.com/monostable/electro-grammar/tree/python) but I encountered the error:

```  
File "/home/kaspar/.local/lib/python3.5/site-packages/lark/tools/nearley.py", line 116, in _nearley_to_lark
    assert False, directive
AssertionError: include
```

So I am guessing `@include` is not supported yet. I also noticed [the TODO for macros](https://github.com/erezsh/lark/blob/3b0ab867ef330435f3aa83738854a5af7cdaa96f/lark/tools/nearley.py#L122). Is my assessment correct that includes and macros are not yet supported?

**Comment by erezsh** [comment]
That is correct! Do you need both? I imagine includes would be easier to add.

**Comment by kasbah** [comment]
I do make use of both in my grammar, yes. There are always workarounds of course. I think I'll have a go at implementing includes when I get a chance though.

**Comment by erezsh** [comment]
Cool, let me know if you have any questions.

**Comment by kasbah** [comment]
Do you agree that the best way to add macros would be to add support for them in Lark and then translate them?

**Comment by erezsh** [comment]
That would be my choice as well.
Since you are familiar with macros in nearley, can you describe their main properties (i.e. features) ?

**Comment by kasbah** [comment]
They are simple pre-processor functions with variables, that are expanded to several rules. I [added a test case to nearley yesterday](https://github.com/Hardmath123/nearley/pull/311/commits/f17550ad52879bf5f1129f814efbe1020ca78d8d) that should be a simple example of a macro.

**Comment by erezsh** [comment]
The way I understand it, there are the following sub-tasks, all in load_grammar.py:

1) Add macro syntax, both definition and usage
2) In GrammarLoader.load_grammar, verify and create macros (also add macros to Grammar object)
3) In Grammar.compile, apply the macros using a transformer

**Comment by kasbah** [comment]
So, starting with syntax, are you opposed to e.g.:

```
combine[X, Y]: $X | $Y | $X "/" $Y | $Y "/" $X
```

**Comment by erezsh** [comment]
Well, square brackets are already used for optional expressions. But I'm fine with

    combine{X, Y}: $X | $Y | $X "/" $Y | $Y "/" $X

**Comment by erezsh** [comment]
Now that Lark supports templates, this should be a lot easier to do.

**Comment by erezsh** [comment]
Closing at there seems to be no interest in this.

(Possibly nearley support will be removed altogether in the future)
