### ISSUE TITLE
Maximum recursion depth exceeded during grammar loading

### ISSUE THREAD

**Issue by SupraSummus** [lark-parser/lark#264]
* python 3.7
* lark ab213bfc1064994a4eb50e3d450b542320a92604
* `Lark('_A: _A "a" |')` raises `RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by SupraSummus** [comment]
`Lark('A: A "a"')` results in same error, but `a: a "a"` is fine. I suspect capital letters have special meaning for Lark.

**Comment by erezsh** [comment]
Solved
