### ISSUE TITLE
Crash when importing a grammar both at top-level and a sub-grammar

### ISSUE THREAD

**Issue by wjl** [lark-parser/lark#268]
If I try to import both at the top-level as well as in a sub-grammar, Lark just crashes with a KeyError. I've attached a very small, silly reproducing example, so you can reproduce the error yourself, but this came up while working on a real grammar (being ported from a different parser).

The first and most obviously place this came up is where a bunch of different custom definitions of whitespace for different contexts is put into its own sub-grammar (whitespace.lark). It then needed to be imported in many sub-grammars, as well as at the top-level, because everyone uses one or more types of whitespace. A similar problem came up for numbers -- they are put into a sub-grammar, and need to be imported by a few sub-grammars which need to use one or more types of custom number parsing -- which is also needed at the top-level. 

[lark_bug.zip](https://github.com/lark-parser/lark/files/2522229/lark_bug.zip)

(Anyway, a workaround -- which I'm using for now -- seems to be to just slap everything into a single monolithic grammar, but that's not very modular.)

**Comment by wjl** [comment]
The previously attached file didn't seem to work. Let's try it again.

[lark_bug2.zip](https://github.com/lark-parser/lark/files/2522247/lark_bug2.zip)

**Comment by erezsh** [comment]
Include a copy-paste of the exception you're getting.

**Comment by wjl** [comment]
> Include a copy-paste of the exception you're getting.

Here is the backtrace I get:

```
Traceback (most recent call last):
  File "parser.py", line 10, in <module>
    parser = lark.Lark(grammar, ambiguity="explicit")
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/lark.py", line 157, in __init__
    self.grammar = load_grammar(grammar, self.source)
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/load_grammar.py", line 704, in load_grammar
    new_td, new_rd = import_from_grammar_into_namespace(g, '.'.join(dotted_path), aliases_dict)
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/load_grammar.py", line 547, in import_from_grammar_into_namespace
    to_import = list(bfs(aliases, rule_dependencies))
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/utils.py", line 40, in bfs
    for next_node in expand(node):
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/load_grammar.py", line 538, in rule_dependencies
    _, tree, _ = imported_rules[symbol]
KeyError: Token(RULE, 'aba')
```

We're you not able to reproduce this with the tiny example I provided? I'm using lark (0.6.5)  installed with pip on Python 3.5 (latest Python in Debian stable). If this actually works for you I'd love to know which version supports this! =)

Hope this helps!

**Comment by erezsh** [comment]
Hi @wjl , I didn't try to run it because I've had other things on my mind.

Looking at your code, I see you have the line: `%import .B (aba)`

But, `B.lark` doesn't have any rule called `aba`, and so Lark fails correctly.

The only issue here is that there should be a friendlier error message.

**Comment by wjl** [comment]
My stripped down example seems to have been a poor example! =) But the bug as I described it does indeed exist. I will fix the example and reupload something that shows the error correctly.

**Comment by wjl** [comment]
[lark_bug3.zip](https://github.com/lark-parser/lark/files/2546407/lark_bug3.zip)

Okay, here is an updated example, and more information.

This doesn't just happen ONLY when importing something both from a module and the top-level. As you pointed out, my first example was faulty, and was just giving a KeyError due to me making a typo in B.

The actual error seems to occur when:
1) You import something from in a module and at at top-level.
2) The rule you import is built from other rules in the module (as any real rule would be, but wasn't in my example since I was trying to strip it down to the basics).
3) A "workaround" is to import the rule and *every subrule* it depends on in a complete transitive closure -- but this of course completely defeats the purpose of modularity. =)

I've uploaded a new example, and the error given now is:

Traceback (most recent call last):
  File "parser.py", line 13, in <module>
    parser = lark.Lark(grammar, ambiguity="explicit")
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/lark.py", line 157, in __init__
    self.grammar = load_grammar(grammar, self.source)
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/load_grammar.py", line 701, in load_grammar
    g = import_grammar(grammar_path, base_paths=[base_path])
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/load_grammar.py", line 519, in import_grammar
    grammar = load_grammar(text, grammar_path)
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/load_grammar.py", line 704, in load_grammar
    new_td, new_rd = import_from_grammar_into_namespace(g, '.'.join(dotted_path), aliases_dict)
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/load_grammar.py", line 547, in import_from_grammar_into_namespace
    to_import = list(bfs(aliases, rule_dependencies))
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/utils.py", line 40, in bfs
    for next_node in expand(node):
  File "/home/wjl/.local/lib/python3.5/site-packages/lark/load_grammar.py", line 538, in rule_dependencies
    _, tree, _ = imported_rules[symbol]
KeyError: Token(RULE, 'A.a_1')

As noted in the new parser.py, you can "fix" it by also importing a_1 at the top-level, but notice that this:
1) Should not be necessary, as I don't use a_1 directly at the top-level, and
2) It isn't required when I do the same import in B, and
3) If I don't import it from A, but import it from *B* instead, then it works.

**Comment by erezsh** [comment]
Thanks for submitting this bug! It should work now (in latest `master`). 

If you have any more trouble, feel free to re-open or submit a new issue.

**Comment by wjl** [comment]
Thanks for fixing this so quickly. I will give the new version a shot soon.

**Comment by erezsh** [comment]
No problem. It's a supported feature (although in alpha status), so I'll do my best to fix whatever issues may arise when using it.

One thing I'll have to add soon is Transformer (and Visitor) support, since currently imported branch names contain dots, which aren't supported with the current interface of using python method names to address branch names.
