### ISSUE TITLE
How to escape characters in regex

### ISSUE THREAD

**Issue by iafisher** [lark-parser/lark#271]
Hello!

I'm looking to match literal asterisks and forward slashes in my regular expression pattern, but prefixing the asterisk with a backslash gives me a DeprecationWarning, and prefixing the forward slash with a backslash doesn't work--it is interpreted as the end of the regex pattern. How can I match these characters as literals within my regex?

Thank you.

**Comment by erezsh** [comment]
Make sure your grammar string is raw. i.e. `r""" grammar """`

**Comment by iafisher** [comment]
That worked perfectly, thank you!
