### ISSUE TITLE
Your example looks simple, input and output is almost same. Can you do infix to postfix conversion as an example.

### ISSUE THREAD

**Issue by LIJUCHACKO** [lark-parser/lark#274]

**Comment by erezsh** [comment]
What? Are you talking about the reconstructor?

**Comment by LIJUCHACKO** [comment]
Functions provided in transformer class (class TreeToJson(Transformer)) is very simple. It doesn't give the idea that, the input (say, def pair(self, p):)  to some of them are actually lists and they can be modified before returning.

**Comment by erezsh** [comment]
It's equivalent. You can do:
```python
def pair(self, x):
    return x[0] + x[1]
```
