### ISSUE TITLE
Parsing length specifiers?

### ISSUE THREAD

**Issue by qwertystop** [lark-parser/lark#276]
For using Lark to parse structured data, it would be very useful to have something like:

    prefixed: NUMBER rule~NUMBER

such that `prefixed` matches a number, followed by that many matches of the rule. I don't see anything about making that sort of backreference in the documentation, except by defining `prefixed` as a terminal with a regex (which prevents the use of all the advantages `lark` provides over regexes, and forces `rule` to be written in the form of a regex).

If it is currently possible, what's the syntax? If not, is it possible that it might be added?

**Comment by qwertystop** [comment]
Thank you for indicating Constructor; it looks like it'll more or less do what I was looking for, if somewhat less readably.

**Comment by erezsh** [comment]
Perhaps it's possible to create a nice DSL that compiles into Construct calls :)
