### ISSUE TITLE
lexers are under documented?

### ISSUE THREAD

**Issue by nbecker** [lark-parser/lark#279]
I'm trying to find some documentation on lexer behaviors.  For example, do they ignore whitespace?  Is this behavior programmable?  I'm not seeing anything about this in the existing docs.

**Comment by erezsh** [comment]
Lexer behavior is relatively standard across parsers. Lexers in Lark don't ignore whitespace, unless you specifically tell them to, with `%ignore`. 

This is mentioned here: https://lark-parser.readthedocs.io/en/latest/grammar/

If you have suggestions on how to improve the docs, I'll be happy to hear them.
