### ISSUE TITLE
Regex syntax used in python example is not supported

### ISSUE THREAD

**Issue by MegaIng** [lark-parser/lark#280]
In the [python3 example](https://github.com/lark-parser/lark/blob/149f7cec1f828358ad74d91bde7ddef63a118159/examples/python3.lark#L181) the syntax `${FLOAT_NUMBER}` is used to include the syntax defined in `FLOAT_NUMBER` into `IMAG_NUMBER`. Sadly, this syntax does not work:
```
import lark

parser = lark.Lark('''
start: IMAG_NUMBER
FLOAT_NUMBER: /((\d+\.\d*|\.\d+)(e[-+]?\d+)?|\d+(e[-+]?\d+))/i
IMAG_NUMBER: /\d+j|${FLOAT_NUMBER}j/i
''')
print(parser.parse("5j").pretty())  # Works
print(parser.parse("5.0j").pretty())  # Fails with UnexpectedCharacters
```

I have no idea why it behaves that way, but it makes for a hard to find bug in the python-grammar.

**Comment by erezsh** [comment]
You're right, this isn't a feature in Lark. I used it in the Python 3 grammar by accident.

A proper way to "reuse" terminals is this:

```ruby
IMAG_NUMBER: /\d+j/i | FLOAT_NUMBER "j"i
```

I fixed the python3 grammar. Thanks.
