### ISSUE TITLE
Earley and LALR parser do not agree on results

### ISSUE THREAD

**Issue by cr1901** [lark-parser/lark#282]
I'm not an expert on parsers, so this may not be a bug, but can't hurt to file an issue...

I'm trying to create a parser for specially-formatted 68k assembly (subset):

```
m68kdis_parser = lark.Lark(r"""
    program : line+
    line : hexint WS_INLINE hexint WS_INLINE (label WS_INLINE)? insn WS_INLINE? NEWLINE
    insn: two_op_insn

    insn_name: UCASE_LETTER+
    two_op_insn: insn_name WS_INLINE addr_offset "," areg

    addr_offset: INT "(" areg ")"
    label: "L" /[0-9]/+

    areg: "A"/[0-7]/

    hexint : HEXDIGIT+

    %import common.WS_INLINE
    %import common.CNAME
    %import common.HEXDIGIT
    %import common.UCASE_LETTER
    %import common.NEWLINE
    %import common.INT
    %import common.WS
    %ignore WS""", start="program", parser="lalr")
```

The following test string succeeds with the Earley parser, but fails with LALR:

```
00000940   47ed0080				LEA	128(A5),A3
```

```
---------------------------------------------------------------------------
UnexpectedCharacters                      Traceback (most recent call last)
<ipython-input-336-f9ec4572c60d> in <module>()
----> 1 m68kdis_parser.parse("00000940   47ed0080                               LEA     128(A5),A3")

C:\msys64\mingw64\lib\python3.6\site-packages\lark\lark.py in parse(self, text)
    221     def parse(self, text):
    222         "Parse the given text, according to the options provided. Returns a tree, unless specified otherwise."
--> 223         return self.parser.parse(text)
    224 
    225         # if self.profiler:

C:\msys64\mingw64\lib\python3.6\site-packages\lark\parser_frontends.py in parse(self, text)
     36         token_stream = self.lex(text)
     37         sps = self.lexer.set_parser_state
---> 38         return self.parser.parse(token_stream, *[sps] if sps is not NotImplemented else [])
     39 
     40 class LALR_TraditionalLexer(WithLexer):

C:\msys64\mingw64\lib\python3.6\site-packages\lark\parsers\lalr_parser.py in parse(self, seq, set_state)
     66 
     67         # Main LALR-parser loop
---> 68         for i, token in enumerate(stream):
     69             while True:
     70                 action, arg = get_action(token.type)

C:\msys64\mingw64\lib\python3.6\site-packages\lark\lexer.py in lex(self, stream)
    257     def lex(self, stream):
    258         l = _Lex(self.lexers[self.parser_state], self.parser_state)
--> 259         for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
    260             yield x
    261             l.lexer = self.lexers[self.parser_state]

C:\msys64\mingw64\lib\python3.6\site-packages\lark\lexer.py in lex(self, stream, newline_types, ignore_types)
    103             else:
    104                 if line_ctr.char_pos < len(stream):
--> 105                     raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, state=self.state)
    106                 break
    107 

UnexpectedCharacters: No terminal defined for 'E' at line 1 col 25

00000940   47ed0080				LEA	128(A5),A3
                        ^
```

The problem is that "LEA" is being misinterpreted as a "label", but since "labels" are optional, shouldn't the parser be trying to match to an "insn" token? Or am I misunderstanding something fundamental?

Lark version is `0.6.4`

**Comment by erezsh** [comment]
LALR is much faster than Earley, but mathematically weaker. That means that grammars that Earley can parse easily, won't parse in LALR.

Actually, it's very possible that LALR can be used in your case. However, the existence of `WS_INLINE` all over the line interferes with its predictive abilities, which are more limited than Earley's.

I am also not sure what is the point, since you are already ignoring all whitespace. If you're trying to "force" a separation of terminals.. Well, that's already built-in to the concept of the parser.

**Comment by night199uk** [comment]
I use this exact case in Earley, so the current Earley parser will handle it. I don't know about LALR. Just wanted to second the use case :-) In my case I want to basically ignore all whitespace - but I have specific places in the files where I need to ensure there is specific whitespace.
```
TABSPACE: TAB|SPACE
_TS: TABSPACE
_MTS:   TABSPACE  // Mandatory Tab/Space
_EOL: CR | LF | ( CR LF )

rule: TOKEN _MTS TOKEN _EOL

%ignore _TS
%ignore _EOL
```

This still ignores extraneous whitespace before and after TOKEN, without having to explicitly encode it but ensures there is a TAB or SPACE between the two tokens. The more useful use case here is the _EOL; which ensures my lines end with an _EOL which is semantically important but otherwise ignores empty lines and extra _EOLs without having to make every line _EOL+ (which is what I used to do).

**Comment by cr1901** [comment]
@erezsh I removed the explicit whitespace, and started reworking the parser:

```
m68kdis_parser = lark.Lark(r"""
program : line+
line : hexint hexint label? directive

directive: "DC" SIZE_MODIFIER dec_literal "," dec_literal
hexint : HEXDIGIT+
label: "L" /[0-9]/*
dec_literal: "#" "-"? INT

SIZE_MODIFIER: (".") ["B" | "W" | "L"]

%import common.WS_INLINE
%import common.CNAME
%import common.HEXDIGIT
%import common.UCASE_LETTER
%import common.NEWLINE
%import common.INT
%import common.WS
%ignore WS""", start="program", parser="lalr")
```

Attempting to parse the first line of the disassembly I'm looking at results in the following error:
```
m68kdis_parser.parse("00000000   534e4342				DC.W	#21326,#17218")
```

```
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.6/site-packages\lark\parsers\lalr_parser.py", line 46, in get_action
    return states[state][key]
KeyError: 'DC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "format.py", line 81, in <module>
    m68kdis_parser.parse("00000000   534e4342                           DC.W    #21326,#17218")
  File "C:/msys64/mingw64/lib/python3.6/site-packages\lark\lark.py", line 223, in parse
    return self.parser.parse(text)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\lark\parser_frontends.py", line 38, in parse
    return self.parser.parse(token_stream, *[sps] if sps is not NotImplemented else [])
  File "C:/msys64/mingw64/lib/python3.6/site-packages\lark\parsers\lalr_parser.py", line 70, in parse
    action, arg = get_action(token.type)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\lark\parsers\lalr_parser.py", line 49, in get_action
    raise UnexpectedToken(token, expected, state=state)  # TODO filter out rules from expected
lark.exceptions.UnexpectedToken: Unexpected token Token(DC, 'DC') at line 1, column 24.
Expected: hexint, __anon_plus_1, HEXDIGIT
```

What do I need to change? Immediately following whitespace is the literal `DC`, so I am unsure what the lalr parser is complaining about.

**Comment by erezsh** [comment]
Well, what is DC? I don't see any terminal matching it..

**Comment by cr1901** [comment]
@erezsh I feel like "DC" should be matching the "DC" literal in the `directive` rule?

```
directive: "DC" SIZE_MODIFIER dec_literal "," dec_literal
```

**Comment by erezsh** [comment]
Ok, the issue is that you declared hexint as a rule instead of terminal (HEXINT):

```python
m68kdis_parser = lark.Lark(r"""
program : line+
line : HEXINT HEXINT label? directive

directive: "DC" SIZE_MODIFIER dec_literal "," dec_literal
HEXINT : HEXDIGIT+
label: "L" /[0-9]/*
dec_literal: "#" "-"? INT

SIZE_MODIFIER: (".") ["B" | "W" | "L"]

%import common.CNAME
%import common.HEXDIGIT
%import common.UCASE_LETTER
%import common.NEWLINE
%import common.INT
%import common.WS
%ignore WS""", start="program", parser="lalr")
                                                                ```

**Comment by cr1901** [comment]
Terminals mean "no further rightmost derivation possible", correct? In this case, isn't `HEXINT` a shorthand for the following rule?

```
HEXINT : HEXDIGIT HEXINT | HEXDIGIT
```

If so, why is `HEXINT` considered a terminal?

**Comment by erezsh** [comment]
When using LALR, you want to pass as much work to the lexer as possible, to reduce the chances of collisions in the parser.

**Comment by cr1901** [comment]
>When using LALR, you want to pass as much work to the lexer as possible, to reduce the chances of collisions in the parser.

Should my second test case [link](https://github.com/lark-parser/lark/issues/282#issuecomment-446684050) have triggered a collision error then? Or is this a case where "there was no collision, I just gave the parser bad input"?

**Comment by erezsh** [comment]
If Earley can parse it, and LALR can't, it's probably a collision.

**Comment by finjulhich** [comment]
I have a file that 1.5Mbytes in size, and has 12k lines.
The file contains space-padded optional fields, which forces me to **not** ignore white spaces.
Some fields can be like "              " (empty: 12 spaces)  or "         4500" (over 12 places).

I suspect there are collisions because of me not ignoring whitespaces and lexing them explicitly.

Here is an example with 3 lines with various fields present/absent:

> JLY20       ----     52.83B     ----     52.83B     ----    UNCH           5      52.51                        6511
> AUG20      ----     52.51B     ----     52.51B     ----    UNCH                  52.47           1           5944
> SEP20      ----     52.82B     ----     52.82B     ----    UNCH           9      52.43        1852       15614

The fields to the right on UNCH are a fixed number of spaces (12) wide, and there could be a number or not.
I lex those fields with this rule:     `volws:     (" " | DIGIT) ~ 12`

Is there a way to rework my grammar with ignoring whitespace and yet still account for "empty" fields?

**Comment by erezsh** [comment]
@finjulhich 
One classic technique in parsers is to handle exceptional cases in the lexer, and then parse them at a second pass. So, for example, you can have the following terminals:

    UNCH: "UNCH" " " [NUM " "]  "    " NUM " "  SPACE_PADDED_NUM

etc. (don't mind the specifics)

And then you can parse UNCH manually after the main parse is finished.

**Comment by finjulhich** [comment]
My rendering was not very good in the previous post.
The format from the beginning of the row to UNCH is fixed and easily parsed.
After that, there are 3 possibilities:
```
"UNCH" FIELD1 FIELD2 NEWLINE
"UNCH" FIELD1 FIELD2 FIELD3 NEWLINE
"UNCH" FIELD1 FIELD2 FIELD3 FIELD4 NEWLINE
```

FIELD1: 12-space padded positive integer, can be only spaces
FIELD2: 10-space padded signed number, always has a number, never only spaces
FIELD3: 12-space padded positive integer, can be only spaces
FIELD4: 12-space padded positive integer, can be only spaces

Is   `(" " | DIGIT) ~ 12 `   the right way to express the FIELD1/3/4 ?
Is  `" "+ SIGNED_NUMBER`  the correct expression for FIELD2 ?

Can I adapt your above suggestion to my problem?

Thank you
