### ISSUE TITLE
Call Transformer children with tree, children instead of only children

### ISSUE THREAD

**Issue by evandrocoan** [lark-parser/lark#302]
This would allow to return something like `self.__default__(tree, children)`, which keeps the tree node intact, i.e.,  with no transformations. For example:
```python
class TreeTransformer(Transformer):

    def somenode(self, tree, children):
        """ Transform this node into the first child """        
        return children[0]

    def someothernode(self, tree, children):
        """ Does no transform anything """        
        self.someinfo = children[0]
        return self.__default__(tree, children)
```

I already implemented this on my fork, all Unit Tests are passing after fixing a few things earlier today:
1. https://github.com/evandrocoan/pushdownparser/commit/32424bc2f3b185cf5924afa3e7a1ff135478493c Added the parent attribute to tree.py and set Transformer to call
1. https://github.com/evandrocoan/pushdownparser/commit/a21b090a48edca0d13adb5ae476ae39db18174ff Fixed TypeError: __default__() takes exactly 4 arguments (3 given)
1. https://github.com/evandrocoan/pushdownparser/commit/17ff00831e9f2f0700fc3f08a560d05442c9f0b5 Fixed TypeError: <lambda>() takes exactly 4 arguments (3 given)

**Comment by erezsh** [comment]
1.

Parents aren't part of the tree, to allow duplicating identical nodes across the tree (which would create parent collision).

You can provide Lark with your own tree instance, that inherits from Tree. You can also create your own `MyTransformer(Transformer)` and override __default__ to produce your own trees.

So changing Lark's Tree class isn't necessary, and can introduce bugs in other people's code.

2.

There is a reason why Transformer provides only children. That is the classic parser interface. To allow for other interfaces, I wrote the `v_args` decorator.
