### ISSUE TITLE
JSON parser example uses a nonstandard grammar

### ISSUE THREAD

**Issue by Zac-HD** [lark-parser/lark#305]
I've been working on a tool to generate strings matching an EBNF grammar (HypothesisWorks/hypothesis#1740), and have found Lark wonderful to work with.  Thanks so much!

I then decided to use the [JSON tutorial grammar](https://github.com/lark-parser/lark/blob/master/docs/json_tutorial.md) as a test input, and discovered three cases that match the grammar but cannot be deserialised by Python's `json.loads` function.  Each of these comes from the `common.lark` grammar:

- The `WS` whitespace terminal matches the `\f` form feed character, which is not ignorable whitespace per [json.org](https://www.json.org/)
- `"." INT` matches as a `NUMBER` (via `DECIMAL`), but the JSON spec required one or more digits before a decimal place.  In Python 3, the regex digit class `\d` also matches *many* numeric characters from other scripts which are not in the valid-for-JSON `[0-9]` digit class.
- The `ESCAPED_STRING` terminal permits unescaped control characters, which are not valid in JSON strings.

I'm not sure what you want to do about this (if anything), but I'd be happy to write a footnote explaining the tradeoff between compact definition for a tutorial and strict standards compliance, with a link to the official grammar listing on the json.org site.

**Comment by erezsh** [comment]
Hi Zac, thanks for your input.

The tutorial exists to instruct users on how to use Lark, and not to provide a practical JSON implementation.

But, if you want to correct the tutorial, or add a note explaining the differences, I'd be fine with that.

**Comment by Zac-HD** [comment]
Thanks Erez - it's definitely a great tutorial, I found it very helpful.
