### ISSUE TITLE
Negative lookahead issue?

### ISSUE THREAD

**Issue by mooncake4132** [lark-parser/lark#308]
The following piece of code works fine:
```py
import lark


grammar = r"""
%import common.WS_INLINE

_WS_INLINE: WS_INLINE
key_value: /[^\s]+/ _WS_INLINE* "=" _WS_INLINE* /"(`"|[^"])+"/
tag_name: /[^\s]+/i
tag: "[" _WS_INLINE* tag_name _WS_INLINE key_value "]"
"""

parser = lark.Lark(grammar, start='tag', parser='lalr')
print(parser.parse("""[yup key = "value"]"""))
```
Output:
```
Tree(tag, [Tree(tag_name, [Token(__ANON_2, 'yup')]), Tree(key_value, [Token(__ANON_0, 'key'), Token(__ANON_1, '"value"')])])
```

But if I add a negative lookahead into tag_name:
```py
import lark


grammar = r"""
%import common.WS_INLINE

_WS_INLINE: WS_INLINE
key_value: /[^\s]+/ _WS_INLINE* "=" _WS_INLINE* /"(`"|[^"])+"/
tag_name: /(?!nop)[^\s]+/i
tag: "[" _WS_INLINE* tag_name _WS_INLINE key_value "]"
"""

parser = lark.Lark(grammar, start='tag', parser='lalr')
print(parser.parse("""[yup key = "value"]"""))
```
I get the following exception:
```
lark.exceptions.UnexpectedToken: Unexpected token Token(__ANON_2, '"value"]') at line 1, column 12.
Expected one of:
        * __ANON_1
        * _WS_INLINE
```

Since `yup` is not `nop`, I expect the output to be the same as the first. The reason I wanted to use negative lookahead is so I can have specialized handling for some tags, such as:
```py
tag_nop: "[" _WS_INLINE* "nop" "]"
```

Am I doing something wrong? I'm using lark v0.6.5.

**Comment by erezsh** [comment]
Does it work in Earley?

Anyway, if you're using LALR, writing `"nop"` is enough to give it priority over other matches, so the negative lookahead isn't necessary.

Also, it's better to `%ignore` whitespace, because adding them interferes with LALR's prediction ability, which is based on lookaheads.

**Comment by mooncake4132** [comment]
Yes it works in earley, but my text is megabytes long and using earley would be too slow.

Correct me if I'm wrong, but I don't think I can use `%ignore`. In the example `[yup key = "value"]`, I can't ignore whitespace if I want to require a space between `yup` and `key` because `%ignore` will silently eat all the spaces, and so I will not be able to put a `_WS_INLINE` in between them.

I'm actually not sure how the priority for lalr works. Do you have that documented somewhere?

**Comment by erezsh** [comment]
If there is no space between `yup` and `key`, they'll be processed as `yupkey` as single terminal. That will produce an error.

You don't need to use priority manually. But yes, it's documented. Check out the cheatsheet. Basically, in LALR it works for terminals, not rules.

**Comment by mooncake4132** [comment]
This is the case I have in mind:
```py
import lark


grammar = r"""
%import common.WS_INLINE
%ignore WS_INLINE

key_value: /[^\s]+/ "=" /"(`"|[^"])+"/
tag: "[" "yup" key_value "]"
"""

parser = lark.Lark(grammar, start='tag', parser='earley')
print(parser.parse("""[yupkey = "value"]"""))
```
I guess I can change `"yup"` to `/yup\s+/`

I have mostly rules now, but I can try to convert them to terminals. This should solve my problem. I'll create another issue if this doesn't work. Thanks!

**Comment by erezsh** [comment]
Changing it to `/yup\s+/` is the right solution, because the lexer can't know that `yupkey` isn't correct in that situation.

Generally, use priority as a last resort.
