### ISSUE TITLE
Issue with \\ in Token

### ISSUE THREAD

**Issue by abialy** [lark-parser/lark#309]
Hi,
I have a following grammar:

start: statement+

statement: _STRING

%import common.ESCAPED_STRING -> _STRING 

%import common.WS -> WS
%import common.WS_INLINE
%import common.NEWLINE -> NEWLINE

%ignore WS
%ignore WS_INLINE

When I test it with e.g.:
"a" "b" 

it works fine showing the tree: 
start
  statement
  statement

However when one of the string has \\ inside it gives me error. 

So when I try to parse: "\\\\"  "a"

I get: 

"\\\\"  "a"
         ^

Expecting: {Terminal('_STRING')}

Any help how to parse such strings?

Regards,
Artur

**Comment by erezsh** [comment]
Are you defining your grammar as regular string? You should use either raw strings, or files.

**Comment by abialy** [comment]
Grammar is in a file.

**Comment by abialy** [comment]
Is it a problem of properly reading that file? Or something wrong with the parser?

**Comment by erezsh** [comment]
I can't tell from this description.

Post a minimal example that reproduces this behavior (including the call to `parse`, ofc)

**Comment by erezsh** [comment]
Actually, I have a guess. You're probably using the string "\\" as it is, but that translates to a single character, which is used for escaping. Since you're using `ESCAPED_STRING`, it expects you to finish the escaping.

**Comment by abialy** [comment]
Yes, that could be the case. 

I do the following:

parser = Lark(open('test.lark'), debug=True)

f = open('test.code')
script = f.read()
tree = parser.parse(script)

**Comment by abialy** [comment]
Could you tell me how I should use that "\\" string?

**Comment by erezsh** [comment]
`r"\\"`

**Comment by abialy** [comment]
Thank you

**Comment by abialy** [comment]
I tried:

script = r"\\" + " " + r"\\"

tree = parser.parse(script)

and it still does not work.

**Comment by abialy** [comment]
Well, appologies for my ignorance but I tried something like:

script = "\"" + r"\\" + "\"" + " " + "\"" + r"\\" + "\""

tree = parser.parse(script)

and it still gives an error: No terminal defined for '\' at line 1 col 7

**Comment by erezsh** [comment]
This works for me with the grammar you provided. Try to build on top of that.

```python
l = Lark(g)
>>> l.parse(r'"\\" "b")
Tree(start, [Tree(statement, []), Tree(statement, [])])
```

**Comment by abialy** [comment]
Which version of Lark you use? 

script = r'"\\" "a"'
tree = parser.parse(script)

gives me (with grammar I provided)

lark.exceptions.UnexpectedCharacters: No terminal defined for 'a' at line 1 col 7

"\\" "a"
      ^

Expecting: {Terminal('_STRING')}

**Comment by erezsh** [comment]
> Which version of Lark you use?

I'm the maintainer. I use the latest version.

Which version do *you* use?

**Comment by abialy** [comment]
Ah, good to know you then :)
I use: 
lark-parser==0.6.5

**Comment by abialy** [comment]
yes, I did copy your code as is and it did not work. I use Python3

When I do print(parser.parse(r'"\\" "b"')) it complaints with Expecting: {Terminal('_STRING')}

When I do print(parser.parse(r'"a" "b"')) it works

My issue is that I read a file that is then parsed. 

f = open('test.sst')
script = f.read()

so \\ is not handled correctly for some reason as I explained earlier. If you could point me to any direction it would be appreciated.

**Comment by erezsh** [comment]
It's difficult for me to read your code, as it's not escaped, and github turns two backslashes into one. Perhaps it's better if you post a complete code sample that produces your error in https://pastebin.com/

**Comment by abialy** [comment]
Please have a look here: https://pastebin.com/7eNZMQyv

**Comment by erezsh** [comment]
You're absolutely right, there is a bug in the common definition. I will fix it in the next release, but meanwhile here's a solution that seems to work:

```python
grammar = r"""
start: statement+

statement: STRING

STRING_INNER: (/[^"]/|"\\\"")
STRING: "\"" STRING_INNER* "\""


%import common.WS_INLINE
%ignore WS_INLINE
"""

from lark import Lark
parser = Lark(grammar)
print(parser.parse(r'"\\" "b" "c"'))
```
Sorry for the inconvenience, and thanks for the bug report!

**Comment by abialy** [comment]
It works now. Thank you. 

I will probably ask more questions as I work on a bigger project that parses pretty complex language.

**Comment by erezsh** [comment]
No problem, you can open an issue if you have any question,  or post on Gitter https://gitter.im/lark-parser/Lobby

**Comment by erezsh** [comment]
Upon further inspection, the solution I gave you wasn't correct either. Here's a better test solution (now in `master`):

```ruby
_STRING_INNER: /.*?/
_STRING_ESC_INNER: _STRING_INNER /(?<!\\)(\\\\)*?/ 

ESCAPED_STRING : "\"" _STRING_ESC_INNER "\""
```

**Comment by abialy** [comment]
But it throws: 

ValueError: ("Dynamic Earley doesn't allow zero-width regexps", TerminalDef('_STRING_INNER', '.*?'))
