### ISSUE TITLE
%ignore multi-line terminals does not seem to work

### ISSUE THREAD

**Issue by jahan-addison** [lark-parser/lark#311]
I want to ignore ANSI C style comments: 

```C+++
/* My program: */

... code here ...

/* More information:
   multi-line comment
*/
```

I have tried many variants of regex for terminals with lookaheads, lookbehinds etc. Here is a very simple example grammar and program:

### Grammar
```lark
%import common.DIGIT           -> DIGIT
%import common.WS              -> WHITESPACE

program: DIGIT+

%ignore WHITESPACE
%ignore COMMENT
COMMENT : "/*"  /(\s|\S)/ * "*/"  // Ignore comments
```

### Program

```
/* hello
   world */

5

/* hello
   world */

6
```

With the above program, I get the following AST:

```
program 6
```

---

When removing the comments, i.e:

```
5

6
```

I get the expected AST:

```
program
  5
  6
```

---

As said before, I have tried many, many variants and none seem to work.

It seems to scan the first comment and then the lexer somehow breaks and fails to catch any others. Is this simply not possible because `%ignore` only works on terminals? That would be very unfortunate.

Thanks.

**Comment by jahan-addison** [comment]
Hi @erezsh,
Thanks for getting back so quickly! Your suggestion makes sense, however, now it doesnt seem to work at all: 
```
lark.exceptions.UnexpectedCharacters: No terminal defined for '/' at line 2 col 1

/* hello
^

Expecting: {Terminal('DIGIT')}
```
Which is probably what let me to trying `\S`

**Comment by erezsh** [comment]
Right, my bad, `/.*?/` doesn't catch newlines.

So you can use `(\S|\s)*?` just the same, or `/.*?/s` which catches newlines as well.

**Comment by jahan-addison** [comment]
@erezsh That worked!! thanks a lot! closing
