### ISSUE TITLE
Can Transform and Visitor handle Tokens?

### ISSUE THREAD

**Issue by autochthe** [lark-parser/lark#312]
It would be useful if the Visitor and Transformer classes could process Tokens.  In this example, a transformer could be used to parse integers.

```python
from lark import Lark, Transformer

parser = Lark("""
start: INT*

%import common.INT
%ignore " "
""")

class MyTransformer(Transformer):
    def INT(self, args):
        print(args)
        return int(args[0])

parse_tree = parser.parse("1 2 3")
print(parse_tree)

transform_tree = MyTransformer().transform(parse_tree)
print(transform_tree)
```

Currently, `MyTransformer.INT` is never called. Could this feature be added?

**Comment by erezsh** [comment]
That's worth considering.

Meanwhile, you can use a helper rule, such as `int: INT`, and then process the rule.

There's also a mechanism for lexer callbacks that can do what you need (but the interface is a bit more primitive), you can read about it here: https://lark-parser.readthedocs.io/en/latest/recipes/

**Comment by erezsh** [comment]
Official issue in #389
