### ISSUE TITLE
VisitError hides original exception

### ISSUE THREAD

**Issue by michael-k** [lark-parser/lark#313]
Replacing Exceptions in `Transformer._call_userfunc` with `VisitError` hides the original exception:

https://github.com/lark-parser/lark/blob/13ddc43782e9f3f34fc5331081682c3678df0598/lark/visitors.py#L45-L46

It would be nice to use [`raise VisitError(…) from e`](https://docs.python.org/3/library/exceptions.html#built-in-exceptions).  But that's only available in Python 3.  Is it really necessary to still support Python 2.7?

Many big projects have already dropped Python 2.7 support or will do so in the near future: https://python3statement.org/

**Comment by erezsh** [comment]
It would be nice to drop Python 2 support, but I don't think we're there yet. Unlike most of the projects in that link, which are framework libraries, or very domain specific, Lark intends to be a utility library, and fit in any Python project.

Regarding the VisitError, it's possible to just store the exception (`e`), and access it using `VisitError.orig_exception` or something of that sort. If you want to provide a pull-request, I'll be happy to add that in.

**Comment by michael-k** [comment]
I just learned about `__context__`.  Here's a way to extract the original exception if anybody else runs into the same problem:

```python
try:
    pass
except VisitError as e:
    if isinstance(e.__context__, CustomException):
        # custom exception handling
        pass
    else:
        raise
```

Or if one doesn't use any of the features in `_call_userfunc` (that's what we switched to):

```python
from lark import Transformer
from lark.tree import Tree


class SimplifiedTransformer(Transformer):
    def _call_userfunc(self, tree, new_children=None):
        raise AttributeError()

    def _transform_children(self, children):
        raise AttributeError()

    def _transform_tree(self, tree):
        children = [
            self._transform_tree(child) if isinstance(child, Tree) else child
            for child in tree.children
        ]
        try:
            f = getattr(self, tree.data)
        except AttributeError:
            return self.__default__(tree.data, children, tree.meta)
        else:
            return f(children)
```
