### ISSUE TITLE
Can Transformer be less naive when using VisitError?

### ISSUE THREAD

**Issue by Vesuvium** [lark-parser/lark#314]
The new VisitError is great, but it come with a problem. If I am raising an error inside a transformer function, VisitError catches it and formats it, so there's no way to retrieve the original error.

Of course the problem in the first place is that there is a catch-all statement that does not leave any room for custom error handling. A simple `handle_errors` flag that could be passed to `Transformer.transform` and disable Transformer raising VisitError and letting the error go would work, but there are many ways to achieve this.

**Comment by mlin** [comment]
+1

In python3, I was able to work around this by adding this handler around the `transform` invocation:

```
except lark.exceptions.VisitError as exn:
        raise exn.__context__
```

**Comment by erezsh** [comment]
@Vesuvium Sorry for breaking backwards compatibility. As mlin mentioned, Python3 lets you bypass my oversight. If you must use Python2, I'll happily accept a patch that adds the exception object, instead of a stringified version.

**Comment by Vesuvium** [comment]
@erezsh No worries, and yes I am using Python3 so I can use the workaround

**Comment by erezsh** [comment]
@rezemika I'm okay with it

**Comment by Vesuvium** [comment]
That would work too
