### ISSUE TITLE
Using pygments as a lexer

### ISSUE THREAD

**Issue by pombredanne** [lark-parser/lark#326]
I need to write several small, not-full-featured programming language parsers for https://github.com/nexB/scancode-toolkit 
Some examples include parsing Ruby gemspac and Gemfile and similar formats. 
One approach would be to use available Pygments lexers that already know how to tokenize many languages alright and then feed that to a custom grammar to recognize the parts I am interested in.
Could I feed an existing stream of `Token` (adapted from pygments own Token type) to use with lark?

**Comment by erezsh** [comment]
Yes, it's possible.
See this example: https://github.com/lark-parser/lark/blob/master/examples/custom_lexer.py

However, I think lexing is almost always the easy part. The hard part is to define the grammar itself.
