### ISSUE TITLE
Implementing preprocessors

### ISSUE THREAD

**Issue by amal-khailtash** [lark-parser/lark#328]
Do you have any examples of how to handle pre-processing using Lark?  Specifically, how to handle _includes_.  Can lexer state/inputs be saved and passed to new Lexer?  Is this what you  handle with a custom Lexer, or you do a normal parsing and use the parse tree for that?  Most pre-processors I have seen, do their operations while lexing.

**Comment by erezsh** [comment]
I wouldn't recommend doing C preprocessing with Lark, or any kind of non-structured parsing. That kind of search-and-replace behavior is better done using other tools, or using a custom loop.

**Comment by geographika** [comment]
@amal-khailtash - as per @erezsh comment above, I implemeted INCLUDES as a search replace loop, prior to the parsing step using Lark - https://github.com/geographika/mappyfile/blob/master/mappyfile/parser.py#L51
