### ISSUE TITLE
Transformers do not work on imported grammars

### ISSUE THREAD

**Issue by rmellema** [lark-parser/lark#332]
I have a grammar that I want to use on its own (for parsing logical formulas), but also as a part of another grammar (so you can do something with the formulas), which I am currently doing by importing the frist grammar into the second. I have also written a transformer that transforms trees from the first grammar into the formulas, but in writing the second transformer I ran into a problem.

Because the second grammar imported the rules from the first grammar as `formula.negation` etc, the transformer is now looking for an attribute `formula.negation` when transforming a negation, which leads to the following two problems:

1.  `formula.negation` is not a valid method name in Python, meaning that it is a bit hard to actually define this function.

2. Now I cannot simply do something like `self.formula = FormulaTransformer()` in the second transformer to use the first one, as the `data` property on the node suggests.

This makes dealing with transformers and imported grammars a bit counterintuitive, but this might also be expected behaviour.

If you would want to solve this, I would suggest splitting the `data` property on `.`s, and then seeing if there is a property for each of the found substrings, replacing line 28 of `visitors.py` with something like:
```
f = self
for attr in tree.data.split('.'):
    f = getattr(f, attr)
```

**Comment by erezsh** [comment]
Fetch latest `master`. Imported rules are now `module__rule`, so they should be accessible to the Transformers.

**Comment by rmellema** [comment]
Thanks, that did the trick! I was even able to reuse the old transformer by overriding `__getattr__` and  checking for `__` in the middle of the attribute name.
