### ISSUE TITLE
How to feed lark with an antlr g4 C# grammar?

### ISSUE THREAD

**Issue by ehouarn-perret** [lark-parser/lark#333]
I would like to use lark to generate a parser for C# 6.

I found a [C# 6 antlr grammar](https://github.com/antlr/grammars-v4/blob/master/csharp/CSharpParser.g4) but it does not work out-of-the-box with lark.

Is there anybody who could tell me how to reformat the g4 grammar to something I can feed lark with?

It seems that the format between what expect lark and g4 are kinda different.

```python
from lark import Lark

filename = 'grammar.bnf'

with open(filename,'r') as file:
    output = file.read()

parser = Lark(output, start='compilation_unit')

```

**Comment by erezsh** [comment]
You just have to rewrite it to Lark's grammar. I'm not sure what's the question.

**Comment by isidentical** [comment]
ANTLR's g4 grammars are pretty popular, I'm not sure if it can be translated directly like nearly but it would be super cool for lark to use antlr grammars with a built-in (or 3rd party) conversion tool

**Comment by erezsh** [comment]
It wouldn't be too hard to write a tool that converts the syntax, but there's a lot more to a grammar. ANTLR grammars often contain Java code, as well as ANTLR-specific directives.

It also uses right-recursion, which Lark can handle, but it's not the most efficient way to write it.

So at best the tool will produce a partial, inefficient grammar, that you'll have to read and debug to get it to work.
