### ISSUE TITLE
Unable to resolve UnexpectedCharacter error when parsing sentences

### ISSUE THREAD

**Issue by lauravdbraak** [lark-parser/lark#334]
I am building a parser that can deal with different types of sentences. The structure of these sentences is based on formal logical structures. However, when parsing a sentence with a "knowledge" structure, I get an UnexpectedCharacters error. This error does not contain the information on what input was expected, so it is difficult to isolate and fix the problem. 
Below is a minimal working example that results in this error. With the input "Abe knows next", the error points at the letter 'k' of knows, even though that word should be defined according to the grammar. 
Two ways in which the error doesn't appear are:
- define the start as 'expr' instead of 'sentence'. Unfortunately, I need the added complexity of the option sentence gives. 
- define AGENT as "Abe". If it is specific as one name it works, but even using something like "Abe"|"Britt" will result in this same error.

```
from lark import Lark, Tree, exceptions

grammar = r"""
	start: sentence

	protocol: CNAME _NL "if" expr "then" expr 

	?sentence: expr
		| protocol

	?expr: LITERAL                 	-> literal
		| AGENT "knows" sentence 	-> knows

	AGENT: UCASE_LETTER LCASE_LETTER+

	LITERAL: LCASE_LETTER+

	_NL: /(\r?\n[\t ]*)+/

	%import common.LCASE_LETTER
	%import common.UCASE_LETTER
	%import common.CNAME
	%import common.WS_INLINE
	%ignore WS_INLINE

"""

expr_parser = Lark(grammar, parser='lalr')
expression = expr_parser.parse

test_input = """Abe knows next"""
test_protocol = """Abe knows firstnext
if first then next
"""

test = expression(test_input)
print(Tree.pretty(test))
```

**Comment by erezsh** [comment]
The problem is that your use of CNAME conflicts with AGENT, and takes priority over it.

You  can fix it by increasing AGENT's priority, but that might prevent CNAME from matching when it should.

```ruby
AGENT.2: UCASE_LETTER LCASE_LETTER+ 
```
If you need ambiguity resolution, such as in this case, you should use `parser='earley'`.

**Comment by lauravdbraak** [comment]
Thank you for the quick response! Changing the priority did the trick. 
If possible, it would be nice to have similar reporting to the Unexpected Token error message for the other errors as well, in the future.

**Comment by erezsh** [comment]
It's difficult to provide high-level error reporting for such cases, because the parser doesn't usually know what the user wanted to happen.

But of course, I would like to improve the error messages as much as I can.
