### ISSUE TITLE
Support relative rule import in interactive environment

### ISSUE THREAD

**Issue by jochasinga** [lark-parser/lark#335]
I'm using lark in a jupyter notebook, and when I try importing from a different `.lark` file like so:

```
%import .opcode.NAME
```

I got this error:

```
~/.pyenv/versions/marlin/lib/python3.6/site-packages/lark/load_grammar.py in load_grammar(self, grammar_text, grammar_name)
    718                 else:  # Relative import
    719                     if grammar_name == '<string>':  # Import relative to script file path if grammar is coded in script
--> 720                         base_file = os.path.abspath(sys.modules['__main__'].__file__)
    721                     else:
    722                         base_file = grammar_name  # Import relative to grammar file path if external grammar file

AttributeError: module '__main__' has no attribute '__file__'
```

Could we add support to relative import in interactive environment like jupyter notebook or ipython prompt?

**Comment by erezsh** [comment]
I'm absolutely in favor. Any idea on what's the best way to accomplish this?

**Comment by jochasinga** [comment]
From the user's pov there should be a more natural way to import local module-level lark rule as an alternative to relative import (which can be complicate i.e. where I work we never do it).

What I'm proposing is a way to reflect Python's import hierarchy, which is to look at Lark's core first if there's `mod_a`, then look locally (or at least that's what I think Python does):

```lark

%import mod_a.rule_1

```

I will look into the code later to see what can be done in detail.

**Comment by erezsh** [comment]
I think the main issue here is to ask - what does "locally" mean? Compared to your python module? Current working directory? Or compared to the lark file you're importing from?

Normally I would say the latter, but there isn't always a lark file to be relative to (which is the case of this issue). What does a relative import signify then?

I see your point about imitating python's import, but I'm not sure it really applies to Lark, when considering the actual use-cases. Perhaps you can provide more detail on how you expect things to work?

**Comment by jochasinga** [comment]
I'm getting ahead of myself here.

The only thing we need to consider is the `sys.modules['__main__'].__file__` because the attribute `__file__` only exists when run as script, not in interactive prompt.

One way to get around that is to add a fallback for this case. For instance, if in `main_grammar.lark` (the grammar file to be passed to `Lark` constructor) there's an import directive like this:

```lark
%import .foo.bar.NAME
```

Then we might try this to access `./foo/bar.lark`:

```python
base_import_path = os.path.abspath(os.path.join(os.path.curdir, 'main_grammar.lark'))
bar_path = os.path.join(base_import_path, 'foo', 'bar.lark')
```

**Comment by erezsh** [comment]
Pushed a fix to `master`.

**Comment by erezsh** [comment]
Feel free to continue the discussion, or open another issue if you have more to say.

**Comment by jochasinga** [comment]
This is awesome. Thanks!
