### ISSUE TITLE
0.66 raising Discard in Transformer callback no longer works

### ISSUE THREAD

**Issue by jnwatson** [lark-parser/lark#337]
Commit 8e7c05a8f6e58c3e7c1ce34956dccc15f68880bc broke allowing a user callback in AST Transformer from raising Discard to have it skip the element (as documented). Problem is here: https://github.com/lark-parser/lark/blob/0.66/lark/visitors.py#L45. It converts any raised `Discard` into a `VisitError`.

I suggest adding a generic `except Discard: raise`. Or, if a PR would be more convenient, I can do that as well.

**Comment by erezsh** [comment]
Thanks! Fixed in master, and released as 0.6.7

**Comment by jnwatson** [comment]
Thanks for the quick work!
