### ISSUE TITLE
v0.6.7 false "Rules defined twice" error

### ISSUE THREAD

**Issue by abialy** [lark-parser/lark#338]
Hi,
I have an error "Rules defined twice"  on the following line in the grammar:

command: "DEFINE" "[" VARIABLE_NAME "=" VARIABLE_TYPE ":"? VARIABLE_LENGTH? ":"? VARIABLE_MANDATORY? ":"? VARIABLE_MUST_FILL? ":"? VARIABLE_DEFAULT? ":"? VARIABLE_DESC? "]" -> define

It works fine on 0.6.5

Any idea what I am doing wrong now?

Regards,
Artur

**Comment by erezsh** [comment]
Please include a code example that reproduces your error.

**Comment by abialy** [comment]
E.g.  DEFINE [TEST=ANY:60:OPT:::]

**Comment by erezsh** [comment]
Include a working example that reproduces the error

```python
>>> from lark import Lark
>>> p = Lark("""command: "DEFINE" "[" VARIABLE_NAME "=" VARIABLE_TYPE ":"? VARIABLE_LENGTH? ":"? VARIABLE_MANDATORY? ":"? VARIABLE_MUST_FILL? ":"? VARIABLE_DEFAULT? ":"? VARIABLE_DESC? "]" -> define""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erez/lark/lark/lark.py", line 170, in __init__
    self.grammar = load_grammar(grammar, self.source)
  File "/home/erez/lark/lark/load_grammar.py", line 829, in load_grammar
    raise GrammarError("Token '%s' used but not defined (in rule %s)" % (sym, name))
lark.exceptions.GrammarError: Token 'VARIABLE_LENGTH' used but not defined (in rule command)
```

**Comment by abialy** [comment]
Apologies. 

The whole grammar is here: https://pastebin.com/tpZ80fkU

**Comment by erezsh** [comment]
`TOKEN` is used but not defined.

You need to provide a fully working, full code example. Sorry, but I'm going to ignore any more partial reports from you.

**Comment by abialy** [comment]
Please check it now. I've tested it now. 

Parser: https://pastebin.com/QrhfT4Ju

Script: https://pastebin.com/BEG7E7HY

**Comment by abialy** [comment]
The code I run: 

from lark import Lark, Transformer, Tree
from lark.tree import pydot__tree_to_png


parser = Lark(open('test.lark'), debug=True)

f = open('test.sst')
script = f.read()
tree = parser.parse(script)
print(tree.pretty())

**Comment by erezsh** [comment]
This code is working on the latest `master`, which you can clone.

You can also wait for the 0.7 release (which should arrive this month), and until then stay on 0.6.5

**Comment by abialy** [comment]
Thank you

**Comment by erezsh** [comment]
0.7 published

**Comment by abialy** [comment]
Thank you. It works fine. Keep up the good work.
