### ISSUE TITLE
Nearley grammars with backslash characters are not parsed correctly

### ISSUE THREAD

**Issue by jarble** [lark-parser/lark#341]
Lark is unable to generate a parser from this Nearley grammar, which contains a `\` character:
```
S -> "\"" T "\""

T -> "1"
   | "2"
   | "3"
   | "4"
```

Instead of generating a parser, Lark prints this error message:

`raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, state=self.state)
lark.exceptions.UnexpectedCharacters: No terminal defined for '\' at line 3 col 14`

Is it possible to re-write this grammar in a way that does not cause this error?

**Comment by erezsh** [comment]
Fixed in latest `master`
