### ISSUE TITLE
False Terminal defined more than once error

### ISSUE THREAD

**Issue by PJCampi** [lark-parser/lark#348]
Consider the following example:
a.lark
```
%import common.INT

a: INT "A"
b: INT "B"
```

b.lark
```

start: a | b

%import .a.a
%import .a.b
```

main.py
```
from lark.lark import Lark

parser = Lark.open('grammar/b.lark', rel_to=__file__)
print(parser.parse('A'))

```
This fails with error:
`lark.exceptions.GrammarError: Terminal 'a__INT' defined more than once`

that's because the tokens from the grammar `a.lark` are added to the namespace on every rule import from a.

One can work around by ensure that rules are either aliased or imported only once like that. That's also more efficient (as the grammar is loaded only once):
```
start: a | b

%import .a (a, b)
```
but this could also possibly be fixed by ensuring that terminals from the same imported grammar are imported to the namespace only once (in `new_td`)?

**Comment by erezsh** [comment]
I think both are required. Grammars should only be imported once (at least per session), and also implicit imports should be skipped if they were already added before. With some basic check for possible collisions.

If you think you can handle it, I'll be happy to accept a PR with a test-case. Or I'll do it myself sometime in the future.

**Comment by erezsh** [comment]
P.S. I think grammars are already cached, in the global var `_imported_grammars`

**Comment by PJCampi** [comment]
I think I will let this be for now. A low hanging fruit could be to add a small comment about it in the documentation?

**Comment by erezsh** [comment]
Let's keep this open. Maybe I'll find time to fix it soon.
