### ISSUE TITLE
v_args(inline=True) does not apply to derivatives of derived Transformers

### ISSUE THREAD

**Issue by chrism0dwk** [lark-parser/lark#350]
Hi there,

What is the expected behaviour of v_args(inline=True) when applied to inheritance chains from lark.visitors.Transformer?  

Minimum example with a really simple grammar:
```
grammar = """
mul: symbol "*" symbol
symbol: INT

%import common.INT
%import common.WS
%ignore WS
"""
```

MyTx1 derives from lark.visitors.Transformer using v_args decorator
```
@v_args(inline=True)
class MyTx1(Transformer):

    def mul(self, a, b):
        return "({a} times {b})".format(a=a, b=b)

    def symbol(self, s):
        return s
```

MyTx2 derives from MyTx1 overriding the mul() method:
```
@v_args(inline=True)
class MyTx2(MyTx1):

    def mul(self, a, b):
        return "({a} wibbles {b})".format(a=a, b=b)
```

Then, when run on a simple phrase:
```
parser = Lark(grammar, start='mul')
tree = parser.parse("1 * 2")
res1 = MyTx1().transform(tree) #  (1 times 2) CORRECT
res2 = MyTx2().transform(tree) # VisitError: "mul() missing 1 required positional argument 'b'"
```

It seems that the v_args(inline=True) isn't inlining arguments in the derived class.  Is this expected behaviour?

Cheers,

Chris

Edit: Python 3.6.6 (Anaconda), Lark 0.7.0 from pip.

**Comment by erezsh** [comment]
Nice find, it was a tricky edge case.

I pushed a fix to `master` which hopefully will solve it, and won't mess other things up. Let me know if it works.

**Comment by chrism0dwk** [comment]
Heh, nice fix.  Works like a charm.  Many thanks!  Will the fix be pushed to pip in the near future?  What's the timescale?

**Comment by erezsh** [comment]
I will probably make a minor release sometime this week. I just completely rewrote the standalone generator, so I want to make sure it's stable.
