### ISSUE TITLE
inline rules are not preserved when imported from another file

### ISSUE THREAD

**Issue by PJCampi** [lark-parser/lark#353]
So I found another bug related to relative imports from another grammar file. Let me know if you are not interested in these and I'll just update in my fork of your repo.

Consider the following example:
a.lark
```
A: "A"
B: "B"

a: A
_b: B

c: _b
```

b.lark
```
start: a " " c

%import .a (a, c)
```

main.py
```
from lark import Lark
parser = Lark.open('grammar/b.lark', rel_to=__file__)
print(parser.parse('A B'))
```

`_b` will fail to inline because it is renamed to `a_ _ _b` instead of `_a_ _b`.

This is easily fixed by updating `get_namespace_name` to:

```
    def get_namespace_name(name):
        try:
            return aliases[name].value
        except KeyError:
            if name[0] == '_':
                return '_%s__%s' % (namespace, name[1:])
            else:
                return '%s__%s' % (namespace, name)
```

**Comment by erezsh** [comment]
The looks like a reasonable solution. Mind creating a PR for that? A test-case would also be appreciated.

**Comment by PJCampi** [comment]
sure, I will do tomorrow.
