### ISSUE TITLE
Unable to assign terminal to group

### ISSUE THREAD

**Issue by Xilpex** [lark-parser/lark#358]
I am new to lark, and have been trying to assign a group to a terminal. Here is part of the code I am using:

```bash
HELLO: "hello"
WORLD: "world"
HELLO_WORLD: (HELLO | WORLD)
```

When I run my python code, it doesn't match either `hello` or `world`. Is there a correct way to assign a terminal to a group?

**Comment by erezsh** [comment]
I'm not sure what you mean by a group. What exactly do you expect to happen?

**Comment by Xilpex** [comment]
@erezsh by group, I mean something like this: In the example I gave above, the terminal `HELLO_WORLD` tried to _group_ the terminals `HELLO` and `WORLD`. I expect that when the terminal `HELLO_WORLD` is called, it will match either `hello` or `world`.

**Comment by erezsh** [comment]
>  I expect that when the terminal HELLO_WORLD is called, it will match either hello or world.

Yep, that's what's going to happen
