### ISSUE TITLE
Name conflict in load grammar

### ISSUE THREAD

**Issue by bjourne** [lark-parser/lark#361]
>>> import lark
    ...
      File "C:\Users\bjorn\AppData\Local\Programs\Python\Python36\lib\site- 
   packages\lark\load_grammar.py", line 5, in <module>
        from ast import literal_eval
    ImportError: cannot import name 'literal_eval'

The problem is that there is already an `ast` module in the current directory. A relative import should be used here.

**Comment by drunkwcodes** [comment]
Renaming your local `ast.py` should be fine.
https://docs.python.org/3/library/ast.html

**Comment by erezsh** [comment]
What do you mean? Lark doesn't have a module called `ast`

**Comment by bjourne** [comment]
Oh. I see.

**Comment by thescribe11** [comment]
I am using the new Python 3.8.0 distro.
When I try to import lark.Lark, it gives me this error:

ImportError: cannot import name 'Lark' from 'lark'

I was wondering if you have a solution?

**Comment by erezsh** [comment]
Please ask your questions on gitter, or open a new issue.

And make sure you `pip install lark-parser`, not `lark`

(Do not reply here)
