### ISSUE TITLE
Are some files missing?

### ISSUE THREAD

**Issue by Asocia** [lark-parser/lark#362]
I cloned the repository and tried to run tests with `python3 -m tests` but I couldn't manage to make them pass. Here is the traceback: [https://pastebin.com/f1tZvVYP](https://pastebin.com/f1tZvVYP) 

Am I doing something wrong?

**Comment by erezsh** [comment]
Lark supports converting grammars from Nearley: https://github.com/kach/nearley

It's an optional feature, so it's not there by default. If you want to test against it, you can clone it, or use git submodules to fetch it:

```
    git submodule sync -q
    git submodule update --init
```

**Comment by Asocia** [comment]
OK thanks! Just learned a new thing :)
