### ISSUE TITLE
reconstructor recreates a new parser at each iteration

### ISSUE THREAD

**Issue by PJCampi** [lark-parser/lark#364]
Hi,

At present, the reconstructor recreates a new earley parser at each step of the reconstruction. This is an expensive operation because the same grammar is re-analysed every single time.

Would it be possible to create the parser at instantiation of the reconstructor and only change the `start` value of the parser afterwards? 
Something like:
```
   def _reconstruct(self, tree):
        self.parser.parser_conf.start = tree.data
        unreduced_tree = self.parser.parse(tree.children)   # find a full derivation
        assert unreduced_tree.data == tree.data
        ...
```
I have tested it on my grammar and it improves performance markedly. However there may be a reason against it that I missed?

Let me know if this solution works and I'll make a PR for it.

**Comment by erezsh** [comment]
There's no practical reason not to. But instead of assigning to `start`, there should be a function such as `update_start`, as future versions might want to pre-calculate according to it.

Perhaps a better interface is to allow parse to accept start as an argument. So you can then do:

```python
unreduced_tree = self.parser.parse(tree.children, start=tree.data)
```

**Comment by PJCampi** [comment]
You actually already cater for parsing with a different start value :) The API of earley parser is:
```
def parse(stream, start_symbol=None):
          ...
```
My pull request reflects that.

**Comment by PJCampi** [comment]
Hey Erez,
I was wondering if you are planning to release a v0.7.1 of the package anytime soon?
Thanks,
PJ

**Comment by erezsh** [comment]
Done! Thanks for the reminder

**Comment by PJCampi** [comment]
Fantastic!
