### ISSUE TITLE
Import all terminals and rules in a file

### ISSUE THREAD

**Issue by Scannow** [lark-parser/lark#374]
Hello,
is there a way to import all the terminals and rules defined in a file using the _%import_ keyword?

Ex. _%import constants.*_
given the _constants.lark_ file.

Thanks,
Luca

**Comment by erezsh** [comment]
Hi, currently that is not possible, sorry. We can keep the issue open as a feature request

**Comment by erezsh** [comment]
But, as you probably know, you can import several rules/terminals on one line:

   %import constants (const1, const2, CONST3, CONST4)

**Comment by Scannow** [comment]
Yes I know, thank you very much!

**Comment by danielbisar** [comment]
would find this very useful as well
