### ISSUE TITLE
Rules defined twice in modified python3 grammar

### ISSUE THREAD

**Issue by MegaIng** [lark-parser/lark#380]
The grammar is here: https://pastebin.com/y4g8YDa3 and the script to run it is here: https://pastebin.com/2M6pzzA1. The error message is a bit surprising since it claims that every single rule is defined twice: https://pastebin.com/4fJSRWrK. This a somewhat new issue that only appeared after I updated (I am not sure what version I was on before)

**Comment by erezsh** [comment]
What did you change in the grammar?

**Comment by MegaIng** [comment]
Here is a diff file: https://pastebin.com/L4H3XepB

I mainly added  things like the `_END` and `EMPTY` Tokens, made type-hints required (That was my main goal), added `_INDENT _NEWLINE* _DEDENT` to allow for empty 'blocks' in code and changed a bit in the syntax for different Tokens (The strings, the numbers, as well as the `_NEWLINE` token)

**Comment by MegaIng** [comment]
Ok, after looking through the grammar and testing every single change individually, I found it. In the `arguments` rule, I added an unnecessary `[","]` at the end. This clashed with the comma before that,making it a duplicate rule. But that should not show me every single rule as duplicated.

I now have a solution, but this should still be fixed to reduce the confusion (If it would have only showed me that rule, I would have found it immediately.)

**Comment by erezsh** [comment]
Closed for lack of interest to the public :)

But I do care about good error messages. If you can reproduce this behavior in a minimal example, I'll make sure to take a look at it.

**Comment by MegaIng** [comment]
This should be minimal enough:

```python
import lark

_parser = lark.Lark("""
start: a b
a: "a" c
b: "b" c
c: [":" [c]] [":"]
""")
```
Produces the following error message:

```
Traceback (most recent call last):
  File "C:/Users/tramp/PycharmProjects/lark_tests/380/minimal/parser.py", line 8, in <module>
    """)
  File "C:\Program Files\Python37\lib\site-packages\lark\lark.py", line 203, in __init__
    self.terminals, self.rules, self.ignore_tokens = self.grammar.compile()
  File "C:\Program Files\Python37\lib\site-packages\lark\load_grammar.py", line 541, in compile
    raise GrammarError("Rules defined twice: %s" % ', '.join(str(i) for i in duplicates))
lark.exceptions.GrammarError: Rules defined twice: <start : a b>, <a : A c>, <b : B c>, <c : COLON c COLON>, <c : COLON c>, <c : COLON COLON>, <c : COLON>, <c : >
```

The most minimalistic you can get is this:

```
start: [":" [start]] [":"]
```
Every part here is required.

**Comment by erezsh** [comment]
Fixed (silly bug), and added a nicer message. Thanks for bringing it to my attention!
