### ISSUE TITLE
Identical subtrees under _ambig

### ISSUE THREAD

**Issue by jnwatson** [lark-parser/lark#381]
I'm trying to hone my grammar and reduce the number of potential ambiguities. I have a big pile of example strings to parse, parse them with `debug=True, ambiguity='explicit', keep_all_tokens=True` (using the default Earley parser) and look for parse trees with any `_ambig` nodes. Most of the time, the children of the `_ambig` nodes are identical, i.e. `tree.children[1] == tree.children[0]` evaluates to true.

Is this expected behavior? If not, I can try to produce a reduced example/bug report.

BTW, great project. Here's one more project dependent on Lark: https://github.com/vertexproject/synapse/blob/master/requirements.txt

**Comment by erezsh** [comment]
This shouldn't happen, and it's the first time it's reported. So yes, please produce an example.

But I can't guarantee I'll solve it in the near future.

The project looks interesting. I'll have a deeper look when I have some free time.

**Comment by jnwatson** [comment]
In trying to produce a minimal example, I see the problem. I had an ambiguity between two rules that both started with an underscore, so the parse trees would have been different if the ambiguous nodes hadn't been collapsed.

Thanks for your help.
