### ISSUE TITLE
Unused rule provokes "GrammarError: Collision in Terminal" when constructing LALR parser

### ISSUE THREAD

**Issue by brady-ds** [lark-parser/lark#384]
The following code:

```python
#! /usr/bin/env python3

from lark import Lark


GRAMMAR = """
    start: EKS* identifier
    unused: identifier* identifier
    identifier: EKS | /y/
    EKS: /x/
"""

if __name__ == '__main__':
    Lark(GRAMMAR, parser='lalr')
```

raises an exception:

```
…
lark.exceptions.GrammarError: Collision in Terminal('__ANON_0'): 
  * Reduce: <__anon_star_0 : EKS>, 
  * Reduce: <identifier : EKS>
```

However, the same code without the rule defining `unused` exits cleanly.  I may be missing something, but it is not clear to me why that should be.

**Comment by erezsh** [comment]
Good catch!

I pushed a fix to `master` that should resolve this issue.

**Comment by brady-ds** [comment]
Thanks; that works great!

But as a follow-up, shouldn't something like:

```python
#! /usr/bin/env python3

from lark import Lark


GRAMMAR = """
    start: /1/ first | /2/ second
    first: EKS* x
    second: x*
    x: EKS
    EKS: /x/
"""

if __name__ == '__main__':
    Lark(GRAMMAR, parser='lalr')
```

also run without a reduce/reduce conflict because `EKS*` and `x*` appear in disjoint contexts and therefore share no states?  (It has been a long time since I have had to worry about what is and is not LALR(1), so please correct me if I am mistaken.)  (Also, if this is an issue, but you would prefer it reported separately, please let me know, and I will open another report.)

**Comment by erezsh** [comment]
Perhaps a more sophisticated implementation of LALR(1) would allow it, but the traditional implementation that appears in every textbook (and Lark) uses a global `FOLLOW` dictionary, which isn't context dependent.

If there's a simple and clever way to allow this, it eludes me at the moment.

**Comment by brady-ds** [comment]
Okay.

**Comment by erezsh** [comment]
Sorry to disappoint!
