### ISSUE TITLE
fail import on Tranformer_InPlace

### ISSUE THREAD

**Issue by nervouskiwi** [lark-parser/lark#385]
Hi. I'm using lark to parse a homebrew config file, and i'd like to keep the Tree structure while adding data to the tree. I figured from the docs that i want to use Transformer_InPlace with the v_args tree=True decorator, so that i could use the fonction callbacks to modify the tree nodes where needed. But the Transformer_InPlace class seems inaccessible to import, and seems to be missing from the top __init__.py file. 

from lark import Transformer_InPlace will throw
AttributeError: module 'lark' has no attribute 'Transformer_InPlace'

And when using the v_arg decorator, it specifies that it doesn't work with the base Transformer... so... did i missread the usage docs or did'nt get something..?

**Comment by erezsh** [comment]
The `Visitor` class might also do what you need.
