### ISSUE TITLE
Example Python 3 does not parse floating-point imaginary numbers

### ISSUE THREAD

**Issue by brady-ds** [lark-parser/lark#387]
On [this line](https://github.com/lark-parser/lark/blob/c2a5f09ad514014f84e708672f7dd56eb70c2454/examples/python3.lark#L181), it appears that the `IMAG_NUMBER` regular expression is attempting to reference the `FLOAT_NUMBER` terminal, but there does not seem to be any code in Lark to treat the `${}` syntax that way.  Consequently, the following code raises an exception:

```python
#! /usr/bin/env python3

from lark import Lark


if __name__ == '__main__':
    Lark(open('…/python3.lark'), parser='lalr', start='single_input').parse('x = 0.0j\n')
```

**Comment by erezsh** [comment]
Fixed, thanks for the report!

It was a remnant of an obsolete feature.
