### ISSUE TITLE
Inconsistent parsing of rules, priority not helping

### ISSUE THREAD

**Issue by Thoob** [lark-parser/lark#388]
I am trying to produce a grammar to parse the SystemVerilog HDL, however I'm experiencing some inconsistent behaviour when parsing numbers. 
In SystemVerilog, by default numbers are interpreted as decimal, but can also be sized binary, octal or hex values. For example:
"123" is the decimal value 123.
"8'hFF" is the 8-bit hex value FF, equal to decimal value 255.
However my parser is around half the time detecting the size "8" in "8'hFF" as the decimal value 8, and "'hFF" as the hex value. I have tried increasing the priority of the hex rule but this seemingly has no effect.

Here is the relevant portion of the grammar:

```
numbers: number*
number: integral_number | real_number
integral_number: hex_number | octal_number | binary_number | decimal_number
binary_number.2: size? BINARY_BASE BINARY_VALUE
octal_number.2: size? OCTAL_BASE OCTAL_VALUE
hex_number.2: size? HEX_BASE HEX_VALUE
decimal_number: UNSIGNED_NUMBER
              | size? DECIMAL_BASE UNSIGNED_NUMBER
              | size? DECIMAL_BASE X_DIGIT "_"*
              | size? DECIMAL_BASE Z_DIGIT "_"*
size: NON_ZERO_UNSIGNED_NUMBER
NON_ZERO_UNSIGNED_NUMBER: /[1-9][0-9_]*/
real_number: FIXED_POINT_NUMBER | /([0-9][0-9_]*)(\.[0-9][0-9_]*)?([eE])([\+\-])?([0-9][0-9_]*)/
FIXED_POINT_NUMBER: /([0-9][0-9_]*\.[0-9][0-9_]*)/
UNSIGNED_NUMBER: /([0-9][0-9_]*)/
BINARY_VALUE: /([0-1xXzZ][0-1_xXzZ]*)/
OCTAL_VALUE: /([0-7xXzZ][0-7_xXzZ]*)/
HEX_VALUE: /([0-9a-fA-FxXzZ][0-9a-fA-F_xXzZ]*)/
DECIMAL_BASE: /'([sS])?[dD]/
BINARY_BASE: /'([sS])?[bB]/
OCTAL_BASE: /'([sS])?[bB]/
HEX_BASE: /'([sS])?[hH]/
X_DIGIT: "x" | "X"
Z_DIGIT: "z" | "Z" | "?"

%import common.WS
%ignore WS
```

When I parse the string "16'habcd", I expect to always match the hex number abcd with size 16. The size "16" is optional, but I expect it to still match the hex_number rule before the decimal_number rule. However running the parser I get inconsistent results:
```
ts $ python3 sv_module_parser.py
numbers
  number
    integral_number
      hex_number                      <-- CORRECT
        size	16
        'h
        abcd

ts $ python3 sv_module_parser.py
numbers
  number
    integral_number
      decimal_number	16       <-- INCORRECT
  number
    integral_number
      hex_number
        'h
        abcd

```

I am using the dynamic Earley parser, and I'd prefer to keep using this as the rest of the grammar also has some ambiguities. Thanks.

**Comment by erezsh** [comment]
Are you using the latest version of Lark? (0.7.1)

**Comment by Thoob** [comment]
Yes:
```
ts $ pip3 freeze | grep lark
lark-parser==0.7.1
```

**Comment by erezsh** [comment]
Non-deterministic ambiguity resolution is a known bug right now (although it usually works).

If you can provide the code to a minimal example that behaves incorrectly, it will help debug the issue. Then I can also make some concrete suggestions that might help. 

For now, I suggest playing around with weights, and rule structure.

**Comment by Thoob** [comment]
Here's a minimal example that behaves as described above, the problem being parsing ```16'habcd```.
```python
from lark import Lark

numbergrammar = """
start: numbers
numbers: number*
number: integral_number | real_number
integral_number: hex_number | octal_number | binary_number | decimal_number
binary_number.2: size? BINARY_BASE BINARY_VALUE
octal_number.2: size? OCTAL_BASE OCTAL_VALUE
hex_number.2: size? HEX_BASE HEX_VALUE
decimal_number: UNSIGNED_NUMBER
              | size? DECIMAL_BASE UNSIGNED_NUMBER
              | size? DECIMAL_BASE X_DIGIT "_"*
              | size? DECIMAL_BASE Z_DIGIT "_"*
size: NON_ZERO_UNSIGNED_NUMBER
NON_ZERO_UNSIGNED_NUMBER: /[1-9][0-9_]*/
real_number: FIXED_POINT_NUMBER | /([0-9][0-9_]*)(\.[0-9][0-9_]*)?([eE])([\+\-])?([0-9][0-9_]*)/
FIXED_POINT_NUMBER: /([0-9][0-9_]*\.[0-9][0-9_]*)/
UNSIGNED_NUMBER: /([0-9][0-9_]*)/
BINARY_VALUE: /([0-1xXzZ][0-1_xXzZ]*)/
OCTAL_VALUE: /([0-7xXzZ][0-7_xXzZ]*)/
HEX_VALUE: /([0-9a-fA-FxXzZ][0-9a-fA-F_xXzZ]*)/
DECIMAL_BASE: /'([sS])?[dD]/
BINARY_BASE: /'([sS])?[bB]/
OCTAL_BASE: /'([sS])?[bB]/
HEX_BASE: /'([sS])?[hH]/
X_DIGIT: "x" | "X"
Z_DIGIT: "z" | "Z" | "?"

%import common.WS
%ignore WS
"""

testparser = Lark(numbergrammar, start="numbers")

test_numbers = """
123.345
0.546e-10
16'habcd
55
"""

parsed_numbers = testparser.parse(test_numbers)
print(parsed_numbers.pretty())
```

**Comment by night199uk** [comment]
I just added some troubleshooting notes and breadcrumbs for a similar ambiguity resolution issue to #372. I haven't had a lot of time to look into this lately, but hopefully the notes there would help to troubleshoot this issue as well.

**Comment by erezsh** [comment]
@Thoob Sorry, didn't see that you replied.

Changing this line seems to fix the issue for me:
```ruby
size.100: NON_ZERO_UNSIGNED_NUMBER
```
Let me know if it helps.

Btw, for the record, here's an actually minimal example:

```python
from lark import Lark

numbergrammar = """
start: number*
number: hex_number | decimal_number
hex_number.100: size? HEX_BASE HEX_VALUE
decimal_number: UNSIGNED_NUMBER
size.100: NON_ZERO_UNSIGNED_NUMBER
NON_ZERO_UNSIGNED_NUMBER: /[1-9][0-9_]*/
FIXED_POINT_NUMBER: /([0-9][0-9_]*\.[0-9][0-9_]*)/
UNSIGNED_NUMBER: /([0-9][0-9_]*)/
HEX_VALUE: /([0-9a-fA-FxXzZ][0-9a-fA-F_xXzZ]*)/
HEX_BASE: /'([sS])?[hH]/

%import common.WS
%ignore WS
"""

testparser = Lark(numbergrammar)

test_numbers = """
16'habcd
"""

parsed_numbers = testparser.parse(test_numbers)
print(parsed_numbers.pretty())                         
```

**Comment by erezsh** [comment]
Closing, as I consider this a duplicate for #343 

However the example here may still be relevant for future debugging
