### ISSUE TITLE
Allow visitors to visit terminals (transformers too)

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#389]
Provide a way to use transformers & visitors to iterate over terminals, in addition to rules.

It can be used as an alternative to lexer_callbacks.

**Comment by bilderbuchi** [comment]
Is this something that can be implemented quickly? 
Otherwise, if I have to use Earley and its default lexer, the best approach is to convert terminals I have to visit to rules, right?

**Comment by erezsh** [comment]
>Is this something that can be implemented quickly?

Probably yes

> the best approach is to convert terminals I have to transform to (helper) rules

Yep. Also, you don't really have to preserve the terminal if  you know its value.

**Comment by erezsh** [comment]
Lark now contains that option for transformers. You can use it with

    Transformer(visit_tokens=True).transform(...)

**Comment by bilderbuchi** [comment]
Great, thanks!

**Comment by erezsh** [comment]
Can you think of a use case in which it makes sense for Visitors?

I think Transformers are the only mechanic where it is useful.

**Comment by bilderbuchi** [comment]
I can't, but I have not used Visitors yet. 
We are creating Python code from another language (https://gitlab.com/librecube/prototypes/python-pluto), there this is useful to do simple modifications to terminals so that valid Python gets passed on during transformation (e.g. `TRUE` to `True`).

**Comment by erezsh** [comment]
A new issue exists (and an implementation for this is already in master)
