### ISSUE TITLE
Receive information about ignored text

### ISSUE THREAD

**Issue by Drolla** [lark-parser/lark#390]
Nice library - I like it!

My goal is to parse a certain programming language that has comments, and I would like to recover the information regarding these comments (e.g. the comment itself, or its position in the parsed text). The language has line ending comments (e.g. //) as well as block comments (e.g. /* .. */).
By using the '%ignore' directive to define a comment terminal (e.g. "%ignore COMMENT), the comments are truly ignored by the parser and I could not find a way to recover information about the comments.
Is there a way to receive information about ignored text pieces? Or, how would comments need to be described in Lark grammar to recover information about them?

**Comment by erezsh** [comment]
See https://lark-parser.readthedocs.io/en/latest/recipes/

**Comment by Drolla** [comment]
Thank you for pointing to this example. This seems to be exactly what I need!

**Comment by erezsh** [comment]
Great. Closing the issue, but feel free to ask more questions.

**Comment by Drolla** [comment]
Unfortunately, lexer callbacks are not supported by the default lexer used by the Earley parser, and I am not able to use the standard lexer in combination with the Early parser.
Could you consider adding an enhancement to the Earely parser to support also the lexer callback?

**Comment by erezsh** [comment]
That would be complicated, because the Earley lexer isn't deterministic.

What happens if there's an ambiguity, and the two possible branches contain different comments?

**Comment by Drolla** [comment]
I recognize that that the support for user callbacks may become more difficult. I see 2 options:

- User callbacks are called during the dynamic lexing step, which means that a callback will be called multiple times, maybe with different arguments in the different branches. It's up to the callback function to handle these multiple calls.
- The user callbacks are only called once the lexing/parsing is completed and the final branch is evaluated.

Coming back to my initial request to have extracted just comments that are described as ignored terminals, I came up with the following patch.

**parser_frontends.py, line 143:**
_Old:_
```
self.parser = xearley.Parser(parser_conf,
                             self.match,
                             ignore=lexer_conf.ignore,
                             resolve_ambiguity=resolve_ambiguity,
                             **kw
                             )
```
_New:_
```
self.parser = xearley.Parser(parser_conf,
                             self.match,
                             ignore=lexer_conf.ignore,
                             resolve_ambiguity=resolve_ambiguity,
                             user_callbacks=lexer_conf.callbacks,
                             **kw
                             )
```
**xearley.py, line 7:**
_Old:_
```
def __init__(self,  parser_conf, term_matcher, resolve_ambiguity=True, ignore = (), complete_lex = False):
    BaseParser.__init__(self, parser_conf, term_matcher, resolve_ambiguity)
    self.ignore = [Terminal(t) for t in ignore]
    self.complete_lex = complete_lex
```
_New:_
```
def __init__(self,  parser_conf, term_matcher, resolve_ambiguity=True, ignore = (), complete_lex = False, user_callbacks = ()):
    BaseParser.__init__(self, parser_conf, term_matcher, resolve_ambiguity)
    self.ignore = [Terminal(t) for t in ignore]
    self.complete_lex = complete_lex
    self.user_callbacks = user_callbacks
```
**xearley.py, line 73:**
_Old:_
```
# e.g. mandatory spacing.
for x in self.ignore:
    m = match(x, stream, i)
    if m:
        # Carry over any items still in the scan buffer, to past the end of the ignored items.
```
_New:_
```
# e.g. mandatory spacing.
for x in self.ignore:
    m = match(x, stream, i)
    if m:
        if x.name in self.user_callbacks:
            self.user_callbacks[x.name]( [m.group(), text_line, text_column] )
        # Carry over any items still in the scan buffer, to past the end of the ignored items.
```
This patch allows extracting the comments and to handle then them with the custom callback function.

**Comment by erezsh** [comment]
For some reason I was very against the idea of calling the callbacks multiple times, but really I'm not sure why. If the user wants to take that performance hit, that's fine. And really, it's not such a huge difference, early is already pretty slow.

So if you want to submit this as a PR, I will accept it.

I'm still not sure what you're planning to do if there's more than one possible interpretation for comments? It might cause phantom comments to appear in your list.

**Comment by Drolla** [comment]
Regarding my plan: I am planning to implement a programming language translator. The translated source code should keep as much as possible from the original source code, including the comments.

I will move forward with the implementation of the translator, and once the concept of the comment recuperation is validated I will submit the patch.

**Comment by erezsh** [comment]
Sounds good! Looking forward to it.

Let me know if you have any questions, or want my input regarding the design or implementation.
