### ISSUE TITLE
Grammar parsing bug

### ISSUE THREAD

**Issue by davaya** [lark-parser/lark#392]
While playing with: https://pastebin.com/Evqme2aM, Lark appears to fail while loading the grammar:

```
Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\lark\parsers\lalr_parser.py", line 59, in get_action
    return states[state][token.type]
KeyError: '_RBRA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[...]
  File "C:\Python36-32\lib\site-packages\lark\parsers\lalr_parser.py", line 62, in get_action
    raise UnexpectedToken(token, expected, state=state)
lark.exceptions.UnexpectedToken: Unexpected token Token(_RBRA, ']') at line 10, column 1.
Expected one of: 
	* _IGNORE
	* _DECLARE
	* $END
	* _IMPORT
	* TERMINAL
	* _NL
	* RULE
```
Although it says the error is on line 10 column 1, the failure is caused by "Another comment" - which is line 8 in the grammar.  (Inserting a blank line before "Another comment" changes the error message to line 11, inserting a blank line after it does not affect the error.  Deleting the comment line allows the grammar to load and execute properly.

This came about because I'm trying to explicitly parse whitespace in my grammar.  The whitespace regex failed even though it's copied from common, and it still fails even when it's commented out!

**Comment by erezsh** [comment]
This isn't a bug in Lark.

You need to define the grammar as a raw string:
```python
grammar = r'''
...
"""
```
That will solve your problem.

**Comment by davaya** [comment]
Ahh, I missed that somewhere; and the examples, e.g.,
https://github.com/lark-parser/lark/blob/master/examples/calc.py,
https://github.com/lark-parser/lark/blob/master/examples/custom_lexer.py
 https://github.com/lark-parser/lark/blob/master/examples/fruitflies.py,
https://github.com/lark-parser/lark/blob/master/examples/qscintilla_json.py,
and
https://github.com/lark-parser/lark/blob/master/examples/turtle_dsl.py
could be updated to use raw strings.

Should grammar files, e.g., https://github.com/lark-parser/lark/blob/master/examples/lark_grammar.py, be opened in binary mode, or is text mode without an .encode() OK for when the grammar is in a separate file?

**Comment by erezsh** [comment]
You deleted your reply?

**Comment by erezsh** [comment]
Haha, no worries, it's closed and that's fine.

Feel free to open new issues, as long as they are as well described as this one.

**Comment by ekagra-ranjan** [comment]
Thanks for not deleting this issue :)
