### ISSUE TITLE
misspelling in wiki

### ISSUE THREAD

**Issue by hubert-lee** [lark-parser/lark#394]
hi
I find out some misspelling in wiki page.
https://github.com/lark-parser/lark/wiki/How-to-use-Lark

as-is
```
gramamr = """start: rules and more rules
```

to-be
```
grammar = """start: rules and more rules
```

**Comment by erezsh** [comment]
The wiki is deprecated. Thanks for reminding me to disable it.

See the docs: https://lark-parser.readthedocs.io/en/latest/
