### ISSUE TITLE
About group items

### ISSUE THREAD

**Issue by zeeqy** [lark-parser/lark#395]
Hi, in grammar, what's the rule for "word and some special characters"

Example
```
I'm sad.
```
The goal is to have "I'm" and "sad".

Using %import common.WORD gives UnexpectedCharacters error

I tried to use group item but not sure about the syntex.

```
wordset: ("I" "m" "'")
```
```
UnexpectedCharacters: No terminal defined for 'I' at line 1 col 1
```

**Comment by erezsh** [comment]
That is because `'` isn't considered part of a word. Try something like:

    ENG_WORD: WORD ["'" WORD]

**Comment by erezsh** [comment]
Closing the issue, but feel free to continue the discussion or ask more questions

**Comment by zeeqy** [comment]
Thanks for helping. I do have one question about number combined with words. 

First everything works well with grammar:

ENG_WORD: WORD ["'" WORD]

Then I encounter strings like "100 students". The goal is to parse it into two ENG_WORD: 100, students.

Also how about word with number in it, like "ww2" and "Iphone8"

I have tried ENG_WORD: WORD ["'" WORD] [NUMBER WORD], it won't work.

(I'm so noob!)

**Comment by erezsh** [comment]
What exactly is the result you're hoping for?

Do you want `ww2` to parse into WORD, or WORD NUMBER?

**Comment by zeeqy** [comment]
my goal is that any consecutive combination of letter and number should be parsed into a "word".

special examples like 
I'm happy should be parsed into 2 words `I'm` and `happy`.
book about ww2 should be parsed into 3 words `book`, `about` and `ww2`

**Comment by erezsh** [comment]
Sounds like you just need to define word yourself:
```python
WORD: (LETTER | DIGIT) +

%import common (LETTER, DIGIT)
```
