### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by thebarbershop** [lark-parser/lark#399]
From the Work Process section of the [How To Use (Guide) page](https://lark-parser.readthedocs.io/en/latest/how_to_use/):

> Use Lark's grammar features to [[shape the tree|Tree Construction]]: Get rid of superfluous rules by inlining them, and use aliases when specific cases need clarification.

I think you meant the link:

> https://lark-parser.readthedocs.io/en/latest/tree_construction/#shaping-the-tree

but don't exactly know how to fit in to the grammar of your docs generator.

**Comment by erezsh** [comment]
Thanks!
