### ISSUE TITLE
Syntax errors in docs (json tutorial)

### ISSUE THREAD

**Issue by yalogon** [lark-parser/lark#403]
https://github.com/lark-parser/lark/blob/master/docs/json_tutorial.md
There are syntax errors in function signatures like so:
`def string(self, (s,)): ...`
Looks like someone is programming in a language with pattern matching) Or am I missing something?

**Comment by erezsh** [comment]
It works in Python 2. They removed this feature in Python 3

**Comment by yalogon** [comment]
Oh I didn't know about that! Sorry.

**Comment by erezsh** [comment]
It's okay. I should probably fix it, which is why I kept it open

**Comment by evandrocoan** [comment]
This was discussed here: [PEP 3113 -- Removal of Tuple Parameter Unpacking](https://www.python.org/dev/peps/pep-3113/)
