### ISSUE TITLE
Why this project chose LALR instead of LL parser?

### ISSUE THREAD

**Issue by evandrocoan** [lark-parser/lark#404]
One upon a time, @erezsh had the idea to write a parser. But instead of writing a LL parser, it chose a LALR parser. Why he did not chose a LL parser? Is their grammars less powerful?

**Comment by erezsh** [comment]
Yes, LL is a weaker algorithm. ANTLR uses LL(*) which should be able to handle every CFG, like Earley, but it doesn't support ambiguity, and its worst time performance is much worse than Earley.
