### ISSUE TITLE
In worst case, CYK and early are O(n^3) or exponencial?

### ISSUE THREAD

**Issue by evandrocoan** [lark-parser/lark#405]

**Comment by erezsh** [comment]
All the information you need is here:

https://lark-parser.readthedocs.io/en/latest/parsers/

For small questions, it's better to ask here: https://gitter.im/lark-parser/Lobby

**Comment by evandrocoan** [comment]
So, now I remember. Exactly 8 days ago, June 30, I had read that page upside down and had noted it on my bibliography:
![image](https://user-images.githubusercontent.com/5332158/60772123-118f0600-a0c8-11e9-881d-bd804962380d.png)

But today when I go to the table of contents I could not find it, and I had completely forgot it existed.

![image](https://user-images.githubusercontent.com/5332158/60772110-ec9a9300-a0c7-11e9-97e4-93c39d96afab.png)

**Comment by evandrocoan** [comment]
I also found this paper for LL(*): https://www.antlr.org/papers/allstar-techreport.pdf

**Comment by erezsh** [comment]
Are they peer-reviewed?

**Comment by evandrocoan** [comment]
I think so. The links I gave were from google, but you can find their final version on ACM:
1. http://doi.acm.org/10.1145/1993498.1993548
1. http://doi.acm.org/10.1145/2660193.2660202
