### ISSUE TITLE
Inject terminals into grammer

### ISSUE THREAD

**Issue by timofurrer** [lark-parser/lark#406]
I'm looking for a way to inject certain terminals into a grammer when defining the parser. I need this for internationalization.

I'm looking for something similar like the `%import`, but I don't want to import it from a file but from Python when defining the parser:

```python
parser = Lark.open("grammer.lark", parser="lalr", terminals={"_FOO": "foo", "_BAR": "bar"})
parser.parse(...)
```

In the `grammer.lark` I could then make use of `_FOO` and `_BAR`. 
Is something like that already possible? Would it make sense to add such a feature to lark?

**Comment by erezsh** [comment]
I suppose you want it to support many languages, right? In that case, you'll have to define quite a few terminals, and possibly even nontrivials ones, which might make this call pretty awkward.

I'm much more inclined to add an `include` keyword, for importing additional lark files on top of the current one. So you can do something like:
```python
parser = Lark.open("grammer.lark", parser="lalr", include=["translations/spanish.lark"])
parser.parse(...)
```

What do you think?

**Comment by timofurrer** [comment]
> I suppose you want it to support many languages, right?

Exactly :)

>  In that case, you'll have to define quite a few terminals, and possibly even nontrivials ones, which might make this call pretty awkward.

Why is that?

The only thing I want is to inject certain strings as a terminal into a grammer. In my case those or plain boring strings, like in the example in the first post.

> I'm much more inclined to add an include keyword, for importing additional lark files on top of the current one.

That's something which would be cumbersome to use in my case, because I have all the translatable strings (keywords of a DSL) as JSON parsed in Python.

**Comment by erezsh** [comment]
>Why is that?

I was thinking of sentences that include `"`, or that some terminals might comprise of the concatenation of others. Or might include regexps of some sort.

> That's something which would be cumbersome to use in my case, because I have all the translatable strings (keywords of a DSL) as JSON parsed in Python.

Yes, I see. It would be awkward for you to generate a lark module, just so you can import it. But at the same time, your use-case is very specific, and I'm not sure it generalizes for others.

Have you considered attaching a token callback for WORD (or equivalent)?

Something like:

```python
def translate(word):
    try:
        word_type, word_text = json_dict[word]
        return Token.new_borrow_pos(word_type, word_text, word)
    except KeyError:
        return word

parser = Lark(..., lexer_callbacks={'WORD': translate})
```

You can read more about it here: https://lark-parser.readthedocs.io/en/latest/recipes/

And you can use `%declare` so you can reference those terminals, without defining them first.

**Comment by timofurrer** [comment]
> Have you considered attaching a token callback for WORD (or equivalent)?

I didn't know about this feature, I'll check it out later today.
At what point are those callbacks evaluated? And how often? For each occurrence?
Couldn't really find anything about this in the docs.

**Comment by erezsh** [comment]
The callback is called once for every time a token is matched to a terminal.

So, in a text with 100 WORDs, the WORD callback will be called exactly 100 times.

(Earley might make more calls than that, if there is ambiguity)

**Comment by timofurrer** [comment]
That sounds like some overhead especially when parsing larger files. 
Since those terminals don't change during the parser it would be nice to inject them once. 
Would that be possible to implement in lark? 
If you point me in the right direction I can implement it myself.

**Comment by erezsh** [comment]
Tokens already go through so much work, like counting lines & columns, and most of the time is spent in the parser anyway. So I wouldn't worry about that.

If your function is just a dictionary lookup, then doubly so; you'll hardly notice the difference.

And since any pure function with a small enough range (which is true for groups such as "all terminal types" or "list of keywords") can be efficiently turned into a dictionary lookup through memoization, I think that should catch most use-cases.

But maybe I'm missing something?

**Comment by timofurrer** [comment]
Sounds interesting. Let me do some bechmarking - I'll keep you posted

**Comment by erezsh** [comment]
Closing, but feel free to continue the conversation

**Comment by MegaIng** [comment]
@erezsh May I ask you how you got this to work? I tried the following simple example, which does not work for obvious reasons:

```python
from lark import Lark, Token

def translate_word(t: Token):
    if t.value == 'test':
        return Token.new_borrow_pos('TEST', t.value, t)
    return t

parser = Lark("""
start: TEST
WORD: /\\w+/
%declare TEST
""", lexer_callbacks={'WORD': translate_word}, lexer='standard')

parser.parse('test')
```
This is because `WORD` is not an acceptable Token, so the `translate_word` function never gets called.

**Comment by erezsh** [comment]
@MegaIng You can't change the token type, only its value. But you can attach your own attributes to it (say, `megaing_type`)

**Comment by MegaIng** [comment]
But wasn't that your proposal for a solution of this issue?

**Comment by erezsh** [comment]
I thought I was solving translation, which only requires to swap the value. Why do you need to change the type?

**Comment by MegaIng** [comment]
What do you get by changing the value? I though the grammar would be like this:

```
start: statement+

statement: FOR EACH VARIABLE FROM NUMBER TO NUMBER DO body END

body: ...
VARIABLE: "$" /\w+/

%import common.NUMBER
%declare FOR EACH FROM TO DO END
```
The tokens `FOR`, `EACH`, `FROM`, `TO`, `DO`, `END` would then be implemented in different languages.
Then the language could be like this:
```
for each $i from 0 to 10 do ... end
```
or (in german)
```
für jedes $i von 0 to 10 mache ... ende
```

**Comment by erezsh** [comment]
Yes, I see. What I proposed won't solve this.

How do you feel about my first proporsal?
```python
parser = Lark.open("grammer.lark", parser="lalr", include=["translations/spanish.lark"])
parser.parse(...)
```
(To be implemented, of course)

There is also the option of allowing all variations:
```ruby
_FOR: "for" | "fur"
_EACH: "each" | "jedes"
etc.
```

It's probably not what you want, but just thought I should suggest it.

**Comment by erezsh** [comment]
I gave this a little more thought. What you need is to modify the terminals, not the tokens.
(perhaps @timofurrer  meant the same and I misunderstood him?)

I can provide an interface to intercept the terminals, just after Lark collected them, and modify their value before parsing the grammar. This can be done as a dictionary of lambdas, much like lexer_callbacks, but they'll modify a `TerminalDef` instance instead.

Let me know what you think.

**Comment by timofurrer** [comment]
> What you need is to modify the terminals, not the tokens.

Yes, that's exactly what I need :) And in the best case I want them to be defined / looked up exactly once before parsing any grammers. 

I assume that internationalization is a big use-case for this - at least it's the same for @MegaIng - as far as I can tell.

> This can be done as a dictionary of lambdas

In the end I just imagine that I can have dict like:

```python
{
    "en": {
        "for": "for",
        "each": "each",
        ...
    },
    "de": {
        "for": "fuer",
        "each": "jedes",
        ....
    }
}
```

And give lark either the `en` or `de` branch whereas the `for` and `each` are name for terminals and e.g. `fuer` and `jedes` are their values in the `de` case.
If I inject those wrapper in lambda are give the `dict` directly doesn't really matter since it's only called once. Probably the lambda gives you more flexibility ...

In case you were thinking about calling that lambda once per terminal - I guess that's fine too - as long as it's at the beginning of parsing and not for each appearance of a terminal.

**Comment by erezsh** [comment]
Added it to `master`. Here's an example of use:

```python
from lark import Lark

grammar = r"""
start: statement+

statement: "for" "each" VARIABLE "from" NUMBER "to" NUMBER "do" body "end"

body: "..."
VARIABLE: "$" /\w+/

%import common.NUMBER
%import common.WS
%ignore WS
"""

translate = {
    "for": "für",
    "each": "jedes",
    "from": "von",
    "to": "zu",
    "do": "mache",
    "end": "ende"
}
def edit_terminals(t):
    s = t.pattern.value
    if s in translate:
        t.pattern.value = translate[s]

en_parser = Lark(grammar)
de_parser = Lark(grammar, edit_terminals=edit_terminals)


en = "for each $i from 0 to 10 do ... end"
de = "für jedes $i von 0 zu 10 mache ... ende"

print(en_parser.parse(en))
print(de_parser.parse(de))
```

**Comment by timofurrer** [comment]
Thanks! I hope I'll have some time this weekend. 
When is `edit_terminals` being called?

**Comment by erezsh** [comment]
When compiling the grammar. There is no difference in performance.

**Comment by mbarrenecheajr** [comment]
Hi, this feature is very helpful for my grammar. Possible to cut a new release to include this?

**Comment by erezsh** [comment]
This is already available as version `0.7.6a1`

**Comment by erezsh** [comment]
Now in 0.7.7

**Comment by clementfaisandier** [comment]
Hello @erezsh 
I've got an issue with this solution but didn't want to create a ticket just yet:

I'm having an issue using `edit_terminals`: I'm finding that Lark is compressing the terminals I've defined before I use edit_terminals.

This is my grammar; the terminal I am looking to modify is `COMMENT_CHAR` to support multiple languages:
```lark
start: (snippet | LINE)*

snippet: snippet_marker LINE* 

// TODO: Evaluate if the prefix for each token should be in or out of the token.
snippet_marker.1: PREFIX MARKER _IWS* /.+/ SUFFIX
PREFIX: _IWS* COMMENT_CHAR _IWS*
MARKER: _SPIDER
SUFFIX: _EOL
_DEFINITION_TOKENS: CONTEXT _IWS* TOPIC _IWS* CONTENT_TYPE
_BOOLEAN_FLAGS: _DEFINITION_TOKENS? (LINK | EMBEDDING)          // Makes the definition tokens filtering options
CONTEXT: "#" /\w{1,16}/     // What's the general theme?
TOPIC: "@" /\w{1,16}/       // What is this snippet about?
CONTENT_TYPE: "$" /[DRAC]/  // Documentation, Reasoning, API, Code
LINK: "?"
EMBEDDING: "!"

// Resources

_SPIDER: "//\(oo)/\\"
_BORING: "SNIPPET"
_ROBOT: "[o_o]"

LINE: _IWS* COMMENT_CHAR? _SENTENCE? _EOL
_SENTENCE: (_WORD _IWS+)* _WORD
_WORD: /\S+/
COMMENT_CHAR: "TO BE OVERRIDE BY PROGRAM- DO NOT REMOVE - DO NOT USE ANOTHER TOKEN FOR COMMENT CHAR"

_EOL: _IWS* _NL
_IWS: /[\t ]/
_NL: /\r?\n/
```

This is the python:

```python
import lark

def terminal_callback(terminal_definition):
        print(terminal_definition)

with open('grammar.lark', 'rt') as file:
    parser = lark.Lark(file.read(), edit_terminals=terminal_callback)

with open('sandbox/src/base_calc.py', 'rt') as file:
        parser.parse(text=file.read())
``` 

But the output is:
```python
TerminalDef('PREFIX', '(?:[\t ])*TO\\ BE\\ OVERRIDE\\ BY\\ LARIAT\\ \\-\\ DO\\ NOT\\ REMOVE\\ \\-\\ DO\\ NOT\\ USE\\ ANOTHER\\ TOKEN\\ FOR\\ COMMENT\\ CHAR(?:[\t ])*')
TerminalDef('MARKER', '//\\\\\\(oo\\)/\\\\')
TerminalDef('SUFFIX', '(?:[\t ])*\r?\n')
TerminalDef('LINE', '(?:[\t ])*(?:TO\\ BE\\ OVERRIDE\\ BY\\ LARIAT\\ \\-\\ DO\\ NOT\\ REMOVE\\ \\-\\ DO\\ NOT\\ USE\\ ANOTHER\\ TOKEN\\ FOR\\ COMMENT\\ CHAR)?(?:(?:\\S+(?:[\t ])+)*\\S+)?(?:[\t ])*\r?\n')
TerminalDef('_IWS', '[\t ]')
TerminalDef('__ANON_0', '.+')
```

Clearly `COMMENT_CHAR` was absorbed by `PREFIX`, which makes it difficult to consistently.

There's a possibility I'm not using this right, but I also feel the `edit_terminals` option should occur before compression, otherwise users need to predict compression to use it consistently.

Let me know if you'd like me to pop open another issue or if I'm completely off the mark.

Thank you

**Comment by erezsh** [comment]
Hello @clementfaisandier ,

That sounds like a reasonable feature request. I can see arguments for editing the terminals both before and after the processing. I'm not opposed to adding a edit_terminals_post option, or something similar.

 Feel free to open a new issue, that would reduce notifications to uninterested parties.
