### ISSUE TITLE
Lark performance with simple grammar

### ISSUE THREAD

**Issue by hniksic** [lark-parser/lark#409]
While evaluating Lark for use in production, we tested it with a simple grammar, and the performance seems significantly worse than shown in the JSON tutorial. I'm curious if this is due to an issue with the grammar.

The file format looks like this (obfuscated):

```
GROUP "qcll_oylsepxe_iyo" "Mkjhxvblo Mrrogqlj Jnh."
  INTRO "yt:0" "b:1" "p:1" "F:0" "I:0.5" "xjq:0" "mh:0" "xcl:0" "djidku:1" "bodrls:0"
  ITEM "gjeruI_nKh"     "cy.peqc(E)/(u.Hq)"   "8.7"                 FLAG1 FLAG2 FLAG3
  ITEM "sadtgT_yaRp"    "uc.pqij(V)/(n.cNm)"  "2160.7"
  ITEM "kexrwF_zwwz"    "ji.zstl(U)/(d.ano)"  "406044.6"
ENDGROUP
```

I tried to describe it using the following grammar:

```
repo: LF* group+

group: begin_group intro item+ end_group

begin_group: "GROUP" group_name group_desc LF+
group_name: quoted_string
group_desc: quoted_string

?end_group: "ENDGROUP" LF+

intro: "INTRO" intro_1 intro_2 intro_3 intro_4 intro_5 intro_6 intro_7 intro_8 intro_9 intro_10 LF+
intro_1: quoted_string
intro_2: quoted_string
intro_3: quoted_string
intro_4: quoted_string
intro_5: quoted_string
intro_6: quoted_string
intro_7: quoted_string
intro_8: quoted_string
intro_9: quoted_string
intro_10: quoted_string

item: "ITEM" item_name item_desc item_extra item_flag1? item_flag2? item_flag3? LF+
item_name: quoted_string
item_desc: quoted_string
item_extra: string
item_flag1: "FLAG1"
item_flag2: "FLAG2"
item_flag3: "FLAG3"

string: quoted_string | bare_string
_quoted_content: /[^"]+/
quoted_string: "\"" _quoted_content? "\""
bare_string: /[!#-~]+/

%import common.WS
%import common.LF
%ignore /[ \t]/
```

Parsing the full file, which has 111 KiB, takes ~0.35s on CPython 2.7, which makes the parsing time 0.3 MiB/s. The maximum CPython performance of the [JSON tutorial](https://github.com/lark-parser/lark/blob/master/docs/json_tutorial.md) appears significantly better. If something can be done in the grammar to make parsing faster, I would appreciate your input.

Here is the script used for testing: [script.zip](https://github.com/lark-parser/lark/files/3414999/script.zip). Start it with `python run_parser items` and it will print the time it took to parse the file.

**Comment by erezsh** [comment]
My first suspect would be your use of `LF+`

Instead, you should declare:

    _LF: LF+

And use `_LF` everywhere

That way the sequence will be consumed at the lexer, instead of the parser.

**Comment by erezsh** [comment]
Also, if performance is really that important to you, you should consider using PyPy.

**Comment by hniksic** [comment]
@erezsh Thanks for the suggestion. I've now tried it, but the change didn't affect the timing. Still, it's a good thing to keep in mind when writing grammars.

Unfortunately we cannot use PyPy because it doesn't support 64-bit Windows and because we rely on C extensions which use CPython features not yet supported by PyPy.

**Comment by erezsh** [comment]
Had another look, and I would say the same about `quoted_string`, which should be a terminal. No reason that the quotes will be handled be the parser, when the lexer can do it. In general, if you care about speed, try to use as little rules as possible. Move everything possible to the lexer, and prefer shifts of reduces.

Or, you know, use a parser written in C or Rust :)

**Comment by hniksic** [comment]
Thanks for the suggestion, this one sped up parsing by a factor of 1.75! It is now close to 1 MiB/s, which is "good enough" for my needs.

The takeaway message is: the more of your grammar is written in all-caps, the faster it will be. :)

**Comment by erezsh** [comment]
ABSOLUTELY ;)
