### ISSUE TITLE
Mixture of byte and unicode strings in `expected` attribute of `UnexpectedToken`

### ISSUE THREAD

**Issue by hniksic** [lark-parser/lark#411]
As promised in #410, here is a minimal example to reproduce getting a mixture of unicode and byte strings in the `expected` set of an `UnexpectedToken` exception raised by the LALR parser:

```py
import lark
_grammar = r'''
start: _ENDLINE | "foo"
_ENDLINE: ";"
'''
_parser = lark.Lark(_grammar, parser='lalr')
try:
    _parser.parse('')
except Exception as e:
    print e.expected
```

Expected output would be either `['_ENDLINE', 'FOO']` or `[u'_ENDLINE', u'FOO']`. Actual output is `['_ENDLINE', u'FOO']`.

**Comment by erezsh** [comment]
Thanks!
