### ISSUE TITLE
Provide access to auto-generated names in lark.load_grammar._TERMINAL_NAMES

### ISSUE THREAD

**Issue by hniksic** [lark-parser/lark#412]
It would be nice to have a mapping from the terminal names provided by lark to their values. The use case for this is error message generation. Consider this (incomplete) grammar snippet:

```
file: "file" _file_pattern _ENDLINE
_file_pattern: "\"" _pattern_part* "\""
_pattern_part: PATTERN_LITERAL | _pattern_column
PATTERN_LITERAL: /[^"$]+/
```

The terminals will be named as follows:

* `"file"` will be automatically named as upper-case `FILE`
* `_ENDLINE` and `PATTERN_LITERAL` will remain as-is, as they are explicitly named
* `"\""` will become `DBLQUOTE`

Given a mapping from `DBLQUOTE` to `"`, it would be possible to write a user-facing error message that says what is expected to follow at that point in the source. The symbols such as `DBLQUOTE` can be mapped to `"`, symbols introduced in the grammar like `PATTERN_LITERAL` can be looked up in a grammar-specific dict, and the rest can be lower-cased. However, the mapping from `"` to `DBLQUOTE` is not public, it is in the underscore-prefixed `lark.load_grammar._TERMINAL_NAMES` dict.

I am aware that I can avoid the need for a mapping by explicitly naming each terminal - but there is a number of those, and the grammar would remain much cleaner without the unnecessary bloat. Also, I would still need to have my own dict mapping my version of `DBLQUOTE` to `"`.

To show an example, here is my current code that converts lark error messages to the form "Parse error at line %d column %d: expecting %s", where %s is either the keyword that must follow (`'{'` or `'file'`) or a description of a more complex terminal (`quoted string` or `integer`). The code would benefit from not having to replicate `_TERMINAL_NAMES` (which could change at any time):

```py
# names built-in to lark, inverse of _TERMINAL_NAMES in lark.load_grammar
_CHAR_TERMINALS = {
    'DOT' : '.',
    ... the rest of reversed _TERMINAL_NAMES pasted here
}

# stuff specific to my grammar, mostly implemented as regular expressions
_ABSTRACT_TERMINALS = {
    'PATTERN_LITERAL': 'a portion of name',
    'COLUMN_TAG': 'column name',
    'COLUMN_UNIT': 'unit name',
    'STRING': 'optionally quoted string',
    'QUOTED_STRING': 'quoted string',
    'BARE_STRING': 'unquoted string',
}

def _prune_terminals(terms):
    ret = []
    for term in terms:
        if term.startswith('_'):
            continue  # remove __ANON_* and _IGNORE_*
        if term in _CHAR_TERMINALS:
            term = "'%s'" % _CHAR_TERMINALS[term]
        elif term in _ABSTRACT_TERMINALS:
            term = _ABSTRACT_TERMINALS[term]
        else:
            term = "'%s'" % term.lower()
        ret.append(term)
    return ret

def _convert_exc(lexc):
    if isinstance(lexc, lark.UnexpectedCharacters):
        expected = sorted(lexc.allowed)
    elif isinstance(lexc, lark.UnexpectedToken):
        expected = sorted(lexc.expected)
    else:
        return lexc
    return ParseError("Parse error at line %d column %d: expecting %s"
                      % (lexc.line, lexc.column,
                         util.itemize(_prune_terminals(expected), 'or')),
                      lexc.line, lexc.column)

def parse_spec(s):
    try:
        return _syntax.parse(s)
    except lark.exceptions.LarkError as e:
        raise _convert_exc(e)
```

**Comment by erezsh** [comment]
That makes sense. I can add a `get_terminal` method to the `Lark` instance, that will return that terminal object by name. You can then inspect it to see if it's a string (and not a regexp), and get its value. It should work for anonymous terminals as well.

What do you think?

**Comment by hniksic** [comment]
Sounds great!

It might also be nice to be able to include terminal descriptions directly in the grammar. Those could automatically appear on the terminal object returned by `get_terminal()`.

**Comment by erezsh** [comment]
That's an interesting idea. Perhaps it would be possible to include the comment after the terminal definition (if such exists) as an attribute.

**Comment by erezsh** [comment]
Added to `master`. Example usage:

```python
t = parser.get_terminal("_ENDLINE")
print(t.name, t.pattern.value, t.pattern.type)
```

**Comment by hniksic** [comment]
Thanks a lot, I'll switch to using it as soon as we update to a release of Lark that includes it.

**Comment by erezsh** [comment]
I will probably make a release (that will include this change) in the upcoming days.

**Comment by erezsh** [comment]
Lark 0.7.2 now available

**Comment by hniksic** [comment]
I've now successfully used this feature, thanks for implementing it. The resulting code no longer contains a copy of `_TERMINAL_NAMES` and now looks approximately like this:

```py
    @staticmethod
    def _describe_terminals(names):
        lst = []
        for termname in names:
            if termname.startswith('__IGNORE'):
                continue
            term = _syntax.get_terminal(termname)
            if term.pattern.type == 'str':
                desc = term.pattern.value
                pretty = "'%s'" % desc
            else:
                desc = pretty = _ParseHelper._ABSTRACT_TERMINALS[termname]
                if desc is None:
                    continue
            lst.append((desc, pretty))
        return [pretty_ for desc_, pretty_ in sorted(lst)]
```

The remaining piece of information that I was unable to find in the `TerminalDef` object is that the terminal was auto-generated out of `%ignore` rule. I would like to omit such terminals from the list, and I'm currently detecting them by checking for a name starting with `__IGNORE`, as shown above. Is there a better way to do it?

**Comment by erezsh** [comment]
It seems like a good enough way. You can just filter all terminals starting with `__` (double underscore)

I could add an API for that, but it seems like an overkill.
