### ISSUE TITLE
Avoiding get_regexp_width

### ISSUE THREAD

**Issue by jayvdb** [lark-parser/lark#413]
There is a reasonable perf boost in avoiding `utils.get_regexp_width`, as it is a red blotch on the startup performance profile.  It is used by `PatternRE` `.min_width` and `.max_width`, and by `XEarley._prepare_match`.

I havent looked at the latter, as I am not using `XEarley`.

For `PatternRE`, 

- `.min_width` could be eliminated by adding a 'sanity' mode to do the sanity checking performed in `TraditionalLexer.__init__` , as that can be disabled for normal use if the caller is enabling sanity mode whenever there are changes to the grammar, or when debugging.  The errors that it catches will result in less pretty errors if these sanity checks are disabled, but for a frozen grammar that is not going to happen.

- `.max_width` can be eliminated by allowing callers to provide their own sort algorithm also occurring in in `TraditionalLexer.__init__` , with the existing one kept as the default.

However the default can also be improved to reduce the use of `get_regexp_width`.  Currently the lambda will always calculate the `.max_width`, because it is a tuple return type, *even* if the priority means the second element of the tuples are never used for sorting.  The algorithm should sort by priority first, and then calculate the regex width only when needed to resolve the order of terminals with the same priority.  Worth noting that for lark's own grammar, removing the `.max_width` has no effect on the test suite.

```py
terminals.sort(key=lambda x:(-x.priority, -len(x.pattern.value), x.name))
```

Ideally lark (in sanity mode?) could inform the dev that the rather expensive `.max_width` was used, and how they can avoid this by changing the priorities.

**Comment by erezsh** [comment]
Interesting. How much of the time goes on `get_regexp_width` ?

Most grammars contain very few actual regexps, so I'm surprised that it's so noticeable.

I agree that `min_width` is not strictly necessary, but again, how much does it actually slow down?

As for `max_width`, I agree that it can be avoided in some cases, but *most* terminals will have the same priority anyway, so it's not likely to help. Anyway, it can't be removed.

If you really care about the start-up time, you should consider using the standalone parser.

**Comment by jayvdb** [comment]
When profiling the lark test suite (default tests) on Python 3.6, and filtering out all of the test runner stuff using https://github.com/w0rp/filter-profiler-results, get_regexp_width and its kids are 0.84%  .  It might not sound like a lot, but it is more than half the time spent in build_mres, and it is a significant amount of the time spent in `parse_sre`.
![lark](https://user-images.githubusercontent.com/15092/61842826-c34d7580-aec3-11e9-8ad8-7af9d1aaf976.png)
Also including stdlib in the graph helps show why removing it helps reduce the `re`/`sre_parse` work
![larkplus](https://user-images.githubusercontent.com/15092/61843241-2b508b80-aec5-11e9-9364-0fb9ab9919b7.png)

Obviously this isnt an ideal scenario to be profiling.

But it is one which can be easily reproduced.

The reason I went down this path is I saw this function outstanding in my profiling of https://github.com/storyscript/storyscript/blob/master/tests/integration/parser/grammar.lark

**Comment by erezsh** [comment]
>get_regexp_width and its kids are 0.84% . 

Yes, and it really isn't a lot.

Anyhow, I just pushed a small fix to `master` which should make it about twice as fast. Let me know if that works.

**Comment by jayvdb** [comment]
That was one of the fixes in my branch. I'll send a PR with the rest when I get back at a desk.

**Comment by erezsh** [comment]
Closing, but send that PR when you get to it
