### ISSUE TITLE
This is possible with lark?

### ISSUE THREAD

**Issue by prsolucoes** [lark-parser/lark#414]
Hi,

I want create a djinni DSL parser because the project was stopped:
https://github.com/dropbox/djinni/blob/master/test-suite/djinni/yaml-test.djinni

This is possible with LARK?

More samples to understand:
https://github.com/dropbox/djinni/tree/master/test-suite/djinni

There is any help here to start parsing interfaces, records, constants, enums with LARK?

Thanks.

**Comment by MegaIng** [comment]
I am not exactly sure what you are asking. Sure, all of this is possible. I would suggest you learn a bit about the basics of lark grammar and then you can just start to write your grammar, implementing construct for construct till you can parse all files. If you need general help on how to implement a language with lark, I have a example: https://github.com/MegaIng/simple-language-example

**Comment by prsolucoes** [comment]
Ok.

But im confused about how it works. Because i only see simple examples of parsing only a small set of things.

To parse djinni i will need parse some different syntax and objects:

RECORDS:

```
customer = record +c {
    id: i64;
    name: string;
    addrress: optional<string>;
    set_list : list<set<string>>;
} deriving (eq, ord, parcelable)
```

INTERFACES:

```
my_interface = interface +j +o +c {
    get_one(record_id: i64): customer;
    find_all(): list<customer>;
    static insert(new_customer: customer): i64;
    static delete_all();
}
```

CONSTANTS:

```
constants = record {
    const bool_constant: bool = true;
    const int_constant: i32 = 1;
}
```

INTERFACES WITH CONSTANTS:

```
constants_interface = interface +c {
    const bool_constant: bool = true;
    const i8_constant: i8 = 1;
}
```

FLAGS

```
access_flags = flags {
  nobody = none;
  owner_read;
  owner_write;
  owner_execute;
  group_read;
  group_write;
  group_execute;
  system_read;
  system_write;
  system_execute;
  everybody = all;
}
```

ENUM

```
color = enum {
	red;
	orange;
	yellow;
	green;
	blue;
	indigo;
	violet;
}
```

COMMENTS

```
Lines starting with # or //
```

Can you help me start? This tool that i want develop will be part of ezored (https://ezored.com). My open source tool for C++ SDK.

Thanks.

**Comment by MegaIng** [comment]
I can help you more later, but right now you might want to look at [python3.lark](https://github.com/lark-parser/lark/blob/master/examples/python3.lark), my very work-in-progress project of a [python-to-llvm](https://github.com/MegaIng/llython) compiler, or my mostly finished implementation of ['F'](https://github.com/MegaIng/F).

**Comment by erezsh** [comment]
Take a look at Lark's example Python grammar. It is far from simple: https://github.com/lark-parser/lark/blob/master/examples/python3.lark
