### ISSUE TITLE
examples/python3.lark progress?

### ISSUE THREAD

**Issue by tdh8316** [lark-parser/lark#421]
Hi, I'm making a subset of Python. (For generating LLVM IR :-)

I'd like to use an example/python3.lark before writing my grammar file (because I am a novice at Lark).

Is it okay to use in a production environment?

**Comment by erezsh** [comment]
Lark's license is MIT, which allows it to be used for commercial purposes (only excluding the standalone parser)

So yes, it includes the Python grammars as well. If you end up improving them, I hope you'll consider contributing back so everyone can benefit.
