### ISSUE TITLE
Broken links to the "wiki" in README.

### ISSUE THREAD

**Issue by thebarbershop** [lark-parser/lark#422]
README.md has two broken links to a "wiki" page.

```md
L75: See more [examples in the wiki](https://github.com/erezsh/lark/wiki/Examples)
L98: See the full list of [features in the wiki](https://github.com/erezsh/lark/wiki/Features)
```

Both link redirects to [the repo main page](https://github.com/lark-parser/lark). Well, technically, they are not _broken_ in the sense of 404, but surely that is not the expected behaviour.

Are the examples and list of features lost with the wiki? Or are they hiding somewhere in the repo but only not being correctly linked to?

**Comment by erezsh** [comment]
Yes, the documentation isn't lost, it's just elsewhere.

Thanks for bringing this to my attention.

**Comment by erezsh** [comment]
Thanks again
