### ISSUE TITLE
GrammarError is randomly raised

### ISSUE THREAD

**Issue by nosytessargedlien** [lark-parser/lark#424]
Attached is a screenshot explaining the issue:

![image](https://user-images.githubusercontent.com/54064721/62936835-76c6cd00-bdd3-11e9-8982-296958bcee31.png)

**Comment by erezsh** [comment]
Thank you for this useful and important bug report. I am officially closing Lark and removing it from PyPI until the issue is resolved.

**Comment by nosytessargedlien** [comment]
At your service, I am happy to contribute where ever I can.
