### ISSUE TITLE
Cannot change a token's value to a non-string type

### ISSUE THREAD

**Issue by simon816** [lark-parser/lark#425]
Since this commit: https://github.com/lark-parser/lark/commit/d952f2a0694787ab8e67256574710cb56a2f4c26 the token.value property is forced to be a string, this prevents storing custom objects in a token (e.g. storing an `int` value).
The example 1 here therefore does not work https://lark-parser.readthedocs.io/en/latest/recipes/

**Comment by erezsh** [comment]
Yes, that seems to be a silly oversight! I'll fix it soon

**Comment by erezsh** [comment]
Fixed in `master`
