### ISSUE TITLE
Earley doesn't always pinpoint line & number of parse error

### ISSUE THREAD

**Issue by gerases** [lark-parser/lark#43]
Hi,

I would like to request a feature where the default parser could report the line and column number of data not conforming to the grammar.

Thanks!
  Sergei

**Comment by erezsh** [comment]
Just pushed a fix to master. It was easier to solve than I anticipated. I'm closing the issue, but feel free to reopen it if there is still an issue.

**Comment by gerases** [comment]
Sorry to bug, but I thought the line/col number would be added in these messages:

```
File "/home/sgerasenko/lark/lark/parsers/xearley.py", line 150, in parse
    raise ParseError('Incomplete parse: Could not find a solution to input')
lark.common.ParseError: Incomplete parse: Could not find a solution to input
```

Did I misunderstand something?

**Comment by erezsh** [comment]
Okay, it might be a bit more challenging, but I'll give it a try.

**Comment by erezsh** [comment]
I changed this exception to be more informative / actionable. Please try the latest version at `master` and let me know if the new exception info is sufficient.

**Comment by gerases** [comment]
It's a bit better because it tells me what it was expecting:

```lark.common.ParseError: Unexpected end of input! Expecting a terminal of: []```

but no line number right? The challenge is that my input file is ~1300 lines long and to understand where it failed requires something like removing half of the file, seeing if the error is gone, removing the half of what was left, etc. I can get by though if it's too difficult.

**Comment by erezsh** [comment]
Yes, I see. It's a difficult error to report, because it's not completely clear, when it occurs, at which point did the parse go wrong. I'll see if I can do better.

Btw, are you getting `Expecting a terminal of: []` ? That list isn't supposed to be empty.

**Comment by gerases** [comment]
I generated that error by putting some garbage in my input -- just to see what the error would look like. No special meaning there.

**Comment by gerases** [comment]
After quite a bit of reducing, I've established the minimum input to trigger the issue is:

```
Cmnd_Alias C_AL1 = CMD1, \
  CMD2
#COMMENT1
Cmnd_Alias C_AL2 = CMD3
# ======> BLAH
# COMMENT2
Host_Alias H_AL = SOME_HOSTS
User_Alias U_AL = me, you, him
```

Removing the last line, for example, hides the issue. And the issue is that `C_AL2` starts being part of the `user_spec` rule instead of a Command_Alias. Removing one of the comment lines also fixes the issue. Here's the grammar for reference one more time:

```
sudo_parser = Lark(r"""
    sudo_item : (alias | user_spec)*

    alias : "User_Alias"    user_alias  (":" user_alias)*
            | "Runas_Alias" runas_alias (":" runas_alias)*
            | "Host_Alias"  host_alias  (":" host_alias)*
            | "Cmnd_Alias"  cmnd_alias  (":" cmnd_alias)*

    user_alias  : ALIAS_NAME "=" user_list
    host_alias  : ALIAS_NAME "=" host_list
    runas_alias : ALIAS_NAME "=" runas_list
    cmnd_alias  : ALIAS_NAME "=" cmnd_list

    user_spec      : user_list host_list "=" cmnd_spec_list (":" host_list "=" cmnd_spec_list)*
    cmnd_spec_list : cmnd_spec ("," cmnd_spec)*
    cmnd_spec      : runas_spec? tag_spec? negator? command
    runas_spec     : "(" runas_list? (":" runas_list)? ")"
    tag_spec       : (tag_nopwd
                       | tag_pwd
                       | tag_noexec
                       | tag_exec
                       | tag_setenv
                       | tag_nosetenv
                       | tag_log_output
                       | tag_nolog_output) ":"
    ?command         : command_name | cmnd_alias_name
    command_name    : all | file_name (args)*
    all             : "ALL"
    file_name       : FILENAME
    args            : (arg)* | star | no_arg_string
    arg             : ARG
    star            : "*"
    no_arg_string   : "\"\""
    negator         : NEGATOR
    cmnd_alias_name : ALIAS_NAME

    host_list  : host      ("," host)*
    user_list  : user      ("," user)*
    runas_list : user      ("," user)*
    cmnd_list  : command   ("," command)*

    host : HOST_NAME

    user :    "!"*       USER_NAME
            | "!"* "%"   GROUP_NAME
            | "!"* "#"   UID
            | "!"* "%#"  GID
            | "!"* "+"   NETGROUP_NAME
            | "!"* "%:"  NONUNIX_GROUP_NAME
            | "!"* "%:#" NONUNIX_GID
            | "!"* user_alias

    tag_pwd          : "PASSWD"
    tag_nopwd        : "NOPASSWD"
    tag_exec         : "EXEC"
    tag_noexec       : "NOEXEC"
    tag_setenv       : "SETENV"
    tag_nosetenv     : "NOSETENV"
    tag_log_output   : "LOG_OUTPUT"
    tag_nolog_output : "NOLOG_OUTPUT"

    NEGATOR            : "!"
    UID                : /[0-9]+/
    GID                : /[0-9]+/
    NONUNIX_GID        : /[0-9]+/
    USER_NAME          : /[-_.a-z0-9A-Z]+/
    GROUP_NAME         : CNAME
    NETGROUP_NAME      : CNAME
    NONUNIX_GROUP_NAME : CNAME
    ALIAS_NAME         : CNAME
    HOST_NAME          : /[-_.a-z0-9A-Z\[\]*]+/
    FILENAME           : /\/[-._a-zA-Z0-9\/]+/
    ARG                : /[-{}\\\\:@;_.\/a-zA-Z0-9]+/

    %import common.CNAME
    %import common.WS
    %ignore /[\\\\]$/m
    %ignore /^#.*$/m
    %ignore /^Defaults.*$/m
    %ignore WS
""", start='sudo_item')
```

**Comment by erezsh** [comment]
It's been two years (wow!), so I'm closing this issue. If this is still of interest, feel free to reopen or open a new issue, and I will try to give it more attention.

**Comment by gerases** [comment]
Oh yeah, for sure. It worked perfectly. Thank you much!!!
