### ISSUE TITLE
%import for rule with parser actions fails

### ISSUE THREAD

**Issue by night199uk** [lark-parser/lark#433]
grammar1.lark:
x: "TEST" -> to_str

grammar2.lark:
%import .grammar1 (x)

Fails with:
  File "lark/load_grammar.py", line 607, in rule_dependencies
    raise GrammarError("Missing symbol '%s' in grammar %s" % (symbol, namespace))
lark.exceptions.GrammarError: Missing symbol 'to_str' in grammar grammar1

**Comment by erezsh** [comment]
That should fix it
