### ISSUE TITLE
Eliminate subtree of ambiguous grammar

### ISSUE THREAD

**Issue by jtrakk** [lark-parser/lark#442]
My tree has an `_ambig` node with several branches, but some of the branches have nodes that are invalid (I can check them in a visitor). I want to transform the tree by removing each branch of the `_ambig` that contains the invalid nodes. 

I'm wondering how to remove children of an `_ambig` based on information in the child's descendants. Ideally then I could say "after filtering invalid branches, if there's only one remaining branch of the `_ambig`, then remove the `_ambig`, and otherwise raise an exception". Is there an example of resolving ambiguity that I could look at? How would you recommend implementing this? Thank you!

**Comment by erezsh** [comment]
You can `tree.find_data("_ambig")`, and for each one collect information using `class CountInvalid(Transformer): ...`

There's more than one way, of course.

**Comment by jtrakk** [comment]
Ah I see, that's pretty simple, thanks!

BTW, is there a preferred venue for asking questions like this? I don't want to be filling up your tracker if you prefer to separate support questions from issues.

**Comment by erezsh** [comment]
Gitter is suitable for that: https://gitter.im/lark-parser/Lobby

**Comment by jtrakk** [comment]
Sounds good, thank you.
