### ISSUE TITLE
pydot dependency breaks Early parser debug mode

### ISSUE THREAD

**Issue by vEpiphyte** [lark-parser/lark#443]
Hi Lark maintainers,

Using lark 0.7.4, unit tests for synapse are now breaking due to the hard dependency on pydot when operating a parser in debug mode.

The following is our test code:
```
    def test_grammar(self):
        '''
        Validates that we have no grammar ambiguities
        '''
        with s_datfile.openDatFile('synapse.lib/storm.lark') as larkf:
            grammar = larkf.read().decode()

        parser = lark.Lark(grammar, start='query', debug=True, ambiguity='explicit', keep_all_tokens=True,
                           propagate_positions=True)

        for i, query in enumerate(_Queries):
            try:
                tree = parser.parse(query)
                # print(f'#{i}: {query}')
                # print(tree, '\n')
                self.notin('_ambig', str(tree))

            except (lark.ParseError, lark.UnexpectedCharacters):
                print(f'Failure on parsing #{i}:\n{{{query}}}')
                raise
```

This test threw an exception when trying to call the parse() function:

```
synapse/tests/test_lib_grammar.py:973: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.7/site-packages/lark/lark.py:306: in parse
    return self.parser.parse(text, start=start)
venv/lib/python3.7/site-packages/lark/parser_frontends.py:185: in parse
    return self._parse(text, start)
venv/lib/python3.7/site-packages/lark/parser_frontends.py:54: in _parse
    return self.parser.parse(input, start, *args)
venv/lib/python3.7/site-packages/lark/parsers/earley.py:302: in parse
    debug_walker = ForestToPyDotVisitor()
venv/lib/python3.7/site-packages/lark/parsers/earley_forest.py:368: in __init__
    self.pydot = import_module('pydot')
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'pydot', import_ = <function _gcd_import at 0x7fc42eee3b00>

>   ???
E   ModuleNotFoundError: No module named 'pydot'

```

This failure can be seen here https://circleci.com/gh/vertexproject/synapse/9074#tests/containers/3

The change in behavior to call `ForestToPyDotVisitor()` was made here https://github.com/lark-parser/lark/compare/0.7.3...0.7.4#diff-4a777feb210f4e06c3f3cbc80487c0a2R300 by the following commit https://github.com/lark-parser/lark/commit/d845aa3bf1cf6408df27b843c02dd9b4b729c41a

Since lark doesn't install pydot, and there is no guarantee that graphviz tools are available for all users, can that check in https://github.com/lark-parser/lark/blob/master/lark/parsers/earley.py#L300 catch those errors caused by the deferred import so that debug users don't fail due to that error?

**Comment by erezsh** [comment]
Just out of curiosity, why not remove `debug=True`? It's used for debugging, and I don't think it gives any extra benefit to the tests.

**Comment by vEpiphyte** [comment]
@erezsh removing that for our project works; but another user who goes to use debug logging with a LARL parser could encounter this same undocumented dependency if this type of graph representation was added to itd.

**Comment by erezsh** [comment]
Usually, I would agree with you. But `debug` is a special mode. I think the important question here is this: Is there ever any reason to use `debug=True`, when not debugging?

If there is, then I would concede that your claim is valid. But if there isn't (which is what I suspect), then it's better, for the long run, to root out incorrect usage, rather than accommodate it.

Maybe I'm wrong about this, and after all, catching the `ImportError` inside Lark won't be difficult. I'm just not sure that's the right thing to do.

**Comment by erezsh** [comment]
Decided to fix it anyway. Will now only show a warning.

**Comment by vEpiphyte** [comment]
@erezsh Thanks for addressing this!
