### ISSUE TITLE
Precedence

### ISSUE THREAD

**Issue by johnny-alvarado** [lark-parser/lark#444]
I have a precedence problem in my grammar:

```
bbx_grammar = """
    ?start: sum
          | TAGNAME "=" sum    -> assign_var
          | TAGNAME ">=" sum    -> increase_var
          | TAGNAME ">" sum    -> increase_var
          | TAGNAME "<=" sum    -> decrease_var
          | TAGNAME "<" sum    -> decrease_var
          | TAGNAME "<>" sum    -> increase_var
          | TAGNAME "IN" list   -> inside_var
          | TAGNAME "NIN" list   -> outside_var
    ?sum: product
        | sum "+" product   -> add
        | sum "OR" product  -> or_op
    ?product: atom
        | product "*" atom  -> mul
        | product "/" atom  -> div
        | product "AND" atom -> and_op  
        | atom "-" atom -> inside_range
    ?list: "(" [product ("," product)*] ")"
    ?atom: NUMBER           -> number
         | TAGNAME          -> var
         | "(" sum ")"
    TAGNAME: "{" NAME "}"
    %import common.CNAME -> NAME
    %import common.NUMBER
    %import common.WS_INLINE
    %ignore WS_INLINE
"""
```

because if I have a sentence like ```{a} = 7```the parser assigns the value ```7``` to variable ```a```and this is correct.  However if I do ```{Temp-1} = 45``` I get an error, since my implementation tries to substract ```1``` from ```Temp```.  I want the parser to handle ```Temp-1``` as a variable instead.

I tried several things unsuccessfully.  What do you recommend me to fix my problem?

**Comment by erezsh** [comment]
Your mistake is using `CNAME`, which doesn't allow for dashes in the name. You should make your own variable name that does allow it, in the way the you expect.

**Comment by johnny-alvarado** [comment]
Ok, and how can I create a variation on CNAME.  I see the definition as:
```CNAME: ("_"|LETTER) ("_"|LETTER|DIGIT)*```
but if I try to include in my grammar a variation, let's call it ```TNAME``` like
```TNAME: ("_"|LETTER) ("_"|"-"|LETTER|DIGIT)*```
I get a key error for ```TOKEN(TERMINAL,'LETTER')```
How do I reference ```LETTER``` and ```DIGIT``` to prevent this error?

**Comment by bilderbuchi** [comment]
Drive by comment: pretty sure it's %import common.LETTER.

**Comment by johnny-alvarado** [comment]
It works.  Thank you!

**Comment by bilderbuchi** [comment]
So, can this be closed?

**Comment by johnny-alvarado** [comment]
Hi Christoph,

Yes, you can close it.

Thank you!

Best Regards,
 
Johnny Alvarado

**Comment by bilderbuchi** [comment]
I can't, either you have to (as the opener) or the Lark maintainer.

**Comment by johnny-alvarado** [comment]
Hi Christoph,

I already closed it.

Best Regards,
 
Johnny Alvarado
