### ISSUE TITLE
Regression: %imported grammar does not find rules

### ISSUE THREAD

**Issue by bilderbuchi** [lark-parser/lark#445]
When a grammar uses an imported second grammar file, this broke between 0.7.3 and 0.7.4 (git bisect tells me with f06a83a8a79e0507ae58e7f8c5af8888e1d92da8).

Hoepfully minimal repro:
file main.lark:
```
start : engineering_units
%import .eng_units.engineering_units
%import common.WS
%ignore WS
```
file eng_units.lark
```
engineering_units : unit_product ["blubb"]
unit_product : "bla"
```
Then, `Lark.open("main.lark")` raises (on current master)
```
lark.exceptions.GrammarError: Rule 'eng_units__unit_product' used but not defined (in rule engineering_units)
```
With 0.7.3, this worked. Interestingly, removing `["blubb"]` in engineering_units makes the error go away.

**Comment by erezsh** [comment]
I pushed a fix to `master`. Let me know if it solves it.

**Comment by bilderbuchi** [comment]
Yes, that fixes it, thank you for the quick fix!

Should that be interesting for you, this was the pytest test I used (+ the two files above):
```
import os
from lark import Lark

_full_path = os.path.dirname(os.path.abspath(__file__))
pluto_grammar_file = os.path.join(_full_path, "main.lark")


def test_rule_used_but_not_defined():
    Lark.open(pluto_grammar_file)
    # raises lark.exceptions.GrammarError: Rule 'engineering_units__unit_product' used but not defined (in rule engineering_units__unit_reference)
```

**Comment by bilderbuchi** [comment]
sorry, next time. :-)
