### ISSUE TITLE
Return Discard instead of raising it

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#447]

**Comment by evandrocoan** [comment]
Why?

**Comment by erezsh** [comment]
I believe it should be faster to return a singleton, instead of raising it.

But I will test it before deciding whether to commit to this idea or not.

**Comment by evandrocoan** [comment]
> But I will test it before deciding whether to commit to this idea or not.

Good work testing it before! As Donald Knuth said:

> “The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places and at the wrong times; premature optimization is the root of all evil (or at least most of it) in programming.”
https://stackify.com/premature-optimization-evil/

**Comment by erezsh** [comment]
Discard is now returned instead of raised.
