### ISSUE TITLE
Folded tokens cannot be visited 

### ISSUE THREAD

**Issue by YuriyPopov** [lark-parser/lark#453]
Visiting tokens is a very cool feature. However it's not possible to visit tokens folded into other tokens. 
For example, I have a token NUMBER and two other tokens DELIMITER and INTEGER folded into the NUMBER token. When I trying to transform the parse tree the NUMBER token is visited but the folded tokens are not. What am I doing wrong? 

Here is a snippet of code to reproduce.

```
from lark import Lark, Transformer

grammar = r"""start: NUMBER 
NUMBER: INTEGER (DELIMITER INTEGER)?
INTEGER: ("0".."9")+
DELIMITER:","|"." 
"""
class MyTransformer(Transformer):
    def NUMBER(self, tok):
        return f"num:{tok}"
    def DELIMITER(self, tok):
        return f"dlmtr:{tok}"

tree = Lark(grammar).parse('24,30')
res = MyTransformer(visit_tokens=True).transform(tree)
```

**Comment by erezsh** [comment]
Yes, what you call "folded" terminals are actually compiled into a single regexp. If you want to access the components, you should do one of the following:

1) Use rules instead of terminals (`number: INTEGER (DELIMITER INTEGER)?`)

2) Parse the result, using a regexp on the value of NUMBER

**Comment by YuriyPopov** [comment]
Thank you! Now it makes sense. I think the issue can be closed now.
