### ISSUE TITLE
Error reporting for ParseError

### ISSUE THREAD

**Issue by jtrakk** [lark-parser/lark#457]
I'm getting a  `lark.exceptions.ParseError`, and I would like to do error reporting similar to [error_reporting_lalr.py](https://github.com/lark-parser/lark/blob/master/examples/error_reporting_lalr.py) but it doesn't look like `ParseError` has the necessary attributes. I guess `ParseError` is for missing characters, rather than unexpected characters. Would it be possible to do reporting from a `ParseError`?

For example, 

```py
lark.Lark(r"""
x: "a" y
y: "b"
""", start="x").parse('a')

```
```
ParseError: Unexpected end of input! Expecting a terminal of: []
```

**Comment by erezsh** [comment]
`error_reporting_lalr.py` uses LALR, while your snippet uses Earley.

Unfortunately, their error reporting mechanisms are different, and currently don't offer the same interface.

However, it should say that it's expecting terminal `B`, so I pushed a fix for that.
