### ISSUE TITLE
Proposal: support for #line directives in line/column tracking

### ISSUE THREAD

**Issue by cmacmackin** [lark-parser/lark#460]
There are many DSLs and even fully-fledged programming languages which feature an `include` statement of some kind, either intrinsicaly or through a preprocessor. Often the nature of the language is such that the included files can not be meaningfully parsed separately from those which reference them.

In and of itself, this is not difficult to handle with Lark. A user can process the input file to embed the contents of all the `included` files before passing the resulting text to the parser. However, at this point the line/column tracking in Lark becomes effectively useless, as it will only provide information on position within the final string the user has generated from the input. A similar issue arises for any preprocessing performed prior to parsing, such as expanding macros.

The approach which the C preprocessor takes to address this is the `#line` macro, which defines  a file name and line number relative to which the compiler can give positions in the text. I've been thinking a bit about how one might add support for something similar in Lark. My idea would be to make this work in a general way (i.e., not tied to the C preprocessor syntax) by the creation of a new directive in Lark grammars. I haven't put too much thought into the exact syntax or algorithm yet, however.

This would also require a change to how position information is calculated and stored, with the addition of an (optional) filename datum. To properly handle file inclusion it would also be useful to express the position information as a stack file/line/column groupings. This would require some changes to the lexers, particularly the [LineCounter](https://github.com/lark-parser/lark/blob/master/lark/lexer.py#L133) and [Token](https://github.com/lark-parser/lark/blob/master/lark/lexer.py#L92) classes.

I would be happy to develop this feature and create a pull request. However, I wanted to raise it here and discuss it first, to ensure I don't waste my time on something which is not of interest or would be considered too disruptive.

**Comment by erezsh** [comment]
Why not just create a mapping of `preproceessed_line -> real_line`, and apply it to all created tokens?

Of course, the mapping can be virtual, through line ranges, with an efficient tree search

**Comment by erezsh** [comment]
As no discussion is taking place, I'm closing this issue. I will reopen if interest is renewed.
