### ISSUE TITLE
How to use different names for the same terminal?

### ISSUE THREAD

**Issue by francisr** [lark-parser/lark#461]
I have a simple grammar showcasing my issue:
```
start: ID " " NAME

ID: WORD
NAME: WORD

WORD: /\w+/
```
I want to use aliases for the terminals to make the grammar more readable, but I get hit with:
```
lark.exceptions.UnexpectedToken: Unexpected token Token(ID, 'tost') at line 1, column 6.
Expected one of: 
	* NAME
```
What's the right way of doing that?

**Comment by erezsh** [comment]
Works like a charm:
```python
>>> l=Lark("""start: ID " " NAME
...
... ID: WORD
... NAME: WORD
...
... WORD: /\w+/""")

>>> l.parse("hello world")
Tree(start, [Token(ID, 'hello'), Token(NAME, 'world')])
```

**Comment by francisr** [comment]
Ah, I was using lexer="standard". When I leave the default it works, thanks.

**Comment by erezsh** [comment]
`lexer="standard"` is a bit like bubblesort. It's there for completeness, but it's almost never what you want.
