### ISSUE TITLE
Don't raise VisitError in _call_userfunc()?

### ISSUE THREAD

**Issue by jtrakk** [lark-parser/lark#464]
As discussed in https://github.com/lark-parser/lark/issues/313, `VisitError` hides the original exception, and requires awkward workarounds like accessing `e.__context__` in order to handle specific exceptions. I am wondering whether `VisitError` is costing us more than it's buying. How would you feel about `Transformer._call_userfunc()` just letting the user's exception bubble up, so I can handle my own exception directly?

**Comment by erezsh** [comment]
Does this solve your problem?

```python
from lark import Tree, Transformer
from lark.exceptions import VisitError

t = Tree("a", [])

class T(Transformer):
    def a(self, args):
        raise ValueError("User error")

>>> try:
...     T().transform(t)
... except VisitError as e:
...     raise e.orig_exc
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "C:\Users\erez\AppData\Roaming\Python\Python37\site-packages\lark\visitors.py", line 47, in _call_userfunc
    return f(children)
  File "<stdin>", line 3, in a
ValueError: User error
```

**Comment by jtrakk** [comment]
Yes, thanks.

**Comment by erezsh** [comment]
Maybe this should be in the docs.

**Comment by evandrocoan** [comment]
> Maybe this should be in the docs.

Yes.
