### ISSUE TITLE
Add Lark to awesome-python

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#465]
A while ago I tried to add Lark to the awesome-python list, so more people can find it. Apparently it didn't get enough votes yet, and soon it will expire.

If you think Lark deserves to be up there next to PLY and PyParsing, please go and vote!

https://github.com/vinta/awesome-python/pull/1130

**Comment by evandrocoan** [comment]
Voted!

**Comment by llpinokio** [comment]
Voted!!!!!

**Comment by phorward** [comment]
Voted!

**Comment by erezsh** [comment]
Well, looks like it didn't work out. Thanks for everyone who voted!
