### ISSUE TITLE
[question] transfromer of token after parsing?

### ISSUE THREAD

**Issue by swuecho** [lark-parser/lark#470]
the rule can be transformed, which is great. how about the token?  

The closest I can find in the doc is recipe #1: lexer callback, but  the returned value have to be token in lexer callback, which is processed before the parsing I guess). 

use cases: turn INT to int, NUMBER to float, etc.

**Comment by erezsh** [comment]
Yes. It's a very new feature, so I hadn't had time to write documentation for it yet.

But if you initialize your transformer with `visit_tokens=True`, it will also process tokens.

Like

```
class T(Transformer):
    def NAME(self, name):
        return lookup_dict.get(name, name)

T(visit_tokens=True).transform(tree)
```

**Comment by swuecho** [comment]
Thanks! 

https://github.com/lark-parser/lark/pull/471/commits/10a09ebba86fb17c2c13dc3080d6aa1d9987211c

copied the example to docs.
