### ISSUE TITLE
From tree to original DSL

### ISSUE THREAD

**Issue by remorses** [lark-parser/lark#473]
Is there a way to generate the original DSL described in the grammar from the tree?
If i build the tree myself can i generate the language string described by the grammar?

**Comment by erezsh** [comment]
There isn't really a good solution to your problem.

But, there is an experimental one, if you want to try it out. See this example: https://github.com/lark-parser/lark/blob/master/examples/reconstruct_json.py

**Comment by remorses** [comment]
Exactly what i was searching for, unfortunely my grammar uses a lot of regex and indents so i will just make a Transformer to my original language.

**Comment by erezsh** [comment]
I don't see why regexes would pose a problem for reconstruction.

Indents might be fairly easy to fix.
