### ISSUE TITLE
Regular expression range fails to match

### ISSUE THREAD

**Issue by hniksic** [lark-parser/lark#474]
Based on [a question on StackOverflow](https://stackoverflow.com/q/58780388/1600898), I would expect this grammar to accept `q` as input, but it doesn't:

```
import lark
grammar = r"""
start      : /[\x23-\x5b\x5d-\x7e]/
//start      : /[\#-\]\[-~]/
"""
parser = lark.Lark(grammar)
print(parser.parse('q'))
```

Expected result: successful parse to a tree containing `q`, e.g. `Tree(start, [Token(__ANON_0, 'q')])`
Actual result: exception raised: `lark.exceptions.UnexpectedCharacters: No terminal defined for 'q' at line 1 col 1`

Replacing the rule with the commented-out version (which should be equivalent) causes the input to be accepted. Removing the first set and leaving just `/[\x5d-\x7e]/` also makes it work.

Python's `re` module accepts all the different variants:

```
>>> re.compile(r'[\x23-\x5b\x5d-\x7e]').match('q')
<re.Match object; span=(0, 1), match='q'>
>>> re.compile(r'[\#-\]\[-~]').match('q')
<re.Match object; span=(0, 1), match='q'>
>>> re.compile(r'[\x5d-\x7e]').match('q')
<re.Match object; span=(0, 1), match='q'>
```

**Comment by MegaIng** [comment]
After looking into this a bit, this is a bug?/feature? in the way lark handles RE: it handles the content between `/` like they were between `"` and `"`, not like they were between `r"` and `"`. And if you test that, you see that your example does no longer work:

    >>> re.compile('[\x23-\x5b\x5d-\x7e]').match('q')
    >>>
which is equivalent to:

    >>> re.compile('[#-[]-~]').match('q')
    >>>

which of course won't work.
Whether or not this is good is an interesting question. I would say change the behavior, but that would break backwards compatibility.

**Comment by hniksic** [comment]
> After looking into this a bit, this is a bug?/feature? in the way lark handles RE: it handles the content between `/` like they were between `"` and `"`, not like they were between `r"` and `"`.

That would imply that the correct way to write the grammar is by doubling the backslashes. That's inconvenient, but it works in `re`:

```py
>>> re.compile('[\\x23-\\x5b\\x5d-\\x7e]').match('q')
<re.Match object; span=(0, 1), match='q'>
```

However, when I try the same in Lark, it results in an exception while building the parser:

```
Traceback (most recent call last):
  File "/home/hniksic/.local/lib/python3.7/site-packages/lark/utils.py", line 175, in get_regexp_width
    return [int(x) for x in sre_parse.parse(regexp).getwidth()]
  File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 580, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range d-\\ at position 16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hniksic/.local/lib/python3.7/site-packages/lark/parser_frontends.py", line 175, in _prepare_match
    width = get_regexp_width(regexp)[0]
  File "/home/hniksic/.local/lib/python3.7/site-packages/lark/utils.py", line 177, in get_regexp_width
    raise ValueError(regexp)
ValueError: [\\x23-\\x5b\\x5d-\\x7e]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lark1.py", line 8, in <module>
    parser = lark.Lark(grammar)
  File "/home/hniksic/.local/lib/python3.7/site-packages/lark/lark.py", line 231, in __init__
    self.parser = self._build_parser()
  File "/home/hniksic/.local/lib/python3.7/site-packages/lark/lark.py", line 251, in _build_parser
    return self.parser_class(self.lexer_conf, parser_conf, options=self.options)
  File "/home/hniksic/.local/lib/python3.7/site-packages/lark/parser_frontends.py", line 154, in __init__
    self._prepare_match(lexer_conf)
  File "/home/hniksic/.local/lib/python3.7/site-packages/lark/parser_frontends.py", line 177, in _prepare_match
    raise ValueError("Bad regexp in token %s: %s" % (t.name, regexp))
ValueError: Bad regexp in token __ANON_0: [\\x23-\\x5b\\x5d-\\x7e]
```

**Comment by erezsh** [comment]
I agree there's a usability issue here. However, it's a very specific edges case, where you're using hex code to represent characters with a special meaning in regexps.

Also, it's very easy to fix the regexp like this: `/[\x23-\x5b]|[\x5d-\x7e]/`

If someone wants to submit a patch, that's fine. There is going to be a backwards incompatible release in a few weeks, so perhaps it could make it in.

**Comment by hniksic** [comment]
> However, it's a very specific edge case, where you're using hex code to represent characters with a special meaning in regexps.

I suspect the OP on StackOverflow expected the hex code to escape the special meaning of the characters. Where possible, it would be nice (or at least less surprising) for regexps in the grammar to be interpreted the same as by `re`.

**Comment by erezsh** [comment]
Closing out of lack of interest. Feel free to reopen or comment if anyone wants to implement it.
