### ISSUE TITLE
Ignore new-line, but allow it to be used somtimes ?

### ISSUE THREAD

**Issue by vsraptor** [lark-parser/lark#475]
Is there a way to ignore new-line so that you have multiline statements, but still allow it to be used in parsing ... f.e. let say we have the following code : 

     def name1 : 
         atom1, atom3,
         atom4;
     #this is a comment
     d name2 : atomx;

so I have multiline definitions, but then I want to have shortcut of "def" to be "d" when it is first character on a new line i.e. defined something like this : 

      def : "def" | /(^|\\n)d\s/  

this almost work.

Another time I want to have access to the end of line access to gobble everything until \n f.e. : 

      text : /.+$/

but this wont work too, cause I probably have to have start-char !!!

**Comment by erezsh** [comment]
Yes, it's possible. If you use LALR, you will have to set the priority yourself. With Earley it should resolve automatically.

> this almost work

When doesn't it?

Reading everything until the end of line isn't difficult either. Look at how I implemented comments in the Python grammar.

Also, consider declaring newline as `_NL: /\n+/` (could in reality be a little more complex with comments and `\r`)

That way maybe you don't even need to ignore it.

**Comment by vsraptor** [comment]
> Yes, it's possible. If you use LALR, you will have to set the priority yourself.

how is it done !? Do you have an example ?

btw I use %ignore WS

**Comment by erezsh** [comment]
Reads the docs about terminal priority.
