### ISSUE TITLE
keywords => Empty list  [] on transformation ?!

### ISSUE THREAD

**Issue by vsraptor** [lark-parser/lark#476]
When I use directly a strings, I don't get back the match  : 

        def domain_kws(self, s):
                print  s
                return s

        domain_kws : "entities" | "actions" | "forms" | "intents"

       In [31]: b.test('actions', 'domain_kws')
       []
     
but if I separate it I get it back during Transformation : 

        domain_kws : "entities" | actions | "forms" | "intents"
        actions : "actions"

         In [31]: b.test('actions', 'domain_kws')
         [Tree(actions, [])]

Is it possible to do it w/o separating the keywords ?

**Comment by erezsh** [comment]
You can use `!domain_kws : "entities" | actions | "forms" | "intents"`

**Comment by vsraptor** [comment]
thanks
