### ISSUE TITLE
LALR parser works exactly as SLR parser!

### ISSUE THREAD

**Issue by denizetkar** [lark-parser/lark#478]
**Version:**
0.7.8

**Problem:**
For each final rule (rules with 'dot' at the very end) in all canonical LR(0) items (states), the 'Reduce' action is assigned to all terminals in the 'FOLLOW' of the left-hand side non-terminal. This is exactly how SLR(1) parsing algorithm works, but not how LALR(1) does.

**The lines causing the problem:**
https://github.com/lark-parser/lark/blob/f07359c31683805f4004fe2d6f37dec84b7c094f/lark/parsers/lalr_analysis.py#L94-L95

**How to reproduce:**

_lalr_test.lark_
```
s: a "[" a "]"
a: ("(" a ")")?
```

_lark_lalr_test.py_
```
from lark import Lark

with open('lalr_test.lark') as f:
    parser = Lark(f, parser='lalr', keep_all_tokens=True, start='s', debug=True)
```

- Start debugging the above python file after placing a breakpoint to:

https://github.com/lark-parser/lark/blob/f07359c31683805f4004fe2d6f37dec84b7c094f/lark/parsers/lalr_analysis.py#L130

- After reaching the above debug breakpoint the first time, let it run free again and reach here a second time (because apparently lark itself uses LALR parser to parse _*.lark_ files).

- Now observe the `self.states` dictionary, preferably with the help of an interactive python debugger console (I am using PyCharm myself):
```
print('{')
indentation = '  '
for k, v in self.states.items():
    print(indentation + str(k) + ':')
    for k2, v2 in v.items():
        print(indentation * 2 + '%s: %s' % (str(k2), str(v2)))
    print(indentation + ',')
print('}')
```
- The output looks like:
```
{
  {<a :  * LPAR a RPAR>, <a :  * >, <s :  * a LSQB a RSQB>, <$root_s :  * s $END>}:
    LSQB: (Reduce, Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None)))
    RPAR: (Reduce, Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None)))
    RSQB: (Reduce, Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None)))
    LPAR: (Shift, {<a : LPAR * a RPAR>, <a :  * >, <a :  * LPAR a RPAR>})
    a: (Shift, {<s : a * LSQB a RSQB>})
    s: (Shift, {<$root_s : s * $END>})
  ,
  {<a : LPAR * a RPAR>, <a :  * >, <a :  * LPAR a RPAR>}:
    LSQB: (Reduce, Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None)))
    RPAR: (Reduce, Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None)))
    RSQB: (Reduce, Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None)))
    a: (Shift, {<a : LPAR a * RPAR>})
    LPAR: (Shift, {<a : LPAR * a RPAR>, <a :  * >, <a :  * LPAR a RPAR>})
  ,
  {<s : a * LSQB a RSQB>}:
    LSQB: (Shift, {<a :  * >, <s : a LSQB * a RSQB>, <a :  * LPAR a RPAR>})
  ,
  {<$root_s : s * $END>}:
    $END: (Shift, {<$root_s : s $END * >})
  ,
  {<a : LPAR a * RPAR>}:
    RPAR: (Shift, {<a : LPAR a RPAR * >})
  ,
  {<a :  * >, <s : a LSQB * a RSQB>, <a :  * LPAR a RPAR>}:
    LSQB: (Reduce, Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None)))
    RPAR: (Reduce, Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None)))
    RSQB: (Reduce, Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None)))
    a: (Shift, {<s : a LSQB a * RSQB>})
    LPAR: (Shift, {<a : LPAR * a RPAR>, <a :  * >, <a :  * LPAR a RPAR>})
  ,
  {<$root_s : s $END * >}:
  ,
  {<a : LPAR a RPAR * >}:
    LSQB: (Reduce, Rule(NonTerminal('a'), [Terminal('LPAR'), NonTerminal('a'), Terminal('RPAR')], None, RuleOptions(False, False, None)))
    RPAR: (Reduce, Rule(NonTerminal('a'), [Terminal('LPAR'), NonTerminal('a'), Terminal('RPAR')], None, RuleOptions(False, False, None)))
    RSQB: (Reduce, Rule(NonTerminal('a'), [Terminal('LPAR'), NonTerminal('a'), Terminal('RPAR')], None, RuleOptions(False, False, None)))
  ,
  {<s : a LSQB a * RSQB>}:
    RSQB: (Shift, {<s : a LSQB a RSQB * >})
  ,
  {<s : a LSQB a RSQB * >}:
    $END: (Reduce, Rule(NonTerminal('s'), [NonTerminal('a'), Terminal('LSQB'), NonTerminal('a'), Terminal('RSQB')], None, RuleOptions(False, False, None)))
  ,
}
```
- According to [this](https://cs.stackexchange.com/a/41835) explanation, the reduction action for `Rule(NonTerminal('a'), [], None, RuleOptions(False, False, None))` should only be performed after receiving `RPAR`. But instead the said reduction action is assigned not only to `RPAR` but also to `LSQB` and `RSQB`. Which is exacly how SLR(1) would prepare its parsing table according to the explanation. I also manually worked out each state by hand on paper to verify the explanation and it checks out.

**Comment by evandrocoan** [comment]
Related to: Proper LALR parser #418

**Comment by denizetkar** [comment]
> That's very observant of you! This issue was recently fixed. Try the latest `master`.

@erezsh  I installed master branch and it is working as expected! You may close this issue (#478) at your will, either now or after the fixes become part of a new official release. Thank you for fixing the issue and keeping this project up-to-date.
