### ISSUE TITLE
How do you create a regular expression with a backslash?

### ISSUE THREAD

**Issue by enjoysmath** [lark-parser/lark#485]
I can't get the grammar below to parse a simple \\_ or anything else with a beginning backslash such as \\;, \\:, etc.  See MATHJAX_SYMS

```
from lark import Lark, InlineTransformer

class UserInputParser:      
   grammar = r'''
      ?start: mathjax_symbols
      mathjax_symbols: MATHJAX_SYMS            -> atomic_literal
      MATHJAX_SYMS: /[&%\^~_'`{}\\]|\[_,;:!{}\\&#%>|\$]/
   '''
   
   def __init__(self):
      self._parser = Lark(self.grammar, parser='earley')
      self._trans = UserInputTransformer()
      
   def parse_to_list(self, s:str) -> list:
      return self._trans.transform(self._parser.parse(s))
   

class UserInputTransformer(InlineTransformer):
   def __init__(self):
      pass
   
   def variable(self, token):
      return Variable(str(token))
   
   def atomic_literal(self, atom):
      return atom
   

if __name__ == '__main__':
   parser = UserInputParser()
   
   while True:
      s = input("s=")
      result = parser.parse_to_list(s)
      print(result)
```

**Comment by enjoysmath** [comment]
This is how it's done:
   grammar = r'''
      ?start: mathjax_symbols
      mathjax_symbols: MATHJAX_SYMS            -> atomic_literal
      MATHJAX_SYMS: /\\[_,;:!{}\\&#%>\|$]|[\\&%^~_'`{}]/
   '''

**Comment by erezsh** [comment]
I'm pasting this here too, for anyone else stumbling into this difficulty:

from lark import Lark
>>> p = Lark(r"""!start: "\\title" /\\shuttle/ """) 
>>> p.parse(r"\title\shuttle")
Tree(start, [Token(__ANON_0, '\\title'), Token(__ANON_1, '\\shuttle')])
