### ISSUE TITLE
How do you do negative lookahead?

### ISSUE THREAD

**Issue by enjoysmath** [lark-parser/lark#486]
`above: expr "\above" (FLOAT "pt")? expr`

I want the second expression to be `!(FLOAT "pt") expr` assuming ! means negative lookahead.

**Comment by evandrocoan** [comment]
Lark grammars are not regex. They just have some similar features. See some lark Style Cheats on: (Design a new Lark cheatsheet #195)

To use regexes, you need to use activate the regex envinroment with: `/regex/`

For example:
```antlr
above: expr "\above" REGEX_TOKEN expr
REGEX_TOKEN: /!(FLOAT "pt")?/
```

**Comment by enjoysmath** [comment]
What I want to do is:

above:  expr "\above" POINT_SIZE NOT_POINT_SIZE expr
POINT_SIZE: /FLOAT pt/
NOT_POINT_SIZE: /!POINT_SIZE/

That seems kind of ridiculous, being as \above is just one command and
there are 100's !

**Comment by evandrocoan** [comment]
`POINT_SIZE: /FLOAT pt/` you cannot use tokens inside regular expressions.

Please, create a minimal and reproducible example with a minimal grammar to reproduce the problem you are having: [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by enjoysmath** [comment]
> `POINT_SIZE: /FLOAT pt/` you cannot use tokens inside regular expressions.
> 
> Please, create a minimal and reproducible example with a minimal grammar to reproduce the problem you are having: [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

I am copying you from your previous post.  You used FLOAT inside of a regex.

**Comment by evandrocoan** [comment]
My bad.

**Comment by ctung** [comment]
Still not sure how to do a negative lookahead
lets say I want to parse "QN not followed by O"
the regex would normally be /QN(?!O)/



```
test = """
FQ
FQN
FQNOM
FQNNOM
"""

grammar = r"""
start:    ("\n"|word)*
word:     (PRE1|PRE2) SUFFIX? "\n"

PRE1:     /FQ(?!N)/
PRE2:     /FQN(?!O)/
SUFFIX:   "NOM"
"""

parser = Lark(grammar, parser='lalr')
tree = parser.parse(test)
print(tree.pretty())
```

gives me this error:
```
lark.exceptions.UnexpectedCharacters: No terminal defined for 'F' at line 4 col 1

FQNOM
^

Expecting: {'PRE2', 'NEWLINE', 'PRE1'}

Previous tokens: Token(NEWLINE, '\n')
```

I'm trying to matchL
```
FQ -> FQ
FQN -> FQN
FQNOM -> FQ, NOM
FQNNOM -> FQN, NOM
```
Help?
