### ISSUE TITLE
Lark parser cannot be pickle'd

### ISSUE THREAD

**Issue by denizetkar** [lark-parser/lark#492]
**Version:**
0e141ec8962cd875e90127bcb94ed1b7b25db5ad

**Problem:**
Lark objects cannot be pickle `dump`ed or `load`ed. Since using `serialize` and `deserialize` functions provided in lark library is not an option in certain cases, `Lark` objects need to be compatible with pickling methods. An example to such cases is spawning a child process using `multiprocessing` library where objects in the main process are serialized by `pickle` methods and copied over to the spawned child process (in the case of Windows).

**How to reproduce:**
```
import lark
import pickle

with open('some_lark_file') as f:
    parser = lark.Lark(f)

with open('lark.pickle', 'wb') as f:
    pickle.dump(parser, f)
```

- The error stack trace is as follows:
```
Traceback (most recent call last):
  File "<input>", line 8, in <module>
  File "D:\Program Files\Python37\lib\site-packages\lark_parser-0.8.0rc1-py3.7.egg\lark\lark.py", line 104, in __getattr__
    return self.options[name]
KeyError: '__getstate__'
```

**Suggested solution:**

- Add the following `__getstate__` and `__setstate__` functions to https://github.com/lark-parser/lark/blob/0e141ec8962cd875e90127bcb94ed1b7b25db5ad/lark/lark.py#L20 :
```
    def __getstate__(self):
        return self.options
    
    def __setstate__(self, options):
        self.__init__(options)
```

**Comment by erezsh** [comment]
Lark now officially supports pickling using the `save` and `load` methods.
