### ISSUE TITLE
Multi-threading bug in parsing

### ISSUE THREAD

**Issue by irwand** [lark-parser/lark#493]
I saw lark had some fixes with multi-threading, but there's still more multi-threading problem.
I have lark 0.7.8. I attach a python script that fails most of the time on my machine, although sometimes it succeeds.
[lark_fail_multithread_sample.zip](https://github.com/lark-parser/lark/files/3957838/lark_fail_multithread_sample.zip)

**Comment by erezsh** [comment]
Please provide a smaller example that still displays this error, as well as the actual error you're getting, and what Python version you're using.

**Comment by irwand** [comment]
Python 3.6.
Sorry, it's LARGE because of the input data, which is just repeated stuff. If the input data is not large I can't reproduce it.

The error varies, but this is one example:
```
$ python lark_fail_multithread.py
Traceback (most recent call last):
  File "D:\venv\irwand\lib\site-packages\lark\lexer.py", line 373, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "D:\venv\irwand\lib\site-packages\lark\lexer.py", line 174, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for '{' at line 1152 col 1

{
^

Expecting: {'RESERVED', '_LF'}

Previous tokens: Token(_LF, '\n')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lark_fail_multithread.py", line 1332, in <module>
    main()
  File "lark_fail_multithread.py", line 1328, in main
    f.result()
  File "C:\Python36\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Python36\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Python36\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "lark_fail_multithread.py", line 1320, in _async_read
    p = parser.parse(_CONTENT)
  File "D:\venv\irwand\lib\site-packages\lark\lark.py", line 311, in parse
    return self.parser.parse(text, start=start)
  File "D:\venv\irwand\lib\site-packages\lark\parser_frontends.py", line 89, in parse
    return self._parse(token_stream, start, *[sps] if sps is not NotImplemented else [])
  File "D:\venv\irwand\lib\site-packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "D:\venv\irwand\lib\site-packages\lark\parsers\lalr_parser.py", line 36, in parse
    return self.parser.parse(*args)
  File "D:\venv\irwand\lib\site-packages\lark\parsers\lalr_parser.py", line 84, in parse
    for token in stream:
  File "D:\venv\irwand\lib\site-packages\lark\lexer.py", line 387, in lex
    raise UnexpectedToken(t, e.allowed, state=e.state)
lark.exceptions.UnexpectedToken: Unexpected token Token(QUOTED_CONTENT, '{\n
path ') at line 1152, column 1.
Expected one of:
        * RESERVED
        * _LF
```

**Comment by irwand** [comment]
Note that the program to reproduce it is very small, it's at the bottom of the attached sample script. What's large is merely the input data to be parsed.

**Comment by evandrocoan** [comment]
And the error only happens when you run multithreading? If you application is single threaded no errors happen if the input program?

**Comment by irwand** [comment]
That's correct.. If you change the sample program so it runs once, it passes just fine.
Even as it is, sometimes it passes on my machine.
The sample program is standalone, you should be able to run it pretty easily.

**Comment by irwand** [comment]
Hmm.. I might have misunderstood the usage.
If on every thread I first create Lark(), then call parse() on it, then there's no multi-threading issue.
The way I was doing it was I created Lark() with the grammar, then call parse on that instance from multiple threads.

Is there a way for me to parse the grammar once, then create a parsing state with that grammar and parse() on each thread ?

**Comment by erezsh** [comment]
> If on every thread I first create Lark(), then call parse() on it, then there's no multi-threading issue.

Yes, but that's not really considered multi-threading :)

I'll look into your error.

**Comment by erezsh** [comment]
Looks like I fixed it. Checkout the latest `master` branch and give it a try.

Thanks for your bug report!

**Comment by irwand** [comment]
Awesome! yeah, looks like it's fixed! Thank you!

**Comment by irwand** [comment]
Fixed in less than 24 hours! Thanks again!

**Comment by erezsh** [comment]
Happy to help :)

Keep reporting bugs if you find any!
