### ISSUE TITLE
Raw graphviz dot output

### ISSUE THREAD

**Issue by felixvuo** [lark-parser/lark#498]
I think it would be nice to have the option to dump a raw graphviz DOT file instead of the sppf.png for a few reasons:

* the file size is a lot smaller
* it's nice to be able to "do things" with the resulting tree in its structured form, rather than navigate the rendered bitmap
* it's only one extra (or no extra) line and could be optional, e.g. if you've turned on "debug" mode.

Any thoughts?

**Comment by erezsh** [comment]
I support the idea
