### ISSUE TITLE
Issues with nearley on Python-3-only systems

### ISSUE THREAD

**Issue by wiene** [lark-parser/lark#501]
I am trying to use `lark` on a Python-3-only system. During these tests I stumbled across the following issue: `lark/tools/nearley.py` depends on [`js2py`](https://github.com/PiotrDabkowski/js2py) and I am not able to make `js2py` work with Python 3 (I get a unit test failure, see https://github.com/PiotrDabkowski/Js2Py/issues/185). The `js2py` author [announced Python 3 support](https://github.com/PiotrDabkowski/Js2Py/issues/98#issuecomment-350860575) some time ago but the issue seems to persist.

Given the imminent end-of-life of Python 2 and the ongoing removal of Python 2 from Linux distributions (see e. g. the [Debian plans](https://wiki.debian.org/Python/2Removal) and the [Fedora schedule](https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3)) what are your plans for dealing with the mentioned `js2py` dependence?

**Comment by erezsh** [comment]
From the `js2py` page:

> Supports Python 2 & 3.

So you should hold them to their claim.

> Given the imminent end-of-life of Python 2 

Python2 will not stop being usable in the foreseeable future. It may not arrive on linux by default, but I'm guessing you can still `apt install` or `yum install` it for the next decade.

However, if you have a suggestion for a better replacement to js2py, I'm willing to consider it.

Either way, it won't affect Lark, as js2py is only an optional dependency and isn't required for anything but Nearley conversions, which honestly aren't too difficult to do by hand.

**Comment by wiene** [comment]
> Python2 will not stop being usable in the foreseeable future. It may not arrive on linux by default, but I'm guessing you can still `apt install` or `yum install` it for the next decade.

Reading https://lists.debian.org/debian-python/2019/11/msg00038.html I am not so sure whether this will be the case but we will see.

> However, if you have a suggestion for a better replacement to js2py, I'm willing to consider it.

Unfortunately I do not have a good suggestion. That is why I was asking.

> Either way, it won't affect Lark, as js2py is only an optional dependency and isn't required for anything but Nearley conversions, which honestly aren't too difficult to do by hand.

Only now I realise that since the last release (0.7.8) the fact that this dependency is optional is also [reflected in the test suite](https://github.com/lark-parser/lark/commit/f3714a572f047c5857a2b3ab8d8a161e142f20bf).
