### ISSUE TITLE
Error when using pycharm debugger

### ISSUE THREAD

**Issue by DavidVenhoff** [lark-parser/lark#503]
When using the pycharm debugger on a lark options object the debugger is unable to show a list of its attributes and instead outputs "unable to display children...".
It seems like __getattr__ of LarkOptions is not implement properly:

`def __getattr__(self, name):`
    `return self.options[name]`
when somebody calls hasattr which will internally call __getattr__ with a name that is not in self.options the __getattr__ method will fail with a KeyError. However, hasattr requires __getattr__ to fail with an AttributeError if the name does not exist in order to return False.
A correct implementation would look like this:
`def __getattr__(self, name):`
        `try:`
           ` return self.options[name]`
       ` except KeyError as e:`
           ` raise AttributeError from e`

PS: Sorry for the formatting ^^

**Comment by erezsh** [comment]
Sounds good. Submit a pull request.

**Comment by erezsh** [comment]
Hope that works
