### ISSUE TITLE
More permissive license for standalone parser?

### ISSUE THREAD

**Issue by j-ulrich** [lark-parser/lark#507]
The standalone parser is licensed under GPLv2. This means it can only be used in projects that also use the GPL due to the copyleft.

After reading #247, I got the impression that the main intention is to prevent that commercial projects use the standalone parser without mentioning. However, this can also be achieved with a more permissive license like the [Apache License](https://choosealicense.com/licenses/apache-2.0/).

So how about switching the license to a more permissive license or maybe dual-licensing the standalone parser under GPL and a more permissive license?

**Comment by erezsh** [comment]
The Apache license allows commercial use, and doesn't require code exposure, so I don't see how it is an alternative.

A dual-license might work. But let's back up for a second. What's wrong with GPL?

**Comment by j-ulrich** [comment]
> The Apache license allows commercial use, and doesn't require code exposure

Yeah. Okay. After reading #247, I got the impression that this is a use can you want to support. Of course, if you don't want to allow usage of the standalone parser in closed source projects, then the Apache license is not an alternative.

> What are you planning to use it for?

I am planning to use it in a tool I will publish soon. And I was considering to use the MIT license. However, using the GPL is also an option for me.

**Comment by erezsh** [comment]
Okay. I will consider moving it to a dual license, if you can come up with a good suggestion that still enforces its main spirit.

**Comment by j-ulrich** [comment]
Well, there is also the [Mozilla Public License (MPL)](https://www.mozilla.org/en-US/MPL/2.0/). It allows combining closed source code with open source (MPL licensed) code to a "Larger Work" as long as the licensee is informed and able to obtain the open source part and use it under the MPL license.

So it would allow the standalone parser to be used in closed source proprietary projects as long as the project states that the standalone parser is used and makes the source code of the standalone parser available under the terms of the MPL.

I'm not sure if this is what you mean with the "main spirit".

**Comment by erezsh** [comment]
So, the standalone parser provides several abilities, some of which are:

- Smaller code and more efficient than including and loading Lark in its entirety

- No need to mention Lark, easier to "hide" the dependency

- No need to include the original grammar. Instead the grammar is obfuscated.

It's the last two I'm particularly concerned about. I don't want a commercial company to profit from Lark without at least contributing back to its popularity, and providing *some* value to its ecosystem.

**Comment by j-ulrich** [comment]
>  I don't want a commercial company to profit from Lark without at least contributing back to its popularity

This is covered by the MPL:
```
3.3. Distribution of a Larger Work

You may create and distribute a Larger Work under terms of Your choice,
provided that You also comply with the requirements of this License for
the Covered Software.
```

The standalone parser would be the "Covered Software" in this case. And "the requirements of this License" then include:
```
3.1. Distribution of Source Form

All distribution of Covered Software in Source Code Form, including any
Modifications that You create or to which You contribute, must be under
the terms of this License. You must inform recipients that the Source
Code Form of the Covered Software is governed by the terms of this
License, and how they can obtain a copy of this License. You may not
attempt to alter or restrict the recipients' rights in the Source Code
Form.
```
and
```
3.2. Distribution of Executable Form

If You distribute Covered Software in Executable Form then:

(a) such Covered Software must also be made available in Source Code
    Form, as described in Section 3.1, and You must inform recipients of
    the Executable Form how they can obtain a copy of such Source Code
    Form [...]
```
as well as:

```
3.4. Notices

You may not remove or alter the substance of any license notices
(including copyright notices, patent notices, disclaimers of warranty,
or limitations of liability) contained within the Source Code Form of
the Covered Software, except that You may alter any license notices to
the extent required to remedy known factual inaccuracies.
```

So a closed source proprietary project using the standalone parser under the MPL would need to "inform recipients" that the standalone parser is cover by the MPL and where to obtain its source code. And that source code would need to contain the original unaltered copyright notices.

So the main difference to the GPL would be that a project using the standalone parser would not need to be under the GPL as well.
Mentioning the standalone parser and publishing its source code is required in both cases.

So if you want to open up usage of the standalone parser in closed source proprietary projects, you could switch to the MPL (or dual-license). If not, then you can just close this issue. :-)

**Comment by erezsh** [comment]
That's interesting, thanks for informing me. Let me give it some thought.

**Comment by erezsh** [comment]
I decided to re-license the standalone parser (tool and generated code) as MPL.

Thanks again for the informative discussion.

**Comment by asmeurer** [comment]
I don't understand why you wouldn't use a license that is at least as permissive as the Lark license itself for this (MIT). You aren't harming "corporate users", you are harming other open source projects that can't include Lark parsers because they are incompatible with their own license.

**Comment by erezsh** [comment]
@asmeurer I'm not harming anyone. Anyone and everyone can use Lark and get all the features of the standalone parser and more, by adding Lark as a dependency. The load times are also equivalent, if you use the new `cache` feature.

In the unusual case that it's not enough, open source authors can spend a minute to ask my permission, which I've yet to refuse.

As you can see, there was a long discussion about this exact subject. If you want to convince me otherwise, it would be more effective to refute the points that brought me to the decision, or to bring up new ones.

**Comment by j-ulrich** [comment]
> you are harming other open source projects that can't include Lark parsers because they are incompatible with their own license.

Which license are we talking about here? GPL?
I guess this would then require dual-licensing of the standalone parser under MPL and (L)GPL.
See https://www.mozilla.org/en-US/MPL/2.0/FAQ/#mpl-and-lgpl

**Comment by asmeurer** [comment]
There are issues with the GPL, but I was actually referring to projects that use license like BSD or MIT, and don't want to make their license more restrictive.

**Comment by j-ulrich** [comment]
Well, depending on what the project is, the restrictions are not very high actually.

In case of an executable/tool, it merely means that the source code of the standalone parser needs to be made available under the MPL and that the project needs to "inform recipients of the Executable Form how they can obtain a copy of such Source Code Form". So IMO this boils down to adding a note like "This project uses a standalone parser of Lark. It's source code is available at <insert link to source code here> under MPL license (<insert MPL license link here>)" in a prominent place.

In case of a library/package (or something else on which a "Larger Work" is build up on), it means that the downstream users need to do the same. Meaning: make the source code of the standalone parser available and "inform recipients of the Executable Form how they can obtain a copy of such Source Code Form".

And as erezsh already said:
> Anyone and everyone can use Lark and get all the features of the standalone parser and more, by adding Lark as a dependency.

And here "use Lark" means "use Lark under MIT license".

And:
> In the unusual case that it's not enough, open source authors can spend a minute to ask my permission, which I've yet to refuse.
