### ISSUE TITLE
Add [pep8] section too setup.cfg and/or fix pep8 errors

### ISSUE THREAD

**Issue by jisaacstone** [lark-parser/lark#509]
Currently flake8 shows the following errors on master branch:

```
 682 E501
 144 E302
 124 E303
  74 E201
  71 E231
  62 E741
  62 E202
  60 E225
  51 E203
  47 F401
  38 E251
  30 E265
  26 E261
  24 E301
  22 F821
  21 E402
  20 E266
  18 E306
  18 E128
  17 E305
  16 F841
  15 F405
  13 E211
  11 W391
   9 E731
   9 E701
   8 E127
   7 E228
   4 F811
   4 E401
   3 W292
   3 E722
   3 E262
   3 E117
   2 E721
   2 E713
   2 E711
   2 E129
   2 E122
   2 E111
   1 E712
   1 E271
   1 E221
   1 E124
```
-----

As I have integrated flak8 linter into my editor these lines all show up as errors. There are 3 options to fix this up:

* add a `[pep8]` section to the `setup.cfg` as described [here](https://pep8.readthedocs.io/en/release-1.7.x/intro.html#configuration)

simply adding `max-line-length = 120` for example cuts the number of errors in half

* fix the errors

Probably don't want to ignore everything. Any directives you want to comply with in future can be fixed up. For example F401 (unused import) or F811 (redefinition of unused variable) can often detect bugs.

* add `# noqa: E***` comments to the code

If we want to not introduce any new errors of this type but don't want to bother fixing up the code right at this time.

-----

I'm happy to tackle the above, but will only do so if it is desired by the maintainers. Once done however should also added a lint step to travis so we don't introduce new pep8 bugs in future.

**Comment by erezsh** [comment]
>add a [pep8] section to the setup.cfg

That sounds good. I'll accept such a PR.

> fix the errors

Can you give an example (filename + line number) where there is an actual problem with the source code? (i.e. not a misunderstanding by the analyzer)

> add # noqa: E*** comments to the code

I am strongly against that.

> added a lint step to travis 

Let's revisit that afterwards.

**Comment by jisaacstone** [comment]
Well that depends on your definition of "actual problem"

pep8 is the standard python style guide, so all the problems identified are in conflict with that standard. However not everyone agrees with the standard, and there is no reason for me to ask other people to confirm.

You can look at the list of [Error Codes](https://pep8.readthedocs.io/en/release-1.7.x/intro.html#error-codes) to make up your own mind, but I don't see any reason to strictly enforce most of them if you don't feel like it. Some however are good to keep because they may help find bugs (E101: mixed tabs and spaces is a good example)

https://github.com/lark-parser/lark/blob/master/lark/lexer.py#L306

This is a potential bug that falke8 identified (bare except will catch things like `keyboardinterrupt` and `sigterm`. except Exception is almost always what you want)

or perhaps a better example is here

https://github.com/lark-parser/lark/blob/master/examples/standalone/json_parser.py#L1804

`os.path` is used, but has never been imported. Likely the example json_parser doesn't actually work and will error at this point.

I have an opinionated `setup.cfg` that only keeps ~20 of the checks and cuts the number of reported errors to 226. Perhaps that is still too many and you'd prefer to cut down the error list further.

Here is an example of the output

```
./lark/tree.py:36:9: E741 ambiguous variable name 'l'
./lark/load_grammar.py:526:161: E501 line too long (165 > 160 characters)
./lark/lark.py:199:36: E711 comparison to None should be 'if cond is None:'
./lark/utils.py:141:1: E402 module level import not at top of file
./lark/utils.py:168:1: F811 redefinition of unused 'sys' from line 1
./lark/lexer.py:306:13: E722 do not use bare 'except'
./lark/reconstruct.py:94:50: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
./lark/parsers/earley_forest.py:73:33: E701 multiple statements on one line (colon)
./lark/parsers/earley_forest.py:82:47: E721 do not compare types, use 'isinstance()'
./lark/parsers/earley_forest.py:157:5: E704 multiple statements on one line (def)
./lark/parsers/lalr_analysis.py:40:9: F841 local variable 'rules' is assigned to but never used
./lark/parsers/lalr_analysis.py:205:24: E713 test for membership should be 'not in'
./tests/test_trees.py:118:13: E731 do not assign a lambda expression, use a def
./examples/qscintilla_json.py:28:20: F405 'QColor' may be undefined, or defined from star imports: PyQt5.Qt
./examples/standalone/json_parser.py:154:19: F821 undefined name '_serialize'
./examples/standalone/json_parser.py:1836:3: E111 indentation is not a multiple of four
```

**Comment by erezsh** [comment]
Thanks, these were good examples. They are now fixed and pushed.

I went through some of the output your wrote here (though some of the lines are different by now). Most of these are not interesting or helpful. Some of the "violations" in the code are necessary, and some are due to an intentional choice of style by either me or one of the other contributors.

I wouldn't mind 1000 warnings that find real potential bugs, but I'm not interested in "this should be two lines instead of one" or "You have to do `is False`" (which is actually wrong).

**Comment by evandrocoan** [comment]
I am not sure it it is related, but I used codacy to catch few problems in my project: https://app.codacy.com/manual/evandrocoan/DebugTools/issues/index

![image](https://user-images.githubusercontent.com/5332158/72207317-da365300-3476-11ea-8b8d-e039643b468b.png)


I had setup it with Continuous Integration: https://github.com/evandrocoan/debugtools/blob/ac121c1e09f85f0f7fae6bc40f4c028026cd6676/appveyor.yml#L97

And put a badge on the README.md
![image](https://user-images.githubusercontent.com/5332158/72207365-3305eb80-3477-11ea-9d14-4939c86febcf.png)

**Comment by jisaacstone** [comment]
Yes, pep8 is mostly about standard python coding style. It is absolutely not required for functional code, though I think it helps in maintainability and readability I see no reason to require you to enforce. I can configure my local checkers to skip the stylistic ones. I'd like to work on  #237 actually

**Comment by erezsh** [comment]
I still see the value in adding a linter, just without all the style warnings. But isn't pylint better at that?

Anyway, if you've lost interest in continuing, that's fine.

#237 should practically work, I think. It just needs rebasing and some testing. And if you can add Earley support, that would be super.

**Comment by jisaacstone** [comment]
Ah so another strategy would be to use a `select =` directive, so you can choose only to lint for what you are interested in. Using `ignore =` to cut out the style errors had 60+ entries and I was not a fan. Can start with a small subset of checks using select and add more if you feel. I can PR this if you like but recommend also to have integration into the CI tool you are using

**Comment by erezsh** [comment]
Closing, but a PR is still welcome.
