### ISSUE TITLE
Parents of node in ParseTree

### ISSUE THREAD

**Issue by JellePiepenbrock** [lark-parser/lark#510]
I have been trying out Lark. Looks very good, keep up the good work. 

I was wondering whether it was possible for the Tree objects to explicitly keep their parent nodes as an attribute. After parsing, I would like to be able to perform local operations on the parse tree.

**Comment by evandrocoan** [comment]
I did few changes as this in my fork: https://github.com/evandrocoan/pushdownparser/blob/4f2529693222873bd482f1aa24a9c56178d87349/source/pushdown/visitors.py#L195

You could create your own methods based on that class.

**Comment by JellePiepenbrock** [comment]
Using the Visitor class got me what I wanted, thank you!

**Comment by erezsh** [comment]
Tree objects sometimes share parents to reduce memory use, so you can't always have a `parent` attribute. But that shouldn't be a problem with LALR, at least at the moment.

However, your solution isn't efficient, as `iter_subtrees` returns **all subtrees** recursively, and the only reason it's correct is because it maintains the same order as `Visitor`.

The right way to do it is:

```python
class Parent(Visitor):
    def visit(self, tree):
        for subtree in tree.children:
            assert not hasattr(subtree, 'parent')
            subtree.parent = tree
```

**Comment by erezsh** [comment]
Correction: Your solution is incorrect!

You are assigning an ancestor, not a parent.

@evandrocoan that does for you too.

**Comment by JellePiepenbrock** [comment]
Yes, I just noticed this downstream. However, your code snippet causes the following error: 

> AttributeError: 'Token' object has no attribute 'parent'

**Comment by erezsh** [comment]
Right, sorry about that. Here's a version that should work correctly (though you probably already figured it out yourself):

```python
class Parent(Visitor):
    def visit(self, tree):
        for subtree in tree.children:
            if isinstance(subtree, Tree):
                assert not hasattr(subtree, 'parent')
                subtree.parent = tree
```

**Comment by JellePiepenbrock** [comment]
Yes, I already fixed it, but I just wanted to let you know. Thank you for the responsiveness in general. Great library!
