### ISSUE TITLE
Small grammar-syntax improvements

### ISSUE THREAD

**Issue by MegaIng** [lark-parser/lark#513]
Two things:

- The current syntax allows the following `"A".       ."Z"` as string range syntax. While not inherently bad, this might be confusing.

- I think the following should parse:
```
start: A 
     // a small explanation of B
     | B
```
To do this, one would have to change the syntax of newlines to include lines that only contain comments:

`(\r?\n)+\s*` to `(\s*(//[^\n]*)?\r?\n)+\s*`

This would have the added benefit of making huge comment chunks (like at the beginning of `python3.lark`) be lexed as a single Token which can be handled by the parser in a single step. which should speed up parsing.

**Comment by erezsh** [comment]
Fixed the `. .` issue.

Also merged PR #482 which allows comments in rule definitions.

It's a simpler change, and I don't think lark grammars are big enough to warrant such optimizations.
