### ISSUE TITLE
repr of abstract syntax tree is not eval-able

### ISSUE THREAD

**Issue by Grumblesaur** [lark-parser/lark#516]
Hi there,

I've been using lark to parse a small expression language that I'm going to be using with a chatbot. To make variables persistent across restarts and server outages, I have been writing the `repr` of a `dict` of them to a file. This works for simple values like `int`s and `str`s, and even collections like `dict`s and lists.

Now that I'm trying to implement functions, I've been trying to save the `repr` of the abstract syntax tree generated for the function's code, but it seems that the `repr` calls for `lark.Tree` and `lark.Token` can't be `eval`'d.

Could `Tree` and `Token` have their `__repr__` definitions changed to use the `repr` of their components instead of just the default formatting to `str` so that `eval` successfully returns a `Tree` object?

**Comment by erezsh** [comment]
Yes, it's possible to make tree repr-able. But you will lose the metadata. Same for token. You will lose the metadata (line, columns, etc.).

I have no intention of showing all these spurious attributes to unsuspecting users who are trying to debug their code.

What you *should* be doing, is use `pickle` to save and restore these objects. That works already, and doesn't require any fix to the code.

Or you can create your own functions for serializing and deserializing that saves and restores these instances to whatever format you like.

**Comment by Grumblesaur** [comment]
Ah -- I hadn't considered that as I haven't been using the metadata. I'll use `pickle` or something else instead.

Thanks for the quick response!
