### ISSUE TITLE
Help with parsing LDAP CNs

### ISSUE THREAD

**Issue by gerases** [lark-parser/lark#518]
Hello, I'm kind of stuck with the grammar to parse something like this:

```
st = "CN=Doe\\, Jane,OU=U1,OU=U2,OU=User_Accounts,DC=domain,DC=com"
```

Here's my grammar:

```
  cn_parser = Lark(r"""
      cn: (cn_spec)*

      cn_spec: "CN=" entry (COMMA ("OU="|"DC=") entry)*

      entry: /[ 0-9a-zA-Z_-]+/ | escaped_chars
      escaped_chars: escaped_comma
      escaped_comma: "\\" COMMA
      COMMA: ","
  """, start='cn_spec', ambiguity='explicit')
```

The problem is handling the escaped comma. No matter what I do, I get:

```
lark.exceptions.UnexpectedCharacters: No terminal defined for '\' at line 1 col 7

CN=Doe\, Jane,OU=U1,OU=U2,OU=User_Accounts,DC=
      ^

Expecting: {'COMMA'}
```

Any ideas?

**Comment by jacovig** [comment]
Hi, it's easy. You should change rule 'entry' to:

entry: /( [ 0-9a-zA-Z_-] | (\\,) )+/

and can delete eschaped_chars and escaped_comma.

Notice that  the scaped comma is inside the brackets, joining the set of letters, numbers and spaces

Best.

**Comment by gerases** [comment]
Hi,

I don't think `(\,)` is right because I'm looking for a literal `\` followed by a literal `,` So the `\` needs itself needs to be escaped. 

Anyway, the parser returns an error against the `D` in `Doe`.

Thank you,
  Sergei

**Comment by jacovig** [comment]
Oh, I'm sorry, my bad. I meant (\\,). This code works for me:

grammar = r"""
      cn: (cn_spec)*

      cn_spec: "CN=" entry (COMMA ("OU="|"DC=") entry)*

      entry: /([ 0-9a-zA-Z_-]|(\\,))+/
      COMMA: ","
      
  """

cn_parser = Lark(grammar, start='cn_spec', ambiguity='explicit')


st = "CN=Doe\, Jane,OU=U1,OU=U2,OU=User_Accounts,DC=domain,DC=com"
results = cn_parser.parse(st)
print(results)

**Comment by jacovig** [comment]
Sorry again. It seems that it's the editor fault. When I write two backslashes the editor changes them to only one?. But the pasted code is correct.

**Comment by gerases** [comment]
Cool, it does work! I'm now curious why the original version didn't work? Do you know? Thanks for the tip big time though :)

**Comment by jacovig** [comment]
Let's see.
Your rule was:

entry: /[ 0-9a-zA-Z_-]+/ | escaped_chars

There are two different things:
- Doe matches the left part, the one inside //, i.e. the regular
expression. After that, there must be a COMMA, according to the cn_spec
rule:

cn_spec: "CN=" entry (COMMA ("OU="|"DC=") entry)*

Now the parser is not looking for an 'entry', so the escaped comma is not
an option now.

The escaped comma is part of the text, and so is a valid caracter, exactly
as much as a or D, so you have to include it BEFORE the +. You could
consider adding the backlash comma inside the squared brackets, but as it
is represented by two characters you can't. So you join it with |. Now you
have [ 0-9a-zA-Z_-]|(\\,). Finally, you put brackets around this, just to
put a +.

By the way, you could simplify it a bit, writing /([ 0-9a-zA-Z_-]|\\,)+/.
Notice that it is not the same if you put the + outside the regular
expressión. That way, each caracter is recognised as a token, which you
don´t want, I guess.

Hope this solves your doubts.

Best.

**Comment by gerases** [comment]
Thanks for the detailed explanation. What I don't understand is:

> Now the parser is not looking for an 'entry', so the escaped comma is not
> an option now.

Why was it not looking at `entry`, which could be the alphanumeric OR an escaped comma?

```
entry: /[ 0-9a-zA-Z_-]+/ | escaped_chars
...
```

That's the crux of why I don't understand it.

**Comment by jacovig** [comment]
Exactly, that is the point. An entry is an alphanumeric OR an escaped
comma. Notice the OR. Once is has found the alphanumeric, is has a valid
entry. It does NOT try the right part of the OR condition, because the
condition is met and it has a match for an entry (Doe). So it proceeds to
try to find the next element in the cn_spec rule:

cn_spec: "CN=" entry (COMMA ("OU="|"DC=") entry)*

which is the COMMA part.

**Comment by gerases** [comment]
Ah, I see, thank you @jacovig for explaining this to me! I think I'm good now.

**Comment by gerases** [comment]
@jacovig, can you clarify this:

> By the way, you could simplify it a bit, writing /([ 0-9a-zA-Z_-]|\\,)+/.
> Notice that it is not the same if you put the + outside the regular
> expressión. That way, each caracter is recognised as a token, which you
> don´t want, I guess.

I think the `+` should be outside the regex?

**Comment by jacovig** [comment]
Try both options and look carefully at the generated tree. If the + is
inside the regex, all the expression is recognised as a token (Doe\, Jane
in this case).

If the + is outside the regex, each character is recognised as a token. So
you have D, o, e, etc. as different tokens, which I think is not what you
want.

As you can see, the token starts at the left / and finishes at the right /.
So if the + is inside, an entry is a token, which is a collection of
alphanumeric of comma escaped characters.

If the + is outside, an entry is a collection of tokens, each of which is
composed by exactly ONE alphanumeric or comma escaped.

**Comment by gerases** [comment]
Got it. I need the `+` inside the `/`. Indeed,  I don't want them as indiv tokens. Also, when the plus is inside, it's part of the regex language. If outside, it's Lark's language.

Awesome, it's working as expected now. The final spec is this:

`cn_spec: "CN=" entry (COMMA ("CN="|"OU="|"DC=") entry)*`

I wonder if that can be simplified because note "CN=" is mentioned there twice because it's valid syntax to have several CNs in one line (turns out). So ideally, I would like it to be something like:

`cn_spec: `("CN="|"OU="|"DC=") entry)*` but because of the comma, I can't do that.

**Comment by jacovig** [comment]
Keep in mind that cn_spec: "CN=" entry (COMMA ("CN="|"OU="|"DC=") entry)*
has one subtle implication. The first 'element' can only be a CN, it's
illegal to have a DC or an OU at the leftmost position. If that is not what
you mean, and any element could do, you could write:

cn_spec: cn_spec_element (COMMA cn_spec_element)*
cn_spec_element: ("CN="|"OU="|"DC=") entry

This way you don't repeat "CN=" but repeat cn_spec_element, but I think
it's the best solucion. In fact, it's the pattern I use. But the decision
is up to you.

**Comment by gerases** [comment]
Ah, that's beautiful. I'll shamelessly adopt your approach. Yes, any entry can begin that string. So, this is the most flexible grammar. Thanks again @jacovig

**Comment by jacovig** [comment]
Glad to help.

**Comment by jacovig** [comment]
Hi @gerases.

This is my final approach. I realised you couldn't identify which tag the
text comes from, so I'd like to propose this grammar:

grammar = r"""

      cn: (cn_spec)*

      cn_spec: _cn_spec_element (COMMA _cn_spec_element)*
      _cn_spec_element: tag "=" entry

      entry: /([ 0-9a-zA-Z_-]|\\,)+/
      tag: "CN" -> cn
        | "OU"  -> ou
        | "DC"  -> dc

      COMMA: ","

  """

This way you have specific Tokens with the name cn, ou or dc, that
help you solve this problem.


HTH

**Comment by gerases** [comment]
I see. It's an improvement indeed since now cn, ou, and dc will appear in the tree if I needed to use them. Thanks, @jacovig!
