### ISSUE TITLE
`Interpreter` and `@v_args` do not mix

### ISSUE THREAD

**Issue by iconmaster5326** [lark-parser/lark#520]
I have the following bit of code to make my own `Interpreter` on a tree:

```python
@lark.v_args(inline=True)
class EvalAST(lark.visitors.Interpreter):
    def __init__(self, context):
        self.context = context

    ...
```

However, when I construct an instance of `EvalAST`, I get the following exception:

```
  File "/usr/local/lib/python3.6/dist-packages/lark/visitors.py", line 287, in f
    return _f(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'context'
```

Removing the use of `@v_args` fixes the issue... At the cost of not being able to use `@v_args`. It seems that it's not treating my custom `__init__` correctly, failing to forward arguments or something.

I am using Lark version 0.8.1.

**Comment by MegaIng** [comment]
You can not use an inline `Interpreter`. That does not make sense: The Interpreter functions take the `tree` as argument, not the children like the `Transformer`. You can just use [multiple assignment](https://treyhunner.com/2018/03/tuple-unpacking-improves-python-code-readability/) to get the same effect.

**Comment by erezsh** [comment]
It's true that v_args wasn't implemented for Interpreter.

It is now, pushed to `master`. Let me know if that solves your issue.

**Comment by iconmaster5326** [comment]
Adding features for me is incredibly kind of you! I'll test it out and get back to you. Thank you so much!

**Comment by iconmaster5326** [comment]
Just tested it out now, and it appears to work. Thanks again!

**Comment by erezsh** [comment]
My rule of thumb is that for every issue that's reported, there are users who faced the same problem but decided to just give up, or will face it in the future. So if the request is reasonable, I try to accommodate my users where I can.

Anyway, happy to help :)
