### ISSUE TITLE
PEP 561 typed package

### ISSUE THREAD

**Issue by KmolYuan** [lark-parser/lark#523]
Hello! Do you want Lark-parser to have type annotations?
A typed API will helpful to developing more convenience. (like PyCharm)
There will be some generic types instead of `Any` in the function signatures.

Some "public" names can be supported by **stub files** (`pyi`) that will not change your source code directly.
And MyPy checker will be able to executed in latest Python to ignore syntax and module compatibility.

**Comment by erezsh** [comment]
If you are suggesting to send a PR to add pyi files to Lark, then I'm all for it.
