### ISSUE TITLE
lark.parse() does not always return a Tree object

### ISSUE THREAD

**Issue by velezsarain** [lark-parser/lark#525]
I'm opening an issue because the documentation does not make clear if this behaviour is intended or not.

I'm currently using lark to parse and transform boolean search queries to feed them into another application later in the execution process.

My grammar is as follows:

```
?exp: term (OR term)*
?term: factor (AND factor)*
?factor: KEYWORD | "(" exp ")"
KEYWORD: ESCAPED_STRING
AND: "&"
OR: "|"
%ignore " "
%import common.ESCAPED_STRING
```
The grammar accepts these two inputs, that I would want to transform later:
```
"x y z"
"x" & "y" & "z"
```
The problem comes when I want to transform the resulting tree. I have a transformer that uses the visit_tokens property to transform KEYWORD terminals, however, because the first input can be reduced into a single KEYWORD terminal, the parse() method returns a `lark.lexer.Token` object instead of a `lark.tree.Tree` object.
This causes the transform method to fail as it expects a Tree as parameter, with the following error message: `'Token' object has no attribute 'children'`

Is this intended?

**Comment by MegaIng** [comment]
I assume you are creating the parser with `start=exp`? Then the behavior is intended, but debatable. The 'problem' is that your entry point, `exp`, has a question mark in front of it, making it invisible if there is exactly one child. If this one child happens to be a `Token`, that token is returned. 

I would suggest either dealing with that case directly or just having a `start` rule as alternative entry point that does nothing but wrap `exp`

**Comment by erezsh** [comment]
Please include a minimal example that reproduces your error, including the transformer and the initialization code.

**Comment by velezsarain** [comment]
It is as Melang says, I do have exp as the entry point of the parser: `parser = Lark(grammar, start='exp')`

This is my transformer (with rules removed for brevity):

```
class QueryTransformer(Transformer):
    def KEYWORD(self, arg):
        return [arg[1:-1].split()]

    def AND(self, arg):
        raise Discard

    def OR(self, arg):
        raise Discard

... etc
```

The error happens when I try this:

```
query_tree = self.parser.parse(query)
return QueryTransformer(visit_tokens=True).transform(query_tree)
```

Currently I'm dealing with the case directly by testing if the returned value is a Token. Using a rule to wrap `?exp ` makes it so `parse()` always returns a Tree.

I would suggest adding this information to the documentation to prevent future confusion.

**Comment by erezsh** [comment]
Well, I think that ...

(answer removed for brevity)

**Comment by velezsarain** [comment]
Closing this because the issue has been resolved.
