### ISSUE TITLE
Transformer Multiplication is not commutative

### ISSUE THREAD

**Issue by JustKiddingCode** [lark-parser/lark#531]
Hi,

I split up my transformers to make my app more easily understandable/explainable, 
but now saw that the Transformer multiplication is not commutative.
Consider the example below:

```

from lark import Lark, Transformer, Tree, __version__

print(__version__)

grammar = """
a : b
b : LETTER
LETTER: /\w+/
"""

class TransformerA(Transformer):
    def a(self, args):
        if not isinstance(args[0], Tree):
            return args[0]
        return Tree("a", args)

class TransformerB(Transformer):
    def b(self, args):
        if not isinstance(args[0], Tree):
            return args[0]
        return Tree("b", args)


class TransformerC(Transformer):
    def a(self, args):
        if not isinstance(args[0], Tree):
            return args[0]
        return Tree("a", args)
    def b(self, args):
        if not isinstance(args[0], Tree):
            return args[0]
        return Tree("b", args)

lark_handle = Lark(grammar, start="a")
ast = lark_handle.parse("hello")

composed = TransformerA() * TransformerB()
composed_invers = TransformerB() * TransformerA()

ast_composed = composed.transform(ast)
ast_composed_invers = composed_invers.transform(ast)
ast_combined = TransformerC().transform(ast)

print(ast_composed)
print(ast_composed_invers)
print(ast_combined)
```

Will give

```
0.7.8
Tree(a, [Token(LETTER, 'hello')])
hello
hello
```
and not like expected three times 'hello'

**Comment by erezsh** [comment]
Yes, multiplication is usually not commutative. It isn't for matrices, functions, etc.

The fact that it is commutative for numbers is the exception, not the rule.

**Comment by JustKiddingCode** [comment]
That really isn't the point.
The point is that this is (at least to me) unexpected behavior, thus this issue. 
If you have the opinion that this behavior is correct you could state it more clearly in the documentation otherwise we could alter the behavior.

**Comment by erezsh** [comment]
My point is that you should expect it.

What does it even mean for a transformer to be commutative? I have no concept of how that would work.

**Comment by JustKiddingCode** [comment]
Well, ok, let's don't call it commutative what I would expect.
The thing I'd expect is, that A*B = C, from the example above.
So that it doesn't make a difference if I define a function in one transformer or the other if I take the product of them.

**Comment by erezsh** [comment]
Oh, I think I understand. You want something like a "union" of the methods. But then the behavior isn't well defined if there are already two methods with the same name.

But perhaps you can just solve your problem using inheritance? Or mixins? Python already has a few mechanisms (and libraries) for that sort of composition.

Anyway, the `*` operator is supposed to represent sequence of operations (like function composition). So, the "mathematical" rule here is:

    t2.transform( t1.transform( x ) ) == (t1 * t2).transform( x )

And as you noticed, not maintaining that sequence produces a different result.

**Comment by JustKiddingCode** [comment]
Using multiple inheritance here seems not appropiate. I would rather add a few lines to do this.
Can I make a PullRequest to get the functionality into Lark?

something like this
```
class CombinedTransformer(Transformer):
    def __init__(self, *transformers):
        self.transformers = transformers

    def __getattr__(self, key):
        for transformer in reversed(self.transformers):
            try:
                return getattr(transformer, key)
            except AttributeError:
                pass
        raise AttributeError()

    def __add__(self, other):
        return CombinedTransformer(*self.transformers, other)
```
and for the transformer

```
    def __add__(self, other):
        return CombinedTransformer(self, other)
```
So every transformer adds the functionality of the previous one and "overwrites" the methods.

**Comment by erezsh** [comment]
I'm not convinced that this is necessary.

**Comment by JustKiddingCode** [comment]
For my use case I don't see another good solution.
I have a grammar that uses something like
Statement = linked | expr
Linked = statement "and" statement
Statements can be other comparisons. 
To keep my code easy to explain and understandable I want to separate my transformers and keep the code in two different classes. This also makes development a lot easier because I can just run the transformer I try to debug. However, in the end I want to run the transformers like they were in one class which is currently not supported. I would have either a statement transformer those expr nodes haven't been transformed or a linked transformer which statements have not be transformed.

**Comment by erezsh** [comment]
Do you know what are mixins? Have you ever used them?
