### ISSUE TITLE
mypy raises error: "VisitError" has no attribute "orig_exc" 

### ISSUE THREAD

**Issue by linw1995** [lark-parser/lark#532]
I run mypy on 0.8.1 working well, but on 0.8.2 is not. After looking into the comparison of two versions of code, I find out the annotation of `VisitError` is missing its attributes.

https://github.com/lark-parser/lark/blob/aa82f5a28a3e5d6d57a4e0ddc93c379ca1b3869b/lark-stubs/exceptions.pyi#L46-L47

**Comment by erezsh** [comment]
Does that solve it?

**Comment by linw1995** [comment]
Yes, thank you. @erezsh

**Comment by erezsh** [comment]
Great! So I'll close it.
