### ISSUE TITLE
get_context or similar for  VisitError?

### ISSUE THREAD

**Issue by swuecho** [lark-parser/lark#537]
with `propagate_positions = True`, the visitor error line and end_line can be accessed. I wonder if it is possible to get the exact location of the error. Thanks.

**Comment by erezsh** [comment]
You can see in the `VisitError` definition:
```python
class VisitError(LarkError):
    def __init__(self, rule, obj, orig_exc):
        self.obj = obj
        self.orig_exc = orig_exc
```

So if you can get the tree, and then access its meta. Like:
```python
try:
	whatever()
except VisitError as e:
	tree = e.obj
	print(tree.meta)
```

**Comment by swuecho** [comment]
Thanks!
