### ISSUE TITLE
[A-z_][A-z_0-9]* matches a[0]

### ISSUE THREAD

**Issue by alcides** [lark-parser/lark#539]
I have the following terminal:

`ID.-5: /[A-z_][A-z0-9_]/`

and it matches a[0], a[], Array[String] and so on. It should not match any of [ or ].

If I replace by the CNAME in the common library, it works:

ID.-5 : CNAME

CNAME is defined using lark's DSL and not using regular expressions. I am missing the issue here?

**Comment by erezsh** [comment]
```python
>>> from lark import Lark
>>> p = Lark("start: ID\nID.-5: [A-z_][A-z0-9_]")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    raise GrammarError("Unexpected input at line %d column %d in %s: \n\n%s" %
  ...
lark.exceptions.GrammarError: Unexpected input at line 2 column 10 in <string>:
```

So what exactly are you doing?

**Comment by alcides** [comment]
Sorry, I meant
` /[A-z_][A-z0-9_]]`

**Comment by erezsh** [comment]
Ah, I get it now. You're doing `A-z`, but there are characters between `Z` and `a`, like `[]`. Check out the ASCII table to see which ones.

What you should be doing is `A-Za-z`, to make sure the gap isn't matched.
