### ISSUE TITLE
Feature idea: template functionality for rules

### ISSUE THREAD

**Issue by graps1** [lark-parser/lark#540]
I am fairly new to this whole grammar thing, so please forgive me if I am missing something. 

I think that adding some kind of template-functionality to lark would be a good idea to avoid redundancy in rules and to increase readability. A template would be a rule that takes parameters. Such a template could then be instantiated into a new rule by giving concrete values to these parameters. A grammar that contains templates could then be transformed into a grammar without templates by instantiating all used template rules.

For example, consider this grammar with templates

    spaced(content): " " content " "
    r1: "+" spaced("hello")
    r2: "-" spaced("world")

`spaced` is a template that takes a parameter `content`. `spaced("hello")` and `spaced("world")` would be concrete instances of `spaced`. In a pre-processing step, the grammar can then be transformed into a grammar without templates:

    spaced_0: " " "hello" " "
    spaced_1: " " "world" " "
    r1: "+" spaced_0
    r2: "-" spaced_1

**Comment by MegaIng** [comment]
I fully agree that this should be added. I want to point out that in the oldest still open issue, #26, this is also proposed.

**Comment by erezsh** [comment]
Yes, I also agreed in issue #26, and even kept the curly-braces from being used for repetition, but apparently no-one cares enough to implement it ;)

But perhaps it's time I took care of it myself.

Either way, it's good to have it as a separate issue. I can also think of another example for it:

    sep{item, delim}: item (delim item)*
	number_list: "[" sep{number, ","} "]"

If you can come up with more examples that demonstrate how it will improve real grammars (and not just toy examples), it might convince me to give it more priority.

**Comment by graps1** [comment]
Cool, so if it isn't a problem, I could give it a try in the coming weeks or so.

**Comment by erezsh** [comment]
Go ahead. Let me know when you have a plan/design, so we can make sure you're on the right track and won't waste time.

**Comment by MegaIng** [comment]
I am currently bored and therefore attempting to implement this. This is my current idea on how to implement it:

- [x] Add syntax for templates, which look like rules (including priorities), but with added curly braces and a parameter list
- [x] Add syntax for template usages, which look like rules with curly braces, which take a argument list.
  - [ ] Question: should they take an `atom`, an `expansions`, an `expr` or a `value`?
- [ ] Add them in `load_grammar`:
  - [ ] Copy them over to the created `Grammar` object for importing
  - [ ] Auto generate rules, creating a new name which includes the braces and the arguments that were passed over: `_sep{number, ","}` would be the name of the created rule (with underscore for auto-always-inline)

**Comment by MegaIng** [comment]
I am now at a point where the templates are in a basic form useable: https://github.com/MegaIng/lark/tree/template_rules.
Missing features:

- Currently imports are broken. ALL imports. Will fix tomorrow
- A lot of TODOs, which I would like you to look over to help with (mainly to make decisions I am not sure about=

**Comment by erezsh** [comment]
Good question. It's probably `expansions`

**Comment by MegaIng** [comment]
I would start a discussion over that question (and others) over on gitter: https://gitter.im/lark-parser/Lobby

**Comment by erezsh** [comment]
This feature has been implemented, so I consider this issue closed. Good job everyone!
