### ISSUE TITLE
Flag to make all terminals case insensitive

### ISSUE THREAD

**Issue by rdeoliveira** [lark-parser/lark#541]
**Feature request**
As a developer using lark-parser
I would like to set a global flag (when instantiating the parser?) to treat all terminals as case insensitive
So that I don't have to add `i` to all my terminals, if case doesn't matter for any of them

**Comment by MegaIng** [comment]
I am currently working my way through the source code to add this feature, but I have a few question regarding the design of the source code. @erezsh How do I best ask these? This is in regards to a few places where I am not sure why it was designed the way it is. (Example: Why don't all Lexers directly take the LexerConf object and unpack it themselves?).

**Comment by erezsh** [comment]
@MegaIng You can ask me on gitter or through mail.

Regarding LexerConf, I really don't remember. Maybe it's possible to just pass it instead of unpacking it, it doesn't seem like a significant difference.

**Comment by MegaIng** [comment]
@rdeoliveira Does the PR fulfill your wishes? If yes, you can close this issue.

**Comment by rdeoliveira** [comment]
I suppose so. I suppose the new version is not yet available via pip install?

Best,
Rodrigo

**Comment by MegaIng** [comment]
No, sadly only @erezsh can create a new release. you can manually download and `setup.py install` the newest 'development' version in this repo.

**Comment by rdeoliveira** [comment]
Not to worry. I'll wait for until this can be pip installed. Will be easier given our CI/CD pipeline.

I can close this now. Thanks @MegaIng for the quick reaction!

**Comment by erezsh** [comment]
@rdeoliveira Luckily, I can create a new release. `0.8.3` is now out with this feature.

**Comment by rdeoliveira** [comment]
@erezsh This is awesome! Thanks.
