### ISSUE TITLE
Parent variable in Tree class

### ISSUE THREAD

**Issue by belerico** [lark-parser/lark#542]
Hi guys, it would be nice to have a parent variable in the Tree class

**Comment by MegaIng** [comment]
Please check old issues before creating a new one: https://github.com/lark-parser/lark/issues/510

**Comment by erezsh** [comment]
I added it to the recipes page: https://lark-parser.readthedocs.io/en/latest/recipes/

(end of page)

**Comment by belerico** [comment]
> Please check old issues before creating a new one: #510

Sorry, my fault: i was in a hurry and i did not check
