### ISSUE TITLE
Release v0.8.3 built with two stubs directories.

### ISSUE THREAD

**Issue by linw1995** [lark-parser/lark#545]
Release v0.8.3 built with two stubs directories, `lark-stubs`(old) and `lark_stubs`(new).

```shell
pip download lark-parser==0.8.3
unzip lark_parser-0.8.3-py2.py3-none-any.whl -d 0.8.3
ls 0.8.3
```

output:

```plain
lark                        lark_parser-0.8.3.dist-info
lark-stubs                  lark_stubs
```

And mypy will use the older stubs directory `lark-stubs` first.

**Comment by erezsh** [comment]
Thanks for the heads up! I cleaned all my caches and released a new version.

**Comment by linw1995** [comment]
Thank you! The new version works well now.
