### ISSUE TITLE
Question: how to prevent lark from recognizing parts of an identifier as a keyword?

### ISSUE THREAD

**Issue by NssTheGreat** [lark-parser/lark#551]
Hi, I have a little question.
```python
parser = Lark('''
    ?start: value 
            | start "or" value -> or
    ?value: DIGIT -> digit 
            | ID -> id

    DIGIT: /[1-9]\d*/

    %import common.CNAME -> ID

    %import common.WS
    %ignore WS
    ''', parser='lalr')

print(parser.parse("1orfoo").pretty())

```
This code outputs the following:
```
or
  digit 1
  id    foo
```

What can I do to make lakr recognize ```orfoo``` as an identifier (thus throwing a syntax error in this case)?

**Comment by erezsh** [comment]
You just need to make that syntax legal.

Like
```python
    ?start: value
            | value value -> orfoo
            | start "or" value -> or

...

$ python .\issue551.py
orfoo
  digit 1
  id    orfoo
```

**Comment by NssTheGreat** [comment]
Thanks for the answer, but that's not exactly the behavior I want. I probably should have been more clear. I actually want that syntax to be illegal. I just don't want expressions like ```1orfoo``` or ```1or2``` to be syntactically correct "or" statements.

Basically, I want to make something a bit like python: if you write ```1or2``` or ```1orfoo``` in a python console, you get a SyntaxError because it sees a digit followed by an identifier, it doesn't parse it as an "or" statement.

**Comment by NssTheGreat** [comment]
Found the  answer here:
https://stackoverflow.com/questions/61711950/how-to-prevent-lark-from-recognizing-parts-of-an-identifier-as-a-keyword

**Comment by erezsh** [comment]
Sorry, this one slipped through the cracks.

That answer may work for this simple grammar, but it will severely limit your grammar going forward, if you plan to add more complex rules.

Maybe that's fine for your use-case. But just fyi, there is another solution, which is to use a regex lookahead and ensure there's no character after or:

_OR: /or(?!\w)/

**Comment by thautwarm** [comment]
This is a severe problem.
