### ISSUE TITLE
Reconstruct: assertion error if maybe_placeholders is enabled

### ISSUE THREAD

**Issue by Cell00phane** [lark-parser/lark#558]
Hello,
I'm fairly new to lark and I'm trying it and so far so good! I've had a try with the reconstruct tree module, and I've had an assertion error when using it with a parser with the maybe_placeholders option on. Are there any reasons behind this assertion?

**Comment by erezsh** [comment]
Sorry! this must have fallen between the chairs. I'm closing it, but if you still want an answer let me know.
