### ISSUE TITLE
Documentation: Wrong syntax for multiple imports

### ISSUE THREAD

**Issue by andreasfelix** [lark-parser/lark#560]
I think I found a mistake in the Documentation:

According to the [Documentation](https://lark-parser.readthedocs.io/en/latest/grammar/) one can import multiple terminals or rules from another grammar using a space separated list:

```
%import <module> (<TERM1> <TERM2> <rule1> <rule2>)
```

Attempting to import multiple terminals form common.lark

```
%import common (INT FLOAT ESCAPED_STRING)
```

I get the following error message:

```
E   lark.exceptions.UnexpectedToken: Unexpected token Token(TERMINAL, 'FLOAT') at line 4, column 21.
E   Expected one of: 
E   	* _RPAR
E   	* _COMMA
```

After looking into `examples/lark.lark` the correct syntax seems to be a comma separated list:
```
name_list: "(" name ("," name)* ")"
```

Using
```
%import common (INT, FLOAT, ESCAPED_STRING)
```
fixes the problem.

**Comment by erezsh** [comment]
Thanks, it appears to be a mistake.

**Comment by erezsh** [comment]
Fixed.
