### ISSUE TITLE
Not being able to use find_pred()

### ISSUE THREAD

**Issue by AlbertoEAF** [lark-parser/lark#564]
**Describe the bug**

Hello, I have a Token (terminal) whose name (node.type) is "IDENTIFIER".

If I go through the tree manually I get matches correctly using a predicate function, however, if I pass that same function to the same tree by calling find_pred it won't work, it always comes empty:
![image](https://user-images.githubusercontent.com/3976753/79910387-88f31380-8416-11ea-8576-e0fd9186f769.png)

This is the function:
```
def gen_find_token(token_type):
    return lambda x: isinstance(x, Token) and x.type == token_type

f = gen_find_token("IDENTIFIER")
```

**What is going wrong?**
I want to modify my subtree nodes inside a transformer, but using find_pred, as in here, does not work, forcing me to trasverse the tree with custom code, which I guess is not necessary.

Thank you :)

**Comment by MegaIng** [comment]
This is slightly confusing naming: the `find_pred()` function only finds tree, not tokens. For those use the `scan_values()` function

**Comment by AlbertoEAF** [comment]
Marvelous! Worked at first try!
Can that be added to the docs? :)

Thank you @MegaIng for your quick replies! :)
