### ISSUE TITLE
Unexpected tokens

### ISSUE THREAD

**Issue by handras** [lark-parser/lark#568]
This issue connects to #517

So here is a short extract based on the DBC grammar I am working on:

``` python 
grammar="""
%import common.CNAME
%import common.INT
%import common.WS
%ignore WS

start : signal* //group
signal : "SG_" signal_name multiplexer_indicator ";"
signal_name : CNAME
!multiplexer_indicator : | "M" | "m" INT

//group: "GR_" CNAME ":" signal_name*

"""
parser = lark.Lark(grammar, parser='lalr', lexer='contextual')
print(parser.parse('SG_ motortemp m8 ; SG_ motorrev m8 ;').pretty())
```
In its current state it can parse the example string.
However when the 'group' rule is introduced the lexer takes `m8` as a CNAME token instead of `m`, raising

```python
lark.exceptions.UnexpectedToken: Unexpected token Token(CNAME, 'm8') at line 1, column 15.
Expected one of: 
	* M
	* __ANON_1
	* SEMICOLON
```

My understanding is that the problem comes from the fact that the `group `rule intruduces the possibility that a `CNAME `is followed by another `CNAME`. However it's not clear for me how the contextual lexer decides which token to try to match.

Prioritizing the `m` token is not working. If I increase the priority of matching `m` that introduces the problem that `motortemp` will no longer be a CNAME token, but a single `m`.

What I did as a workaround is that I defined a new terminal `SWITCH.2 : /m\d+/`. So it has priority over CNAME which means there can't be signals named starting with this token. This is acceptable.

Furthermore there are other issues in the grammar where INT and DOUBLE tokens get confused.

Maybe this means that a LALR parser is not appropriate for this grammar. I do this parser for a Compilers course where we only discussed LL and LR parsers. I'm sure this grammar is LR parseable, however I am not aware of the limitations a LALR parser has.

**Comment by MegaIng** [comment]
This is a problem, and maybe even a bug in the lexer. It combines conflicting tokens (CNAME and "m") and just tries to parse CNAME. But it is expected, to allow the parser to recognize `def` vs `define` with `def` being a keyword as example in python, where as `define` should just be a name. You specifically don't want this behavior, but I don't think you can deactivate it.

**Comment by erezsh** [comment]
@MegaIng You can deactivate it by giving the smaller token a higher priority.

@handras 
Does this solve your problem?

import lark

grammar="""
%import common.CNAME
%import common.INT
%import common.WS
%ignore WS

start : signal* group
signal : "SG_" signal_name multiplexer_indicator ";"
signal_name : CNAME
multiplexer_indicator : M?

M.10: "M" | "m" INT

group: "GR_" CNAME ":" signal_name*

"""
parser = lark.Lark(grammar, parser='lalr')
print(parser.parse('SG_ motortemp m8 ; SG_ motorrev m8 ; GR_ m8 : m8').pretty())

**Comment by MegaIng** [comment]
If you don't want the combined token of `m8`, you can use this:

```
multiplexer_indicator : "M" | _M INT

_M.10: "m"
```
