### ISSUE TITLE
Regex with "+" sign not working correctly?

### ISSUE THREAD

**Issue by yamaryoxxxx** [lark-parser/lark#569]
I write grammar with regex, sometimes getting trouble with "+" sign in regex.

### WORKS:
```python
from lark import Lark
grammar = """
start: /./+ "c"
"""
print(Lark(grammar).parse("abc"))
```

### DOESN'T WORK:
```python
from lark import Lark
grammar = """
start: /.+/ "c"
"""
print(Lark(grammar).parse("abc"))
```
with error
```
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: * C
```

Sometimes `/.+/` doesn't work while `/./+` works. Is it violating any syntax or regulation?

**Comment by MegaIng** [comment]
The regex `/./+` matches "abc" as one Token. Lark can not break that up. `/./` doesn't, so Lark can deal with it.

**Comment by yamaryoxxxx** [comment]
I see. thanks!
