### ISSUE TITLE
Wrong parse results?

### ISSUE THREAD

**Issue by yamaryoxxxx** [lark-parser/lark#570]
This code

```python
from lark import Lark

grammar = """
start: any zeros any
any: /./+
zeros: "0"+
"""

print(Lark(grammar, ambiguity="explicit").parse("a00b").pretty())
```

results in 

```
_ambig
  start
    any a
    zeros
    any
      0
      b
  start
    any a
    zeros
    any
      a
      0
    zeros
    any b
```

The former of the ambiguity seems relevant, but the latter of it implies that the string `"a00b"` is parsed into `any(a) zeros any(a0) zeros any(b)`, which seems wrong.

Here is the reproduction and the version is 0.8.5.
https://repl.it/@RyoYamamoto/Lark-test-3

**Comment by MegaIng** [comment]
Please look at old issues if they are the same: #455.

**Comment by yamaryoxxxx** [comment]
I think it's same.Thank you.
