### ISSUE TITLE
SLY (PLY) implementation for benchmark

### ISSUE THREAD

**Issue by goodmami** [lark-parser/lark#571]
The README states the following:

> *Note: I really wanted to add PLY to the benchmark, but I couldn't find a working JSON parser anywhere written in PLY. If anyone can point me to one that actually works, I would be happy to add it!*

I have created an implementation in [SLY](https://github.com/dabeaz/sly), which is the modernized (Python 3.6+) version of PLY by the same author. See here: https://github.com/goodmami/python-parsing-benchmarks/blob/master/bench/sly/json.py

A few notes:
* This was my first time using SLY (or PLY, for that matter), so I'm not confident that it's the normal way of doing things. I've raised https://github.com/dabeaz/sly/issues/52 to hopefully get some advice regarding this.
* The implementation follows the requirements of my other benchmarks, meaning that it follows the JSON spec exactly, which may not be true for the other implementations in your benchmarks, but it is true for the others in my set
* My repo is MIT-licensed, so if you wish to use this code you should just need a comment at the top with a link to my repo and its LICENSE file (speaking of which, I may need a similar statement in my Lark implementation, since some code was contributed by @erezsh)

I ran my benchmarks a few times (each time does 5 rounds of loading a large file). Each time SLY was just a bit slower than Lark with both CPython and PyPy, but not significantly so.

When I do a single run at a time without any warmup time, Lark is about 5.2s vs SLY's 4.9s on my machine, and I think this is due to the instantiation time as SLY does not need to parse a grammar like Lark does (e.g., for the same reason, pyparsing is the fastest in my tests to instantiate (but, unrelatedly, the slowest to parse)). Lark also uses a bit more memory than SLY in this test: ~55M vs ~45M.

Hope that helps!

**Comment by erezsh** [comment]
Very cool!

I think most implementations are fairly similar. The main differences are the regexps, which I don't think will affect performance that much. If yours follows the standard, you can mark those that don't. I'll be happy to update Lark's json benchmark to fit it, if necessary.

Lark also has the MIT license, so I think it should be fine? But let me know if you need anything from me.

> Each time SLY was just a bit slower than Lark with both CPython and PyPy, but not significantly so.

That was the same for PLY, which makes sense if they share the same engine.

> I think this is due to the instantiation time as SLY does not need to parse a grammar like Lark does

The latest Lark commit comes with a cache feature. You can just run `Lark(..., cache='filename.cache') and it will use it for caching the grammar. That should help with the warm-up time, and possibly also the memory consumption.

P.S. interesting that pe is performing so well! the api looks nice too

**Comment by goodmami** [comment]
> I think most implementations are fairly similar. The main differences are the regexps, which I don't think will affect performance that much.

Yes, these are the main difference in recognizing valid JSON values. I think the post-parse string-unescaping may slow things more, though.

> If yours follows the standard, you can mark those that don't. I'll be happy to update Lark's json benchmark to fit it, if necessary.

All implementations in my benchmarking repo pass the same tests, so you can use them (or the tests) to update your benchmarks if you like. I don't have the ANTLR grammar you used so I cannot validate that. Did you just use https://github.com/antlr/grammars-v4/blob/master/json/JSON.g4? At a first glance it looks like it follows the spec well enough, but it doesn't have any actions so they'd need to be added.

> Lark also has the MIT license, so I think it should be fine? But let me know if you need anything from me.

The licenses are compatible but the terms require that the license accompanies copied or derived work. It's not like I'm going to enforce the terms or anything, but I think it's better to just tick these boxes now so there's no question down the road. In any case, I just pushed a docstring for that file with authorship info and a link to the repo, so if you copy that it'll be fine.

> The latest Lark commit comes with a cache feature. ...

Hmm, that's a nice feature. I'll need to figure out how to incorporate it into my benchmarks. I may need to split the "compile-time" into separate "compile" and "start" time. This way I could also count parsers that generate code, such as ANTLR.

> P.S. interesting that pe is performing so well! the api looks nice too

Thanks! Its times, particularly with PyPy, are not very stable, though. I recently got memoization working without as big a performance hit as before, so I enabled it by default. This seems to make it harder for PyPy to optimize or something. Also, I'm becoming less enthused with JSON as the primary benchmark. As you can see from the arithmetic test, pe does much worse when there's lots of backtracking (and unbearably worse if there's no memoization), but JSON requires almost no backtracking, so it's not a complete picture of the performance. On the flip side, disabling memoization makes JSON parsing about 16% faster.

**Comment by goodmami** [comment]
Also, regarding #487, since you said your benchmarking code was not readily available, if you want to use https://github.com/goodmami/python-parsing-benchmarks for your numbers, I can give you write access. This could also help keep things fair.

**Comment by erezsh** [comment]
> Did you just use antlr/grammars-v4:json/JSON.g4@master

Most probably, though perhaps an earlier version

> All implementations in my benchmarking repo pass the same tests, so you can use them (or the tests) to update your benchmarks if you like

Those benchmarks are a little out of date anyway. Maybe I'll just link to your repo instead. I do like my colorful graphics better though.

> I'm becoming less enthused with JSON as the primary benchmark

That's very reasonable. JSON was intentionally designed to be very simple to parse. Even a simple SLR parser can parse it, without even having shift/reduce collisions to resolve.
I only chose it because that was the only grammar that every library had a working example of, knowing full-well that it actually puts Lark at a disadvantage.

> I can give you write access

What would I do with write access?

**Comment by goodmami** [comment]
> I do like my colorful graphics better though.

They are prettier, for sure. The nice thing about text-charts is they are diffable (e.g., [here](https://github.com/goodmami/python-parsing-benchmarks/commit/280feb2cced950d50ff4f3cb3a6e30f085d2df6b#diff-04c6e90faac2675aa89e2176d2eec7d8) you can see how the memoization-by-default hurt pe's performance with PyPy), and when they are updated frequently it takes less space in the repo than a bunch of binary blobs such as PNGs. Maybe I could commit a data file with timing info which could be used to generate the nicer charts.

> What would I do with write access?

Hmm, well I suppose if you wanted to update a Lark grammar with new features I suppose you could always just fork and submit PRs. I guess my thought was that if the repo were shared there'd be less of a conflict-of-interest than just me (being the author of one of the libraries) being the sole gatekeeper of all implementations.

**Comment by erezsh** [comment]
> Maybe I could commit a data file with timing info which could be used to generate the nicer charts.

Sounds good. I understand the advantage of making it diffable. I wonder if github can display SVG..

> I guess my thought was that if the repo were shared there'd be less of a conflict-of-interest than just me

Sure, that makes sense, I guess we're in the same boat. Then I'll accept the write access.

**Comment by goodmami** [comment]
Done. Of course there's no obligation but I appreciate any help!

**Comment by erezsh** [comment]
@goodmami Any progress on the timing info file? :)

I'm thinking I could write something to generate those charts automatically in SVG format. It's light and sorta-kinda diffable, and apparently github supports it (https://github.com/NNTin/test)

**Comment by goodmami** [comment]
Hi, sorry I had to get back to other things. For the timing info file, I think it's easiest to just use the `--benchmark-autosave` options of pytest-benchmark (see [here](https://pytest-benchmark.readthedocs.io/en/stable/usage.html#commandline-options)). We could write a script that reads one of those files and produces the chart. Here's an example entry for Lark on the JSON benchmark:

```json
        {
            "group": "json",
            "name": "test_parse_time[lark]",
            "fullname": "test_json.py::test_parse_time[lark]",
            "params": {
                "parse": "UNSERIALIZABLE[<function compile.<locals>.<lambda> at 0x7f42d00d2f70>]"
            },
            "param": "lark",
            "extra_info": {},
            "options": {
                "disable_gc": false,
                "timer": "perf_counter",
                "min_rounds": 5,
                "max_time": 1.0,
                "min_time": 5e-06,
                "warmup": false
            },
            "stats": {
                "min": 3.447319899001741,
                "max": 3.498912533003022,
                "mean": 3.471022134803934,
                "stddev": 0.01834199988169421,
                "rounds": 5,
                "median": 3.469542160004494,
                "iqr": 0.013358146989048691,
                "q1": 3.463851011259976,
                "q3": 3.4772091582490248,
                "iqr_outliers": 1,
                "stddev_outliers": 2,
                "outliers": "2;1",
                "ld15iqr": 3.447319899001741,
                "hd15iqr": 3.498912533003022,
                "ops": 0.288099574466265,
                "total": 17.35511067401967,
                "iterations": 1
            }
        },
```

More info than we need, but it's easy to pull out the mean or min and plot them. This also stores each run, so we can compare performance across time (i.e., diachronic performance). For diachronic charts, though, I think it would be better to plot relative performance and not absolute.

Also, the pytest-benchmark package can produce an SVG on its own, but the last time I tried it wasn't very readable. Yours are better for simple comparisons.

Finally, this package doesn't test (and thus doesn't store) memory usage statistics. So we'd have to run memory tests separately and the chart generator would need to pull in info from two sources.

How does that sound?

**Comment by erezsh** [comment]
Yeah, this JSON should be good enough.

It seems the best way is to use `--benchmark-json`, so that we can predict the filename. It will be a much bigger JSON, but we don't need to commit it anyway.

Memory will be a little more tricky.

We can use `psutil`, run each parser in a separate process, sample it constantly, and take the highest measurement.

**Comment by goodmami** [comment]
Hmm, as long as we can ignore the fine-grained timing info, then `--benchmark-json` is fine. The nice thing about using the regular save location is we can use the `--benchmark-compare` option, but maybe that's not a big deal.

For memory, there's also things like https://github.com/pythonprofilers/memory_profiler which use psutil under the hood to do the memory sampling you described.
