### ISSUE TITLE
how to write grammar for fixed size columns?

### ISSUE THREAD

**Issue by finjulhich** [lark-parser/lark#573]
**What is your question?**
When trying to parse tabulated output, made out of adjacent, fixed size columns,
COL1(5)   COL2(6)    COL3(7)     COL4(5)

Each column is made of n printable ascii characters.
when a column is empty it is replaced with space characters.
after the right-most non-empty column, even if it's not the last one, there's no spaces, just the newline character.

How does one write such a grammar?

**Comment by MegaIng** [comment]
You can create fixed sized tokens: `/.{6}/` parse any string of length 6. But it would help if you could paste an example you want to parse and the expected output in code formatting so that spacing is not messed up.

**Comment by erezsh** [comment]
If all the columns are of fixed size, why not just write a small python script to parse it?

Something like:

```python
def split_at(line, *indices):
    for i in indices:
        yield line[:i].strip()
		line = line[i:]

for line in lines:
    cols = split_at(line, 5, 6, 7, 6)
    do_whatever(cols)
```

You could make it a little more efficient of course (and maybe I have bugs, I didn't check), but doesn't that solve your problem?

**Comment by erezsh** [comment]
Also, `pandas` comes with a lot of features for reading tabulated data, and probably other libraries offer such a feature out of the box.

**Comment by finjulhich** [comment]
a subsection of the file that I'm parsing is tabulated, the rest is more suitable to lark

**Comment by erezsh** [comment]
In terms of the tools that Lark provides, you can use the `~n..m` to match a fixed number of rules, you can use regexps to capture only `{n..m}` characters, and you can use post-parse column attributes to figure out association.

I think all of these, while possible solutions, won't be a simple and resilient approach. So my recommendation is to capture the entire tabulation without parsing it, and then parse it in a separate phase.
