### ISSUE TITLE
Help: I receive error message at the the start of the grammar (My first time)

### ISSUE THREAD

**Issue by khaled-ek** [lark-parser/lark#575]
Hello,
I am totally new to parser generators and creating grammars.
I am writing a program to parse sub Modelica code, down is a part of the grammar which I use.

grammar = r'''
    start: program

    program: "block", 
        name,
        "protected",
        { declaration },
	"public",
        { function_declaration },
        "end",
        name,
        ";"
...
'''

parser = Lark(grammars.grammar, parser='lalr', transformer=ReadTree())

I receive an error message that reports the first comma after "block" (lark.exceptions.UnexpectedToken: Unexpected token Token(_COMMA, ','))

Any support would be much appreciated.

Thank you in advance
Khaled

**Comment by erezsh** [comment]
Lark grammars aren't separated by commas..

You should read one of the tutorials (JSON/Turtle) can then read some of the examples.

**Comment by khaled-ek** [comment]
Thank you for your response

**Comment by erezsh** [comment]
You're welcome to ask more questions, but please make sure you covered all the basics first.

**Comment by khaled-ek** [comment]
You are right, I missed the point that Lark cannot accept all EBNF rules. right?

**Comment by erezsh** [comment]
It can accept all EBNF rules, but there are several ways to write EBNF.

For Lark I chose the minimalistic version, following Python's philosophy.

**Comment by erezsh** [comment]
You could say Lark is more similar to ABNF than EBNF

https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_form

But it's all a mess anyway
