### ISSUE TITLE
Are the parse trees generated with the Earley algorithm with rule priority consistent?

### ISSUE THREAD

**Issue by JellePiepenbrock** [lark-parser/lark#580]
**What is your question?**

Are the parse trees generated with the Earley algorithm with rule priority consistent? What is guaranteed?

In an expression like: 
x ^ 3 * y + x ^ 2 * y ^ 2 + x ^ 2 * y + x * y ^ 2

With priority ^, *, + in decreasing order,

There are (I believe) multiple parse trees that would be consistent with this expression. How is this ambiguity resolved? Is it deterministic, and can I assume that for very similar expressions, the parse tree will have the analogous structure?

For example, will: 

x ^ 4 * y + x ^ 2 * y ^ 2 + x ^ 2 * y + x * y ^ 2 (higher power)
or
x ^ 2 * y ^ 2 + x ^ 2 * y + x * y ^ 2 (first term removed)
Have the same structure, apart from the difference in the expression?

**Comment by MegaIng** [comment]
That depends on your grammar. IG, yes it should be consistent, but your grammar might make it not be.

**Comment by JellePiepenbrock** [comment]
What are features of the grammar that would cause inconsistent parsing? 

I'm currently using this grammar:

"""?start: expression

                ?expression: atom
                | addition
                | multiplication
                | power
                | parentheses

                ?atom: WORD | NUMBER

                ?power.3: expression "^" expression -> pow

                ?multiplication.2: expression "*" expression -> mul

                ?addition: expression "+" expression -> add

                ?parentheses: "(" expression ")"

                %import common.NUMBER
                %import common.WORD
                %ignore " "           // Disregard spaces in text
             """,

**Comment by MegaIng** [comment]
This should make it consistent. The problem occurs when you have any ambiguity that isn't forced. But I would suggest looking at the calculator example or the python.lark file for a better way to deal with operators.

**Comment by erezsh** [comment]
It's supposed to be consistent, but it's possible that there are still some edge cases in which it's not. Like @MegaIng said, if at all, it comes out in highly ambiguous grammars.

**Comment by JellePiepenbrock** [comment]
Thank you both for the quick replies.

@MegaIng, regarding your comment on operator handling, do you mean replacing the priorities by making the operator with highest priority be the first option that the algorithm comes across? In the calc example, the "product" operations are closer to the atom level (I'm not sure what the terminology is here). That should allow me to use LALR for better performance, correct?

**Comment by MegaIng** [comment]
Yes, it allows you to use LARL. It removes any kind of ambiguity:

```
start: add
?add: (add "+")? mul
?mul: (mul"*")? atom
```
When we see a `1 + 2 * 3` it has to be understood as `1 + (2 * 3)`, since the grammar doesn't allow anything else. `(1 + 2) * 3` is not a possible interpretation: `mul` can not have an `add` as child, except in parentheses from inside `mul`.

**Comment by JellePiepenbrock** [comment]
I think I understand. I tried to generalize from the calculator example. Is this what you meant?

```python
"""?start: sum
        
                        ?sum: product
                        | sum "+" product -> add
                        
                        ?product: power
                        | product "*" power -> mul
                        
                        ?power: atom
                        | power "^" atom -> pow
                        
                        ?atom: NUMBER
                        | WORD
                        | "(" sum ")"    
    
                        %import common.NUMBER
                        %import common.WORD
                        %ignore " "           // Disregard spaces in text
                     """
```

**Comment by MegaIng** [comment]
Yes

**Comment by JellePiepenbrock** [comment]
It's much faster and achieves the consistency that I was looking for. Thank you for being so helpful!
