### ISSUE TITLE
Terminal: how to exclude some matches?

### ISSUE THREAD

**Issue by finjulhich** [lark-parser/lark#585]
I have this terminal **NAME**

`NAME.3: UCASE_LETTER (UCASE_LETTER|DIGIT)~1..2
             | DIGIT UCASE_LETTER~1..2
             | UCASE_LETTER`

How can I forbid it from match month names given another terminal **MONTHNAME**

`MONTHNAME: "JAN"
             | "FEB"
             | "MAR"
             | "APR"
             | "MAY"
             | "JUN"
             | "JLY"
             | "AUG"
             | "SEP"
             | "OCT"
             | "NOV"
             | "DEC"`

I suppose the q is rather how do I write a rule that matches NAME but not MONTHNAME?

**Comment by MegaIng** [comment]
Give `MONTHNAME` a higher priority. Terminals with a higher priority are tried first. If this for some reason doesn't work because of other restrictions in your grammar (unlikely, but possible), you can lookup python regex negative lookahead.
