### ISSUE TITLE
Validate subtree preserving original input

### ISSUE THREAD

**Issue by piwonskp** [lark-parser/lark#586]
**Suggestion**
I am writing DSL designed to unit test Python code which is named [takathon](https://github.com/piwonskp/takathon). In grammar file I import some of Python rules. I would like to be able to pass the code validated by them directly to Python interpreter.

**Describe alternatives you've considered**
For the time being I [monkeypatched lark's `load_grammar`](https://github.com/piwonskp/takathon/blob/master/src/takathon/interpreter/parser/inline_python.py#L28) although it is quite hackish and unelegant solution. Basically my solution transforms grammar tree to make any rule which starts with `python__` private.

A possible solution would be to add new directive. For example `import_validator`.
```python
parser = Lark("""
start: import_stmt
%import_validator .python.import_stmt
""")
parser.parse("from x import y")
```
After validating input it would result in the following tree:
```python
Tree("start", [Tree("import_stmt", [Token("IMPORT_STMT", "from x import y")])])
```
A more generic approach could be to mark such rules at the beginning (similarly to private or inlined rules).

**Comment by MegaIng** [comment]
Did you consider using a Reconstructor?

**Comment by erezsh** [comment]
@piwonskp If all you want is the original text, you can use `propagate_positions=True`, and use the `start_pos`/`end_pos` properties to slice the text.

**Comment by piwonskp** [comment]
@MegaIng  I did, however I gave up quickly since example Python grammar is not adapted to use reconstructor. Furthermore I feel like using reconstructor in this particular case is even more hackish. That's because initially I don't want to create tree for these rules so why would I build the tree just to instantly destruct it. Manipulating grammar tree and setting all python nodes private feels at least like using the right tools to shape the tree.

@erezsh  It shall solve my problems. Will try it. Thanks for help!

**Comment by piwonskp** [comment]
For future readers:
I solved the problem using @erezsh solution. There was an additional issue of imported rules marked with `?`. Basically I had to transform about 20 rules because they might be inlined. It can be solved easily by encapsulating imported rule in your own rule:
```
python_expr: test
%import .python.test
```
