### ISSUE TITLE
Position API unification

### ISSUE THREAD

**Issue by piwonskp** [lark-parser/lark#587]
Is there any reason why Tree.meta uses `start_pos` while Token uses `pos_in_stream`? Do the two mean different things?  If not it would be handy to have the API unified. 

Use case is related to [issue](https://github.com/lark-parser/lark/issues/586). After unification it would be easy to construct Token borrowing rule's position: `Token.new_borrow_pos("type", "value", tree.meta)`.

**Comment by erezsh** [comment]
No, they are the same thing in different contexts.

I agree it would be better to unify them into one name.

**Comment by erezsh** [comment]
Recently fixed this.
