### ISSUE TITLE
String parsing right to left.

### ISSUE THREAD

**Issue by mariohackandglitch** [lark-parser/lark#589]
Hello, I have a problem with a language parsing.

I have the following grammar:
```
?start: expression

?expression: "(" expression ")"
| expression operator expression
| negation expression
| string

?operator: "AND" -> andt
| "OR" -> ort

negation: "NOT" -> nott

string: /[0-9a-zA-Z_]\w*/

%import common.WS
%ignore WS
```
And a possible string would be the following:
test AND NOT test2 

However, for the following case:
test AND test2 OR test3
the parsing is equivalent to:
test AND (test2 OR test3)
however the desired behaviour is:
(test AND test2) OR test3

The first case makes sense, as the first `operator` token is the AND, so it grabs that as the "pivot" and parses the left and right expressions individually. Is there a way to make the parsing from right to left, so that in this case, it finds the OR operator first?

**Comment by MegaIng** [comment]
Check the calculator example. This is standard precedence problems, which I am sure you will find multiple previous questions about in the closed issues list.

**Comment by mariohackandglitch** [comment]
Sorry, I think that using boolean operations was not a good example, I saw in the calculator example that the * sign has preference, this is not the case here, in my case the right-most operator is the one that takes preference.

**Comment by mariohackandglitch** [comment]
Here are more examples, just in case:
1 AND 2 OR 3 = (1 AND 2) OR 3
1 OR 2 AND 3 = (1 OR 2) AND 3
1 OR NOT 2 AND 3 = (1 OR (NOT 2)) AND 3
1 OR 2 AND NOT 3 = (1 OR 2) AND (NOT 3)
NOT 1 OR 2 AND NOT (3 AND 4 AND NOT 5) = ((NOT 1) OR 2) AND (NOT ((3 AND 4) AND (NOT 5)))

**Comment by erezsh** [comment]
@mariohackandglitch If I understand correctly, you have several operators of the same precedence, and you want them grouped to the right, instead of to the left.

In that case you should do the same thing as the calculator example, but use right-recursion instead of left-recursion.

Example:

```python
>>> l = Lark('?start: /./ ("+" start)?')

>>> print(l.parse('a+b+c').pretty())
start
  a
  start
    b
    c
```

**Comment by mariohackandglitch** [comment]
Thanks @erezsh, this almost works, but it's dividing the right tokens by characters, instead of strings.

**Comment by erezsh** [comment]
You just need to define a string terminal (`/.+/` insteaod of `/./`). But better to limit it to the right set of characters.

Infinite recursion? I'm not sure what you mean, since the input is finite.

**Comment by mariohackandglitch** [comment]
In fact, your example was exactly the opposite of what I needed, so now that I know how recursion can be defined, I changed  `| expression operator expression` with `| (expression)? operator expression`

Keep in mind that for 1 AND 2 AND 3, it has to first calculate 1 AND 2 and then the result AND 3.

Thanks for the help!

**Comment by erezsh** [comment]
*scratches head*
