### ISSUE TITLE
Multiple executions of the same query and grammar yields different results.

### ISSUE THREAD

**Issue by mariohackandglitch** [lark-parser/lark#594]
**Describe the bug**
I have a python script that given a grammar produces a tree, however executing the same script multiple times yields different results. (Note that executing the query in the same instance will not produce the issue.)

**To Reproduce**
Execute the following script, it will run the query parse multiple times on different python instances, different executions will produce different results.
https://gist.github.com/mariohackandglitch/964901f93dda992739f3daae321c108f

**Comment by mariohackandglitch** [comment]
By the way, the proper result I would like to get with this query is:
`
Tree(expression, [Tree(expression, [Tree(nott, []), Tree(string, [Token(__ANON_0, 'isla')])]), Tree(ort, []), Tree(expression, [Tree(expression, [Tree(nott, []), Tree(string, [Token(__ANON_0, 'val')])]), Tree(andt, []), Tree(string, [Token(__ANON_0, 'pero')])])])\r\n`

**Comment by MegaIng** [comment]
This is not really a bug. Your grammar is highly ambiguous. Look at the calculator example to see how to write a non-ambiguous grammar.

**Comment by mariohackandglitch** [comment]
I already looked at the calculator, it doesn't satisfy my needs, OR and AND have the same priority, after NOT. However in an ambiguous situation a AND b OR c, a AND b should take priority, then the result ORed with c. I kind of fixed it in another issue by doing recursion on the first expression, but this causes this ambiguous behaviour.

**Comment by MegaIng** [comment]
The important part is to have more than one rule: clearly define how your tree should look like, and then model the grammar after how the tree should look like:

For your example `a AND b OR c` you want this parse tree
```
expression
  expression
    name a
    operator and
    name b
  operator or
  name c
```

The first child of `expression` can be either `name` or `expression`, the second only an operator, the third only a name:

```
expression: (expression|name) operator name
```

Apply this to all nodes, and you will have an unambiguous grammar.

**Comment by erezsh** [comment]
Look at the example python grammar, it does exactly this.

**Comment by mariohackandglitch** [comment]
I've came up with a grammar that seem to remove all ambiguities,
```
?start: parexpression

?exprwithpar: "(" parexpression ")"

?parexpression: (exprwithpar | expression)

?expression: (parexpression|term) operator term
| (parexpression|term) operator ([negation] exprwithpar | parexpression)
| negation parexpression
| term

?operator: "AND" -> andt
| "OR" -> ort

?term: [negation] string

negation: "NOT" -> nott

string: /\b[\w\-_]+:*[\w\-_]*\b/

%import common.WS
%ignore WS
```
This handles all cases properly, including order preference, pharentesis and negations.

Thanks for the help again!
