### ISSUE TITLE
How to resolve tokens ambuguity?

### ISSUE THREAD

**Issue by imihajlow** [lark-parser/lark#596]
I use lark to parse a C-like language. Among other, it has operators `&&` (boolean AND), `&` (bitwise AND), and `&` (address of). Since boolean AND has lower priority than the other two, when parsing expressions like `a < b && c < d` it gets parsed as `(a < b) & (&c < d)`. Is there a way to force the lexer to always treat double ampersand as a single token? Or maybe there's another way to write my grammar?
For the reference, the grammar for my language is [here](https://raw.githubusercontent.com/imihajlow/ccpu/a5c4447ea6ac12e3cf9362136c7bf439ac927fa3/tools/natrix/grammar.lark).

**Comment by MegaIng** [comment]
Use the 'lalr' parser. Your grammar is unambiguous, and 'lalr' automatically resolves this ambiguity.

**Comment by imihajlow** [comment]
Thank you. After a few modification to the grammar it worked with the LALR parser.
