### ISSUE TITLE
README.md: description for installation could be more verbose

### ISSUE THREAD

**Issue by danielbisar** [lark-parser/lark#599]
**Describe the bug**

Try to install the program as described in the README.md on Fedora 32. I am not sure how this is on other systems but i needed to install via 

`pip install --user lark-parser`

without --user I get an error message because a directory could not be created, installing it with sudo is not what i want and i would need to probably add some folder to my PATH variable.

P.S.: Thank you for this awesome project, i was searching for something easy to use for my going to be open source project. It is super easy to use and does exactly what i need. EBNF is awesome.

**Comment by MegaIng** [comment]
I would not do this. This is not special to lark, but a general 'problem' with your system. Installing with `--user` is not always the best idea (I would suggest using a virtual environment)

**Comment by danielbisar** [comment]
So what do you think is wrong with my system (it's a fresh installation) - or an advice what I should search for?

**Comment by MegaIng** [comment]
There is noting wrong. That is why problem is in quotes. Your python installation is global, so the `site-packages` folder is a protected folder that can only be written to with `sudo`. This is normal. You can either use a virtual environment, install with `sudo` or use `--user`. But this has nothing to do with `lark`. You can google any of these options, or even your exact error message.

**Comment by erezsh** [comment]
@danielbisar 

There is nothing wrong with your system.

It's simply common knowledge for Linux users.

The reason you're getting an error, is that pip by default tries to install into the system library, but it doesn't have the right permissions to do it.

So the solution is to either give it permissions with `sudo`, use `--user` to change the targeted path, or use `virtualenv` which also uses a path that has permissions. So as you see, this has nothing to do with Lark.

I don't know why `pip` chose to make this their default behavior, but perhaps you should bring it up with them. Honestly I don't think it makes much sense, but more linux users learn it pretty quickly anyway.

**Comment by danielbisar** [comment]
Ok so it is common that I need to add this option. This is why I thought it makes sense to include that in the readme for users like me who are not so firm with pip or python in general. Thank you for your help.

**Comment by erezsh** [comment]
No problem.

P.S. Fedora is a good choice.
