### ISSUE TITLE
Missing PyInstaller hook in PyPI release

### ISSUE THREAD

**Issue by KmolYuan** [lark-parser/lark#600]
Happened in version `0.8.6`.

The entry point is created but "lark/__pyinstaller" folder is not included.

So the error comes:

```
...
  File "C:\Python38\lib\site-packages\PyInstaller\building\build_main.py", line 207, in __init__
    hookspath += list(entry_point.load()())
  File "C:\Python38\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "C:\Python38\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'lark.__pyinstaller'
```

Copy it to installed path or remove the entry point can solve this issue.

My CI builds:
https://travis-ci.org/github/KmolYuan/Pyslvs-UI/builds/697084381

**Comment by erezsh** [comment]
Fixed it and release 0.8.7

Let me know if it works.

**Comment by KmolYuan** [comment]
@erezsh  Yes it works.

**Comment by KmolYuan** [comment]
The reverted changes 3bee21051e8440e506ea13f45b224e2f6d668662 is caused this issue again.

https://github.com/lark-parser/lark/commit/3bee21051e8440e506ea13f45b224e2f6d668662#diff-2eeaed663bd0d25b7e608891384b7298L9

**Comment by erezsh** [comment]
Oops, I accidentally reverted setup.py too... Sorry!

I'll fix it.

**Comment by erezsh** [comment]
Uploaded as `0.8.9`.. Hopefully that's the last of it.
