### ISSUE TITLE
How to match a line-start?

### ISSUE THREAD

**Issue by pwwang** [lark-parser/lark#602]
How should a line-start be matched?

In python `re`, we can do `r/^abc/`, which will match each line-start. However, in `lark`, that will only match the very beginning of the text.

Or we can require that the previous character is a line break:
```
abc: /\nabc/
```

However, that will consume the `\n`. So I also tried lookbehind:
```
abc: /(?<=\n)abc/
```

But it doesn't work in `lark`.

So is there a good way to match the line-start in `lark`?

**Comment by MegaIng** [comment]
In general, you shouldn't. Lark is designed for EBNF with context free grammars.

But you can still do it with flags. You can specify flags after the regex. This means you can match the beginning of a line with `/^abc/m`.

**Comment by erezsh** [comment]
Try this:

```python
from lark import Lark

l = Lark(r"""
    start: ("a"|"\n")* /^b/m
        """)

print(l.parse('aaa\nb'))    # OK
print(l.parse('aaab'))      # Exception
```

**Comment by pwwang** [comment]
> Try this:
> 
> ```python
> from lark import Lark
> 
> l = Lark(r"""
>     start: ("a"|"\n")* /^b/m
>         """)
> 
> print(l.parse('aaa\nb'))    # OK
> print(l.parse('aaab'))      # Exception
> ```

This works! Thanks a lot!

Closing.
