### ISSUE TITLE
Add terminals at runtime

### ISSUE THREAD

**Issue by rdeoliveira** [lark-parser/lark#605]
Is there a way to add terminals at runtime? 
For example, say:
* The hard-coded grammar string doesn't have a token named `FRUIT` (or it declares one without any terminals).
* Then a list is built at runtime with elements `['apple', 'banana', 'cherry']`, say by looking up a database.
* Some magic happens =)
* The grammar object (not the grammar string) has the token/terminals `FRUIT: "apple" | "banana" | "cherry"`.

**Comment by erezsh** [comment]
Check if the `edit_terminals` option works for your purposes

**Comment by rdeoliveira** [comment]
sounds like a good candidate. could you provide an example?

**Comment by erezsh** [comment]
See this: https://github.com/lark-parser/lark/issues/406

**Comment by erezsh** [comment]
(Read the end)

**Comment by rdeoliveira** [comment]
Thanks. Again, promising =)
Correct me if I'm wrong, but your solution only works if I wanted to **modify** existing terminals, right?
What I need is to **add** terminals. I guess I could live with declaring the token `FRUIT` upfront without any terminals (using `@declare`?), but then I don't know how to add terminals to it.
Any ideas?

**Comment by erezsh** [comment]
That's a simple regex.

Make sure `FRUIT` is a regular expression, by declaring it with a fake regexp

```ruby
FRUIT: /<PLACEHOLDER>/
```

And then use `apple|banana|orange` as the token value.

**Comment by rdeoliveira** [comment]
True!

Now, how do I pass the fruit list as a param in the callback? This didn't work:

```python
# grammar
grammar = """
    // more rules and terminals...
    FRUIT: /FRUIT_PLACEHOLDER/
"""

#callback
def add_fruits(t, fruits=None):
    if t.pattern.value == 'FRUIT_PLACEHOLDER':
        t.pattern.value = fruits

#constructing parser
fruits = "|".join(get_fruits()) # imagine this returns ['apple', 'banana' , 'cherry']
fruit_parser = Lark(grammar,
                          ambiguity='explicit',
                          g_regex_flags=re.IGNORECASE,
                          edit_terminals=add_fruits(fruits=fruits))
```

**Comment by erezsh** [comment]
```python
from lark import Lark

grammar = """
    start: FRUIT
    FRUIT: /FRUIT_PLACEHOLDER/
"""

fruits = "|".join(['apple', 'banana' , 'cherry'])
def add_fruits(t):
    if t.name == 'FRUIT':
        t.pattern.value = fruits

fruit_parser = Lark(grammar, ambiguity='explicit', edit_terminals=add_fruits)

print(fruit_parser.parse('apple'))
```

**Comment by rdeoliveira** [comment]
ah sorry, I forgot to emphasise that I cannot hard-code the list. it must be constructed at runtime.
example, someone is editing a shopping list, so the items in the list must be collected every time the parser runs.
i'll look at how to pass parameters to callbacks (never done this in Python =)

**Comment by rdeoliveira** [comment]
Got it!
```python
from lark import Lark
from functools import partial

grammar = """
    start: FRUIT
    FRUIT: /FRUIT_PLACEHOLDER/
"""

def add_fruits(fruits, t):
    if t.name == 'FRUIT':
        t.pattern.value = fruits

fruits = "|".join(get_fruits()) # get_fruits() returns ['apple', 'banana' , 'cherry']
fruit_parser = Lark(grammar, ambiguity='explicit', edit_terminals=partial(add_fruits, fruits)))

print(fruit_parser.parse('apple'))
```

**Comment by erezsh** [comment]
Terminal editing will only happen once whenever you create a Lark instance.

Perhaps what you need shouldn't be done with a parser. You can just match all words, and filter them out later (or report them as an error).

**Comment by rdeoliveira** [comment]
I'd rather use the parser. I cannot disclose the actual domain I'm working on, but I do need the structure around the terminals too. The solution I pasted above works fine. Thanks for your help!
