### ISSUE TITLE
Help need to resolve bug in grammar file

### ISSUE THREAD

**Issue by delzac** [lark-parser/lark#608]
**If you're having trouble with your code or grammar**

```
from lark import Lark


parser = Lark(grammar=r"""WS: /[ \t\r\n]/+

NEWLINE: "\\\\"
AMPERSAND: "&"
BRACE: "\\brace"

MISC_SYMBOLS: NEWLINE | AMPERSAND

BEGIN_MATRIX: "\\begin{matrix}"
END_MATRIX: "\\end{matrix}"

// rules
?start: math
?math: expr

expr: term+
?term: func  | symbols

func: matrix_func | brace_func
symbols: MISC_SYMBOLS

matrix_func: BEGIN_MATRIX expr END_MATRIX
brace_func: BRACE expr NEWLINE | BRACE expr | BRACE

%ignore WS
""", parser='lalr')
parse = parser.parse

tree = parse("\\begin{matrix} \\\\ & \\\\ {0} \\end{matrix}")

```

Attempting to parse
`tree = parse("\\begin{matrix} \\\\ & \\\\ \\end{matrix}")`

gets the following error:
```
lark.exceptions.UnexpectedToken: Unexpected token Token(NEWLINE, '\\\\') at line 1, column 21.
Expected one of: 
	* END_MATRIX
```

I have figured out that the error has something to do this putting `NEWLINE` after `expr`.

If i remove NEWLINE from
`brace_func: BRACE expr NEWLINE | BRACE expr | BRACE`

The error goes away. But i don't know why this is the case. I suspect it has something to do with `expr: term+`, but i can't figure it out.

Thanks for taking the time to read and help! :)

EDIT: edited based on feedback below.

**Comment by erezsh** [comment]
Hi @delzac , please write it as a working Python code that, when run, reproduces the error.

Perhaps the problem is in the initialization of Lark, etc.

**Comment by delzac** [comment]
Sorry about that. Working code below

```
from lark import Lark


parser = Lark(grammar=r"""WS: /[ \t\r\n]/+

_L_BRACE: "{"
_R_BRACE: "}"

NEWLINE: "\\\\"
AMPERSAND: "&"
BRACE: "\\brace"


MISC_SYMBOLS: NEWLINE | AMPERSAND

DIGIT: "0".."9"

LCASE_LETTER: "a".."z"
UCASE_LETTER: "A".."Z"

LETTER: UCASE_LETTER | LCASE_LETTER

BEGIN_MATRIX: "\\begin{matrix}"
END_MATRIX: "\\end{matrix}"

// rules
?start: math
?math: expr

expr: term+
?term: func | letter | digit | symbols

func: matrix_func | brace_func
symbols: MISC_SYMBOLS
digit: DIGIT
letter: LETTER

matrix_func: BEGIN_MATRIX expr END_MATRIX
brace_func: BRACE expr NEWLINE | BRACE expr | BRACE

%ignore WS
""", parser='lalr')
parse = parser.parse

tree = parse("\\begin{matrix} \\\\ & \\\\ {0} \\end{matrix}")
```

Attempting to parse
`tree = parse("\\begin{matrix} \\\\ & \\\\ \\end{matrix}")`

gets the following error:

```
lark.exceptions.UnexpectedToken: Unexpected token Token(NEWLINE, '\\\\') at line 1, column 21.
Expected one of: 
	* END_MATRIX

```
I have figured out that the error has something to do this putting `NEWLINE` after expr.

If i remove `NEWLINE` from
`brace_func: BRACE expr NEWLINE | BRACE expr | BRACE`

The error goes away. But i don't know why this is the case. I suspect it has something to do with `expr: term+`, but i can't figure it out.

**Comment by erezsh** [comment]
I removed MISC_SYMBOLS and it now works.

In general, try to make sure two separate terminals don't overlap (unless there's a very good reason). Because these are regexps, Lark can't check for collisions by itself.

The error was a little confusing, I admit.

```python
from lark import Lark

parser = Lark(grammar=r"""WS: /[ \t\r\n]/+

NEWLINE: "\\\\"
AMPERSAND: "&"
BRACE: "\\brace"

BEGIN_MATRIX: "\\begin{matrix}"
END_MATRIX: "\\end{matrix}"

// rules
?start: math
?math: expr

expr: term+
?term: func  | symbols | "{0}"

func: matrix_func | brace_func
symbols: NEWLINE | AMPERSAND

matrix_func: BEGIN_MATRIX expr END_MATRIX
brace_func: BRACE expr NEWLINE | BRACE expr | BRACE

%ignore WS
""", parser='lalr')
parse = parser.parse

tree = parse("\\begin{matrix} \\\\ & \\\\ {0} \\end{matrix}")
```

**Comment by delzac** [comment]
Thanks for taking the time to look through and guide me! I really appreciate it :)

The reason why the 2 terminals are merge is because i wanted `brace_func: BRACE expr NEWLINE` to work. Without merging the two terminals, the example below raise an exception.

```
from lark import Lark, Tree

parser = Lark(grammar=r"""WS: /[ \t\r\n]/+

NEWLINE: "\\\\"
AMPERSAND: "&"
BRACE: "\\brace"
MISC_SYMBOLS: NEWLINE | AMPERSAND

BEGIN_MATRIX: "\\begin{matrix}"
END_MATRIX: "\\end{matrix}"

// rules
?start: math
?math: expr

expr: term+
?term: func  | symbols

?func: brace_func | matrix_func
symbols: NEWLINE | AMPERSAND

matrix_func: BEGIN_MATRIX expr END_MATRIX
brace_func: BRACE expr NEWLINE

%ignore WS
""", parser='lalr')
parse = parser.parse

tree = parse("\\begin{matrix} \\\\ & \\\\ \\end{matrix}")  # this work fine if you do not merge the two terminals ( i.e. using MISC_SYMBOLS)
print(tree)

result = parse("\\brace & \\\\ ")  # this raises error if the two terminals are not merge ( i.e. using MISC_SYMBOLS)
print(result)
print(result.pretty())

```

**Comment by erezsh** [comment]
It's hard to give you advice, because I don't know what your goal is, or the specifics of the language you're trying to parse. In general, you're going to have difficulties if your separator (NEWLINE) is also a symbol in the language. The parser uses whitespace and punctuation to orient itself in the search space.

Perhaps for your purposes, it's better if you use the Earley parser.

**Comment by delzac** [comment]
I'm trying to parse [LaTeX](https://en.wikipedia.org/wiki/LaTeX).

It does work with Earley! I'm not very conversant with parsing technologies, so thank you have taking the time out to help! :)
