### ISSUE TITLE
Canonical way to remove nodes in AST

### ISSUE THREAD

**Issue by delzac** [lark-parser/lark#609]
***First Question***
What's the canonical way to remove nodes from the AST?

Within the lark-parser library, there's `Transformer` that walk from leaves to root. But they are useful only for transformation of nodes.

If i naively remove a node using the transformer with `@v_args(tree=True)` i get nested list in my children:
```
# from
Tree(parent, [Tree(child1, [data1, data2]), child2, child3])
# To
Tree(parent, [[transformed_data1, transformed_data2], child2, child3])
```

Is this the canonical way to do it? Or is there a better pattern available somewhere in the library?

I find it quite uncomfortable to have nest list in my children.

***Second Question***
Is there a way to access the parent node's data from the transforming methods in `Transformer`? That is transformation depends on the parents data.

**Comment by erezsh** [comment]
1. See here: https://lark-parser.readthedocs.io/en/latest/visitors/#discard

2. You can't access the parent. But you can write your own iteration/transformer that will let you.

**Comment by delzac** [comment]
For 2. got it!

For 1. Discard completely prunes the branch off. I'm wondering if i can retain children by moving the children into the parent's children without causing a nested list situation.

**Comment by MegaIng** [comment]
You can just create a new Tree. Tree is a simple container class exposed by lark.

**Comment by delzac** [comment]
@MegaIng I'm not sure i get you.

The situation i'm in is that i have a lot of transformation where i want to lift the children up to join the children of the parent node.
Using transformer, i get this `Tree(parent, [[child_of_deleted_node, child_of_deleted_node], child, child ]`
But i really want this `Tree(parent, [child_of_deleted_node, child_of_deleted_node, child, child ]`

I'm write a lot of boilerplate code, so i was wondering whether there was existing patterns that i can already leverage.

**Comment by erezsh** [comment]
@delzac Perhaps you missed the `_rule` feature?

Any rule starting with an underscored is always inlined to its parent.

**Comment by delzac** [comment]
Hmmmm, no quite what i was looking for. But i think i'll need to think about this more carefully. Once again thanks for taking the time out to help :) @erezsh @MegaIng
