### ISSUE TITLE
Lark cache fails when custom lexers are used

### ISSUE THREAD

**Issue by adefazio** [lark-parser/lark#613]
**Describe the bug**

In parser_frontends.py, the passed lexer is wrapped using functools.partial: 
```
return partial(LALR_CustomLexer, lexer)
```

but this results in a functools.partial object, not a lexer object, so when deserialize is called later, it fails with
```
AttributeError: 'functools.partial' object has no attribute 'deserialize'
--> 338         self.parser = self.parser_class.deserialize(data['parser'], memo, self._callbacks, self.options.postlex, self.re)
```

**To Reproduce**
I've modified the custom lexer example

```
from lark import Lark, Transformer, v_args
from lark.lexer import Lexer, Token

class TypeLexer(Lexer):
    def __init__(self, lexer_conf, re_=None):
        pass

    def lex(self, data):
        for obj in data:
            if isinstance(obj, int):
                yield Token('INT', obj)
            elif isinstance(obj, (type(''), type(u''))):
                yield Token('STR', obj)
            else:
                raise TypeError(obj)

grammar = """
        start: data_item+
        data_item: STR INT*
        %declare STR INT
        """
parser = Lark(grammar, parser='lalr', lexer=TypeLexer, cache=True)

# Fails
parser = Lark(grammar, parser='lalr', lexer=TypeLexer, cache=True)
```

**Comment by pwwang** [comment]
`functools.partial` is not picklable, according to python's pickling doc: https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled

You have to avoid using `functools.partial`. Instead, you can define a function at the top level of a module:
 
```python
# you may want to detail args and kwargs in your case
def MyLexer(*args, **kwargs):
  return LALR_CustomLexer(lexer, *args, **kwargs)
```

**Comment by MegaIng** [comment]
@pwwang What in that documentation makes sou think you can't pickle partial?

**Comment by pwwang** [comment]
@MegaIng My bad. I took it for granted. The actual reason is that `functools.partial` does not have `deserialize` method. The right way is to subclass.

**Comment by adefazio** [comment]
I've tried out the fix and it works.
https://github.com/adefazio/lark/blob/3d0928805be28c921b1816b116ba75cfae65515d/lark/parser_frontends.py#L21
It's not very elegant though. If that's ok I can make a pull request with the addition of a unit test perhaps.

**Comment by erezsh** [comment]
@adefazio It looks good to me, make a PR with a test.
