### ISSUE TITLE
"Unused" terminals are filtered out before post-lexer can handle them

### ISSUE THREAD

**Issue by jwcraftsman** [lark-parser/lark#616]
Over a year ago, I implemented parsing for a custom language with significant whitespace.  I used a custom post-lexer (written by me) to transform certain tokens (e.g. newline and following whitespace) into new tokens (e.g. indent, unindent) that are used in the grammar.  This worked fine with the version of lark I was using at that time.  When I resumed development with the current version of lark, my code no longer worked.  I discovered that the source of my problems is commit:

145d8a8e7c64046bc7938d7a5e4dfcecfbbcb6eb

which is associated with issue #309 

The problem is that I have some terminals that are not used directly in the grammar, but are used by the post-lexer.  Filtering these terminals out breaks everything.  I was wondering how I should handle this?  Is there some way to tell lark to not filter out certain terminals that appear to be unused.

Thank you for any advice you can provide.

-Jeff

**Comment by erezsh** [comment]
If they are unused, it means that they aren't filtered out, they're just never created. The error is probably because the parser doesn't expect them to exist.

In that case, you should use `%declare`, like in the examples.

Or did you mean something different?

**Comment by MegaIng** [comment]
#500 This should solve your problem.

**Comment by jwcraftsman** [comment]
@erezsh : I do use %declare for the terminals generated by my post-lexer.  That part works fine.  The problem is that I have terminals defined in my grammar (e.g. newlines) that are not used by rules listed in the grammar file, but are recognized and consumed by my post-lexer.  The post-lexer transforms the newline terminals into indent terminals, for example.  The commit I mentioned causes the newline terminals to be removed from the grammar because it thinks they are not used (it does not know that my post-lexer is going to use them).  The error I get is that a newline in my input does not match any terminal because lark removed that terminal, thinking that it was not used.  Does this explanation make the problem more clear?

**Comment by jwcraftsman** [comment]
@MegaIng Thanks for pointing me to that issue.  It looks like a similar problem, but I haven't gotten the workaround mentioned there (the "_unused" trick ) to work for me yet.  I will keep investigating.  Just for the record, I know the specified commit is the issue because things work if I revert that commit.  Thanks again!

**Comment by MegaIng** [comment]
@jwcraftsman Why didn't the unused trick work? It should work, if it doesn't work, it's a bug.

**Comment by erezsh** [comment]
@jwcraftsman I tried to recreate what you told me in code. It's working, so perhaps I misunderstood your problem?

```
from lark import Lark, Token

class PostLexer:
    def process(self, stream):
        yield from stream
        yield Token('C', 'c')

    @property
    def always_accept(self):
        return []

p = Lark('''
    start: "a" "b" C
    %declare C
''', parser='lalr', postlex=PostLexer())

print(p.parse("ab"))
```

**Comment by erezsh** [comment]
On a second read, I think I understand. Consider this solution:

```python
from lark import Lark, Token

class PostLexer:
    def process(self, stream):
        for i in stream:
            if i.type != 'D':
                yield i

    @property
    def always_accept(self):
        return ['D']

p = Lark('''
    !start: "a" "b" "c"

    unused_terminals: D
    D: "d"
''', parser='lalr', postlex=PostLexer(), start=['start', 'unused_terminals'])

print(p.parse("abdc", start='start'))
```

**Comment by erezsh** [comment]
It basically forces Lark to consider those terminals as used, without interfering with the main parse table (which I assume is what the "_unused" trick does).

**Comment by jwcraftsman** [comment]
I updated your original code snippet such that it exhibits my problem:

`from lark import Lark, Token

class PostLexer:
    def process(self, stream):
        for token in stream:
            if token.type == 'A':
                yield Token('C', 'c')
            else:
                yield token
        yield from stream

    @property
    def always_accept(self):
        return ["A"]

p = Lark('''
    start: C "b"
    A: "a"
    %declare C
''', parser='lalr', postlex=PostLexer())

print(p.parse("ab"))
`

This code worked before, but does not work after the commit I mentioned.

It looks like you have posted a solution for me to try in the meantime.  I think you understand my problem now.  I will try out your solution and get back to you.  Thanks!

**Comment by jwcraftsman** [comment]
This similar modification seems to fix our example:

```
from lark import Lark, Token

class PostLexer:
    def process(self, stream):
        for token in stream:
            if token.type == 'A':
                yield Token('C', 'c')
            else:
                yield token
        yield from stream

    @property
    def always_accept(self):
        return ["A"]

p = Lark('''
    start: C "b"
    A: "a"
    unused: A
    %declare C
''', parser='lalr', postlex=PostLexer(), start=['start', 'unused'])

print(p.parse("ab", start='start'))
```

I also tried this approach with my real grammar, and it works.  Thanks for all the help in resolving this.  I think it would be nice to find a way to make this a little more straight-forward, but this approach certainly works for now.

Thanks for your work on Lark -- it is a great tool that enables non-experts like me to create parsers for custom languages with straight-forward, clean code.

**Comment by erezsh** [comment]
That's a great testimonial, thanks :)

Btw, that means @MegaIng was right all along.

Maybe it would be a good idea to add a switch for it, something like `remove_unused=False`. What do you think?

**Comment by jwcraftsman** [comment]
Adding a `remove_unused` switch sounds good to me.  In the documentation for that switch, it might be a good place to mention that that it is useful in conjunction with a post-lexer, and that unused terminals are removed from the grammar by default.  Thanks!

**Comment by MegaIng** [comment]
@erezsh Which option would you prefer?

- Add an `%used TERMINAL` command to prevent it from being removed
- Add the `remove_unused` option to Lark.
- Add an `used` option to Lark
- Don't add anything, keep the current hack (my least preferred option)
- Postpone the unused Terminal removing to a latter stage
- Pass the Postlexer to `load_grammar`

I would prefer option 1 since it is the only option (except maybe 4/5) that doesn't create a problem with the standalone parser.

**Comment by erezsh** [comment]
Maybe option 6 could work, where we pass something like `always_accept` to the grammar loader.

**Comment by MegaIng** [comment]
I am pretty sure that all of these options are relatively easy to implement. The question is just which interface we want. I am just not sure that when the standalone parser is built, wouldn't the terminals be filtered out without the postlexer being available?

**Comment by erezsh** [comment]
I think the terminals are only filtered out when loading the grammar. The standalone parser doesn't do any such filtering, it just accepts whatever has been saved into it.

**Comment by erezsh** [comment]
Adding more and more options to the Lark init is always the easiest option. But I don't want to overload the interface if I can avoid it.

**Comment by MegaIng** [comment]
But currently the filtering happens in `load_grammar`, which is still called in the standalone generator if I am not wrong, so we would have to move it out of there I think. But I agree that overloading the interface is not a good idea.

**Comment by erezsh** [comment]
If you look at the code for generating the standalone, you'll see it doesn't even read `load_grammar.py`
