### ISSUE TITLE
Support for binary string (bytes())

### ISSUE THREAD

**Issue by mrschyte** [lark-parser/lark#617]
**Describe the bug**
Lark fails to parse Python3 binary strings. IMHO the following code should work:
```
import lark
print(lark.Lark('''
start: token
token: "a"+ | "b"+
''').parse(b'aabb'))
```

Currently running parse on a binary string results in a TypeError, since lark tries to apply an str typed regex to the binary input:

```
    return self.regexps[term.name].match(text, index)
TypeError: cannot use a string pattern on a bytes-like object
```

**Expected result**
Lark should be able to parse binary strings. It should check whether the input is a byte object and apply the regexps with a bytes pattern if needed.

**Comment by erezsh** [comment]
That's an interesting thought. I suppose there's a good reason you can't just convert the binary string to a unicode string?

If it was implemented, seems to me like the grammar would have to be a binary string as well.

**Comment by mrschyte** [comment]
Yes, I'm not able to convert to unicode as some fields might contain binary data in my input.

I've given it some thought and I don't think that the grammar itself should be a byte string.  If the whole grammar is a byte object, you lose the ability to specify unicode characters directly.

Terminals and regexp patterns could have a b'whatever' and b/.*/ notation similar to Python to indicate byte sequences.

The other solution I was thinking about is that you could decode a pattern or terminal using latin1 encoding to produce a bytes object when needed (when input is a bytes object). In this case you also have to account for unicode characters implementing something along the lines of:
```
def encode_bytes(xs):
  def encode_byte(x):
    try:
      return x.encode('latin1')
    except UnicodeError:
      return x.encode('utf-8')
  return b''.join([encode_byte(x) for x in xs])
```
```
>>> encode_bytes("ŵ:\xc5\xb5")
b'\xc5\xb5:\xc5\xb5'
```

**Comment by erezsh** [comment]
Solved. The following works:

```python
import lark
print(lark.Lark('''
start: token+
token: "a" | "b"
''', use_bytes=True).parse(b'aabb'))
```

**Comment by mrschyte** [comment]
Awesome! Thank you very much.

**Comment by createyourpersonalaccount** [comment]
Is there a bug in this? I tried using the calculator example with `use_bytes=True` but it wouldn't parse a NUMBER:

```
ValueError: could not convert string to float: Token('NUMBER', b'1')
```

I had to modify https://github.com/lark-parser/lark/blob/f68e3534f45ccfb481b68ca89ae387383a951e38/examples/calc.py#L46 to:

```python
    number = lambda _, token = float(token.value)
```

even though [`Token.value`](https://lark-parser.readthedocs.io/en/stable/classes.html#lark.Token.value) specifies that it is redundant to write `token.value` because it's always equal to `token`.

**Comment by erezsh** [comment]
@createyourpersonalaccount Yes, it seems to be a small oversight. You should open a new issue for it.
