### ISSUE TITLE
Documentation: Link to SPPF article is dead

### ISSUE THREAD

**Issue by liona24** [lark-parser/lark#621]
On https://lark-parser.readthedocs.io/en/latest/parsers/ in section **SPPF & Ambiguity resolution** the link for further information on SPPF seems to be expired.

Link for reference:
http://www.bramvandersanden.com/post/2014/06/shared-packed-parse-forest/

**Comment by erezsh** [comment]
It seems like the server is down. I would wait a while before deciding it's a dead link.

Meanwhile, here's a link that works: https://web.archive.org/web/20191229100607/www.bramvandersanden.com/post/2014/06/shared-packed-parse-forest/
