### ISSUE TITLE
Incorrect stub file

### ISSUE THREAD

**Issue by Inky-developer** [lark-parser/lark#622]
**Describe the bug**

the file `lark-stubs/lark.pyi` at `Lark.__init__` does not contain the new cache option parameter. This leads to some ides thinking that cache is an invalid parameter (tested in pycharm).

**To Reproduce**

Just install pycharm, create a project with lark and create a lark object with the cache option. Pycharm should warn about unexpected arguments.

Missing cache optione here:
https://github.com/lark-parser/lark/blob/b5abf2d7afcd70af2be6c57aa454e532c8a99a0b/lark-stubs/lark.pyi#L36-L61

**Comment by MegaIng** [comment]
These files are not auto generates, because there is a lot of internal stuff that shouldn't normally be exposed. A simple PR would be appreciated.
