### ISSUE TITLE
[documentation bug] `Interpreter` class undocumented

### ISSUE THREAD

**Issue by ctrlcctrlv** [lark-parser/lark#625]
The "Classes" documentation page (`classes.md`), in [&sect; `Interpreter`](https://github.com/lark-parser/lark/blob/master/docs/classes.md#interpreter), says `See the [visitors page](visitors.md)`.

[That page](https://github.com/lark-parser/lark/blob/master/docs/visitors.md) doesn't reference `Interpreter`.

**Comment by erezsh** [comment]
It does now. Thanks!
