### ISSUE TITLE
debugging help:  raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan)) lark.exceptions.UnexpectedCharacters: No terminal defined for ';'

### ISSUE THREAD

**Issue by judekanjamala** [lark-parser/lark#627]
So I am new to lark and parsing in general, therefore I am not sure if I am missing something trivial but i keep getting the following error:

     raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
     lark.exceptions.UnexpectedCharacters: No terminal defined for ';' at line 1 col 1

     ;; Function main 
     ^

     Expecting: {'COMMENT'}

when i try the following:

    tree = cfg_parser.parse(""";; Function main """) 

The grammar used to generate the parser is:

    %import common.WS
    %ignore WS

    start : (COMMENT)*

    COMMENT : ";;" /.*\n/

Could you tell me where it has gone wrong? Thanks!

**Comment by erezsh** [comment]
Your comment expects a newline.. The easiest solution is to always add `\n` to the input before parsing.

**Comment by judekanjamala** [comment]
Thanks so much. It works now.
