### ISSUE TITLE
Best way to parse s-expressions in Python

### ISSUE THREAD

**Issue by brando90** [lark-parser/lark#634]
**What is your question?**

What is the difference between using lark vs sexpdata for parsing s-expressions?

related: https://github.com/jd-boyd/sexpdata/issues/27

**If you're having trouble with your code or grammar**

No issues. Just curious.

**Comment by MegaIng** [comment]
sexpdata is specialized for s-expressions, lark is a general EBNF parsing library. With lark you have to write the grammar yourself. If sexpdata is optimized for performance, it will be faster.

**Comment by erezsh** [comment]
I'll just add the obvious, that with Lark it would then be possible to extend the syntax.
