### ISSUE TITLE
UnexpectedCharacters: No terminal defined for ':' 

### ISSUE THREAD

**Issue by ybbekele** [lark-parser/lark#635]
I am using lark to parse gatlevel netlist files and while capturing most of the features, it is throwing an error UnexpectedCharacters: No terminal defined for ':' for some structures. 
Here is the grammar:
`grammar = """
    start: (module)*
    module: "module" name parameters ";" (_statement)* "endmodule"
    parameters: "(" [ name ( "," name )* ] ")"
    _statement: input | output | inout | tri | wire | assign | instantiation
    input: "input" signal ( "," signal )* ";"
    output: "output" signal ( "," signal )* ";"
    inout: "inout" signal ( "," signal )* ";"
    tri: "tri" name ";"
    wire: "wire" signal ( "," signal )* ";"
    assign: "assign" name "=" name ";"
    instantiation: name name "(" [ pin ( "," pin )* ] ")" ";"
    pin: "." name "(" name ")" |"." name "(" name "[" /[0-9]+/ _COLON /[0-9]+/ "]"  ")" | "." name "({" ( name "," | "[" /[0-9]+/ ":" /[0-9]+/ "]" ",")* name "})"
    signal:  name | "[" /[0-9]+/ ":" /[0-9]+/ "]" name | name "[" /[0-9]+/ ":" /[0-9]+/ "]"
    name: ( /[a-z_][a-z0-9_\\[\\]]*/i | /\\\\[^\\t \\r\\n]+[\\t \\r\\n]/i | /1'b0/i | /1'b1/i )
    COMMENT: "//" /[^\\n]*/
    _COLON: ":"
    %import common.INT
    //%import common.HEXDIGIT
    %ignore ( /\\r?\\n/ | COMMENT )+
    %ignore /[\\t \\f]+/
    """`

While it gives an output for structures such as the one here:
  input [15:0] csb2nvdla_addr;
  input [31:0] csb2nvdla_wdat;
  output [31:0] nvdla2csb_data;
  GEN_AO22_D1 u_partition_o_ICCADs_U58941 ( .a1(
        u_partition_o_ICCADs_cdp2csb_resp_valid), .a2(
        u_partition_o_ICCADs_cdp2csb_resp_pd[20]), .b1(
        u_partition_o_ICCADs_n58263), .b2(
        u_partition_o_ICCADs_u_NV_NVDLA_csb_master_ICCADs_cdp_resp_pd[20]), 
        .z(u_partition_o_ICCADs_n35129) );

It throws the error above for the following structure:
GEN_AO22_D1 u_partition_o_ICCADs_U58941 ( .a1(
        u_partition_o_ICCADs_cdp2csb_resp_valid), .a2(
        u_partition_o_ICCADs_cdp2csb_resp_pd[20:9]), .b1(
        u_partition_o_ICCADs_n58263), .b2(
        u_partition_o_ICCADs_u_NV_NVDLA_csb_master_ICCADs_cdp_resp_pd[20:32]), 
        .z(u_partition_o_ICCADs_n35129) );
I tried to modify the code by creating a COLON terminal (as shown in the code) but the error persists.
I wonder what is going wrong.
PS: The file to be parsed is very large and has these kinds of structures repeatedly.
Appreciate your help!!

**Comment by MegaIng** [comment]
Please format your code with triple backticks ```` ``` ````. And these kind of support question are probably better for the [gitter chat](https://gitter.im/lark-parser/Lobby)

**Comment by ybbekele** [comment]
Thank you @MegaIng
