### ISSUE TITLE
How do I parse letters with accents?

### ISSUE THREAD

**Issue by oliveirandre** [lark-parser/lark#639]
Hello, 

I'm using a tool that aims to develop a dialogue manager in a state transition approach. To parse the user input, it uses Lark. I have no background using Lark, but this is the way the parser is defined: 

grammar = r"""
start: term (","? " "? term)*
term: rigid_sequence | disjunction | assignment | reference | macro | literal
rigid_sequence: "[!" " "? term (","? " "? term)* "]"
disjunction: "{" term (","? " "? term)* "}"
reference: "$" symbol
assignment: "$" symbol "=" term
macro: "#" symbol ( "(" macro_arg? (","? " "? macro_arg)* ")" )? 
macro_arg: macro_literal | macro
macro_literal: /[^#), ][^#),]*/
literal: /[a-z_A-Z@.0-9:]+( +[a-z_A-Z@.0-9:]+)*/ | "\"" /[^\"]+/ "\"" | "\"" "\"" | "`" /[^`]+/ "`"
symbol: /[a-z_A-Z.0-9]+/
"""
parser = Lark(grammar, parser='earley')

Since I'm portuguese and am developing my system to understand portuguese inputs, accented words are super important and the way that the parser is defined doesn't allow for accented chars (example: No terminal defined for 'é' at line 1 col 11). 

My question is: is there a simple way for me to change the parser so it can allow accented words without having background knowledge on Lark?

**Comment by erezsh** [comment]
The problem is with your regexp. 

`a-zA-Z` only matches English letters.

This isn't really a "Lark" issue, but I can give you a hint that `[^\W]` is one way to match all unicode letters.

```python
>>> re.findall("[^\W]+", "say héllo")
['say', 'héllo']
```

**Comment by oliveirandre** [comment]
Thank you for the answer!

Managed to tweak things a bit with your hint and make it work.
