### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by lucabecchetti** [lark-parser/lark#643]
Hi guys, I'm new with lark and I don't know if is the right tool, I have a python code that contains custom syntax like this:

@{Keydord}.method() or @{Keyword1}.method(param, param1) 

is this lark right to parse all this syntax and replace it with another string?

Thanks!

**Comment by MegaIng** [comment]
If the syntax is this simple, re might be enough. Otherwise you can rework the python grammar in examples to fit your needs.
