### ISSUE TITLE
what dose it mean  UnexpectedToken: Unexpected token Token($END, '') at end of input

### ISSUE THREAD

**Issue by RonaldinhoL** [lark-parser/lark#654]
how to write a rule to match $END?

**Comment by MegaIng** [comment]
The grammar doesn't expect the EOF at this point in the grammar.

**Comment by RonaldinhoL** [comment]
> The grammar doesn't expect the EOF at this point in the grammar.

That is to say,if the "start" grammar is whole matched, there will not be an error when meet EOF, is it right?

**Comment by MegaIng** [comment]
Yes

**Comment by RonaldinhoL** [comment]
> Yes

thank you very much! ：）
