### ISSUE TITLE
Provide a way to list orphaned rules in the grammar

### ISSUE THREAD

**Issue by charles-esterbrook** [lark-parser/lark#658]
For example, list the orphaned rules with `logging.debug()`.

The benefits for listing orphans:

- May inform the developer that a rule they thought was part of the grammar is actually not.
- Helps clean up grammars that evolved over time when removing such unused rules.
- Removing orphans prevents misinforming those who read the grammar that the orphans are part of the grammar though they are not.

Recently discussed on Gitter

**Comment by erezsh** [comment]
Fixed. To enable do the following

```
from lark import logger
logger.setLevel(logging.DEBUG)
```
