### ISSUE TITLE
caret indicator in error messages doesn't take into account tabs in line

### ISSUE THREAD

**Issue by starwarswii** [lark-parser/lark#663]
run this code and look at the output error message:
```python
from lark import Lark

grammar = '''
%import common.WS
%ignore WS

start: "a"
'''

p = Lark(grammar)

p.parse("\tb")
```

for me, this outputs:
```
...
lark.exceptions.UnexpectedCharacters: No terminal defined for 'b' at line 1 col 2

        b
 ^

Expecting: {'A'}
```

note that the caret is not properly lined up with the incorrect character "b"
there are 8 spaces in front of the b in the output, but, 1 space in front of the caret
(8 is probably because it's the tab size for cmd.exe, and i'm sure the number varies per environment)

if spaces are used instead, the caret lines up properly.

if you replace the `\t` in `p.parse("\tb")` with an embedded tab character:
```
p.parse("	b")
```
you get the same result

i think lark is treating the tab as a one-width character, when it should be expanded to some number of spaces.

I'm on windows 10, 64-bit
Python 3.8.3, 64-bit
Lark 0.9.0

**Comment by starwarswii** [comment]
looked through the code and I believe one way this can be solved is by using `str.expandtabs()` in `UnexpectedInput.get_context()` in `exceptions.py`

using `len(before.expandtabs())` instead of `len(before)` seemed to fix my local copy.

**Comment by erezsh** [comment]
Good catch. Submit a PR?

**Comment by starwarswii** [comment]
with just that one tiny change? sure.
