### ISSUE TITLE
Designing a new forest visitor interface

### ISSUE THREAD

**Issue by chanicpanic** [lark-parser/lark#673]
I noticed in the docs that there are plans to make processing the SPPF more user-friendly. After becoming familiar with the current implementation, I am interested in taking this on. Of course, I would like some input on what a good interface might look like.

**Notes on the current implementation**

1. `ForestVisitor` is an abstract base class for performing a depth-first walk of the SPPF with the `visit` method. 
2. Subclasses of `ForestVisitor` receive events from the super class via  specific method overrides. Namely,

  - `visit_token_node`
  - `visit_symbol_node_in`
  - `visit_symbol_node_out`
  - `visit_packed_node_in`
  - `visit_packed_node_out`

3. The walk is controlled by the return value of the `visit_symbol_node_in` and  `visit_packed_node_in` methods.

  - If `None` is returned, the visitor will begin to backtrack.
  - If a node is returned, it will be visited next.
  - If an iterator over nodes is returned, they will be visited in order.

4. The return value of `visit` is the value of `self.result`. Subclasses are expected to manipulate this value during the visit.

5. When an attempt is made to visit a node that is already being visited (i.e. a cycle), an exception is thrown by `ForestVisitor`. Recovering from this as a subclass is effectively impossible.

**My thoughts**

i. Visiting by subclassing is the right approach. This is consistent with  the Visitors and Transformers for trees.

ii. Handling nodes by overriding certain methods seems reasonable. The set  of methods is also functional. It could be expanded by adding separate methods for intermediate nodes (more reflective of the structure of the  SPPF). Or, an entirely different/higher level interface could be used.

iii. Controlling the walk could certainly be simplified/reworked, although I  am not sure what a good approach would be. At the very least, I would  add support for returning an iterable of nodes.

iv. The current way of setting a return value does not feel quite right. I have not thought of a good alternative at the moment.

v. I think the superclass should notify the subclass of a cycle. Perhaps through another method. That way, the subclass can decide how to proceed. 

vi. Does the current implementation do too much? Right now, it has aspects of all of Interpreter, Visitor, and Transformer for trees. Should these functionalities be separated?

**Comment by erezsh** [comment]
I'll be happy to accept a PR that simplifies that interface. Generally I agree with what you wrote, but I don't feel like I have anything smart to say at the moment.

Anything that's more in-line with the Transformer/Interpreter of the Tree class seems like the right direction.

If you come up with some ideas for the alternative interface, perhaps I'll be able to comment and advise.

**Comment by chanicpanic** [comment]
As of now, I have kept the `ForestVisitor` mostly the same except for the small changes I mentioned above. As I do not have an idea of what most people want to get out of an SPPF walk, I am leaving it at its low-level as an advanced feature.

I have made a `ForestTransformer` on top of the visitor that is also "low-level" (methods are based on node type). This separates the visit from the production of a result.

As I figured a common transformation would be to a tree, I implemented a class to facilitate this which uses an interface similar to the tree `Transformer`. Upon further inspection, I found that the implementation might be flexible enough to be used for more than tree transformations. i.e. A user would not have to fallback to `ForestTransformer` to perform a non-tree transformation of a forest.

I have opened a draft PR, #675 , so you can see the code.

**Comment by erezsh** [comment]
Overall it looks pretty good! But I didn't dive into the code itself, and so I might have some comments later on.

I usually ask contributors to rebase their commits to reduce the clutter in the git log. It's okay to have a few tiny commits here and there, but ideally changes should be grouped together into a small number of logical steps.

**Comment by chanicpanic** [comment]
> I usually ask contributors to rebase their commits to reduce the clutter in the git log. It's okay to have a few tiny commits here and there, but ideally changes should be grouped together into a small number of logical steps.

Of course, when you are happy with the code, I will make a new PR with a cleaner history.

A question I had: For the final version, would you want the utilities to be in `earley_forest.py`, or would you want them to be in `visitors.py` or some new file?

**Comment by erezsh** [comment]
What do you mean by utilities?

I think anything which is sppf-specific should be in `earley_forest`, but if there's anything that's more generic, then perhaps it's worth moving it out. I'd say my default would be to keep it in, unless there's a good reason.

**Comment by chanicpanic** [comment]
I meant `ForestVisitor`, `ForestTransformer`, and `TreeForestTransformer`. My thought was that as users would subclass them, they would have to import from `lark.parsers.earley_forest`. As far as I know, no other objects meant for general use are in `lark.parsers`. Of course, they could be kept in `earley_forest` while making them importable from another module.

**Comment by erezsh** [comment]
Yeah, that's probably for the best. I think subclassing them won't be very obvious for the casual user anyway.

But if you'd like to provide some user-facing documentation about it and an example of how to use it, it would go a long way to improve the chances that it will be used.

**Comment by chanicpanic** [comment]
True. In the future I'll write documentation and examples for it.

On a related note, for the classes to be useful, I think lark would need an option for earley to return the forest instead of a tree. Maybe `ambiguity='forest'`?

**Comment by erezsh** [comment]
Yes, that sounds like a good idea.

The idea has come up before, but the interface was too complicated.

**Comment by erezsh** [comment]
This can be closed right? Seems like you achieved all the goals.
