### ISSUE TITLE
How does tree class must behave?

### ISSUE THREAD

**Issue by omega16** [lark-parser/lark#676]
**What is your question?**
Hi. 

What things would I have to have in account to use a custom Tree class? 

**If you're having trouble with your code or grammar**

I was jumping from python-lark to haskell parser back and forward again and again, then I found mypy and it seems like what I want, a python with static type checking. I could be only me, but I feel like Haskell static type inference helps a lot to define how to transform a parsed tree. 

The problem with current lark Tree is that stub file has `data: str` and `children : List[Union[str, Tree]]` and I want to use some custom class in my tree (like Enums in data or annotations in the tree), so, when i attempt to build a Tree with Enum in Data on my transformer, mypy complains for the type clash and that's right! 

An approach must be to just subclass Tree (or string like Token), add parameters that don't clash with the internal Lark parameters and leave `data =""` at transformer. Problem is, well, I don't know how this would affect lark, like "hey! were does my file error reconstruction go?". 

In the same line of sub-classing I suppose I can use the python `@property`to do a trick like the `meta` does on the Tree so that `var1 = tree.data` construct the correct `data` that lark expects. I don't know if mypy would allow this (most probably it wont) 

A third approach would be to copy the entire Tree class and rewrite it to support polymorphism in a transparent way, some that instead of say "i want to be a string but i don't" says "I need this exactly set of functions right now to be fully compatible with lark". This maybe affect lark performance (i suppose that's the reason of subclassing `str`) so it would need to be a completely independent tree class. 

So, What things does I need to be aware of at replacing Lark Tree ? 

Note: Just lying to mypy is not an option as this would just invalidate all the point of use mypy.

----------------------------------------------

-----------------------------------------------

 I want to say thanks for Lark. 
Lark it's my favorite tool to write parsers out of haskell parsec (sadly parsec and in general monadic parsing is a BIG NO to be used in python since python and recursion don't behave good). It's just easier than other advanced frameworks and let's you do a lot of things! .

**Comment by erezsh** [comment]
Iirc, all Lark really expects from `Tree` is its attributes (`data & children`) and that equality will work (i.e. `__eq__`).

It might be a good idea to implement `Tree.copy()` and `Tree.__hash__()`, but I don't think it's even necessary.

I haven't tried it, but why not just subclass from Tree and override the type?

```python
class MyTree(lark.Tree):
    data: typing.Any
``` 

I think it should work for mypy, and `Tree` really doesn't care what type is data. We only set it to string so it will work with Lark's visitors and transformers.

------

Thanks for the compliment! I hope

**Comment by omega16** [comment]
Exactly!

That's the problem, I can't `data=EnumClass.attrib` without break visitor an tranformers and that's the reason I'm using Lark XD . But apart from them, I don't need the string on data, so, being capable of storing the enum and use them to provide a data like this:

~~~python
class RealTree(Tree):
    data_ :Enum
    @property
    def data(self):
        return str(data_)

    def __init__(self,
                data :Enum,
                children: typing.List[typing.Union[str, Tree]], 
                meta : typing.Optional[Meta]= None
                ):
        super().__init__("", children, meta)
        self.data_=data
~~~

That would be great and mypy allows it without `typing.Any`, but python complains : 
`AttributeError: can't set attribute`

By the other side, using `typing.Any` is against the purpose of use typing and mypy (please, just don't do that, all people using python type checker would be grateful to you if you don't do that or if you do, you will become the target of all it's frustration).

What I'm trying to do is to have a generic Tree of two types and compatible with lark, like: 

~~~python

GenericVar1 = typing.TypeVar("GenericVar1")
GenericVar2 = typing.TypeVar("GenericVar2")
class Leaf(typing.Generic[GenericVar1]):
    value :GenericVar1
    type_ :Enum
    
    def __init__(self, type_: Enum, value: GenericVar1):
        self.value = value
        self.type_ = type_
    

class SimpleTree(typing.Generic[GenericVar1, GenericVar2]):
    my_data: GenericVar1
    my_children: typing.Sequence[typing.Union["SimpleTree[GenericVar1, GenericVar2]", Leaf[GenericVar2]]] 
    meta_ : typing.Optional[Meta] 
    
    def __init__(self, 
            my_data: GenericVar1,
            my_children: typing.Sequence[typing.Union["SimpleTree[GenericVar1, GenericVar2]", Leaf[GenericVar2]]], 
            meta: typing.Optional[Meta]
            ):
        self.my_data=my_data
        self.my_children=my_children
        self.meta_=meta

    @property
    def data(self):
        #transform data here and save on var "new_data"
        return new_data

    @property
    def children(self):
        #transform children here and save on var "new_children"
        return new_children
~~~

Why?

That's the way to work with types! without the `typing.Any` but using Generics.

So a `SimpleTree[Union[str,Enum], CustomClass]` would be a Tree with `my_data` a string or Enum no less and no more and that only allows the Leafs to have value `CustomClass`. Python won't enforce this but mypy can now do the inference work! And even better, the propertyes for `data` and `children` can be used to allow Visitors and Transformers without change them (unless they use another representation). 


Just in case you haven't notice it, counting with mypy support save your from a ton of errors. 

~~~python
grammar = """ 
INTEGER: /([1-9][0-9]+)|(0+)/
STRING : /"[a-zA-Z]*"/
expr: INTEGER
| STRING
sume: expr "+" expr
start: sume
"""
#asume we pass some Token tranformer to have STRING as Leaf[str] and INTEGER as Leaf[int] instead of tokens
parser = Lark(grammar, class_tree=SimpleTree, ...)

class Trans(Transformer):
    @staticmethod
    def expr(nodes: typing.Sequence[Leaf[Union[str,int]]])->
        SimpleTree["CustomMyData", Union[str, int]]:

        value1= Leaf.value
        value2= Leaf.value
        #mypy can't infer if value1 or value2 are ints or str and would complain
        return SimpleTree(value1+value2,...)
~~~

If that snnipet works (i wrote that on browser, so, no test) and we use `Trans` on parsed tree, then python could say at runtime: 
`TypeError: can only concatenate str (not "int") to str`
in case we pass " 'abc'+ 1" to the parser, instead if we follow mypy complain we could found on time some claim like: 
~~~
Error, value1 can be one of "str" or "int" and value2 can be one of "str" or "int", the operator "+" won't allow to sum "str" and "int"
Maybe use the isinstance function to determine value1 and value2 type
~~~
(or somethin like that, again, was wrote on browser, without test)
Then we can notice the error and add an `if isinstance(value1,int) and isinstance(value2, int) : ...` we could prevent the python runtime error. 

This is a simple case, but as grammar grows the number of special cases become bigger and then it start to be as a hell of cases. The best tool we can have to save us from omit a case would be mypy. 

That's why writing parsers on static strong typed languages is a pleasure most of the time, the compiler complains about edge cases and force you to maintain the cases hell properly. This is especially useful if you are developing your grammar (as I'm doing), you don't need to be as afraid of changes if you adjust the types and let compiler point what you omit. 

So I have been jumping from python to haskell just for this reason, I'm more comfortable writing python code, but even with lark I'm more comfortable developing the grammar on haskell, now, with mypy, I can have type check and can be even more comfortable only using python.


So, my question is, what other places would  I check for the uses of tree (and now token) to have a Generic Tree fully compatible with all of lark ? 

Something like: "I know you won't expect to have a Tree or Token dependence on the module 'foo' but in fact we use the internal parts of Tree un a non expected way here.. to provide that..." 

I'm aware that in Cpython implementation of python, the new tree would be less performant (but safe to use mypy to work with it) but I'm not that sure about pypy and mypyc since both could use the typing to apply some aggressive code transformations if they want. With that said, I don't expect to merge the three here and replace the actual tree (don be crazy), in fact i just want the tree for myself (unless this become a interest point an then of course i'm willing to contribute : ) )

**Comment by erezsh** [comment]
Wow, that was long! I have to say I don't really understand the problem. Any chance you can summarize that for me?

This code works:

```
from lark import Tree

class Enum:
    pass

class RealTree(Tree):
    data_ :Enum
    @property
    def data(self):
        return str(self.data_)
```

Maybe you can provide a minimal example that doesn't work?

**Comment by omega16** [comment]
Basically: 
I wan't to fully use mypy help  to write code and want a Tree that behave in a consistent way to what I'm saying to mypy that at the same time is full compatible with all of the features of lark and allow me to put custom data.

This trick could work but i would add :


~~~python
@property
def children(self):
  #construct a list that won't clash with the other functions in the Lark Tree
  return generated_list
~~~

I will see if it could do all the needed things (most of what is in my previous post is a explication of my use case, if this works, just ignore it). 

Just a important remark from the long post : **Please DON'T use typing.Any** unless you want all the people using a type checker to complain on you. Instead use the **Generics** and **Union** unless you are pretty sure that the annotated var would need to change his type in unexpected ways.

**Comment by erezsh** [comment]
I think Lark already uses generics when relevant, and `Any` is pretty rare in the codebase, no? 

Okay, let me know if you need any help.

**Comment by omega16** [comment]
It works!, it even works for Tokens!

Now i can use Transformers, visitors and pretty with custom Token and Parser
