### ISSUE TITLE
Table at json tutorial isn't rendering

### ISSUE THREAD

**Issue by omega16** [lark-parser/lark#677]
The table at end of json tutorial on read the docs ([here](https://lark-parser.readthedocs.io/en/latest/json_tutorial.html)) is treat as plain text.

I haven't work with readthedocs or sphinx but acording to doc:

sphinx uses MkDocs to render CommonMarkdown ([here](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html#external-resources))

MkDocs uses python-markdown to transform to CommonMarkdown to html ([here](https://www.mkdocs.org/user-guide/configuration/#markdown_extensions)) and allow extensions like `tables` by default.

It seems to my like MkDocs is disabling the `tables` and it needs to be configured to allow `tables` ([here](https://docs.readthedocs.io/en/stable/config-file/v2.html#mkdocs)).

In case it's other kind of problem an alternative would be to just put and html `table`

As say, I haven't work with sphinx or readthedocs and right now I can't test if changing configuration works (I don't know if even I can test it since i don't know if i need a readthedocs fake account to test).

**Comment by erezsh** [comment]
Thanks for pointing it out. We just changed from mkdocs to sphinx last week, so it makes sense that a few adjustments will be necessary.

@chsasank Any ideas?

**Comment by chsasank** [comment]
Sphinx now uses recommonmark to render markdown. Tables should be part of its markdown parser. It's probably a matter of formatting the markdown the way recommonmark wants.

**Comment by erezsh** [comment]
So, where can I read about what it wants?

**Comment by chsasank** [comment]
All of the docs are here I guess: https://recommonmark.readthedocs.io/en/latest/auto_structify.html?highlight=table#auto-toc-tree . Table is not there unfortunately :(

Not sure normal markdown tables are supported or not: https://talk.commonmark.org/t/tables-in-pure-markdown/81

**Comment by erezsh** [comment]
Fixed.

**Comment by chsasank** [comment]
sphinx_markdown_tables huh. Nice!
