### ISSUE TITLE
How to speed up lark for a simple grammar?

### ISSUE THREAD

**Issue by sygi** [lark-parser/lark#685]
I have a very simple grammar:
```
predicate: CNAME
           | CNAME "(" arg_list ")"

arg_list: predicate ("," predicate)*
```

I am parsing mostly short strings, on the order of 100 characters.
I used to use my hand-written ONP parser to parse it, which worked fine, but I didn't want to support it.

I gave lark a go, but I observed a huge (around 30x, from ~0.5ms to 14ms) increase in parsing time.

Is there any way I may be able to make lark faster under the assumption that my grammar is very simple and my texts are short? Any idea why it may be so slow (I don't count transforming nor building the parser in the timing above, although my parser also does a transformation after parsing).

**Comment by MegaIng** [comment]
Hand written parsers will always be faster than any library. You could try parser combinatorics as an alternative to lark ( I am assuming you are already using lalr instead of early). But this discussion is better had on [gitter](https://gitter.im/lark-parser/Lobby).

**Comment by erezsh** [comment]
Are you using `parser="lalr"`?

**Comment by erezsh** [comment]
@MegaIng 

> Hand written parsers will always be faster than any library

That may be true for expertly written grammars. But I don't think it would be very easy to beat Lark on a non-trivial grammar.

**Comment by MegaIng** [comment]
@erezsh 
Yes, but this specific grammar is really simple.

**Comment by sygi** [comment]
Thank you for such a quick response! Indeed, adding `parser="lalr"` improves speed 10x for me, making lark ~3x slower than my hand-written parser, which I'd find acceptable.

**Comment by erezsh** [comment]
It can be made even faster. Read the JSON tutorial for tips.
