### ISSUE TITLE
`exceptions.pyi` is missing `UnexpectedEOF`

### ISSUE THREAD

**Issue by rshin** [lark-parser/lark#686]
`UnexpectedEOF` is defined here: https://github.com/lark-parser/lark/blob/fbab27ce0b9d447e82a57bf4ce0a299ff42094e8/lark/exceptions.py#L18

However it's missing from `exceptions.pyi`: https://github.com/lark-parser/lark/blob/fbab27ce0b9d447e82a57bf4ce0a299ff42094e8/lark-stubs/exceptions.pyi#L27

This means that if you have
```python
import lark.exceptions
lark.exceptions.UnexpectedEOF
```
then mypy will complain about a missing attribute.

**Comment by erezsh** [comment]
Thanks! Added in `master`
