### ISSUE TITLE
A backreference in a regular expression pattern causes exceptions

### ISSUE THREAD

**Issue by rec** [lark-parser/lark#690]
**Describe the bug**

Trying to use a backreference in a regular expression gets one of two tracebacks.

**To Reproduce**
[test_simple.py.txt](https://github.com/lark-parser/lark/files/5239106/test_simple.py.txt)

Results of that test program are here:

[parsing-attempts.txt](https://github.com/lark-parser/lark/files/5239113/parsing-attempts.txt)

**Analysis**

The regular expression which is actually compiled contains the given regular expression as a parenthesized subexpression, so it makes sense that `\1` doesn't work, but I don't understand the issue on `\2`.

**Comment by rec** [comment]
(i would have tracked it down further but for some reason my pdb is broken on this machine.  :-/ )

**Comment by rec** [comment]
Actually, let me just paste the file here:

```
import traceback, sys
import lark


class Transformer(lark.Transformer):
    def binary(self, b):
        print('--> Parsed', b, type(b))
        return b


def make_parser(data):
    return lark.Lark(
        data,
        transformer=Transformer(),
        parser='lalr',
        lexer='standard',
        propagate_positions=False,
        maybe_placeholders=False,
    ).parse


TO_MATCH = 'XOXO'

REGEXS = [
    r'X(.)X.',   # Should succeed and does
    r'X(.)X',    # Should fail and does
    r'X(.)X\1',  # Fails because this regex is embedded in another
    r'X(.)X\2',  # Fails for unclear reasons
]

GRAMMAR = """
?start: binary
binary : /{}/
"""

if __name__ == '__main__':
    for r in REGEXS:
        print()
        grammar = GRAMMAR.format(r)
        print('--> Compiling', r)
        try:
            parser = make_parser(grammar)
        except:
            print('--> Failed')
            traceback.print_exc(file=sys.stdout)
            continue

        print('--> Matching')
        try:
            parser(TO_MATCH)
        except:
            print('--> Failed')
            traceback.print_exc(file=sys.stdout)
            continue

        print('--> Success!')

    print('DONE')

```

**Comment by erezsh** [comment]
This isn't an issue with Lark. Your regexps are illegal.

Run this:

```python
>>> import re
>>> re.compile('X(.)X\\2')
  File "C:\Python38\lib\sre_parse.py", line 423, in _escape
    raise source.error("invalid group reference %d" % group, len(escape) - 1)
re.error: invalid group reference 2 at position 6
```

**Comment by rec** [comment]
Read more closely, please.  :-D

**Comment by rec** [comment]
This regexp fails:  r'X(.)X\1' - it is legal.

The reason it fails is because in one place, you embed the regex in another one.

**Comment by erezsh** [comment]
Okay, so here's a minimal example:
```python
import lark

GRAMMAR = r"""
?start: binary
binary : /X(.)X\1/
"""

p = lark.Lark(GRAMMAR, parser='lalr')
print(p.parse('XOXO'))
```

It indeed fails but probably shouldn't. I'll look into it.

**Comment by rec** [comment]
Yes, sorry, I wanted to show my attempted workaround too.

This is my last blocker before finishing my (self-imposed) project, so I'm eager to proceed - I shouldn't be so impatient!

**Comment by erezsh** [comment]
Okay, so the issue is that Lark uses named capturing groups in order to efficiently match several regexps at once. It seems that it's impossible to have a named group not affect the capturing numbers: https://stackoverflow.com/questions/16471776/named-non-capturing-group-in-python

My suggestion is to use a named group instead of a numbered group.

This seems to work:

```python
import lark

GRAMMAR = r"""
start: /X(?P<REC1>.)X(?P=REC1)/
"""

p = lark.Lark(GRAMMAR, lexer='standard')
print(p.parse('XOXO'))
```

Just take care that you use a unique name, that won't collide with other terminal names.

**Comment by erezsh** [comment]
Happy that we managed to entertain you ;)

**Comment by rec** [comment]
Oh, gah, why didn't I think of a named group?!  That's a better solution anyway.
