### ISSUE TITLE
Visitor visits nodes in the wrong order

### ISSUE THREAD

**Issue by Nolagx** [lark-parser/lark#692]
**Describe the bug**

It seems that the Visitor class visits the tree nodes in the wrong order. Recursive_Visitor behaves correctly.

**To Reproduce**

I used the following script:

```

from lark import Lark, Visitor
from lark.visitors import Visitor_Recursive

my_grammar = """
?start: (statement _NEWLINE)*

?statement: rule
          | name -> only_name

rule: name "<-" rule_body

rule_body: name

name: NAME

%import common.CNAME -> NAME
%import common.WS_INLINE
%ignore WS_INLINE
%import common.NEWLINE -> _NEWLINE
%ignore _NEWLINE
"""

my_input = """
b
c <- b

"""


class TestVisitor(Visitor):

    def __init__(self):
        super().__init__()

    def only_name(self, tree):
        print("A")

    def rule_body(self, tree):
        print("B")

    def rule(self, tree):
        print("C")


def main():
    parser = Lark(my_grammar, parser='earley', debug=False)
    parse_tree = parser.parse(my_input)
    TestVisitor().visit(parse_tree)


if __name__ == "__main__":
    main()

```

when TestVisitor inherits from Visitor the output is:
B
A
C

while when TestVisitor inherits from Recursive_Visitor the output is:
A
B
C

I believe the expected output should be the output of Recursive_Visitor in both cases.

This is the tree the parser produces:
(with pretty())
```
start
  only_name
    name	b
  rule
    name	c
    rule_body
      name	b
```

(without pretty())
```python
Tree(start, [Tree(only_name, [Tree(name, [Token(NAME, 'b')])]), Tree(rule, [Tree(name, [Token(NAME, 'c')]), Tree(rule_body, [Tree(name, [Token(NAME, 'b')])])])])
```

**Comment by erezsh** [comment]
It seems that one of them iterates depth first, while the other iterates breadth-first. However, they both always iterate the subnodes before proceeding to the parents. So in that sense, I wouldn't say it's wrong.

Visitors (and transformers) should maintain depth hierarchy, which they do. I'm not sure if it's important to have a strict ordering besides that. I'm not even sure which is more correct.

I do think it makes sense to add a comment on each one explaining the difference.

But I'm open to be convinced otherwise. And if anyone wants to submit a patch that aligns them, I will accept it.

**Comment by Nolagx** [comment]
In the original program I was writing (this is a very simplified version), I wanted to check if a variable was declared before being referenced. I could not do that with the normal visitor, as it visited the second statement before the first.

This is also the case with the grammar that I posted here. You can't check with the normal visitor that "b" from the second statement was previously declared.

I think this behavior is wrong since in most programs the statements of the program depend on each other and the behavior of the program depends on the order of the statements, so it makes sense to be able to visit the statements in their original order.

**Comment by MegaIng** [comment]
@Nolagx For that exact use case there is the Interpreter class which gives you full control. The Visitors are designed to locally modify each node without context.

**Comment by Nolagx** [comment]
@MegaIng Thank you. It seems I have misunderstood the purpose of the visitors.
