### ISSUE TITLE
Incorrect behaviour for maybe_placeholders

### ISSUE THREAD

**Issue by MegaIng** [lark-parser/lark#696]
**Describe the bug**

When maybe constructs are nested, maybe_placeholders gets confused.

**To Reproduce**
```
from lark import Lark

parser = Lark("""
start: [A [B]]

A: "a"
B: "b"
""", maybe_placeholders=True)

print(parser.parse(""))
print(parser.parse("a"))
print(parser.parse("ab"))
```

produces

```
Tree(start, [None])
Tree(start, [Token(A, 'a'), None])
Tree(start, [Token(A, 'a'), Token(B, 'b')])
```
instead of the expected

```
Tree(start, [None, None])
Tree(start, [Token(A, 'a'), None])
Tree(start, [Token(A, 'a'), Token(B, 'b')])
```

I don't know how the generation works, but I will try to look into it.

**Comment by erezsh** [comment]
Hmm... I don't know, it actually seems like the right behavior to me.

```python
 start: [A B]
```

Will also produce `Tree(start, [None])`, which is what's expected, so I don't see why `[A [B]]` should behave differently.

**Comment by MegaIng** [comment]
Then I would strongly suggest tying to change this behavior. In my understanding the purpose of this was to allow the inline transformer/tuple unpacking or something similar to always expect the same number of children. This is obviously not the case here.

**Comment by ornariece** [comment]
i agree with @MegaIng 's argument, this prevents proper unpacking as you can't expect the same number of children.
i can't think of a case where that behavior would be preferable to producing None for each potential children, am i missing something?

**Comment by erezsh** [comment]
I forgot to respond. I can see how this suggestion is more practical than the current behavior. I won't object to a PR that changes it.
