### ISSUE TITLE
Provide option to get whitespace tokens even when ignored

### ISSUE THREAD

**Issue by fabioz** [lark-parser/lark#697]
**Suggestion**
I have a language where something as "NAME NAME" is a single identifier, yet, to parse the language I decided to ignore whitespaces (so, a rule like that is simply NAME+), but now, I'm unable to directly get the tokens that'd comprise the identifier, so, I'd like to check if there would be a way to get those whitespace tokens (at least inside that single rule).

**Describe alternatives you've considered**
Right now I'm able to make it work by having the original (full) source and then getting the name I want from the start_pos/end_pos, but I was hoping to have a way to get those tokens from the parser itself.

**Comment by erezsh** [comment]
I don't really see what is the problem. If you define NAME as

```
NAME: /[\w]([\w\d ]*[\w\d])?/
```

It should catch spaces even if they are ignored.

**Comment by fabioz** [comment]
Humm, the problem is that this would then match more than expected...

For instance, if I have something as `From my.module Import (Some Function With Spaces AS Something Else)` it'll match the `AS` as part of the word in that regexp and not as a keyword...

As a reference, what I have for that is something as:

```
import_from: "from"i import_from_path "import"i "(" import_from_as_name ("," import_from_as_name)* [","] ")"
import_from_path: (NAME | "." | "/")+
import_from_as_name: import_alias_name ["AS" import_alias_as_name]
import_alias_name: (NAME | " ")+
import_alias_as_name: (NAME | " ")+

NAME: /[a-zA-Z_]\w*/
%ignore /[\t \f]+/  // WS
```

So, if I change it to match whitespaces with a regexp as proposed it'd match the keywords (which is not expected).

**Comment by erezsh** [comment]
I don't understand the rules of your language. So `a has b` is an identifier, but `a as b` is two identifiers separated by "as"?

**Comment by fabioz** [comment]
Yes -- except that identifiers are all uppercase, so, in `a AS b` it's something as: `identifier`  `AS keyword`  `identifier` whereas in `a as b` there's a single identifier.

**Comment by fabioz** [comment]
Actually, not all identifiers are actually all uppercase -- when possible they're case independent (so, the `from` and `import` there can be in any case, but as the `AS` there which appears between words needs to be all uppercase (so, when possible it's case-independent and when required to remove ambiguity it must be all uppercase).

**Comment by erezsh** [comment]
That's a little confusing.. But I'm sure Earley can handle it. But you might have to use `lexer="dynamic_complete"`, at the cost of runtime speed.

**Comment by fabioz** [comment]
Well, I have a workaround already (at the cost of keeping the original source until the ast is built), so, using the lalr approach seems to be working reasonably well... (I prefer speed vs the cost of having such a minor inconvenience).

Feel free to close this issue if you believe it's hard to incorporate this into the lalr approach (really, I don't want to litter your project with things you feel don't feel are well suited for it and I do have a workaround already, so, it's probably pretty low priority).

p.s.: Thanks for Lark. I just started using it and it seems pretty nice -- I do have some previous experience parsing with JavaCC... initially I started investigating using antlr in Python, but it didn't feel very Pythonic to use whereas Lark does feel like that, so, thanks for the nice project.

**Comment by erezsh** [comment]
I think the workaround should be pretty straightforward. Just do something like

```ruby
name: NAME+
```

The lexer should be clever enough to recognize keywords as separate from `NAME`.

Thanks for the compliments!

I'll close the issue, but let me know if you have any more difficulties. I'll do my best to help!
