### ISSUE TITLE
TreeIndenter cannot _DEDENT back to column 1

### ISSUE THREAD

**Issue by richarddb** [lark-parser/lark#701]
Following the example for the "whitespace significant" language, the following will fail to parse:

```
a
    b
    c
d
```

A workaround is to insert a "fake" root element, such as:

```
BEGIN
    a
        b
        c
    d
```

It seems that the initial indentation level should be initialised in the __init__ method.

**Comment by erezsh** [comment]
Lark follows Python as the model for significant indentation.

Try to run this code:
```python
  print("hello")
  # notice both these lines are indented
```

**Comment by richarddb** [comment]
My comment formatting went out, so perhaps I didn't make myself clear. I do understand that the two indented lines will fail in Python. But the following would work in Python:

```
print('hello')
print('world')
```

It's this structure that I think does not parse in Lark. It will give an error of the form:

```
lark.exceptions.UnexpectedToken: Unexpected token Token(...) at line 2, column 1.
Expected one of: 
	* $END
```

**Comment by MegaIng** [comment]
This is probably a mistake in your grammar, that your grammar doesn't expect multiple instances of the same rule. We can't help you without your showing us your grammar.

**Comment by erezsh** [comment]
Closing this issue. If you still think this is a problem in Lark, please reopen with proof.
