### ISSUE TITLE
Handle resources when running from zipped archive

### ISSUE THREAD

**Issue by sinoroc** [lark-parser/lark#703]
For context, _Poetry_ depends on [_poetry-core_](https://pypi.org/project/poetry-core/) which itself uses _lark-parser_. I have been experimenting with running _poetry_ from a zipped archive (see [_`zipapp`_](https://docs.python.org/3/library/zipapp.html)). But apparently _lark_ relies a lot on things such as `__file__` and `__path__` to load resources (_package data_), and this is not possible when the code is running from a zipped archive.

The right way to do such loading of resources from _package data_ is to use something like [_`pkgutil.get_data()`_](https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data) or now even better [_importlib-resources_](https://docs.python.org/3/library/importlib.html#module-importlib.resources).

To be honest I am not entirely sure yet, if there is anything that should be done in this project, or if the necessary changes can be contained to _poetry_. But my first impression is that some things have to be modified here.

**_References_**:

* https://github.com/python-poetry/poetry/issues/2965

**Comment by MegaIng** [comment]
This is only a problem if you use `%import common.*` or similar to use the stdlib. This can be easily avoided by just not using it and instead implementing your own terminals. (But this should probably be changed)

The passage shown in the other passage is the part where Lark provides a helper method for loading grammars from files via `Lark.open`. This is not the responsibly of lark to change, since it isn't a dependency of Lark, but of the user.

**Comment by erezsh** [comment]
I agree with @MegaIng, lark only uses __file__ when importing library files. 

How does zippapp work? Is it still possible open files within the package using `open()` and a path? And if so, why doesn't it provide `__file__` that matches the right path inside the zip?

**Comment by MegaIng** [comment]
@erezsh Is there currently any way to customize from where grammars are imported? If yes, is there any documentation for it? If not, maybe we should add it to fix this, with a fallback on the current file based method. (I don't see how it would be possible to replace the current import mechanic with `importlib-resources`. Except `common.lark` which should probably have a fallback that works from within zipapps).

**Comment by erezsh** [comment]
@MegaIng I don't think we have that in. This seems relevant: https://github.com/lark-parser/lark/issues/603

**Comment by sinoroc** [comment]
> This is only a problem if you use `%import common.*` or similar to use the stdlib. This can be easily avoided by just not using it and instead implementing your own terminals. (But this should probably be changed)
> 
> The passage shown in the other passage is the part where Lark provides a helper method for loading grammars from files via `Lark.open`. This is not the responsibly of lark to change, since it isn't a dependency of Lark, but of the user.

Yes, this is the same conclusion I arrived at in the mean time. :)

**Comment by sinoroc** [comment]
> Is it still possible open files within the package using `open()` and a path?

This can be done with something like that:

```python
import importlib.resources

with importlib.resources.path('mypackage.mygrammars', 'mygrammar.lark') as grammar_path:
    parser = Lark.open(grammar_path, parser="lalr")
```

I assume `parser` does not need access to `grammar_path` once we leave the context. But I am not sure, can you confirm?

**Comment by erezsh** [comment]
I'd really rather not add any dependencies to lark if I can avoid it.

If it can be done with pkgutil that would be much better.

**Comment by erezsh** [comment]
And yes, Lark reads the file only once.

**Comment by sinoroc** [comment]
> And yes, Lark reads the file only once.

Good!



> I'd really rather not add any dependencies to lark if I can avoid it.

Understandable. `importlib.resources` is part of the standard library, but only for later releases, _Python 3.7+_, depending on what features we need exactly.

> If it can be done with pkgutil that would be much better.

It can somewhat be done with `pkgutil`, but as far as I understood, you would get _binary string_, and not a (temporary) path:

https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data

**Comment by sinoroc** [comment]
Also, yes, _poetry-core_ seems to be using _lark_'s standard library:

https://github.com/python-poetry/poetry-core/blob/72291f379f87e41e22714f0eff0dbbdf57d9c060/poetry/core/version/grammars/markers.lark#L35-L37

Which I believe is my current show-stopper.

(Aside: thanks for being so reactive here, much appreciated!)
