### ISSUE TITLE
rule priority is not working as it is supposed to be

### ISSUE THREAD

**Issue by khaled-ek** [lark-parser/lark#705]
Hello,

The "API Reference" contains information about using priority, but I could not manage to make it work. I also tried the example included in issue #502, and I also noticed that the priorities over rules are ignored by the parser. I wonder if you have any updates about using priorities.

Thanks

**Comment by erezsh** [comment]
Are you using Earley or LALR?

**Comment by khaled-ek** [comment]
I tried to run the following example with both Earley and LALR and I get the same output:

class ReadTree(Transformer):
   def __init__(self):
        pass
   def mul(self, node):
      print(node)
   def add(self, node):
      print(node)

l = Lark("""?start: expression

   expression: atom
      | addition
      | multiplication
      | power
      | parentheses

      atom: WORD | NUMBER

      power.3: expression "^" expression -> pow

      multiplication.2: expression "*" expression -> mul

      addition: expression "+" expression -> add

      parentheses: "(" expression ")"

      %import common.NUMBER
      %import common.WORD
      %ignore " "           """, parser="earley", priority="auto")
   
p = l.parse("5 + 2 * 3")
p = ReadTree().transform(p)

Output is;

[Tree(expression, [Tree(atom, [Token(NUMBER, '2')])]), Tree(expression, [Tree(atom, [Token(NUMBER, '3')])])]
[Tree(expression, [Tree(atom, [Token(NUMBER, '5')])]), Tree(expression, [None])]

**Comment by khaled-ek** [comment]
class ReadTree(Transformer):
   def __init__(self):
        pass
   def mul(self, node):
      print(node)
   def add(self, node):
      print(node)

l = Lark("""start: expression

   expression: atom
      | addition
      | multiplication
      | power
      | parentheses

      atom: WORD | NUMBER

      power.3: expression "^" expression -> pow

      multiplication.2: expression MULT expression -> mul

      MULT: "*"

      addition: expression ADD expression -> add

      ADD: "+"

      parentheses: "(" expression ")"

      %import common.NUMBER
      %import common.WORD
      %ignore " "           """, parser="earley", priority="auto")
   
p = l.parse("5 + 2 * 3")
p = ReadTree().transform(p)

Output is:
[Tree(expression, [Tree(atom, [Token(NUMBER, '2')])]), Token(MULT, '*'), Tree(expression, [Tree(atom, [Token(NUMBER, '3')])])]
[Tree(expression, [Tree(atom, [Token(NUMBER, '5')])]), Token(ADD, '+'), Tree(expression, [None])]

I would like to get the correct node instead of None, something like:
[Tree(atom, [Token(NUMBER, '2')])]), Token(MULT, '*'), Tree(expression, [Tree(atom, [Token(NUMBER, '3')])])

**Comment by MegaIng** [comment]
You are using a Transformer. This means that the node that you get passed to `mul` and `add` are replaced by their return values. You don't return anything explicit, so `None` is returned. This has nothing to do with priority, as you can see when you check the output of `print(p.pretty())`

**Comment by khaled-ek** [comment]
I think that you are right , going back to the example in issue #502 shows a clear difference when running with Earley. For the transformer, I missed the return. You are right, Sorry
