### ISSUE TITLE
maybe_placeholders and anonymous terminal omits the None

### ISSUE THREAD

**Issue by omega16** [lark-parser/lark#706]
Doc says [here](https://lark-parser.readthedocs.io/en/latest/grammar.html#rules) that `maybe_placeholders=True` makes ` rule : some1 [item] some2` to produce a `None` if item is not found, but anonymous token seems to not produce `None`.

Minimal reproduction: 
~~~python
from lark import Lark

grammar = r"""
UINT : /\d+/

math_atom : UINT 

LESS : "<"

math_script : math_atom ("_" ["<"] math_atom)*
"""

parser = Lark(
    grammar= grammar,
    parser="lalr",
    keep_all_tokens=True,
    maybe_placeholders=True,
    start="math_script"
     )

test_file= "1_1"
tree = parser.parse(test_file)
print(tree.pretty())
~~~

Produces: 
~~~
math_script
  math_atom     1
  _
  math_atom     1
~~~

If you replace `math_atom` to `UINT` it works. 
if you replace `["<"]` with `[LESS]` it works. 

~~~
math_script
  math_atom     1
  _
  None
  math_atom     1
~~~

I have both a global lark installed and a fresh environment with just lark

global install `Version: 0.9.0`
environment install  `Version: 0.10.0`

**Comment by MegaIng** [comment]
This is a feature, not a bug. Only tokens that normally produce a node (e.g. when found) produce None when not found. You can check this by adding `!` to the beginning of the rule name so that anonymous Tokens are returned.

**Comment by omega16** [comment]
Thanks.

This is a little weird (for me) since `keep_all_token`  says 

`Prevent the tree builder from automagically removing “punctuation” tokens (default: False)`

It makes me thing having both `keep_all_token=True` and `maybe_placeholders=True` would produce a None always. So, maybe add to doc a note about this? 

And, What's a "puntuation" token then?

**Comment by MegaIng** [comment]
Oh, I skipped over the part `keep_all_token=True`. Yes, this is a bug.
