### ISSUE TITLE
Consider chasing down the name `lark` for pip.

### ISSUE THREAD

**Issue by MegaIng** [lark-parser/lark#712]
Sadly, the name `lark` is taken on pip, and it appears to be used [a bit](https://pypistats.org/packages/lark). However, I think there is a really good chance that 99.9% of those are people wrongly trying to install `lark-parser`.

 This is especially evident when you look at [libraries.io attempt](https://libraries.io/pypi/lark/usage) to figure out dependents. Half is recognized, other half is wrongly depending on lark instead of `lark-parser`. Exactly one is is correctly dependent, by the same author as `lark` itself @voidfiles.

 If you look at the [github analysis](https://github.com/voidfiles/lark/network/dependents?dependent_type=REPOSITORY) the picture doesn't really change. 

@voidfiles is also ignoring [an issue about this](https://github.com/voidfiles/lark/issues/4) since half a year, despite being active on github.

We can try to use [PEP 541](https://www.python.org/dev/peps/pep-0541/) if @voidfiles doesn't answer here, but we would have to first try to reach him via email, then shoot an issue at pypi-support.

**Comment by voidfiles** [comment]
Not ignoring, just didn’t realize. I’m happy to grant folks access to lark in anyway to fix the issue.

**Comment by erezsh** [comment]
Hi @voidfiles,

Are you saying that you're willing to give up the `lark` name on pypi so that we can use it instead?

That would be very gracious of you!

**Comment by voidfiles** [comment]
Yea, just let me know what I need to do.

**Comment by erezsh** [comment]
@voidfiles You need to login to PyPI, and then you can either 

1. add me (username `erez`) as an owner, via https://pypi.org/manage/project/lark/collaboration/. Then I will remove you as owner, and change it to host this project instead.

Or

2. Delete the project yourself, via https://pypi.org/manage/project/lark/settings/ , and then let me know so I can re-create it for this project.

Much appreciated!

**Comment by voidfiles** [comment]
K, should I've invited you. Sorry that I didn't see this earlier.

**Comment by erezsh** [comment]
I'm happy to announce it is now possible to `pip install lark`!

Thanks you @voidfiles for being so helpful and understanding! I will add a small thank you note in the next release, if that's alright with you.
