### ISSUE TITLE
'Incorrect' Download Url

### ISSUE THREAD

**Issue by MegaIng** [lark-parser/lark#714]
https://github.com/lark-parser/lark/blob/16d41d177420964c1b0556eb2a1caca5e2b6161e/setup.py#L33

Well, that line still references the age old times where the package was hosted on your personal github @erezsh. 

But independent of that, wouldn't it be better if the download URL is bound to a specific release?

**Comment by erezsh** [comment]
You mean the latest release?

**Comment by MegaIng** [comment]
On github, you are creating release which always link have a static link. Wouldn't it be better to use that instead of the dynamic link that `tarball/master` uses? But I am not sure.

**Comment by erezsh** [comment]
I am also not sure, but it seems fine the way it is.

Closing until new ideas come to light.
