### ISSUE TITLE
Please publish both sdist and whl to PyPI

### ISSUE THREAD

**Issue by mlin** [lark-parser/lark#716]
The wheel is great but the sdist is preferable for [conda repackaging](https://github.com/conda-forge/lark-parser-feedstock) according to my discussion with a couple of the conda-forge operators below. I'll try the suggested github route as well, but they seem to indicate one "ought to" publish both in general (I'm not an expert in this myself...)

![image](https://user-images.githubusercontent.com/356550/95795788-f75ab500-0c86-11eb-8943-a6cd559c209a.png)

**Comment by erezsh** [comment]
Uploaded sdist of 0.10.0

**Comment by ThatXliner** [comment]
Should this be closed now?
