### ISSUE TITLE
Missing git tag for 0.10.1 release

### ISSUE THREAD

**Issue by felixonmars** [lark-parser/lark#718]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by MegaIng** [comment]
There is nothing new in that version. I even think it is the same git tag as v0.10.0

**Comment by bluefish6** [comment]
nope, 0.10.0 and 0.10.1 on pypi have different code (apart from the fact that 1 is a wheel and 2 is a tar.gz).

example difference:
```
0.10.1 - load_grammar.py

def load_grammar(grammar, source, re_, global_keep_all_tokens):
    return GrammarLoader(re_, global_keep_all_tokens).load_grammar(grammar, source)
```

```
0.10.0 - load_grammar.py

def load_grammar(grammar, source, re_):
    return GrammarLoader(re_).load_grammar(grammar, source)
```

See the changes in file sizes: 

![image](https://user-images.githubusercontent.com/3324881/98131078-39a89800-1ebb-11eb-86fa-8ca94534688b.png)

**Comment by erezsh** [comment]
0.10.1 was uploaded because it was a wheel.

There should be no difference in functionality.

But you're right, I dropped the ball on this. They should be kept in sync.
