### ISSUE TITLE
Move man page to section 7

### ISSUE THREAD

**Issue by wiene** [lark-parser/lark#720]
At present lark generates a man page [in section 1](https://manpages.debian.org/unstable/manpages/man-pages.7.en.html#Sections_of_the_manual_pages). I think it would be more suitable to move it to section 7.

**Comment by erezsh** [comment]
We generate a man page?

Can you provide more details?

**Comment by MegaIng** [comment]
@wiene Aren't you the maintainer of the debian package?

**Comment by wiene** [comment]
Your sphinx machinery is prepared to generate a man page (see https://github.com/lark-parser/lark/blob/0.10.0/docs/conf.py#L163-L166). It is configured in such a way that the generated man page ends up in section 1 (if the user chooses to build it).

**Comment by wiene** [comment]
> @wiene Aren't you the maintainer of the debian package?

Yes, I am.

**Comment by erezsh** [comment]
Oh, I see. So just changing 1 to 7 should do the trick?

**Comment by wiene** [comment]
> So just changing 1 to 7 should do the trick?

Yes, that would change the man page section.

**Comment by erezsh** [comment]
Done.
