### ISSUE TITLE
Generate text from grammar

### ISSUE THREAD

**Issue by frechette-alex** [lark-parser/lark#726]
I have an EBNF grammar, I can use Lark to parse text according to the grammar spec. My question is, is there a way to go from a parsed AST back to pure text, using the grammar specs?

**Comment by marwern** [comment]
Hello, I have a basic question about the generated parse tree. For my understanding, the result of lark without the ast_utils(?) extension is a concrete parse tree (CST), right?

After all, the reconstruction example you have shared refers to the CST.

I have seen the other example to get an AST from CST.

For the reconstruction of the source code a conversion from CST to AST is not necessary at all or am I wrong?

Thank you.
