### ISSUE TITLE
How to deal effectively with errors?

### ISSUE THREAD

**Issue by fabioz** [lark-parser/lark#736]
**What is your question?**

Right now, I'm trying to make sure that when I have some error I can still produce a valid tree (with as much info as possible).

Still, I'm not having much success there... it seems pretty hard to manage the state properly to recover from some error.

I think it's a bit hard to discuss that abstractly, so, I'm going to attach an example: [test_lark.py.txt](https://github.com/lark-parser/lark/files/5451521/test_lark.py.txt)
(it's is a very simplified version of my grammar just so that it's possible to discuss based on it)

Just for some context, it's an indent-based grammar, so, it should accept something as:

```
*** Function: Some function ***
    Some Call(param)
    Another Call
```

So, in the example there I'm trying to recover from something as an unclosed parenthesis:

i.e.: 

```
*** Function: Some function ***
    Some Call(
    Another Call
```

In that example I get the error when it finds the `_DEDENT`. Initially I thought that it'd be possible to just feed the `")"` back and the dedent and it'd work:

i.e.:
```
e.puppet.feed_token(Token("RPAR", ")"))
e.puppet.feed_token(e.token)
```

but it doesn't -- it just ends up in another internal error and then bails out:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bin\Miniconda\envs\py_38_tests\lib\site-packages\lark\parsers\lalr_parser.py", line 86, in feed_token
    action, arg = states[state][token.type]
KeyError: '_DEDENT'
```

So, I'm a bit confused now on how to proceed... for my particular language, I'd usually just want to try to skip whatever is there until a new line is found and restart based on the new statement for the function scope or a new global definition (depending on the current level), but I can't really figure out if it's possible at all to manage the parse state or skip tokens (the API seems to be only around feeding new tokens).

On JavaCC (which I'm mentioning just for food for thought here, since the approach is definitely different), it'd be possible to do something as a try..except in the language definition so it'd act exactly at the point where the error was found, and it'd be possible to say in the grammar in a `try..except` that if some token/statement can't be matched, when the error is found it'd just be at the proper state for the next statement and it'd also allow to inspect the token stream and navigate in it (the current token had a reference to `next` and it'd be possible to navigate that stream to find a new line, set the current token and try to proceed from there, mostly ignoring what didn't work until that place) -- I don't really recommend the actual JavaCC API (the actual error recovery implementation seemed like a bit of a hack), but having those capabilities would be really useful to recover from errors.

After writing all this (sorry for the long report), I think that the main point is probably that without managing the parse state I don't see a way to do proper error recovery (just the current token isn't enough information)-- so, is there a way/plans to manage it? (can I skip tokens to a new line and just go to a state where it should start to match the next statement?)

Apart from `feed_token`, are there any additional capabilities for error recovery?

**Comment by erezsh** [comment]
I appreciate the detailed write-up, but I think you just forgot to feed the puppet with a newline:

```python
                e.puppet.feed_token(Token("RPAR", ")"))
                e.puppet.feed_token(Token("_NEWLINE", "\n"))
                e.puppet.feed_token(e.token)
```

That should work.

**Comment by fabioz** [comment]
You're right in that it does fix the exact case there, but the fix itself doesn't really do what I wanted.

i.e.: the fix will convert

```
*** Function: Some function ***
    Some Call(
    Another Call
```

to:

```
*** Function: Some function ***
    Some Call(
    Another Call
    )
```

But what I really wanted was to drop the `(`.

i.e.:

```
*** Function: Some function ***
    Some Call
    Another Call
```

But I can't really say in which point the error should be handled (and thus it's too late for that fix).

**Comment by MegaIng** [comment]
You can do one more thing: Modify the lexer state. For this you should know a bit about how the `lalr` parser works, both in theory and in this implementation. I would suggest reading the source code.

You can modify the lexer state by popping of `LexerState.state_stack` and `LexerState.value_stack`.
