### ISSUE TITLE
Non-Breaking spaces are not included in WS_INLINE

### ISSUE THREAD

**Issue by ArthurLapraye** [lark-parser/lark#738]
The WS_INLINE token does not include the character `U+00A0 NO-BREAK SPACE`, thus the `%ignore WS_INLINE` directive does not behave as expected if non-breaking spaces happen to be included in the code.

(Looking at the definition, it seems like the `WS_INLINE` definition doesn't include other whitespace unicode characters either but I didn't test this)

The problem is that, due to the nature of the character, the error is very difficult to understand, as it makes it seem that the unexpected character is a normal space (`U+0020 SPACE`). 

I would argue that the expected behavior for `WS_INLINE` should include any whitespace character except for new line characters.

**To Reproduce**

To reproduce this bug, take a grammar using the `%ignore WS_INLINE` directive and include the `NO-BREAK SPACE` character anywhere in the code to be parsed.

**Comment by MegaIng** [comment]
Not a bug. `common.lark` only includes ASCII. If you want more, use regex syntax.

**Comment by erezsh** [comment]
We could introduce a new terminal, `WS_INLINE_UNICODE`, that will include it and all the others.

**Comment by MegaIng** [comment]
If we do that, I would suggest creating a new `common.lark` that uses unicode for everything.

**Comment by MegaIng** [comment]
(e.g. a second common.lark, not replacing the current one)

**Comment by erezsh** [comment]
Interesting idea.. The only other terminals that would benefit from it are `LETTER`, `WORD` and `CNAME`, right? Or is there anything else?

**Comment by MegaIng** [comment]
Technically NUMBER as well, but I am not sure how usefull that would be.

**Comment by erezsh** [comment]
Why NUMBER?

**Comment by MegaIng** [comment]
Unicode ofcourse defines addtitional numerals: https://en.m.wikipedia.org/wiki/Numerals_in_Unicode

Same as unicode also defines a structure for identifiers, that is in theory what most implementations should follow. But as I said, few programs will know how to handle non standard number literals (i think Java as example deals with them), so it might not be worth the hassle.

This is certaintly different for IDs, which implementations shouldn't care about.

**Comment by ArthurLapraye** [comment]
I think whitespace characters are especially important because they can be hard to catch and make for hard to read error messages. It's hard to use a greek numeral without meaning to, and even if you do, the error will be relatively straightforward to catch and fix. 
On the other hand it's comparatively more likely  for unusual whitespace characters to end up in your code (if you paste it from a spreadsheet or word processing software or a website for example), and when it looks like the unexpected character is a space, the problem is really not obvious to track down.

**Comment by MegaIng** [comment]
> when it looks like the unexpected character is a space

If I am honwst this is the real problem in the current implementation: that the character itself and not it's repr is used.

**Comment by erezsh** [comment]
You can now do `%import unicode.WS_INLINE`, so I consider this closed.

Of course, there are other unicode whitespace characters, as well as other unicode-specfic terminals. If anyone wants to open a PR for it, it would be welcome.

**Comment by MegaIng** [comment]
@erezsh Would you have something against making the `unicode.lark` grammar required the `regex` module? If you are specifically working with unicode, you should use it anyway, and the `\p{}` category syntax makes it very easy to correctly match identifiers.

**Comment by erezsh** [comment]
What sort of errors do the users get if they use them without having the module?

**Comment by MegaIng** [comment]
None for python2.7 (Except that it doesn't match correctly: `\p{isXID_CONTINUE}` will try to match the string.). I personally don't care about this

For python3.6+ `bad escape \p at position X`. If we want, we could catch this specific error message compile time and put a more helpful message.
