### ISSUE TITLE
Contextual lexer matching terminal that can't be reached in context

### ISSUE THREAD

**Issue by fabioz** [lark-parser/lark#742]
I think this is a bug, but it may be possible I'm misunderstanding how the contextual lexer works.

The grammar I have has tokens based on the context, but until now it seemed to work ok using `lalr` with the `contextual` lexer, but after I added the `return_stmt` it seems it started to do some wrong choices on how to lex the code.

In this case, where the grammar should parse a `NAME_CONT` it's parsing a `DEC_NUMBER`.

Let me give some more info:

The grammar is trying to match the code:

```
*** Functions ***
My Function 1
    While var 2
        var 3
```

and it's matching the `1` from `My Function 1` as a `DEC_NUMBER` instead of a `NAME_CONT` (even though a `DEC_NUMBER` isn't valid at that context and a `NAME_CONT` is (the `identifier` rule is: `identifier: NAME  (NAME|NAME_CONT|WS)*` and it matched the `NAME` for `My` and `NAME_CONT` for `Function`, yet it then failed to match the `1` as `NAME_CONT` and ended up matching as a `DEC_NUMBER`, which isn't valid in the context.

The place where the rules should be matching is at the `func_name` -- i.e.:

```
file_input: (_NEWLINE | root_stmt)*
?root_stmt: func_block
func_block: func_header WS? _NEWLINE (func_stmt)*
func_header: BLOCK_START "functions"i  BLOCK_END
func_stmt: func_name func_suite
func_name: identifier
?identifier: NAME  (NAME|NAME_CONT|WS)*
NAME: /[^\d\W]\w*/
NAME_CONT: /\w+/
WS: /\s+/
```

That alone works, but it fails in the actual grammar:

[test_lark_contextual_lexer_issue.py.txt](https://github.com/lark-parser/lark/files/5476277/test_lark_contextual_lexer_issue.py.txt)

This happened right after I added the `return_stmt`!

So, in that same grammar just removing the `return_stmt` the lexer seems to do the right thing -- I'm not sure why though...

The docs say that:

The contextual lexer communicates with the parser, and uses the parser's lookahead prediction to narrow its choice of tokens. So at each point, the lexer only matches the subgroup of terminals that are legal at that parser state, instead of all of the terminals.

Given that, I think it's a bug in that the lexer is not considering the context as it should in this case -- otherwise, I'm probably misunderstanding the approach on how it decides how to lex based on the context or the grammar can reach a `DEC_NUMBER` through some means that I can't see (as far as I see it the `func_suite` needs a `_NEWLINE` to start, so, it should not be possible to get to a `DEC_NUMBER` from there).

**Comment by MegaIng** [comment]
Well, `1` is not a valid `NAME`. That `DEC_NUMBER` is appearing in the error message is because the Contextual Lexer tests whether it knows any Terminal that could match the encountered illegal sequence, even if the Terminal is not valid right now.

**Comment by fabioz** [comment]
Yes, it's not a valid `NAME` (it should match `NAME_CONT` and not `NAME` at that place).

**Comment by fabioz** [comment]
(and it did match `NAME_CONT` until I added the `return_stmt` at that same grammar)

**Comment by erezsh** [comment]
> In this case, where the grammar should parse a NAME_CONT it's parsing a DEC_NUMBER

Is it actually parsing it as `DEC_NUMBER`, or only saying so in the `UnexpectedToken` error?

**Comment by MegaIng** [comment]
I am currently confused as to how this ever worked: `identifier` consumes all `\w` and `\s`. This includes newlines.

(And yes, apperantly it is actually parsed as `DEC_NUMBER`)

**Comment by fabioz** [comment]
> > In this case, where the grammar should parse a NAME_CONT it's parsing a DEC_NUMBER
> 
> Is it actually parsing it as `DEC_NUMBER`, or only saying so in the `UnexpectedToken` error?

It's actually parsing as a `DEC_NUMBER`.

The full exception trace is:

```
Traceback (most recent call last):
  File "X:\lark\lark\parsers\lalr_parser.py", line 86, in feed_token
    action, arg = states[state][token.type]
KeyError: 'DEC_NUMBER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\vscode-robot\rflang\tests\rflang_tests\test_lark_contextual_lexer_issue.py", line 97, in <module>
    parse(
  File "X:\vscode-robot\rflang\tests\rflang_tests\test_lark_contextual_lexer_issue.py", line 87, in parse
    tree = lark_spec.parse(source_code)
  File "X:\lark\lark\lark.py", line 493, in parse
    return self.parser.parse(text, start=start)
  File "X:\lark\lark\parser_frontends.py", line 138, in parse
    return self._parse(start, self.make_lexer(text))
  File "X:\lark\lark\parser_frontends.py", line 73, in _parse
    return self.parser.parse(input, start, *args)
  File "X:\lark\lark\parsers\lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "X:\lark\lark\parsers\lalr_parser.py", line 129, in parse
    return self.parse_from_state(parser_state)
  File "X:\lark\lark\parsers\lalr_parser.py", line 145, in parse_from_state
    raise e
  File "X:\lark\lark\parsers\lalr_parser.py", line 136, in parse_from_state
    state.feed_token(token)
  File "X:\lark\lark\parsers\lalr_parser.py", line 89, in feed_token
    raise UnexpectedToken(token, expected, state=state, puppet=None)
lark.exceptions.UnexpectedToken: Unexpected token Token('DEC_NUMBER', '1') at line 3, column 13.
Expected one of: 
	* WS
	* _NEWLINE
	* NAME
	* NAME_CONT
```

**Comment by fabioz** [comment]
> I am currently confused as to how this ever worked: `identifier` consumes all `\w` and `\s`. This includes newlines.
> 
> (And yes, apperantly it is actually parsed as `DEC_NUMBER`)

Changing `WS` to `WS: / /+` so that it only consumes spaces has the same result (in that it will work if `return_stmt` is removed and will fail when it's present) -- my bad, I thought that `\s` would only get whitespaces.

**Comment by MegaIng** [comment]
The problem is somewhere in here:
```
WARNING:root:Shift/Reduce conflict for terminal NAME: (resolving as shift)
WARNING:root: * <identifier : NAME __identifier_star_6>
WARNING:root:Shift/Reduce conflict for terminal WS: (resolving as shift)
WARNING:root: * <identifier : NAME __identifier_star_6>
WARNING:root:Shift/Reduce conflict for terminal NAME: (resolving as shift)
WARNING:root: * <call_expr : arguments WS identifier __call_expr_star_4>
WARNING:root:Shift/Reduce conflict for terminal LPAR: (resolving as shift)
WARNING:root: * <call_expr : arguments WS identifier __call_expr_star_4>
WARNING:root:Shift/Reduce conflict for terminal LPAR: (resolving as shift)
WARNING:root: * <name_expr : identifier>
WARNING:root:Shift/Reduce conflict for terminal NAME: (resolving as shift)
WARNING:root: * <call_expr : arguments WS identifier>
WARNING:root:Shift/Reduce conflict for terminal LPAR: (resolving as shift)
WARNING:root: * <call_expr : arguments WS identifier>
WARNING:root:Shift/Reduce conflict for terminal NAME: (resolving as shift)
WARNING:root: * <call_expr : arguments identifier __call_expr_star_4>
WARNING:root:Shift/Reduce conflict for terminal LPAR: (resolving as shift)
WARNING:root: * <call_expr : arguments identifier __call_expr_star_4>
WARNING:root:Shift/Reduce conflict for terminal NAME: (resolving as shift)
WARNING:root: * <call_expr : arguments identifier>
WARNING:root:Shift/Reduce conflict for terminal LPAR: (resolving as shift)
WARNING:root: * <call_expr : arguments identifier>
WARNING:root:Shift/Reduce conflict for terminal NAME: (resolving as shift)
WARNING:root: * <call_expr : identifier arguments>
WARNING:root:Shift/Reduce conflict for terminal LPAR: (resolving as shift)
WARNING:root: * <call_expr : identifier arguments>
WARNING:root:Shift/Reduce conflict for terminal NAME: (resolving as shift)
WARNING:root: * <identifier : NAME>
WARNING:root:Shift/Reduce conflict for terminal WS: (resolving as shift)
WARNING:root: * <identifier : NAME>
WARNING:root:Shift/Reduce conflict for terminal NAME: (resolving as shift)
WARNING:root: * <call_expr : identifier arguments __call_expr_star_5>
WARNING:root:Shift/Reduce conflict for terminal LPAR: (resolving as shift)
WARNING:root: * <call_expr : identifier arguments __call_expr_star_5>
```

That is the log output when `debug=True`. That many Shift/Reduce conflicts can't be good.

**Comment by fabioz** [comment]
> That is the log output when debug=True. That many Shift/Reduce conflicts can't be good.

Is that `debug=True` to the `Lark` constructor? I can't seem to get that log setting `debug=True` there (even adding a logger):

i.e.: code:

[test_lark_contextual_lexer_issue.py.txt](https://github.com/lark-parser/lark/files/5476821/test_lark_contextual_lexer_issue.py.txt)

(I'm trying with the `master` version)

**Comment by fabioz** [comment]
I've simplified the grammar a bit more so hopefully it's easier to debug (while still having the same error -- which doesn't happen if the `return_stmt` is removed -- and I can't see any message reported with `debug=True` with the `master` version):

[test_lark_contextual_lexer_issue.py.txt](https://github.com/lark-parser/lark/files/5476977/test_lark_contextual_lexer_issue.py.txt)

**Comment by MegaIng** [comment]
In the master (and maybe even in 10.0) we changed the logging system to use `lark.logger` instead of the `root` logger. The output I posted was with the `0.9` version.

**Comment by fabioz** [comment]
In the last version I sent (in https://github.com/lark-parser/lark/issues/742#issuecomment-720630825) I see the following messages:

```
Unused terminals: ['COMMENT']
Shift/Reduce conflict for terminal NAME: (resolving as shift)
 * <identifier : NAME __identifier_star_3>
Shift/Reduce conflict for terminal NAME: (resolving as shift)
 * <identifier : NAME>
```

It seems related to:

`?identifier: NAME  (NAME|NAME_CONT|WS)*`

changing it to:

`identifier: NAME  (NAME_CONT|WS)*`

fixes the warnings (but parsing still fails) -- but it now fails because it finds a `Function` in `My Function 1` as a `NAME` when it should find it as `NAME_CONT`, so, it's still an error in determining how the lexer works in a given context.

This version (which doesn't have any warnings) is:
[test_lark_contextual_lexer_issue.py.txt](https://github.com/lark-parser/lark/files/5477218/test_lark_contextual_lexer_issue.py.txt)

As in others, removing the `return_stmt` makes everything work.

**Comment by erezsh** [comment]
I took a look at your example, and I'll try to explain what happens.

Basically the LALR parser performs two functions: shift, and reduce. Shift takes in the next token. Reduce happens when a rule is complete. 

In your case, `identifier` could be reduced in two situations: Either it's inside `func_stmt`, and then the following terminal is `_NEWLINE`, or it's inside `test`, which means it's also inside `return_stmt` and then the following rule can be another `test`, which means the next token can be `DEC_NUMBER` (among others).

Only after reducing, the shift learns it's not in the middle of a `return_stmt` after all. In theory, I could try to make the LALR(1) parser clever enough to know it before reducing. But all it will give you is a better error, because your text is obviously incorrect for the grammar.

Tbh, I'm not sure that a better error is worth it. Is there anything I could say in this situation which would help you solve it faster? (that doesn't involve grammar analysis, ofc)

**Comment by erezsh** [comment]
Right now the contextual lexer only looks at the next action, and in this case it sees a legal reduce for `DEC_NUMBER`. I can make it also look into the shift operations afterward, but that would mean extra computation for each token. I don't think it's worth it, just so you will instead get the exact same error from the lexer.

**Comment by fabioz** [comment]
Ok, I think I understand now. Let me try to rephrase to see if this is it:

The issue is that the contextual lexer on lark sees the current construct and all other possible reachable states from that construct (even if invalid in the actual parse state) when determining the next token in the lexer, so, even though at `func_stmt/identifier/NAME` only a `NAME_CONT/WS/_ENDLINE` is valid it may end up creating tokens reachable from `stmt/test/identifier` (so, it's an improvement over yacc/bison but the grammar must be constructed to have unique rules to overcome that limitation -- indeed if I don't reuse the `identifier` rule and create an `identifier_func` with a `NAME_FUNC` it seems to recognize it properly at that specific place).

So, it seems I was really overestimating the parser lookahead capabilities.

Personally, I think that given that it was inside the `identifier` and it already matched the `NAME`, I think it should try to tokenize the next words using the remainder of the identifier construct (`NAME_CONT|WS`) and then the tokens based on rules that can happen at that context (which in that sample grammar would be just `_NEWLINE`) -- this doesn't seem like an issue in how LALR(1) works, but rather on the (unique) approach used to do the lexing based on the parse state.

If it did that I believe the grammar would be valid and it would probably handle some ambiguity in the grammar better (closer to what PEGs do).

Anyways, thanks for the explanation, I think I understand better the limitations now to try to work around them.

Feel free to close if you don't plan on changing how the tokenization works based on the parse state lookahead (I guess this would be a feature request).

**Comment by MegaIng** [comment]
Alternatively, you could fix your grammar: `return_stmt` should require a `_NEWLINE` at the end. Adding that fixes this error.

This was by the way a true ambiguity in your grammar.

`return var 1 1`

could have been parsed as
```
return_stmt
    identifier
        var
        1
        1
```
(which is probably what you wanted)

or, incorrectly as 
```
return_stmt
    identifier
        var
        1
test
    number_expr
        1
```

Sorry that it took me this long to discover this.

**Comment by fabioz** [comment]
> Alternatively, you could fix your grammar: `return_stmt` should require a `_NEWLINE` at the end. Adding that fixes this error.

Agreed, that's the proper fix -- thank you for spotting it (I should've spotted it myself, but I guess I got sidetracked by how the error was expressed, I should've known better... on the bright side, now I have more knowledge in what I can expect from lark).

> Sorry that it took me this long to discover this.

I must say that the response seemed quite speedy and high quality, so, thank you very much for the really nice support given by the lark team, it's much appreciated! (I know how much effort goes into supporting a high quality open source project)

**Comment by erezsh** [comment]
> I think it should try to tokenize the next words using the remainder of the identifier construct (NAME_CONT|WS) and then the tokens based on rules that can happen at that context

That may be possible, but it is an extraneous complication just to shift the error from one place to another, that will have real performance implications. So, I don't plan to do it. But I appreciate the suggestion.
