### ISSUE TITLE
Where is the meta-language parsing code?

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#743]
**What is your question?**

For Lark to be able to parse other languages, it must be able to parse it own syntax at the first place. Where is the code where Lark does this?

**Comment by MegaIng** [comment]
In examples `lark.lark`. This is not actually used, but more of a synced definition.

In a half prepossessed state in `load_grammar.py`. This is used to load the grammar at runtime.

**Comment by ThatXliner** [comment]
I want the python script that parses the grammars

**Comment by MegaIng** [comment]
... `load_grammar.py`

**Comment by ThatXliner** [comment]
Thanks!
