### ISSUE TITLE
Help is needed to manage ambiguity

### ISSUE THREAD

**Issue by khaled-ek** [lark-parser/lark#751]
Hello,

I have the following rules for declaring variables:

state_declaration: DATA_FLOW var_declaration
DATA_FLOW: ("input" | "output" | "parameter") 
var_declaration: (type | state_compartment) variable_name
type: PRIMITIVE_TYPE
PRIMITIVE_TYPE: "Boolean" | "Integer" | "Real"
state_compartment: name
variable_name: name
name: (ALPHABETIC_CHARACTER (ALPHABETIC_CHARACTER | DIGIT)*)

ALPHABETIC_CHARACTER: "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m"
        | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
        | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M"
        | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"

DIGIT: "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

Everything works fine until I choose a variable name which causes ambiguity. For example, the following variable declaration can be parsed correctly:

input Real value

and the relevant tree nodes are as follows:

Tree(var_declaration, [Tree(type, [Token(PRIMITIVE_TYPE, 'Real')]), Tree(variable_name, [Tree(name, [Token(ALPHABETIC_CHARACTER, 'v'), Token(ALPHABETIC_CHARACTER, 'a'), Token(ALPHABETIC_CHARACTER, 'l'), Token(ALPHABETIC_CHARACTER, 'u'), Token(ALPHABETIC_CHARACTER, 'e')])])])

However, when I choose a variable name such as inputValue the problems start

input Real inputValue

and the relevant tree nodes are as follows:

Tree(var_declaration, [Tree(state_compartment, [Tree(name, [Token(ALPHABETIC_CHARACTER, 'V'), Token(ALPHABETIC_CHARACTER, 'a')])]), Tree(variable_name, [Tree(name, [Token(ALPHABETIC_CHARACTER, 'l'), Token(ALPHABETIC_CHARACTER, 'u'), Token(ALPHABETIC_CHARACTER, 'e')])])])

I would like to ask about a way to avoid confusion and make the parser read inputValue as a variable_name.

Thank you

**Comment by charles-esterbrook** [comment]
Normally something like "name" is done as a token/terminal instead of a parse tree.

```lark
// change:
name: (ALPHABETIC_CHARACTER (ALPHABETIC_CHARACTER | DIGIT)*)
// to:
NAME: /[A-Za-z][A-Za-z0-9]*/
// change uses of: name
// to: NAME
```
This should fix your problem.

**Comment by khaled-ek** [comment]
Thank you for your response, I actually cannot use name as a terminal because it can have several options, what I provided in my first example is just a snapshot, the name can have the following rule:

name: identification | quoted_identification  
identification: (ALPHABETIC_CHARACTER (ALPHABETIC_CHARACTER | UNDERSCORE | NON_ZERO_DIGIT | ZERO)*) //- (keyword)
quoted_identification: "'" (PREV OPEN_PARENTHESES reference CLOSE_PARENTHESES)"'"

**Comment by charles-esterbrook** [comment]
Okay leave `name` as-is, but then make `identification` a regex:

```lark
name: ID | quoted_identification
ID: /[A-Za-z][A-Za-z\d_]*/
```

Try that. This is the normal approach seen everywhere. At the "bottom" is a regex defining a name of some kind.

**Comment by khaled-ek** [comment]
Thank you for your support, what you suggested works well for me. I would like to ask if it is possible to exclude any keywords from the name, meaning the name should not be any of the keywords.

**Comment by charles-esterbrook** [comment]
You're welcome.

Keywords seem to happen automatically. For example, my grammar has a keyword "repeat" which I'm not able to use as a NAME. The keywords you use in the grammar get higher precedence.  Or maybe it's because I put my NAME token definition at the bottom.

If you have problems with this, move your ID further down in your grammar.

Also, check out https://gitter.im/lark-parser/Lobby for discussion and help.

**Comment by charles-esterbrook** [comment]
I think you can close this issue now.
