### ISSUE TITLE
Nearley importation does not support case insensitive

### ISSUE THREAD

**Issue by charles-plante** [lark-parser/lark#753]
On my grammar, when I use a string with an 'i" at the end, this is recognize to match the string without case
ex  "This is my String"i

When im using nearley to lark, the 'i' is recognize as a rule and the following error is raised

> lark.exceptions.GrammarError: Rule 'n_i' used but not defined (in rule n_word)

**To Reproduce**
Use the following grammar and try to use it with the nearley to lark tool
```
Main -> word _ expression _ word  {% function(d) {return d[0] + " " + d[2] + " " + d[4]} %}
word ->
    "test"i   {% function(d) {return d[0]} %}
  | "String"i   {% function(d) {return d[0]} %}
expression ->
  "="		{% function(d) {return d[0]} %}
| "+"	{% function(d) {return d[0]} %}
| "-"	{% function(d) {return 'OR'} %}
_ -> [\s]:*     {% function(d) {return null } %}
```

**Comment by ThatXliner** [comment]
I think the string to make case insensitive should be all lowercase.

**Comment by charles-plante** [comment]
I've tried to make all string lowercase and still got the same issue. Just to make sure we are on the same page, on Nearley JS, if you put an 'i' after a string, the string will match any case.
Grammar :
```
Main -> word _ expression _ word  {% function(d) {return d[0] + " " + d[2] + " " + d[4]} %}
word ->
    "test"i     {% function(d) {return d[0]} %}
  | "string"i   {% function(d) {return d[0]} %}
expression ->
  "="	{% function(d) {return d[0]} %}
| "+"	{% function(d) {return d[0]} %}
| "-"	{% function(d) {return 'OR'} %}
_ -> [\s]:*     {% function(d) {return null } %}
```
Test expression that match:
`TeSt = StRiNG`

**Comment by erezsh** [comment]
I think this should solve it. Try the `master` branch.

**Comment by charles-plante** [comment]
Works great. Thanks for the quick response !
