### ISSUE TITLE
Clarification on the use_accepts option of lark.exceptions.UnexpectedInput

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#761]
**What is your question?**

What does the `use_accepts` option of [`lark.exceptions.UnexpectedInput`](https://lark-parser.readthedocs.io/en/latest/classes.html#lark.exceptions.UnexpectedInput) do?

**If you're having trouble with your code or grammar**

Provide a small script that encapsulates your issue.

Explain what you're trying to do, and what is obstructing your progress.

**Comment by erezsh** [comment]
You can remove the parts that aren't relevant..

Anyway, it uses information from the parser in order to give a better error.

In v1.0 it may become the default.

**Comment by ThatXliner** [comment]
In [`lark.exceptions.UnexpectedInput.match_examples`](https://lark-parser.readthedocs.io/en/latest/classes.html#lark.exceptions.UnexpectedInput.match_examples), is `examples` mandatory?

**Comment by erezsh** [comment]
Yeah... otherwise what's the point of the function?

**Comment by ThatXliner** [comment]
Ok
