### ISSUE TITLE
`Unexpected token` errors can be inscrutable ootb

### ISSUE THREAD

**Issue by charles-esterbrook** [lark-parser/lark#778]
**Suggestion**
The use of `__ANON_22` style token names is useless to end users (and probably devs as well):
```
Unexpected token...
Expected one of:
        * __ANON_22
        * MORETHAN
        * OR
        * __ANON_20
        * __ANON_18
        * __ANON_17
```
While this could be addressed by each individual developer who uses Lark, it would make more sense if it was improved in Lark itself both to reduce duplication of effort and to provide a default experience that is more productive.

As a minor aside, it might be interesting to name anonymous tokens with their line number and column number where they appeared in the grammar, such as __ANON_8_15. But even with that scheme, which could be helpful in other situations, the "Unexpected token" error needs a rework to be useful.

**Describe alternatives you've considered**
The alternative is for each developer using Lark to study how the error is generated and write their own code to rework it for the benefit of their end users.

**Additional context**
N/A

**Comment by MegaIng** [comment]
#717, #727

**Comment by charles-esterbrook** [comment]
Sorry about the duplicate issue. I skimmed through the issue list, but obviously not well enough. Closing.
