### ISSUE TITLE
running the examples

### ISSUE THREAD

**Issue by gitshub** [lark-parser/lark#780]
Hi,

I'm inexpert with python, but to run some examples I followed 

"How to run the examples:

After cloning the repo, open the terminal into the root directory of the project,"

and it seems to me that in

https://lark-parser.readthedocs.io/en/latest/examples/index.html
and
https://github.com/lark-parser/lark/blob/master/examples/README.rst

the line
   [lark]$ python -m examples.python_parser
should read
   [lark]$ python -m examples.advanced.python_parser

Also, in

https://github.com/lark-parser/lark/blob/master/examples/advanced/error_puppet.py

I had to change the line

from _json_parser import json_parser

to

from examples.advanced._json_parser import json_parser

Of course, you may know better ways to fix these issues.  Thanks.

**Comment by erezsh** [comment]
Thanks for letting us know. The examples have moved around recently, and I guess we missed a few spots.

**Comment by gitshub** [comment]
Thank you

**Comment by erezsh** [comment]
Let's keep it open, so I'll remember to fix it :)

**Comment by erezsh** [comment]
Well, that took way too long, lol.. But it's fixed now.

**Comment by gitshub** [comment]
Thanks
