### ISSUE TITLE
How would I parse an import statement with lark?

### ISSUE THREAD

**Issue by AbooMinister25** [lark-parser/lark#783]
So im parsing a programming language using lark, and I was wondering on how to implement an import system. I'm pretty sure I can import external grammars, but I'm not sure on how to import and connect external transformers to my main transformer, help would be appreciated, thanks!

**Comment by MegaIng** [comment]
This is something that Lark doesn't currently handle. You probably have to build the grammar at runtime, and same goes for the transformer. Here a few ideas for the transformer:

- If possible, you can keep subtrees that the Main Transformer doesn't work with intact, and pass those as a whole to the PLugin Transformer.
- You could implement `__default__` in the main Transformer, and dynamically look up the corresponding Sub transformer.
- You can also dynamically subclass the main transformer, and use all Sub transformer as mixins.

**Comment by erezsh** [comment]
Can you explain your question? Are you trying to implement an import system in your language, or to use Lark's import system to connect several subgrammars together?

**Comment by AbooMinister25** [comment]
Hey, thanks for the answer, what I'm trying to do is implement an import system for my language.
