### ISSUE TITLE
Generate random parse trees based on grammar

### ISSUE THREAD

**Issue by jlp1701** [lark-parser/lark#784]
I'm using Lark in a bigger compiler project with several passes. 
I would like to increase my testing depth by processing randomly generated parse trees, given my grammar, as input for unit and integration tests. 
Is there a feature like this already present and I missed it? If not, is this something that could be interesting for the project?
Possible parameters for random trees could be tree depth and a map token/rule -> function which can generate random samples for tokens or rules.

What do you think about that?

**Comment by MegaIng** [comment]
Hypothesis has a way of generating text based on Lark grammars: https://hypothesis.readthedocs.io/en/latest/_modules/hypothesis/extra/lark.html

**Comment by jlp1701** [comment]
Hey,
thanks for the hint, didn't know that. 
That solves my problem :)
