### ISSUE TITLE
Problem with indentation

### ISSUE THREAD

**Issue by ornariece** [lark-parser/lark#793]
hi, i am trying to use the built-in indentation parsing solution, but seem to fail in doing so.
here is my grammar, the indenter, and a few input examples the last of which fails to be parsed. the error it's throwing states it's not expecting a _DEDENT token before "indent_b", while, from my understanding, this is the token to expect.
am i doing something wrong?

```
from lark import Lark
from lark.indenter import Indenter


class _TreeIndenter(Indenter):
    NL_type = '_NL'
    OPEN_PAREN_types = []
    CLOSE_PAREN_types = []
    INDENT_type = '_INDENT'
    DEDENT_type = '_DEDENT'
    tab_len = 8


_parser = Lark(r"""
    ?start		: (key _NL _INDENT start _DEDENT)+ | command [_NL start]

    key         : KEY
    command     : COMMAND
    
    KEY	        : ( "a".."z" | "_" )+ ":"
    COMMAND     : /[^\n]/+
    
    %import common.WS_INLINE
    %declare _INDENT _DEDENT
    %ignore WS_INLINE
    
    _NL: /(\r?\n[\t ]*)+/
    """, parser='lalr', postlex=_TreeIndenter())


_parser.parse('smth')

_parser.parse('smth\nsmth')

_parser.parse('indent_a:\n    smth_a')

_parser.parse('indent_a:\n    smth_a\nindent_b:\n    smth_b')
```

**Comment by MegaIng** [comment]
I am not sure what you plan was with the `start` rule, but I don't think it is doing what you want it to do. Best split it up into multiple rules: `block`/`blocks` or similar.

**Comment by ornariece** [comment]
here is a (probably) cleaner syntax. i'm still having the same issue though
```
?start		: value (_NL value)*

?value      : pair | command
pair        : KEY _NL _INDENT start _DEDENT
command     : COMMAND

KEY	        : ( "a".."z" | "_" )+ ":"
COMMAND     : /[^\n]/+

%import common.WS_INLINE
%declare _INDENT _DEDENT
%ignore WS_INLINE

_NL: /(\r?\n[\t ]*)+/
```

**Comment by MegaIng** [comment]
Ok, the problem is that the grammar is wrong expectations about the order/amount of `_NL` Tokens.

This works:
```
?start		: value*

?value      : pair | command _NL?
pair        : KEY _NL _INDENT start _DEDENT
command     : COMMAND

KEY	        : ( "a".."z" | "_" )+ ":"
COMMAND     : /[^\n]/+

%import common.WS_INLINE
%declare _INDENT _DEDENT
%ignore WS_INLINE

_NL: /(\r?\n[\t ]*)+/
```

Note how I moved the `_NL` into `value`. The core of this problem is that after the `_DEDENT` of pair, there isn't a `_NL` (it is before the `_DEDENT`).

**Comment by ornariece** [comment]
riight, the ``_DEDENT`` handles the newline, meaning expecting a ``_NL`` right after it doesn't make sense in that case.
thanks!
