### ISSUE TITLE
Question about syntax of %ignore

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#796]
Isn't `%ignore` the same as `%declare`? Or am I missing something? If they are the same, then this could probably be more simplified

https://github.com/lark-parser/lark/blob/7b6a730abc5234ac27f23b7c4dfca34522135b8d/lark/grammars/lark.lark#L15

**Comment by erezsh** [comment]
I don't understand the question. They are different directives..

**Comment by ThatXliner** [comment]
Is the syntax of `%ignore` the same as `%declare`?
as in structure

**Comment by MegaIng** [comment]
No. You can put a literal (or any combination of them) as an argument for `%ignore`, but not for `%declare`. This is valid:
```
%ignore " "|"\t"
```
This isn't:
```
%declare " "
```

**Comment by ThatXliner** [comment]
oh ok.
