### ISSUE TITLE
Improve support for grammar inheritance

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#803]
- Implement `%override` for terminals
- Implement `%extend` for both rules and terminals
- Fix `%declare` to work for rules (to allow abstract grammars)

@MegaIng if you feel like it, you can implement these. Otherwise I'll do it at some point.

**Comment by MegaIng** [comment]
Would you opposed to add these points:

[ ] refactor of `GrammarLoader.load_grammar`
[ ] adding a `GrammarBuilder` class, allowing for a gradual building of a `Grammar` object, to be used when creating plugin system.

I have a few ideas for the `GrammarBuilder`. (It could also just the `GrammarLoader` class with a bit of refactor work put into it.)

Here a few methods I would expect:

- `add_grammar`, which takes a source code and adds it in it entirety.
  - This should also have an parameter `mangle_except` or similar, which would do what is currently done to the names of import rules and terminals
- `import_grammar`, which takes the name (or path) of a grammar file (also with `mangle_except`)
- `define`/`override`/`extend`/`declare`/`ignore`, allowing one to define manually add entries to the grammar
  - I am not sure in what format `define` etc. should take their arguments
- `check` checks whether or not the currently added content is a legal grammar (same checks as done at the end of `load_grammar` at the moment). 
  - This implies that the other methods allow one to create a grammar in an illegal state without throwing (e.g. undefined rules/terminals)
- `build`, or `compile`, which would create either
  - a `Grammar` object, which would then be passable to `Lark`, meaing we would have to change the interface there
  - directly a `Lark` instance
- `to_source`, creating a source representation that should be at least somewhat humanly readable.

**Comment by MegaIng** [comment]
Also, is there a particular reason why `expansions` is handle as a recursive structure and not inlined while parsing like `expansion` is?

**Comment by erezsh** [comment]
> refactor of GrammarLoader.load_grammar

Yes, that's probably a good idea, especially with the recent additions

> adding a GrammarBuilder class

How do you imagine it helping the creation of a plugin system? Will they be able to interject at the different stages of building the grammar? That would make any future internal refactor backwards incompatible.

I have a few more questions:

> mangle_except

What does that mean?

> define

What does that do? Why is it needed?

Other than the separate `check` and addition of `to_source` (which should work with the current implementation), it seems like a very similar design to the current one.

> Also, is there a particular reason why expansions is handle as a recursive structure

Not sure I understand the question.

**Comment by erezsh** [comment]
Keep in mind I haven't read the code there for a few months, at least, so it would help if you explained it a little more clearly.

**Comment by MegaIng** [comment]
> How do you imagine it helping the creation of a plugin system? Will they be able to interject at the different stages of building the grammar?

I would imagine that a plugin system would have multiple grammars that should be put together into one parser. Currently there isn't a good method of combing them:

- Just putting together the grammars into one str. Doesn't work when you have clashing names.
- Importing each subgrammar. Sadly, the subgrammars need to be complete, meaning they would all have to import a base grammar which leads to bloated grammar objects.

`extend` and `override` already go a long way, now we just need to have a decent way of loading multiple different grammars.

> define

The basic rule/term syntax, e.g. default non-override/non-extend. If you have a better name, suggest it.

> mangle_except

The current implementation prefix names when importing them with the name of the grammar to prevent clashing in the resulting grammar. `mangle_except` would activate this mangling, but skip all names in the list. My reasoning for putting the activation and the exclude list in the same parameter is that loading a grammar where everything is mangled is kinda useless.

> Also, is there a particular reason why expansions is handle as a recursive structure

https://github.com/lark-parser/lark/blob/955e64597abbb90895165140de63eeb72394f7a5/lark/load_grammar.py#L113

In comparison to

https://github.com/lark-parser/lark/blob/955e64597abbb90895165140de63eeb72394f7a5/lark/load_grammar.py#L118

This makes handling it a little annoying. 

---

I will make a PR that implements at least some of this.

**Comment by MegaIng** [comment]
Would you be ok with breaking backwards compatiblty in the names that imported names get in the resulting tree? Currently, they get a name consiting of the path where the grammar was import:

Grammar `a` imports `b`, which imports from `c`. The rules and terminals from `c` that don't get used in `a` are now named `b__c__[name}`. Would you be ok with them just being named `c__[name}`? This would also reduce duplications, since if `a` also imports `c`, the rules might be present twice with the prefixes`c__` and `b__c__`.

**Comment by erezsh** [comment]
This naming scheme was adopted so that we can display an error that makes sense to the user, and won't make them wonder where that rule or terminal came from. But perhaps it makes more sense, now that we are expanding the capabilities of the grammar, to separate it to `id` and `display_path`. Where, `id` is the more optimized  `c_{hash}` and `display_path` would be `a.b.c`, which would also improve the errors.

**Comment by erezsh** [comment]
> Sadly, the subgrammars need to be complete, meaning they would all have to import a base grammar which leads to bloated grammar objects.

Do they really? I thought `%declare` would take of that issue.

> The basic rule/term syntax, e.g. default non-override/non-extend. If you have a better name, suggest it.

I don't have a name, because I don't understand why a name is needed. That's just the default rule declaration, isn't it?

> mangle_except

Maybe something like this would make more sense?

`[rule if rule in imported else mangle(rule) for rule in rules]`

**Comment by MegaIng** [comment]
I am completely failing at coming up for a design for the `GrammarBuilder` class that both fits the needs of normal grammar loading and also of my own needs of manually putting together a grammar out of multiple parts, while not being overly complicated. This is very easy when I don't need to handle imports and name mangling, but as soon as that is a factor I have zero ideas for a decent interface.

---

> I don't have a name, because I don't understand why a name is needed. That's just the default rule declaration, isn't it?

The idea was that it is possible to manually declare rule by calling a function on the class. But I think I will be dropping this public interface.

> Do they really? I thought %declare would take of that issue.

(Currently doesn't work for rules). Importing also has the problem that grammars need to be accessible as files, which is not always possible/easy. Being able to combine the grammars with name mangling from a text would be better.

> Maybe something like this would make more sense?

Yeah, I am not really sold on a what the correct interface is here.

**Comment by erezsh** [comment]
> The idea was that it is possible to manually declare rule by calling a function on the class. But I think I will be dropping this public interface.

Oh, you meant to make it accessible as a Python API?

> (Currently doesn't work for rules). Importing also has the problem that grammars need to be accessible as files, which is not always possible/easy. Being able to combine the grammars with name mangling from a text would be better.

The point is that it will work for rules. Then you can declare them without defining them, and import them, which would stop them from being mangled.

I don't understand what use-case you think wouldn't work with that system.

-------------------

Regarding design, what are you struggling with?

I'm under the impression that only `load_grammar` really needs to change, by

* Rewriting it so `override`, `extend`, etc. work on the entire set of symbols, and only use rule/terminal specific code when necessary

* Extracting the validation code to a different method (and even that, I'm not sure is necessary)

Do you have any specific use-case in mind? Is there any leading principle that makes you think that this isn't enough?

**Comment by MegaIng** [comment]
> Oh, you meant to make it accessible as a Python API?

Yes that was the plan. I am not sure if I will go through with.

> I don't understand what use-case you think wouldn't work with that system.

When you have different plugins that each define their own grammar they want to add, their grammar files might be in different places across the file system, meaning that it isn't really possible to have a consistence path to `%import` from.

> I'm under the impression that only load_grammar really needs to change,

My goal is to also break up this function into smaller functions to be easier extensible. 

> Extracting the validation code to a different method (and even that, I'm not sure is necessary)

This makes it easier to use subgrammars, since there is nothing forcing them to be complete on their own. Also, it causes a speedup since not everything is checked multiple times.

**Comment by erezsh** [comment]
> Yes that was the plan. I am not sure if I will go through with.

Seems a bit extraneous.. Might as well use something like

```python
lark_instance.feed('rule: A B C')
lark_instance.feed('%override rule: A B C')
```

That way you don't have to invent a whole new API, and it's probably nicer visually anyway

> When you have different plugins that each define their own grammar they want to add, their grammar files might be in different places across the file system, meaning that it isn't really possible to have a consistence path to %import from.

Why can't each plugin define its own base import path?

I can't imagine what the difficulty is. Maybe give me an actual scenario.

> it causes a speedup since not everything is checked multiple times.

Yes, a good point.

**Comment by MegaIng** [comment]
> Seems a bit extraneous.. Might as well use something like

That is also something I realized after some thinking about it. Only think I would add are convince functions for loading a grammar from a file.

> `lark_instance`

Well that won't work (unless you want to redesign quite a bit of the core interface). Here I would stick with GrammarBuilder (or similar)

--- 

> Why can't each plugin define its own base import path?

Yeah true, with the new interface it might be possible to this this somewhat nicely. You still have to auto generate some kind of main grammar that `%import` all the grammars of the plugins though.

**Comment by erezsh** [comment]
> You still have to auto generate some kind of main grammar that %import all the grammars of the plugins though.

Again not following. But even so, that doesn't sound hard.

**Comment by erezsh** [comment]
Done.
