### ISSUE TITLE
Lark parse performance and parent / child indentation

### ISSUE THREAD

**Issue by mpenning** [lark-parser/lark#806]
**What is your question?**

I have a text parser ([ciscoconfparse](https://github.com/mpenning/ciscoconfparse)) which I use to parse various configurations.   [ciscoconfparse](https://github.com/mpenning/ciscoconfparse) parent / child line assignment happens based on whether the child candidate line is indented more than the parent is indented.  See Example01 below.

All code in this github issue was parsed under Debian 10 and Python3.7:
* Lark version 0.11.1
* ciscoconfpasre version 1.5.22

**If you're having trouble with your code or grammar**

I am interested in converting my script to use Lark, but I can't stomach the Lark performance hit that I see in Example01.  ciscoconfparse is 20x faster than Lark's parse times (of the same text).

* Is there a way for me to accelerate Lark's parse time in Example01?
* So far, I can't find a way to extract `indent_level` for the Lark-parsed config.  Can someone give me assistance with how I can quantify the indent-level of each Lark-parsed line in Example01?

[As recommended in Lark's docs](https://lark-parser.readthedocs.io/en/latest/examples/indented_tree.html), the `NL` Token parses the next-lines' whitespace indent.  I realize I could carry the `indent_level` over from the previous-line's `NL` but I hope for a simpler option than that.

Explain what you're trying to do, and what is obstructing your progress.

```python
# Example01
# File: lark_test_indent.py
import time

from lark import Lark
from lark.indenter import Indenter

from ciscoconfparse import CiscoConfParse

from snoop import Config
config = Config(color=True)
snoop = config.snoop

class MyTreeIndenter(Indenter):
    tab_len = 1
    NL_type = 'NL'
    OPEN_PAREN_types = []
    CLOSE_PAREN_types = []
    INDENT_type = '_INDENT'
    DEDENT_type = '_DEDENT'

grammar = r"""
start        : (empty_line
             | instruction
             | comment)+

comment      : (_INDENT | _DEDENT)* COMMENT NL
instruction  : (_INDENT | _DEDENT)* INSTRUCTION NL
empty_line   : NL+

// Tokens are defined with uppercase names...
COMMENT       : /\![^\n]*/
INSTRUCTION   : /\w[^\n]*/
// NL *must* match leading whitespace on new lines...
NL            : /(\r?\n)+[\s\t]*/


%import common.WS_INLINE
%ignore WS_INLINE
%declare _INDENT _DEDENT
"""

text_01 = """
vehicle for Jim
 600 horsepower
 18 wheels
 red color
 2 doors
  chrome handles outside
  no pushbutton lock outside
"""

text_02 = """
vehicle for Jim
 600 horsepower
 18 wheels
 red color
 2 doors
  chrome handles outside
  pushbutton lock outside
vehicle for Charles
 320 horsepower
 4 wheels
 green color
 4 doors
 !
  chrome handles outside
  !no pushbutton lock outside
!
"""

#@snoop(depth=2)
def lark_parse(instructions=""):
    parser = Lark(grammar, parser='lalr', postlex=MyTreeIndenter())
    parse_tree = parser.parse(instructions)
    for inst_obj in parse_tree.children:
        print("INSTRUCTION", str(inst_obj))

def ccp(instructions=""):
    parse = CiscoConfParse(instructions.splitlines())
    for obj in parse.ConfigObjs:
        print(obj, "Comment:", obj.is_comment)

if __name__=='__main__':
    begin = time.time()
    lark_parse(text_02)
    end = round(time.time() - begin, 6)
    print("Lark parse time: %s" % end)

    print("---------------------------")

    begin = time.time()
    ccp(text_02)
    end = round(time.time() - begin, 6)
    print("CiscoConfParse parse time: %s" % end)
```

Example01 parse output:
```
$ python lark_test_indent.py
INSTRUCTION Tree('empty_line', [Token('NL', '\n')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', 'vehicle for Jim'), Token('NL', '\n ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', '600 horsepower'), Token('NL', '\n ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', '18 wheels'), Token('NL', '\n ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', 'red color'), Token('NL', '\n ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', '2 doors'), Token('NL', '\n  ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', 'chrome handles outside'), Token('NL', '\n  ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', 'pushbutton lock outside'), Token('NL', '\n')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', 'vehicle for Charles'), Token('NL', '\n ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', '320 horsepower'), Token('NL', '\n ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', '4 wheels'), Token('NL', '\n ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', 'green color'), Token('NL', '\n ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', '4 doors'), Token('NL', '\n ')])
INSTRUCTION Tree('comment', [Token('COMMENT', '!'), Token('NL', '\n  ')])
INSTRUCTION Tree('instruction', [Token('INSTRUCTION', 'chrome handles outside'), Token('NL', '\n  ')])
INSTRUCTION Tree('comment', [Token('COMMENT', '!no pushbutton lock outside'), Token('NL', '\n')])
INSTRUCTION Tree('comment', [Token('COMMENT', '!'), Token('NL', '\n')])
Lark parse time: 0.037327
---------------------------
<IOSCfgLine # 0 'vehicle for Jim'> Comment: False
<IOSCfgLine # 1 ' 600 horsepower' (parent is # 0)> Comment: False
<IOSCfgLine # 2 ' 18 wheels' (parent is # 0)> Comment: False
<IOSCfgLine # 3 ' red color' (parent is # 0)> Comment: False
<IOSCfgLine # 4 ' 2 doors' (parent is # 0)> Comment: False
<IOSCfgLine # 5 '  chrome handles outside' (parent is # 4)> Comment: False
<IOSCfgLine # 6 '  pushbutton lock outside' (parent is # 4)> Comment: False
<IOSCfgLine # 7 'vehicle for Charles'> Comment: False
<IOSCfgLine # 8 ' 320 horsepower' (parent is # 7)> Comment: False
<IOSCfgLine # 9 ' 4 wheels' (parent is # 7)> Comment: False
<IOSCfgLine # 10 ' green color' (parent is # 7)> Comment: False
<IOSCfgLine # 11 ' 4 doors' (parent is # 7)> Comment: False
<IOSCfgLine # 12 ' !' (parent is # 7)> Comment: True
<IOSCfgLine # 13 '  chrome handles outside' (parent is # 11)> Comment: False
<IOSCfgLine # 14 '  !no pushbutton lock outside' (parent is # 11)> Comment: True
<IOSCfgLine # 15 '!'> Comment: True
CiscoConfParse parse time: 0.001478
$
```

**Comment by erezsh** [comment]
Hi @mpenning 

You are not only measuring the parse time, but also the construction of the grammar, which is a one time cost. Try running your benchmark like this:

```python
parser = Lark(grammar, parser='lalr', postlex=MyTreeIndenter())

#@snoop(depth=2)
def lark_parse(instructions=""):
    parse_tree = parser.parse(instructions)
    for inst_obj in parse_tree.children:
        print("INSTRUCTION", str(inst_obj))
```

I think you'll find that the performance is very similar.

You can also look into using the `cache=True` option, so that the init time will be even shorter.

**Comment by mpenning** [comment]
> Hi @mpenning
> 
> You are not only measuring the parse time, but also the construction of the grammar, which is a one time cost. Try running your benchmark like this:
> 
> ```python
> parser = Lark(grammar, parser='lalr', postlex=MyTreeIndenter())
> 
> #@snoop(depth=2)
> def lark_parse(instructions=""):
>     parse_tree = parser.parse(instructions)
>     for inst_obj in parse_tree.children:
>         print("INSTRUCTION", str(inst_obj))
> ```
> 
> I think you'll find that the performance is very similar.
> 
> You can also look into using the `cache=True` option, so that the init time will be even shorter.

Hello @erezsh , thank you for your suggestions.  When I removed grammar parsing from the timing loop, `timeit()` shows that CiscoConfParse is roughly 3.5 times faster (when parsing the same text).

Do you have any other suggestions for improving performance?

FWIW, this was what I timed...

```python
# File: lark_test_indent.py
import timeit
import time
import os

from lark import Lark
from lark.indenter import Indenter

from ciscoconfparse import CiscoConfParse

from snoop import Config
config = Config(color=True)
snoop = config.snoop

class MyTreeIndenter(Indenter):
    tab_len = 1
    NL_type = "NL"
    OPEN_PAREN_types = []
    CLOSE_PAREN_types = []
    INDENT_type = "_INDENT"
    DEDENT_type = "_DEDENT"


GRAMMAR = r"""
start        : (empty_line
             | instruction
             | comment)+

comment      : (_INDENT | _DEDENT)* COMMENT NL
instruction  : (_INDENT | _DEDENT)* INSTRUCTION NL
empty_line   : NL+

// Tokens are defined with uppercase names...
COMMENT       : /\![^\n]*/
INSTRUCTION   : /\w[^\n]*/
// NL *must* match leading whitespace on new lines...
NL            : /(\r?\n)+[\s\t]*/


%import common.WS_INLINE
%ignore WS_INLINE
%declare _INDENT _DEDENT
"""

text_01 = """
vehicle for Jim
 600 horsepower
 18 wheels
 red color
 2 doors
  chrome handles outside
  no pushbutton lock outside
"""

text_02 = """
vehicle for Jim
 600 horsepower
 18 wheels
 red color
 2 doors
  chrome handles outside
  pushbutton lock outside
vehicle for Charles
 320 horsepower
 4 wheels
 green color
 4 doors
 !
  chrome handles outside
  !no pushbutton lock outside
!
"""

# @snoop(depth=2)
lark_parser = Lark(
    GRAMMAR,
    cache=os.path.join(os.path.abspath(os.getcwd()), "lark_test_indent.lark"),
    parser="lalr",
    postlex=MyTreeIndenter(),
)
def lark_parse(instructions=text_02):
    # Store parser as a global, outside this function...
    lark_parse_tree = lark_parser.parse(instructions)
    for inst_obj in lark_parse_tree.children:
        pass
        #print("INSTRUCTION", str(inst_obj))

def ccp(instructions=text_02):
    parse = CiscoConfParse(instructions.splitlines())
    for obj in sorted(parse.ConfigObjs):
        pass
        #print(obj, "Comment:", obj.is_comment)

if __name__ == "__main__":
    ITERATIONS = 1000
    t1_avg = timeit.timeit(stmt=lark_parse, number=ITERATIONS)
    print("Lark average parse time is %s seconds" % float(t1_avg/ITERATIONS))
    print("---------------------------")

    t2_avg = timeit.timeit(stmt=ccp, number=1000)
    print("CiscoConfParse parse time is %s seconds" % float(t2_avg/ITERATIONS))
```

**Comment by MegaIng** [comment]
A dedicated parser will almost always be faster than something like Lark. There might be small stuff, but a lot faster will not be possible. 

`(_INDENT | _DEDENT)*` is a complete NOP, meaning currently you can completely drop `Indenter` and the corresponding parts in your grammar and the result will be the same.

**Comment by erezsh** [comment]
Is the quest for speed driven by practical considerations, or it more of a theoretical exercise?

Because if you're after speed, the best and easiest thing you can do is switch to PyPy instead of CPython.

Also, `NL` already catches multiple newlines. It will be slightly faster if you just define
```
empty_line   : NL
```

**Comment by mpenning** [comment]
Megalng [said](https://github.com/lark-parser/lark/issues/806#issuecomment-751519113):
> A dedicated parser will almost always be faster than something like Lark. There might be small 
> stuff, but a lot faster will not be possible.

ok, it seems like we're approaching the same problem space from different directions.  CiscoConfParse was originally a "whitespace-only" parser and I've had to glue in support for brace-delimited config parsing after-the-fact.   On the other hand, Lark is a general-purpose parsing library.

> `(_INDENT | _DEDENT)*` is a complete NOP, meaning currently you can completely drop `Indenter` 
> and the corresponding parts in your grammar and the result will be the same.
 
Do you any suggestions for how I can properly Tokenize `_INDENT` and `_DEDENT` for whitespace-parsing in Example01?

**Comment by mpenning** [comment]
erezsh [said](https://github.com/lark-parser/lark/issues/806#issuecomment-751519933)
> Is the quest for speed driven by practical considerations, or is it more of a theoretical exercise?
> 

Fair question; this is not a theoretical exercise.  I am considering how I can replace the parsing guts in CiscoConfParse with a general-purpose parser like Lark.  After someone parses an original Cisco IOS config with CiscoConfParse, adding / removing  config lines incurs a "reparse from scratch" penalty for every atomic config change.   As configs get big, reparsing from scratch is  slow and I'm trying to avoid making it "really slow".  See where I'm calling [`_bootstrap_from_text()`](https://github.com/mpenning/ciscoconfparse/blob/1e25bd0fdf254e8ae17fddf07cc9c0fa432b40db/ciscoconfparse/ciscoconfparse.py#L3118) in CiscoConfParse to get an idea of reparsing status quo.

> Because if you're after speed, the best and easiest thing you can do is switch to PyPy instead of CPython.
> 

I would like to avoid asking people to switching their python environment just to fix "slow operations in CiscoConfParse".

**Comment by MegaIng** [comment]
> Do you any suggestions for how I can properly Tokenize _INDENT and _DEDENT for whitespace-parsing in Example01?

That depends on what your goal is. Your current grammar is probably not finished. You should first make the grammar work correctly and then make it faster.

**Comment by erezsh** [comment]
> As configs get big, reparsing from scratch is slow and I'm trying to avoid making it "really slow"

Are you sure that parsing is the biggest bottleneck here?

You should probably do some measurements before assuming that.

**Comment by mpenning** [comment]
> > As configs get big, reparsing from scratch is slow and I'm trying to avoid making it "really slow"
> 
> Are you sure that parsing is the biggest bottleneck here?
> 
> You should probably do some measurements before assuming that.

Wow.  I've maintained CiscoConfParse for over a decade.  I could say more, but... nevermind... this is really a really quick test...

<hr>
<pre>
(py37_test) [mpenning@mudslide ciscoconfparse]$ python append_performance_test.py
Append 1000 lines without reparse took 5.41691230610013e-05 seconds per operation
---------------------------
Append 1000 lines **with reparse** took 0.01367343232105486 seconds per operation
---------------------------
At 1000 lines, append with reparse takes 252.4211497 times longer than a simple append
(py37_test) [mpenning@mudslide ciscoconfparse]$
</pre>

<hr>

Source code:

```python
import timeit

from ciscoconfparse import CiscoConfParse

ORIGINAL_CONFIG = """!
interface GigabitEthernet 1/1
 ip address 192.0.2.1 255.255.255.0
!
end
"""

parse = CiscoConfParse(ORIGINAL_CONFIG.splitlines())
intf_obj = parse.find_objects(r"^interface")[0]

def modify_without_reparsing():
    intf_obj.append_to_family(" description TestThisOperation")

def modify_with_reparsing():
    intf_obj.append_to_family(" description TestThisOperation")
    parse.atomic()

if __name__=="__main__":
    ITERATIONS = 1000
    t1_avg = timeit.timeit(stmt=modify_without_reparsing, number=ITERATIONS)
    print("Append %s lines without reparse took %s seconds per operation" % (ITERATIONS, float(t1_avg/ITERATIONS)))
    print("---------------------------")

    t2_avg = timeit.timeit(stmt=modify_with_reparsing, number=ITERATIONS)
    print("Append %s lines **with reparse** took %s seconds per operation" % (ITERATIONS, float(t2_avg/ITERATIONS)))

    print("---------------------------")

    print("At %s lines, append with reparse takes %s times longer than a simple append" % (ITERATIONS, round(t2_avg/t1_avg, 7)))
```

**Comment by erezsh** [comment]
I don't get it. Is this an issue with Lark?

**Comment by mpenning** [comment]
> I don't get it. Is this an issue with Lark?

I answered [your question](https://github.com/lark-parser/lark/issues/806#issuecomment-751528261), which said nothing about parsing with Lark.
