### ISSUE TITLE
Adding a priority to a rule causes parser to run without termination

### ISSUE THREAD

**Issue by michelleful** [lark-parser/lark#807]
**Describe the bug**

I am writing a grammar to parse a few Classical Chinese sentences as I work through a book on the subject. The grammar is highly ambiguous (nouns can act as verbs, etc). I added a rule (below, `verbal_sentence_no_subject`) that is necessary but resulted in a lot of the default parses opting to use that rule incorrectly. Therefore, I tried to increase the priority of a competing rule so that `verbal_sentence_no_subject` would not be picked as often. However, upon adding the priority setting, the script, which previously took 0.106s to run, now continues running for over an hour without terminating.

**To Reproduce**

I apologise that this is not short but I think the amount of ambiguity is necessary to reproduce the behaviour. I don't expect anyone to actually work through this grammar to figure out what's going on, I'm just wondering (a) whether it's expected that adding a priority can cause this behaviour, (b) whether I did something wrong with the priority setting, or (c) if there is another way to approach this. Basically, I want the `verbal_sentence_no_subject` rule to only kick in when a parse is impossible without it.

```
from lark import Lark

grammar = """
    sentence: sentence*
            | verbal_sentence
            | verbal_sentence_no_subject
            | nominal_sentence

    verbal_sentence.1: noun verb  # <------- Adding the positive priority to this rule
                                  #          causes the issue. Without it, the script
                                  #          runs very fast (but with what are, from 
                                  #          my perspective, sub-optimal parses)
                                  #          remove this comment to run the code.
    verbal_sentence_no_subject: verb
    nominal_sentence: noun noun nominal_particle

    noun: PROPER_NOUN | NOUN | stative_verb
    verb: adverb? VERB direct_object? indirect_object?
        | negative? stative_verb
    stative_verb: adverb? STATIVE_VERB | noun
    direct_object: noun
    indirect_object: preposition noun

    negative: NEGATIVE
    adverb: ADVERB
    nominal_particle: NOM_PRT
    preposition: PREPOSITION
    
    PROPER_NOUN: "子" | "孔子" | "齊景公" | "公" | "樊遲"
    NOUN: "性" | "習" | "政" | "君" | "臣" | "父" | "子" | "仁" | "人"
    ADVERB: "相" | "對"
    STATIVE_VERB: "近" | "遠"
    VERB: "曰" | "問" | "愛" | "知"
    NEGATIVE: "不"
    NOM_PRT: "也"
    PREPOSITION: "於"
"""

parser = Lark(grammar, start="sentence")

print(parser.parse("齊景公問政於孔子孔子對曰君君臣臣父父子子公曰君不君臣不臣父不父子不子").pretty())
```

Thank you!

**Comment by erezsh** [comment]
@chanicpanic Got ideas? It seems like `ForestSumVisitor` is choking on this grammar.

**Comment by chanicpanic** [comment]
@michelleful 
Your grammar is cyclical. If you change `sentence` to `(verbal_sentence | verbal_sentence_no_subject | nominal_sentence)*`, the parse terminates in a few seconds.

@erezsh 
I think `ForestSumVisitor` is taking an excessively long time traversing the SPPF because it has so many cycles. I could make it handle cycles similar to how `ForestToParseTree` does. In that case, it might be worthwhile to extract this behavior to `ForestVisitor`.

**Comment by erezsh** [comment]
@chanicpanic That sounds like a good plan.

**Comment by michelleful** [comment]
Thank you @chanicpanic that does work a lot better! Thanks also @erezsh for your help!
