### ISSUE TITLE
How to parse the exception symbol in EBNF?

### ISSUE THREAD

**Issue by moewww** [lark-parser/lark#812]
**What is your question?**

Through the [wiki](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form
) (See *Table of symbols*), I learned that there is an `exception symbol` in EBNF, but when I tried to parse it using lark, I got an exception.

**If you're having trouble with your code or grammar**

```
from lark import Lark

l = Lark('''
            DIGIT: "0".."9"
            LCASE_LETTER: "a".."z"
            UCASE_LETTER: "A".."Z"
            LETTER: UCASE_LETTER | LCASE_LETTER
            KEYWORDS: "bool"
                | "double"
                | "float"
                | "int"
            
            NAME: LETTER (LETTER | DIGIT | "_")* - KEYWORDS

            
            start: NAME
            %ignore " "           // Disregard spaces in text
         ''')

print(l.parse("bool"))
```

Explain what you're trying to do, and what is obstructing your progress.

My expectation is that `KEYWORDS` should not be included in the `NAME`, but there is an error in this line `NAME: LETTER (LETTER | DIGIT | "_")* - KEYWORDS`

**Comment by MegaIng** [comment]
Lark doesn't support this syntax. You don't need to worry about it, lark will do the right thing™. There wont be a conflict when parsing this. Just in case, you can give `KEYWORDS` a higher priority. (by using `KEYWORDS.2: `)

**Comment by erezsh** [comment]
As @MegaIng said, there is no "substraction" syntax in Lark.

Lark, by default, will recognize that KEYWORDS are a subset of NAME, and make sure to match them instead.

**Comment by moewww** [comment]
Thank you, @erezsh @MegaIng

**Comment by moewww** [comment]
I'm sorry to reopen this issue. I wrote a demo following the instructions above, but the result was not as expected.
```python
from lark import Lark

l = Lark('''
KEYWORDS.2: "bool"
    | "double"
    | "float"
    | "int"

IDENTIFIER: ("a".."z" | "A".."Z") ("a".."z" | "A".."Z" | "0".."9" | "_")*

demo: "demo" (IDENTIFIER | KEYWORDS) ";"

start: demo

WHITESPACE: " "
%ignore WHITESPACE''', parser="lalr")

print(l.parse("demo bool;"))
# Output: Tree('start', [Tree('demo', [Token('KEYWORDS', 'bool')])])
print(l.parse("demo username;"))
# Output: Tree('start', [Tree('demo', [Token('IDENTIFIER', 'username')])])
print(l.parse("demo integer;"))
"""
Expect: Tree('start', [Tree('demo', [Token('IDENTIFIER', 'integer')])])
But got an exception
~~~~~~~~~~~~~~~~~~~~~
lark.exceptions.UnexpectedToken: Unexpected token Token('IDENTIFIER', 'eger') at line 1, column 9.
Expected one of: 
        * SEMICOLON
Previous tokens: [Token('KEYWORDS', 'int')]
"""
```

**Comment by moewww** [comment]
Finally I decided to implement this function in the transformer.
