### ISSUE TITLE
Ambiguous grammar help

### ISSUE THREAD

**Issue by InCogNiTo124** [lark-parser/lark#815]
**What is your question?**

Hello,
I have a pretty ambiguous grammar and I need help in getting around the problem.

**If you're having trouble with your code or grammar**
Provide a small script that encapsulates your issue.
This is a toy example with a stripped down grammar:
```from lark import Lark

grammar="""start: expression
?expression: _monoarg{"len"i} -> len | _monoarg{"len_p"i} -> len_p | _monoarg{"len_s"i} -> len_s | MBR
_monoarg{x}: x "(" expression ")"
_biarg{x}: x "(" expression "," expression ")"
MBR: ("a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z")+ | SIGNED_NUMBER
%import common.SIGNED_NUMBER
%ignore " "
"""

parser = Lark(grammar, parser='lalr')
parser.parse("len_s(abcbac)")
```
Explain what you're trying to do, and what is obstructing your progress.

I need to parse the string `len_s(abcbac)` and evaluate it (using a custom defined definition of `len_s` - not important for this situation). I modified [the REPL calc](https://lark-parser.readthedocs.io/en/latest/examples/calc.html#sphx-glr-examples-calc-py) example.
My current implementation uses `Transformer` class to recursively apply my transformations to the AST. If the `MBR` terminal is constrained to `("a" | "b" | "c")+`, there is no problem, but if I allow all the lowercase letters for the `MBR` terminal, the following error shows:
```
raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal defined for '_' at line 1 col 4

len_s(abcbac)
   ^

Expecting: {'LPAR', 'MBR', 'LEN', '__ANON_1', 'RPAR', '__ANON_0'}

Previous tokens: Token('LEN', 'len')
```

If I use `Earley` parser, the parsing succeeds but I cannot evaluate it with the transformer.

Is there any way to parse _and evaluate_ the parse tree despite these ambiguities? I would like to retain this grammar if possible.

**Comment by InCogNiTo124** [comment]
I actually found out I can transform the tree **after** I've parsed it with `earley`. Somehow I missed that in the documentation haha

Anyhow, I will be closing this one now. Sorry for getting ahead of myself.

**Comment by MegaIng** [comment]
Alternative fix, if you want to use the generally faster lalr parser: Specify a priority for `MBR` lower than the default (1). The the literals will be matched first:

```
start: expression
?expression: _monoarg{"len"i} -> len | _monoarg{"len_p"i} -> len_p | _monoarg{"len_s"i} -> len_s | MBR
_monoarg{x}: x "(" expression ")"
_biarg{x}: x "(" expression "," expression ")"
MBR.0: ("a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z")+ | SIGNED_NUMBER
%import common.SIGNED_NUMBER
%ignore " "
```

This might have other problems, but here it works.

**Comment by InCogNiTo124** [comment]
This is even better!
