### ISSUE TITLE
Markdown parser

### ISSUE THREAD

**Issue by buhl** [lark-parser/lark#817]
**What is your question?**
I have been using the weekend trying to learn how to use lark and decided to try to make a markdown parser.
Being a noob, in hindsight, i could probably have chosen a more simple first task.

This is how far I have gotten
https://gist.github.com/buhl/0f7b738f4b096edafd16f4873e7d4958

I would like some comments, ideas on what I am doing wrong/could do better

The solution still feels a bit shaky

**If you're having trouble with your code or grammar**
I am yet to try to make nested lists. Ideas on this would also be appreciated
I will update the gist if I succeed in using INDENT/DEDENT.

I hope it's okay to ask for this kind of help here.
Thanks in advance

**Comment by MegaIng** [comment]
The reason this feels shaky is that Markdown isn't really a CFL (Context free language). This directly includes stuff like the list syntax requiring indentation handling, header line syntax with `---`, and similar. But also problematic is that there is a lot of ambiguity, especially with the bold/italic syntax. In general lark is not really made for this stuff. Markdown is normally parsed manually.

---

> I hope it's okay to ask for this kind of help here.

It's okay. Maybe slightly better would be the [gitter chat](https://gitter.im/lark-parser/Lobby).

**Comment by erezsh** [comment]
I agree, Lark isn't best suited for parsing Markdown.

The main thing Lark (and context-free parsers in general) is good for is recognizing recursive structures. There's very little structure in Markdown. There are lists, and tables, but they are not context-free, so Lark isn't the best tool to parse them.

You also omitted from your grammar the only thing that *does* have structure in Markdown, which is the sections.

Here's how a grammar that takes sections into account might look (taken from a snippet I wrote once):

```lark
start: section0

section0: text? section1*
section1: heading1 text? section2*
section2: heading2 text? section3*
section3: heading3 text?

text: text_line+

heading1: HEADING1 text_line
heading2: HEADING2 text_line
heading3: /### (.+)/ text_line

HEADING1: /# (.+)/
        | /(.+)/ _NL /===+/

HEADING2: /## (.+)/
        | /(.+)/ _NL /---+/

text_line: TEXT? _NL

TEXT.0: /.+/
_NL: /\r?\n/
```

But ideally, you wouldn't want the lexing done using Lark, but using a custom-lexer that was written especially for markdown.

**Comment by buhl** [comment]
Hey @MegaIng and @erezsh 
Thank you for your input. I had a feeling I was doing something a little silly.
But it was a fun dive into a new (for me) topic. :smile:

On a side-note: How is the priority rule enforced in your example @erezsh?

**Comment by erezsh** [comment]
It means it will be matched after everything else (default priority is 1)

It's necessary in this case, because it will literally match anything, so it's essentially an "else" clause.

**Comment by buhl** [comment]
Thank you so much for taking your time helping me. I think we can close this issue now if it's OK with you?
