### ISSUE TITLE
Problem Parsing Python 3 Collection Initializers 

### ISSUE THREAD

**Issue by david-29** [lark-parser/lark#824]
The sample Python 3 parser can't parse collection initializers like:

FOO: Set[str] = {
    'abc', 'def', 'xyz'
}

The error is:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\lark\lexer.py", line 431, in lex
    yield lexer.next_token(lexer_state)
  File "C:\Python39\lib\site-packages\lark\lexer.py", line 354, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal defined for '\n' at line <nnn> col <ccc>

Likely a problem with EOL, INDENT, DEDENT processing.  Or just no grammar section for initializations.

In the Python REPL:

>>> from typing import Set
>>> FOO: Set[str] = {
... 'abc', 'def', 'xyz'
... }
>>> FOO
{'xyz', 'def', 'abc'}
>>>

**Comment by MegaIng** [comment]
How are you creating the `Lark` instance? What options are you passing? With the default parser as created in `python_parser.py` I can parse this.

**Comment by david-29** [comment]
Hi Erez,

This is what I used:

class Parser:

    def __init__(self):
        self.parser = lark.Lark(grammar, start='file_input',
parser='lalr', propagate_positions=True)

    def parse(self, text: str):
        try:
            tree: lark.Tree = self.parser.parse(text)
        except lark.exceptions.UnexpectedInput as e:
            print(f"Parser error [unexpected
input]:\n{e.get_context(text, 24)}")
            raise
        return tree



This is for an experimental translator, Python 3 ==> Rust. I'm trying to
parse some of my own Python code.

As an aside, I have used your parser generator successfully as part of an
interpreter for a data sciences DSL of my own. The LALR version, I didn't
need Earley. I felt the need to rewrite / transform your tree into my own
AST, which I walk three times, first to check that variables are defined,
second to perform type checking and third to interpret and evaluate my
(vector) expression lists.

I think I could use your tree directly for all three steps if I understood
your code better. I may go back later and have a go at that.

Your parser is a much better fit to my needs coding in Python than Antlr 4.
Congratulations on a great piece of software!

Best,
David



David Beckedorff
314 Chicago Blvd
Sea Girt, NJ  08750

Mobile:  (781) 820-0567
Home:  (732) 449-3473

**Comment by erezsh** [comment]
Hi,

The Python example shows how you are supposed to initialize Lark: https://github.com/lark-parser/lark/blob/master/examples/advanced/python_parser.py

It won't work without a postlex.

> As an aside

I think the Lark tree serves best as an intermediate tree. If you're doing iterated operations on the tree, and especially if you mutate it, it's better to create the AST using Python classes, that capture the hierarchy and validate the types.

> Congratulations on a great piece of software!

Thank you. Coincidentally, my new project can also be described as a DSL for data science. Take a look if you're curious: https://github.com/erezsh/Preql

**Comment by david-29** [comment]
Thank you for the postlex tip ...

Impressive:

D:\EzmAlpha\venv\Scripts\python.exe D:/EzmAlpha/to_rust/translator.py

text len= 12086

Parsing ...

file_input
  import_stmt
    import_from
      dotted_name typing
      import_as_names
        import_as_name List
        import_as_name Tuple
        import_as_name Set
        import_as_name Dict
  expr_stmt
    var ALLOWED_DATE_PERIODICITIES
    annassign
      getitem
        var Set
        subscript
          var str
      set
        set_comp
          string 'Y'
          string 'y'
          string 'Q'
          string 'q'
          string 'M'
          string 'm'
          string 'W'
          string 'w'
          string 'D'
          string 'd'
  expr_stmt
    var MODE_TO_PERIODICITY_MAP
    annassign
      getitem
        var Dict
        subscript_tuple
          subscript
            var int
          subscript
            var str
      dict
        dict_comp
          key_value
            number 1
            string 'Y'
          key_value
            number 2
            string 'Q'
          key_value
            number 3
            string 'M'
          key_value
            number 4
            string 'W'
          key_value
            number 5
            string 'D'
  expr_stmt
    var _PERIODICITY_TO_MODE_MAP
    annassign
      getitem
        var Dict
        subscript_tuple
          subscript
            var str
          subscript
            var int
      dict
        dict_comp
          key_value
            string 'Y'
            number 1
          key_value
            string 'Q'
            number 2
          key_value
            string 'M'
            number 3
          key_value
            string 'W'
            number 4
          key_value
            string 'D'
            number 5
  expr_stmt
    var _NDM_OFFSET1
    annassign
      getitem
        var List
        subscript
          var int
      list
        tuplelist_comp
          number 0
          number 0
          number 31
          number 59
          number 90
          number 120
          number 151
          number 181
          number 212
          number 243
          number 273
          number 304
          number 334

. . .  [a few thousand lines omitted]


        return_stmt
          testlist
            arith_expr
              term
                var nwks
                *
                number 5
              +
              var ndw2
              -
              var ndw1
              +
              number 1


Process finished with exit code 0




David Beckedorff
314 Chicago Blvd
Sea Girt, NJ  08750

Mobile:  (781) 820-0567
Home:  (732) 449-3473

**Comment by david-29** [comment]
Re:

I think the Lark tree serves best as an intermediate tree. If you're doing
iterated operations on the tree, and especially if you mutate it, it's
better to create the AST using Python classes, that capture the hierarchy
and validate the types.

That's what I have done.


I will take a look at your data science DSL.



David Beckedorff
314 Chicago Blvd
Sea Girt, NJ  08750

Mobile:  (781) 820-0567
Home:  (732) 449-3473
