### ISSUE TITLE
ESCAPED_STRING doesn't parse \n

### ISSUE THREAD

**Issue by matiasmorant** [lark-parser/lark#825]
**Describe the bug**

ESCAPED_STRING doesn't parse "\n". I expected to get `Tree('start', [Token('ESCAPED_STRING', '"\n"')])`

**To Reproduce**
With `lark.__version__ == '0.11.1'`
```
Lark(
r"""
start: ESCAPED_STRING
%import common.ESCAPED_STRING
"""
).parse('"\n"')
```
Will result in error:
```
UnexpectedCharacters: No terminal defined for '"' at line 1 col 1

"
^

Expecting: {'ESCAPED_STRING'}
```

**Comment by ThatXliner** [comment]
Try python.STRING

**Comment by matiasmorant** [comment]
@ThatXliner same issue

**Comment by erezsh** [comment]
It is working as expected. You are trying to match

	"
	"

Which string isn't supposed to match.
 
But the following works:

```python
Lark(
r"""
start: ESCAPED_STRING
%import common.ESCAPED_STRING
"""
).parse(r'"\n"')
```

**Comment by matiasmorant** [comment]
Ah good catch!
Lark is impressive, you are a genious @erezsh . I started using it yesterday

**Comment by erezsh** [comment]
Thanks! I hope you'll keep having a good experience with it.
