### ISSUE TITLE
Transfomer_NonRecursive Not Calling Token Userfunc

### ISSUE THREAD

**Issue by mikeiovine** [lark-parser/lark#826]
**Description**

I am trying to use `Transfomer_NonRecursive` since I have a very large parse tree. However, I don't think it is calling the token user funcs I defined. 

**To Reproduce**
Example grammar:
```
OP: "+"
?expr : (expr OP)? STRING
STRING: /\"[^"^+]*\"/
```
And a script:
```python
import lark

parser = lark.Lark.open(
    'example.lark', start='expr')

tree = parser.parse('"test"+"hello"+"world"')

class Transformer(lark.visitors.Transformer):

    def expr(self, values):
        concat = str(values[0]) + str(values[1]) + str(values[2])
        return concat

    def STRING(self, value):
        print('Token func called')
        return value[1:-1]

transformer = Transformer()
print(transformer.transform(tree))
```
When I use `Transformer`, I get the expected result; "Token func called" is printed 3 times, and the output of the last line is `test+hello+world`. However, when I use `Transformer_NonRecursive`, the token func is not called, and the output of the last line is `"test"+"hello"+"world"`

**Possible Fix**
I believe the issue [is here](https://github.com/lark-parser/lark/blob/master/lark/visitors.py#L222). That line should be:
`stack.append(self._call_userfunc_token(x))`.
Edit: err, I guess it should probably query `__visit_tokens__`, but the idea is the same.

**Comment by MegaIng** [comment]
I made a PR #827  based on your suggestion. Could you check that it solves your problem?

**Comment by mikeiovine** [comment]
Looks good. Thank you!

**Comment by erezsh** [comment]
Merged. Good job everyone.
