### ISSUE TITLE
Parsing fixed-width columns?

### ISSUE THREAD

**Issue by qwertystop** [lark-parser/lark#828]
I am attempting to parse tabular data, which is unfortunately just messy enough to make the usual route (Pandas `read_fwf`) implausible without first passing the data through some form of preprocessing. Given that Lark serves well to do that preprocessing, I was wondering whether it might be possible to have the grammar properly detect columns, and thus not need to bother with the Pandas stage. However, I can't figure out how to do so, in the specific case of some cells being empty (whitespace only).

For an example file:
```
  1  2 23
 12 12 32
    43 43
 12    32
```
If I don't account for blanks, it fails to parse them:
```
%import common.INT
%import common.NEWLINE -> _NL
%ignore " "
start: row+
row: INT INT INT _NL
```
If I make all cells `[INT]` instead of `INT`, the grammar is invalid due to colliding optionals.

I have managed a successful parse with `row: (" "~1..2)? (INT | / /) (" "~1..2)? (INT | / /) (" "~1..2)? (INT | / /) _NL` and no `%ignore " "`, but this is clunky, increasingly complicated with longer rows even if templates are added (and you can't pass numbers as template arguments, so it becomes even more of a mess if different columns are different widths), requires capturing whitespace rather than the more conceptually accurate `[INT]`, and seems likely to run into problems with (for example) columns that contain unquoted strings which can contain whitespace.

And, of course, my actual in-practice grammar following the above pattern, cut down to just the bit that parses one line of the table without any of the bits that parse other non-tabular parts of the input, is:
```
%import common.NEWLINE -> _NL
%ignore " "
start: /[A-Z0-9]+/ (" "~1..13 [string]) (" "~1..24 [string]) (" "~1..18 [string]) (" "~1..33 [string]) string state string _NL
string: (/\S+ /)* /\S+/
state: /[A-Z]{2}/
```
and this is very slow even to load the grammar, and turns out not to properly match the data anyway for reasons that are probably not worth investigating given all the other problems arguing to scrap this pattern and try another way.

I feel like the core issue is that I can't figure out a way to specify the combined length of multiple terminals that are not individually further length-constrained – I can do a sequence of "up to Y spaces followed by up to Z digits" (can capture too much or too little), or "X mixed spaces and digits" (allows for capture of the last half of one column and the first half of the next, if variable-size terminals exist to mismatch, and requires stripping leading spaces in the transformer when the grammar ought to be able to handle that), but I can't find any way to say "spaces followed by digits, total length X" other than enumerating every possible Y+Z=X individually.

Am I missing something that would make this (relatively) cleanly doable, or will I have to leave it at "just grab the entire line and do the parsing in the transformer"?

**Comment by ThatXliner** [comment]
I think a regex may be more suitable here

**Comment by erezsh** [comment]
I am not sure exactly of your domain and limitations. Generally what you're trying to do is considered "context-sensitive" and isn't recommended for LR parsers.

But, it is possible to parse the example you gave, by doing a bit of post-lexer trickery.

Check this out:

```python
from lark import Lark

class PostLex:
    always_accept = ['INT']    # necessary because it's not used in the grammar

    def process(self, tokens):
        for t in tokens:
            if t.type == 'INT':
                yield t.update(type_='INT%s' % (t.column // 4))
            else:
                yield t

p = Lark("""
%import common.INT
%import common.NEWLINE -> _NL
%ignore " "
start: row+
row: [INT0] [INT1] [INT2] _NL

%declare INT0
%declare INT1
%declare INT2
""", parser='lalr', postlex=PostLex(), maybe_placeholders=True)


s = """
  1  2 23
 12 12 32
    43 43
 12    32
"""

print(p.parse(s).pretty())
```
