### ISSUE TITLE
Get Lark into awesome-python

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#830]
According to the rules, if we get 20 likes it will be accepted.

https://github.com/vinta/awesome-python/pull/1731

**Comment by ThatXliner** [comment]
# Kinda off-topic...

Makes me wonder: how come it isn't in there already? Lark is like ANTLR but minus Java... well, that might be an understatement. Lark is powerful as any other tool. Yet the meta-grammar is (IMO) is more readable.

**Comment by ThatXliner** [comment]
Just one more like...

**Comment by JeppeKlitgaard** [comment]
@erezsh there you go!

**Comment by ThatXliner** [comment]
Are you supposed to.. request a review?

**Comment by erezsh** [comment]
Closing this because awesome-python is vaporware
