### ISSUE TITLE
What are the best-practices for writing grammars for the contextual lexer?

### ISSUE THREAD

**Issue by qwertystop** [lark-parser/lark#833]
**What is your question?**

I believe I understand from the discussion under #742 that the contextual lexer is potentially better or worse at ruling things out depending on whether rules and/or terminals are re-used, even if multiple such rules and/or terminals can match the same input. I have been frequently encountering situations where said lexer seems to be making similar mistakes to that described at the start of #742. For example, matching an integer where only a decimal is valid, and then reading the decimal point as an invalid token, or matching an "arbitrary alphanumeric sequence" terminal in places where all the valid tokens are more specific subsets of that (and the actual text does match one such subset).

Unfortunately the inputs causing this are my employer's invoices, and when I try to construct simpler test-cases to reproduce the behavior without breaking NDA, they parse fine. As far as I can tell, any individual section of the input (each with its own format) is unambiguous, and they all have distinct headers to make it unambiguous which one you're in at any given time, but making one grammar that includes all of these sections has a tendency to confuse things. So far, I've gotten past this with a combination of priority-tweaking, small narrowings of regexes to reduce mismatches (at risk of overfitting the grammar to the test data and failing on live data), and in the worst cases, terminals that match some fixed number of characters or lines (or everything-until-a-new-subsection) and leave the actual parsing for that chunk to be done in the transformer.

I assume, by default, that this is due to a fundamental problem with my approach to grammar-writing, rather than a problem with Lark. How can I maximize the degree to which the contextual lexer can avoid that kind of error? Make a different rule for every field even if they look the same? Similar, but for terminals? Both? Would anonymous terminals (either each in their own rule, or multiple in larger rules) make this better or worse?

More generally, what are the best-practices for when to put things in terminals vs. rules wrapping terminals, assuming both are possible?

**Comment by erezsh** [comment]
It's hard to understand what sort of difficulty you're facing, just from reading your description.

If you can provide some minimal example that demonstrates the conflict (the more abstract the better), it might help me give you more relevant advice.

In general, I'd say that there are several techniques that can help. Off the top of my head:

- Use regex lookahead/lookbehind to include or exclude certain situations.

- Combine the two terminals into one, and distinguish between them at a later time (decimal vs int is a prime candidate for this one, but it's not the only way to solve it)

**Comment by qwertystop** [comment]
Minimal and abstract is unfortunately difficult, because as said when I try to cut things down for such an example, the errors disappear. Here's something that's at least small, though:

The subset of the grammar referring to the case of what appears directly below a line-item on the invoice for the purchase of a kit is as follows:

```
%import common.NEWLINE -> _NL
%ignore " "
ITEM_CODE.-1: /[A-Z0-9-]{3,}/
LONG_DESC.-1: /(\S+ )*\S+(?=( *)[A-Z]{2}$)/m

_kit: _KIT_HEADER _NL kit_comp+
_KIT_HEADER.2: "** Kit Components **"
kit_comp: ITEM_CODE ".000" ITEM_CODE LONG_DESC /[A-Z]{2}/ _NL
```

An example of this segment, with actual prices and item codes/descriptions and such redacted of course, is:
```
     ** Kit Components **
     12354P                  .000 1-2354P PART & OTHER WORDS A      QN
     12354T                  .000 1-2354T PART B                    QN
```

The `ITEM_CODE` and `LONG_DESC` and `_NL` terminals also appear elsewhere in the full grammar. The `_kit` and `kit_comp` rules, and the `_KIT_HEADER` terminal, does not appear elsewhere.

When I attempt to parse this limited subset – the full grammar but with `start` set to `_kit`, and just that small segment of the full text, it parses fine. When I attempt to parse the full invoice that contains this particular kit, it lexes the numeric part of the item code for the second component as an `INT`, presumably because after the first kit component is complete, it's possibly no longer in a kit (a regular line item starts `INT ITEM_CODE INT`). I had to make `ITEM_CODE` lower-priority and set a minimum length on it to prevent similar errors elsewhere in this and other files, where non-item-code things were being lexed as item codes.

The full error trace is:

```
---------------------------------------------------------------------------
UnexpectedCharacters                      Traceback (most recent call last)
~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/lexer.py in lex(self, lexer_state, parser_state)
    430                 lexer = self.lexers[parser_state.position]
--> 431                 yield lexer.next_token(lexer_state)
    432         except EOFError:

~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/lexer.py in next_token(self, lex_state)
    353                     allowed = {"<END-OF-FILE>"}
--> 354                 raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
    355                                            allowed=allowed, token_history=lex_state.last_token and [lex_state.last_token])

UnexpectedCharacters: No terminal defined for 'T' at line 370 col 11

     12354T                  .000 1-2354T PART & O
          ^

Expecting: {'ITEM_CODE'}

Previous tokens: Token('INT', '79170')


During handling of the above exception, another exception occurred:

UnexpectedToken                           Traceback (most recent call last)
<ipython-input-27-2e51d0128ad6> in <module>
      7     debug=True
      8 )
----> 9 parsed = contents_parser.parse(contents)

~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/lark.py in parse(self, text, start, on_error)
    493 
    494         try:
--> 495             return self.parser.parse(text, start=start)
    496         except UnexpectedInput as e:
    497             if on_error is None:

~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/parser_frontends.py in parse(self, text, start)
    135 
    136     def parse(self, text, start=None):
--> 137         return self._parse(start, self.make_lexer(text))
    138 
    139     def init_traditional_lexer(self):

~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/parser_frontends.py in _parse(self, start, input, *args)
     70                 raise ValueError("Lark initialized with more than 1 possible start rule. Must specify which start rule to parse", start)
     71             start ,= start
---> 72         return self.parser.parse(input, start, *args)
     73 
     74 

~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/parsers/lalr_parser.py in parse(self, *args)
     33 
     34     def parse(self, *args):
---> 35         return self.parser.parse(*args)
     36 
     37 

~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/parsers/lalr_parser.py in parse(self, lexer, start, value_stack, state_stack)
    127         parse_conf = ParseConf(self.parse_table, self.callbacks, start)
    128         parser_state = ParserState(parse_conf, lexer, state_stack, value_stack)
--> 129         return self.parse_from_state(parser_state)
    130 
    131     def parse_from_state(self, state):

~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/parsers/lalr_parser.py in parse_from_state(self, state)
    143             except NameError:
    144                 pass
--> 145             raise e
    146         except Exception as e:
    147             if self.debug:

~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/parsers/lalr_parser.py in parse_from_state(self, state)
    133         try:
    134             token = None
--> 135             for token in state.lexer.lex(state):
    136                 state.feed_token(token)
    137 

~/.pyenv/versions/venv/lib/python3.9/site-packages/lark/lexer.py in lex(self, lexer_state, parser_state)
    436             # This tests the input against the global context, to provide a nicer error.
    437             token = self.root_lexer.next_token(lexer_state)
--> 438             raise UnexpectedToken(token, e.allowed, state=parser_state.position)
    439 
    440 

UnexpectedToken: Unexpected token Token('CITY', 'T') at line 370, column 11.
Expected one of: 
	* ITEM_CODE
```

**Comment by erezsh** [comment]
Copy+paste from the gitter:
```
When I get confused by a grammar, I do the following:
1. create a copy, so I can change the parser/grammar without worries
2. find the minimal input that creates the error
3. slowly remove rules from the grammar, while making sure the error still happens
By the time I get to a minimal grammar, the problem usually becomes clear.
But if it doesn't, post the end result here and I'll help you solve it.
```

**Comment by qwertystop** [comment]
Ah. Sorry.

**Comment by erezsh** [comment]
Don't worry about it. I assume you figured it out?
