### ISSUE TITLE
Better docs for match_examples

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#834]
I have no clue what does `match_examples` does. Maybe adding examples in the docs would help. 

I was reading: https://github.com/lark-parser/lark-language-server/pull/2#issuecomment-778309135

<sub>I'm making the issue here since commenting there would be off topic</sub>

**Comment by MegaIng** [comment]
> Originally posted by @erezsh in lark-parser/lark-language-server#2 (comment)

No. This is not true. Why would you add that kind of remark if it isn't true?

> Maybe adding examples in the docs would help.

Well, examples are there: https://lark-parser.readthedocs.io/en/latest/examples/advanced/error_reporting_lalr.html#sphx-glr-examples-advanced-error-reporting-lalr-py

But adding a sentence or two in the docs would help

**Comment by ThatXliner** [comment]
> 
> No. This is not true. Why would you add that kind of remark if it isn't true?
> 


My bad!

**Comment by MegaIng** [comment]
I just checked, and there are docs: https://lark-parser.readthedocs.io/en/latest/classes.html#lark.exceptions.UnexpectedInput.match_examples , at least since we migrated to sphinx.

**Comment by ThatXliner** [comment]
This is an old issue. I've also managed to successfully use `.match_examples`. Thanks for the response, though!
