### ISSUE TITLE
Grammar cache should contain hash inside, and update accordingly

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#835]
**Suggestion**

Store the grammar hash in the cache, so that if the user specifies a filename, it will be updated as necessary.
(right now it will create it, but not overwrite it if the grammar changes)

`cache=True` should behave the way it currently does. The stored hash can be used for extra validation.

(edited)

**Comment by ThatXliner** [comment]
Does this also mean we can rename the stored file into anything we want? (Assuming this is implemented)

**Comment by erezsh** [comment]
@ThatXliner That is already possible with `cache="filename"`, but Lark will not overwrite that file, even if the grammar has changed. This feature would make sure that file is updated if necessary.

Now that I think about it, `cache=True` will still have to work the way it does now, with the hash in the filename, in order to avoid collisions.

**Comment by erezsh** [comment]
Done
