### ISSUE TITLE
Parsing slightly ambigious grammar with LALR

### ISSUE THREAD

**Issue by ashish01** [lark-parser/lark#841]
First of all thanks for creating LARK. I have used bison in past life and to me it always felt challenging but it was an absolute joy when I first used Lark.

I have a slightly ambiguous grammar which works fine with early parser but fails with error when using LALR. The grammar is

```
parser = Lark(r"""
    expr: SIGNED_NUMBER
        | SIMPLE_STRING
        | name
        | FUNCTION_NAME "(" function_args ")"

    function_args : expr
                  | function_args "," expr
                  
    name: NAME

    NAME : /[a-zA-Z0-9_]+/
    SIMPLE_STRING : /'[^']*'/
    FUNCTION_NAME : /[a-zA-Z0-9_]+/
    
    %import common.SIGNED_NUMBER
    %import common.WS
    %ignore WS
""", start="expr", parser="lalr")
```

A token without any context can be either NAME or FUNCTION_NAME. While using the default parser, it resolves these ambiguities correctly

```
tree = parser.parse("A(B(x, y, 5))")
print(tree.pretty())
```

produces

```
expr
  A
  function_args
    expr
      B
      function_args
        function_args
          function_args
            expr
              name	x
          expr
            name	y
        expr	5
```

But with `lalr` it fails to parse with following error

```
UnexpectedCharacters: No terminal defined for ',' at line 1 col 6

A(B(x, y, 5))
     ^

Expecting: {'LPAR'}

Previous tokens: Token('FUNCTION_NAME', 'x')

```

I am sure its a very n00b question. So if its recommended to read something (books etc.) for me to understand this, I would love some suggestions. Thanks!

**Comment by erezsh** [comment]
I'm glad you're enjoying lark!

Regarding your question, it's a very simple matter of terminal collision. You made NAME and FUNCTION_NAME match the exact same thing, and the lexer has to choose one over the other "arbitrarily".

Just drop FUNCTION_NAME, and everythign should work:

```lark
| NAME "(" function_args ")"
```

**Comment by erezsh** [comment]
As for a tip for next time, try to keep your terminals to a minimum, make sure there no collisions between regexps (regexp-string and string-string aren't a problem, Lark can detect those).

We're actually working a feature that would print a warning in this exact situation, but it's not ready yet.

**Comment by ashish01** [comment]
Thanks! It works. As suggested I changed the grammar to

```
parser = Lark(r"""
    expr: SIGNED_NUMBER
        | SIMPLE_STRING
        | name
        | function_name "(" function_args ")"

    function_args : expr
                  | function_args "," expr
                  
    function_name: NAME
    name: NAME

    NAME : /[a-zA-Z0-9_]+/
    SIMPLE_STRING : /'[^']*'/
    
    %import common.SIGNED_NUMBER
    %import common.WS
    %ignore WS
""", start="expr", parser="lalr")
tree = parser.parse("A(B(x, y, 5))")
print(tree.pretty())
```

and got the right parse tree

```
expr
  function_name	A
  function_args
    expr
      function_name	B
      function_args
        function_args
          function_args
            expr
              name	x
          expr
            name	y
        expr	5
```

However I tried a small variation in the input

```
tree = parser.parse("A(B(7x, y, 5))")
```

and I got the error

```
UnexpectedCharacters: No terminal defined for 'x' at line 1 col 6

A(B(7x, y, 5))
     ^

Expecting: {'COMMA', 'RPAR'}

Previous tokens: Token('SIGNED_NUMBER', '7')
```

I am curious why does `7x` not match the `NAME`. I agree that `7` matches both `NAME` and `SIGNED_NUMBER` but how is the decision made? What determines the priority? Also it parses fine with early parser

```
expr
  function_name	A
  function_args
    expr
      function_name	B
      function_args
        function_args
          function_args
            expr
              name	7x
          expr
            name	y
        expr	5
```

Thanks.

**Comment by MegaIng** [comment]
> I am curious why does 7x not match the NAME. I agree that 7 matches both NAME and SIGNED_NUMBER but how is the decision made? What determines the priority? 

The longest matching terminal is used. `SIGNED_NUMBER` matches `7`, but `NAME` matches `7x` so `7x` is matched.

**Comment by ashish01** [comment]
@MegaIng But when using `LALR` it **didn't match** `7x` as `NAME`. Instead it matched `7` as a number and then failed. See error above. Thanks!

**Comment by erezsh** [comment]
@ashish01 In LALR mode, Lark's lexer stops when it finds its first match. Conceptually, it iterates over the entire set of terminals, and stops once it finds a match. Therefor the order of the terminals matter. Lark uses a bunch of rules to try to minimize collisions, but it won't always work. If you have two colliding regexps on purpose, it's better to give them an explcit priority, rather than rely on Lark.

**Comment by ashish01** [comment]
Excellent! Thanks, adding a explicit priority solves the issue. For reference, here is how I changed the grammar

```
parser = Lark(r"""
    expr: SIGNED_NUMBER_R
        | SIMPLE_STRING
        | name
        | function_name "(" function_args ")"

    function_args : expr
                  | function_args "," expr
                  
    function_name: NAME
    name: NAME

    NAME.2 : /[a-zA-Z0-9_]+/
    SIMPLE_STRING : /'[^']*'/
    SIGNED_NUMBER_R.1: SIGNED_NUMBER
    
    %import common.SIGNED_NUMBER
    %import common.WS
    %ignore WS
""", start="expr", parser="lalr")
tree = parser.parse("A(B(x, 7y, 5))")
print(tree.pretty())
```

which produces

```
expr
  function_name	A
  function_args
    expr
      function_name	B
      function_args
        function_args
          function_args
            expr
              name	x
          expr
            name	7y
        expr
          name	5
```
