### ISSUE TITLE
what's the best practice to write a parser for speech recognition results ?

### ISSUE THREAD

**Issue by Morojs** [lark-parser/lark#843]
i want to create a smiple parser for speech recognition results ,the grammar going to be complex that's why i want some advices about how to deal with complex grammar .
i have this simple example below using speech recognition api and lark parser    : 
```
from lark import Lark,Token, Transformer, v_args
from helpers.file_process import FileProcess
import numpy as np

speech_grammar = """
start              : KEY TYPE FNAME PATH?
KEY                : "create" | "delete" | "open" | "read" | "make" 
TYPE               : "file" | "folder" 
FNAME              : (/[a-z]/)+ 
PATH               : (/[a-zA-Z]/)+":"(/[\\/]/)+DIRNAME
DIRNAME            : ((/[a-zA-Z0-9]/)+(/[\\/]/)?)*

%ignore (" ")+
"""

speech_parser = Lark(speech_grammar)

def run(input):
    try:
        speech = speech_parser.parse(input)
        instr=np.array(speech.children)
        return FileProcess(instr).request_process()
    except Exception as err :
        return err

def main(input):
    return run(input)

def test():
    print(run("make file test d:/test"))
    print(run("delete file test"))
```

i will add more terminals (Vt) in the grammar part , any suggestions or advices  would be much appreciated ?

**Comment by ThatXliner** [comment]
Can you give us an idea of speech recognition results?

**Comment by Morojs** [comment]
for a word or phrase that has been positively recognized by speech recognition api and this has been communicated back to the app as a set of words  , when i say  " create file test" the api will return :
```
{ token : KEY , value : create , token : type , value : file, token : fname, value : tes t}
```

**Comment by ThatXliner** [comment]
It's not going to be nested, right? If not, that's not *too* hard!

Try to play around with the grammar until you can get it to parse. The documentation for making a [JSON parser](https://lark-parser.readthedocs.io/en/latest/json_tutorial.html) can probably help.

**Comment by Morojs** [comment]
yes that's right but if you look at the PATH (Vn) in the grammar! , imagine when you say " CREATE FILE TEST" plus the path where the file will be created , how to make api understood file path then i can use it for lark parsing?

**Comment by ThatXliner** [comment]
I'm kind of confused... can show you me what happens when you tried that? (We can only parse what the API gives)

**Comment by Morojs** [comment]
the grammar describe how users interact with speech api , we can't use "create file test d:/myfolder" like that because the api doesn't understand the path and it doesn't have the concatenation between each path item, is there any way to make it easier to understand and use for speech api?

**Comment by erezsh** [comment]
It sounds like you're asking about the lingual interface, rather than parsing.

Maybe if you provide some examples of the output you're getting (or hoping to get) from the voice API, we can tell you how to parse it.

I would suggest considering a "DSL" for the paths that's more natural for speaking, like "drive d folder myfolder"

**Comment by Morojs** [comment]
path_dsl that's what i'm looking for , thank you so much @erezsh @ThatXliner
