### ISSUE TITLE
A simple example: what am I doing wrong?

### ISSUE THREAD

**Issue by sdia** [lark-parser/lark#845]
As soon as I use `ESCAPED_STRING` the following code will break. 
Can someone explain me what am i doing wrong? 
Basically everywhere I use regular expression I did so because using string will make the code to break.
I think I am missing something fundamental about how strings work.
Any help appreciated.

Great project btw, many thanks.

```python
from lark import Lark
parser = Lark(r"""
    line: comment
        | req

    req: project_name extras? specifier? comment?
    extras: "[" [extra ("," extra)*] "]"
    specifier: comp version ("," comp version)*

    comp:   /</
        |   /<=/
        |   /!=/
        |   /==/
        |   />=/
        |   />/
        |   /~=/
        |   /===/

    version: /[\w\.]+/
    extra: /[\w\.]+/          // ESCAPED_STRING
    project_name: /[\w\.]+/   // ESCAPED_STRING
    comment: /#.*$/

    %import common.ESCAPED_STRING
    %import common.WS
    %ignore WS

""", start='line')

text = 'HelloWorld'
print(parser.parse(text).pretty())


```

**Comment by erezsh** [comment]
A string is not a sequence of characters, like `abc`. It's the visual representation of a string, like `"abc"`
