### ISSUE TITLE
Inconsistent visiting of tree for Interpreter

### ISSUE THREAD

**Issue by aviallon** [lark-parser/lark#851]
**Description**

In some cases I wasn't able to pinpoint, some visitor function are weirdly ignored. Their children are visited, but neither the `__default__` method nor the `my_rule_overload` method are called. The behavior is always the same between runs, even on different machines.

**To Reproduce**

My pet compiler project here: https://gitlab.com/aviallon/alang-compiler/-/tree/lark-bug consistently reproduces the behavior. Pay attention to `Visiting: decorated_function`, and then check the code in `alang_compiler/ir/__init__.py` :

```python
    def decorated_function(self, tree: lark.Tree):
        debug(tree, "Called decorated_function")
        if tree.meta.decorator == "entrypoint":
            entrypoint_label = IRLabel("entrypoint")
            exit_status = self._new_var("exit_status", scope=[])
            function_identifier = scoped_identifier(tree.meta.decorated_function.meta.scope,
                                                    tree.meta.decorated_function.meta.name)
            argument_number = 2
            self.IRLabels += [entrypoint_label]
            self.IR = [QLabel(entrypoint_label),
                       QCall(exit_status, function_identifier, argument_number)] + self.IR

        # self.visit_children(tree)
```

You can see that I even commented out the `self.visit_children(tree)`, yet its children are still visited, and the there is no `Called decorated_function` in the debug messages. Adding a breakpoint in the function does nothing... which clearly tells me that it is never actually called !

**Comment by erezsh** [comment]
If the children are visited, but shouldn't be, put a breakpoint in one of them an check the stacktrace.

**Comment by aviallon** [comment]
Yup, found out what happened. For some reason I was blind and didn't see that my visitor was defined twice...

**Comment by aviallon** [comment]
@erezsh  perhaps showing a warning for dumb people like me if a visitor is redefined? (if that is actually possible to detect at all)

**Comment by erezsh** [comment]
Happy to help either way.
i
Unfortunately I don't think there is a way to detect redefinition in Python. I wish there was.
