### ISSUE TITLE
[BENCHMARK] Add textX to benchmarks

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#853]
[textX](https://github.com/textX/textX) seems quite promising with many features. But I wonder, (runtime and developing) performance-wise, is Lark better?

IMO, Lark's syntax is simpler (which is another advantage)

**Comment by erezsh** [comment]
Well, someone will have to write the code to benchmark it.

But the right place to request it is here: https://github.com/goodmami/python-parsing-benchmarks

**Comment by ThatXliner** [comment]
Oh cool! Thanks!
