### ISSUE TITLE
Problem with importing ast_utils when running /examples/advanced/create_ast.py

### ISSUE THREAD

**Issue by DannyFS** [lark-parser/lark#854]
I recently started using Lark for a project that required some parsing. When I ran /examples/advanced/create_ast.py, I always get this error:

  File "main.py", line 5, in <module>
    from lark import Lark, ast_utils, Transformer, v_args
ImportError: cannot import name 'ast_utils' from 'lark' (C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\lark\__init__.py)

**Comment by MegaIng** [comment]
Did you use the latest master? `ast_utils` isn't on pip right now.

**Comment by DannyFS** [comment]
Ahh ok, tysm
