### ISSUE TITLE
Not successfully removing all // comments from parsed file

### ISSUE THREAD

**Issue by diarmidmackenzie** [lark-parser/lark#861]
**Describe the bug**

I am trying to parse a file that consists of a set of whitspace separated fields / values.

The value should include everything following the first whitespace break, but excluding any // comments.  However values may explicitly include both whitespace and /s, and are not delimited by any markers like " or similar...

Unfortunately, I cannot find a way to do this without the comments at the end of lines being incorrectly included in the field values.

My expectation is that by using the %ignore directive, comments should be stripped out before any parsing takes place.  But this doesn't seem to be happening, and the comments end up in the values.

**To Reproduce**

Here is a python script that shows the problem:

```
from lark import Lark

text_to_parse = """
// A comment (correctly ignored)
             // Another comment (also ignored)
field1       value
field2       complex/value/with/slashes
field3       this value contains spaces
field4       this value contains spaces/and/also/slashes
field5       this value contains spaces/and/also/slashes // And here is a comment which I want to be ignored
field6       value // Another comment that I would like to be ignored
"""

lark_grammar = r"""
?start: [_NL] ( pair _NL)*
pair   : [_WS] _field _WS _value

_field  : STRING
_value  : VALUE

%ignore COMMENT

_WS: /[ \t\f]+/
_NL: /(\r?\n)+\s*/

// syntax used here to match // comments matches that used in the lark grammar:
// https://github.com/lark-parser/lark/blob/master/lark/grammars/lark.lark#L56

COMMENT: /\s*/ "//" /[^\n]/*

STRING : /\S+/
VALUE  : /[^\n]/+
"""

parser = Lark(lark_grammar,
              parser="lalr",
              lexer='auto')

print(parser.parse(text_to_parse).pretty())
```

Output as follows:

```
start
  pair
    field1
    value
  pair
    field2
    complex/value/with/slashes
  pair
    field3
    this value contains spaces
  pair
    field4
    this value contains spaces/and/also/slashes
  pair
    field5
    this value contains spaces/and/also/slashes // And here is a comment which I want to be ignored
  pair
    field6
    value // Another comment that I would like to be ignored
```

The // parts should not be included in the last two values.
    
If values only needed to contain spaces but not /s then I can get this working using:
    
```
VALUE  : /[^\/\n]/+`
```    

If values only needed to contain /s, and not spaces, then I could get this working using:
    
```
VALUE  : /\S+/`
```
    
But given the need to match on both whitespace and /s, the only Regexp I can find that works is:
    
```
VALUE  : /[^\n]/+
```

and this seems to also match on the comments, even though IMO the comments ought to have already been stripped out due to the %ignore directive.
    
 This (comments being left in) seems like a bug to me.  But I am very new to lark, so maybe this is not a bug, and I'm just using the wrong grammar?
 
 Any help would be much appreciated.

**Comment by MegaIng** [comment]
This is not a bug. Ignoring tokens happens on after the Lexer, which matches the regex greedily, e.g. as long as possible. The best course of action is to prevent `VALUE` from matching the comments with something like this:

`VALUE: /(?:[^\/\n]|\/(?!\/))/+`

This matches anything but newline and a `/` followed by another one.

**Comment by diarmidmackenzie** [comment]
That's working perfectly, thank you!

I had been trying to construct something like that but all my attempts had run into this error: "Lexer does not allow zero-width terminals."

Thank you.
