### ISSUE TITLE
ParserPuppet.copy does not copy LexerState

### ISSUE THREAD

**Issue by evilnose** [lark-parser/lark#865]
**Describe the bug**

`ParserPuppet.copy` does not copy the lexer state. Instead it makes a shallow copy of `LexerThread`.

**To Reproduce**

```python3
# make a copy
puppet_copy = puppet.copy()

# advance LineCounter of copy
puppet_copy.lexer_state.state.line_ctr.feed('foo')

# assertion fails
assert puppet.lexer_state.state.line_ctr.char_pos != puppet_copy.lexer_state.state.line_ctr.char_pos
```

This should be simple to fix. The reason for the bug is that the member `lexer_state` of `ParserPuppet` is in fact not a `LexerState` but a `LexerThread` (see [here](https://github.com/lark-parser/lark/blob/1d61de4f94b4af441b2f32c790db4290348d7a93/lark/parsers/lalr_parser.py#L149)), which does not have a custom copy function. So `copy(self.lexer_state)` would only be a shallow copy. I think we can just add a `__copy__` method to `LexerThread` ([here](https://github.com/lark-parser/lark/blob/1d61de4f94b4af441b2f32c790db4290348d7a93/lark/lexer.py#L459)) to fix this, namely
```python3
    def __copy__(self):
        return type(self)(
            self.lexer,
            copy(self.state)
        )
```

**Comment by MegaIng** [comment]
This is correct. You can just create a simple PR (preferably include a test/extend the [existing puppet test](https://github.com/lark-parser/lark/blob/811a4eb4925679fb62640f56e3bec4acada42fb9/tests/test_parser.py#L2400)
