### ISSUE TITLE
Remove redundant PyPi project?

### ISSUE THREAD

**Issue by drewrisinger** [lark-parser/lark#867]
I noticed two PyPi projects for ``lark``
* https://pypi.org/project/lark-parser/, at 0.11.2
* https://pypi.org/project/lark/, at 0.11.1

Obviously they are not maintained equally, and ``lark`` doesn't have version history < 0.10.1. Assuming that the "proper" one is ``lark-parser``, it would be nice if ``lark`` was deprecated/removed/there was an OBVIOUS link to the correct project on the PyPi page.

Some projects have started using the "redundant" package: https://github.com/rigetti/pyquil/blob/55670be8c30f5365433bae55de001c630319a999/requirements.txt#L4

**Comment by erezsh** [comment]
Everywhere the documentation says to use `lark-parser`, but I guess the internet has a mind of its own.

We will be moving to the `lark` package very soon, and deprecate the use of `lark-parser`.

**Comment by MegaIng** [comment]
If you want to know a bit more as to way we have two names: #712 and #505

**Comment by drewrisinger** [comment]
Closing based on answer about proper usage of ``lark`` vs ``lark-parser``.
