### ISSUE TITLE
Obtain ParserPuppet directly?

### ISSUE THREAD

**Issue by evilnose** [lark-parser/lark#868]
**Suggestion**
I'm writing a language server with Lark, and I'm using a recursion-based approach for error handling and inference. For this I make use of `ParserPuppet` extensively, as a helper to store copies of states and try other branches. However, right now `ParserPuppet` can only be created through exceptions during parsing. It would be much more convenient if there is a method that generates a `ParserPuppet` directly based on the initial states of the parser, so that I can start off with a puppet at the root.

This should be as simple as creating a method similar to `_Parser.parse` in `LALR_Parser` but instead returning a `ParserPuppet` instead of parsing.

**Describe alternatives you've considered**
Creating a `ParserPuppet` manually, but this feels quite hacky as `ParserPuppet`, `ParserState` and `ParseConf` are not explicitly exported.

**Additional context**
None

**Comment by MegaIng** [comment]
The 'problem' is that ParserPuppet is `lalr` specific:

- We can have a method on `Lark` that fails if `parser!='lalr'`. This would probably mean we would create `get_puppet` methods for all classes in the `.parser` chain.
- We could have a method only on `LALR_Parser`/`lalr_parser._Parser`. This would be accessed with `lalr_instance.parser.parser.parser.create_puppet()` (plus minus a `parser`). I don't like this. It would also kinda force us to fix that part of the internals.
- The method could also be `ParserPuppet.create(lark_instance, text)`. I don't like this either.

**Comment by evilnose** [comment]
How about an optional keyword argument for `Lark.parse()` (e.g. `get_puppet`), which if True, will return a `ParserPuppet` if we are using an `LALR_Parser`, or throws an exception otherwise?

**Comment by MegaIng** [comment]
@evilnose I created a PR: #869

**Comment by evilnose** [comment]
Great, thank you!
