### ISSUE TITLE
Make cache file more resilent

### ISSUE THREAD

**Issue by alexandermorozov** [lark-parser/lark#870]
Currently grammar cache files that Lark creates can end up containing malformed data. It can happen as a result of:
1. Python version mismatches,
2. Truncated file in case of power loss, or python interpreter getting killed or interrupted in the middle of the write.
3. Simultaneous write from multiple threads / processes,

It can be solved by implementing the following:

1. Adding a suffix that indicates version of interpreter that created the cache file. I believe you'd need first 2 numbers from python version + interpreter type, e.g. cpython-3.8, pypy-3.5.

2. Making sure that contents of file are commited to disk and the cache file is atomically replaced. Here are approximate steps: a) create a temp file in the same dir as cache file (to make sure that the files are on the same filesystem). Python has a lib to work with temp files, b) after data is written to the file, do `f.flush()` to flush in-python buffer, and then `os.fsync(f)`. It'll make sure that contents are properly commited to disk, and not just pushed into OS-level RAM fs cache. Then do `os.rename` to replace the old cache file (if any?) with the new one. This op is usually atomic -- the file is either renamed or it's not.

3. Actually step 2) would already prevent data races from multithreaded writes since they'd write into different files, and rename is atomic. But it's possible to go futher and use file-based locks (e.g. filelock module) to make sure that only one process does all the compute, and all other processes idle until the cache is ready. Larger grammars can take tens of seconds to prepare, so it can add up, especially if lark is used in multithreaded/multiprocess server where grammar is loaded on init (20 processes, 30 seconds each -> 10 minutes of CPU time). I'm not sure that it's Lark responsibility though, and you may not want to add dependency on other packages.

**Comment by alexandermorozov** [comment]
BTW it may be possible to use an existing container to solve all 3 issues. Sqlite3 would work -- it has all the transactions and safety but looks a bit heavyweight. There are built-in modules like `shelve`, but shelve in particular doesn't manage concurrent access itself, you would still have to do locking on top of it. Also container would have to work across all python versions and varieties, including cpython and pypy.

**Comment by MegaIng** [comment]
> Python version mismatches,

Sure, this is a relatively simple fix. (It at least should be contained within the hash)

> Truncated file in case of power loss, or python interpreter getting killed or interrupted in the middle of the write.

This is one of this thinks were IMO, though luck, you need to regenerate the cache file.

I would suggest slightly reducing the pain for the end user by not forcing the user to delete the cache file if unpickling fails and instead to just carry on, recompile the parser and override the file. (Potentially with a log message).

We certainly don't wanna add third party dependencies. If you want to create a PR that implements all you suggest in a simple manner, do it.

**Comment by MegaIng** [comment]
> Simultaneous write from multiple threads / processes.

This would only collide when multple threads access the exact same grammar/options combination. I would suggest instead manually creating a cache with `Lark.save`/`Lark.load` or even with a standalone parser.

**Comment by alexandermorozov** [comment]
Well, I believe that implementing (1, 2) should cover all "normal" instances of cache corruption, and it also solves concurrent write issue. It still leaves "abnormal" issues like physical disk corruption, FS failure, files being modified externally by a third party and other things that are usually considered to be outside of the scope of an individual program. It's not 100% clear if it's right to try to autorecover under those conditions, or if it's fine to fail and let user fix the system.

There is actually one more issue -- lark version should be also added to hash, since internal structures may change.

Relying on unpickle to throw error can lead to correctness / safety issues. I'm not sure if pickle has is strong checksumming in place, of if it'll happily try to restore whatever mess concurrent writes managed to create, which can easily cause OOM or undefined behaviour.

**Comment by MegaIng** [comment]
> lark version should be also added to hash

It is.

Also, is this issue passed on actual problems you had, or is this just a theoretical problem?

**Comment by MegaIng** [comment]
> 30-60s 

I assume this number is without cache.

If multiple parsers need to be create with the exact same parameters, then I would assume that not using the cache option is the easiest and most robust solution, either via standalone or via manual calls to `.load()`. But I agree that something should be done here.

The 'correct' solution is to depend on something like [`python-atomicwrites`](https://python-atomicwrites.readthedocs.io/en/latest/). But we probably don't want to have a dependency that most users don't need. We could handle it similar to how we handle `regex`, e.g. use it when available and otherwise fallback to a simple system of our own creation.

It *might* be worth adding an option `safe_cache` that has three states:

- `False` current behavior (would also not do whatever file detection we decide in #871, in cases where this is a performance problem/the imported grammars are not available.)
- `True` (the default). Would try to use atomic writes, and would do file detection.
- `"atomic"` Require `atomicwrites` to be installed.

**Comment by erezsh** [comment]
Keeping this open because multi-threaded writes might still pose a problem that could be improved.

**Comment by erezsh** [comment]
In theory. But it's not part of the tests.

@alexandermorozov Any chance you can check to see if it's solved now?

**Comment by erezsh** [comment]
I assume it's solved. Let me know otherwise.
