### ISSUE TITLE
Invalidate cache when grammar changes

### ISSUE THREAD

**Issue by alexandermorozov** [lark-parser/lark#871]
Currently you have to manually delete cache files if you update the grammar. It's quite error prone, and sometimes can go unnoticed.

It'd be great to ensure that all source .lark files that were used haven't changed, and invalidate the cache if they did.

**Comment by MegaIng** [comment]
The problem here is that we don't know on which files the grammar depends before parsing it, which would kinda defeat the purpose of the cache. While this is certainty possible, the easiest fix is for the user to just not specify `cache=True` while developing the grammar.

**Comment by alexandermorozov** [comment]
During initial parse it's possible to store list of files which generated the grammar and their checksums. If the grammar doesn't support incudes with globs and specifies file names exactly, then on cache load we can just test that checksums match.

It'll ensure that all files are unchanged. And since they are unchanged, no new files were referenced.

Actually patterns (*, ?, ...) can be also handled -- just include the list in cache and do expansion when loading the cache to check that no new files are referenced.

**Comment by MegaIng** [comment]
Yes, it is possible, at the cost of quite a bit of complexity in different places:

Currently there are two distinct steps to loading from cache:

- Check if we got different inputs hash(given grammar + options_string)
- Deserialize the `Lark` instance

We would have to add another non-trivial step in here that:
- Deserialize another object (e.g. a third value stored in the file)
- Does a non-trivial amount of file access, potentially reducing the performance of the cache significantly.

We would also have to record the accessed files:
- (No lark does not support glob imports)
- This would certainly be possible, but would be another decent spaghetti factor in `load_grammar.py`.

Considering that this would reduce the overall performance of `cache=True` even when nothing changed, and you can get equivalent results by passing `cache=False`, I don't think this is worth the trouble.

**Comment by erezsh** [comment]
@MegaIng It can actually become quite cumbersome when the grammar is fragmented (i.e. includes many `%import`s)

Also, most of the performance hit comes from the LALR analysis, and not the initial parsing of the file.

So I think this feature is useful, not that hard to do, and I also don't think the performance difference will be noticeable.

**Comment by alexandermorozov** [comment]
There definitely would be an impact from having to read and checksum all source files. Usually it should be quite fast, though -- I suspect impact with respect to CPU time would be less than a few percent of what it takes to unpickle the grammar. IO cost may wary though -- if those files are on sshfs or such it can easily multiply load time by 2-10x depending on number of files accessed. That's an edge case though.

It's also possible to compare timestamps instead of content checksums like venerable `make` does -- very light on IO, but can have correctness issues.

**Comment by erezsh** [comment]
I believe this can be closed.
