### ISSUE TITLE
Be able to use $END as a token in lark grammars

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#879]
**Suggestion**
I want to be able to use $END as a token.

**Describe alternatives you've considered**
None. Well, it *could* be a different name. But the `$`, IMO, conveys special meaning

**Additional context**
Sometimes, I either want the next token to be a newline or the end of the file.

**Comment by erezsh** [comment]
Duplicate of #237

**Comment by ThatXliner** [comment]
Oops.
