### ISSUE TITLE
Parsing pairs on same line along with pairs on new lines for each section

### ISSUE THREAD

**Issue by sukujgrg** [lark-parser/lark#881]
**What is your question?**

I am trying to parse an autosys JIL file. It's syntax allows multiple pairs on same line or new line. 

It's syntax rule says following. 
> You can enter multiple *attribute statements* on the same line, but you must separate the attribute statements with at least one space.

Here by *attribute statements*, it means a pair string separated by colon. 

Also, if a colon is in the value of attribute statements, it should be escaped.
> Because JIL parses on the combination of a keyword followed by a colon, you must use escape characters (a backslash) or enclose the value in quotation marks with any colons used in an attribute statement's value. For example, to define the start time for a job, specify 10\:00or “10:00”.
Note: When specifying drive letters in commands, you must use escape characters with the colon (:). For example, "C:\tmp" and C\:\tmp are valid; C:\tmp is not.

I am able to parse attribute statements if it's on a new line, but same line attribute statements are getting appended to the
preceding attribute statement.

Can someone please help me on getting this attribute statements on the same line right?

**If you're having trouble with your code or grammar**

**grammar**

```
$ cat jil.lark
start : jil+

jil : SUB_CMD WS* ":" WS* NAME WS* pairs
pairs: pair+
pair: KEY WS* ":" WS* VALUE WS*


SUB_CMD: "insert_job"
NAME: CNAME | "\"" CNAME "\""
KEY: CNAME
VALUE: ESCAPED_STRING | /.+/

%import common.CNAME
%import common.LETTER
%import common.ESCAPED_STRING
%import common._STRING_ESC_INNER
%import common.WS
%import common.C_COMMENT
%import common.SH_COMMENT
%ignore C_COMMENT
%ignore SH_COMMENT
%ignore WS


```

**code**

```
$ cat jil.py
import json
from typing import List

import lark
from lark import Lark, Transformer


text = """
/* ----------------- p01_frl_d_1639_00_mst_schd_cmd ----------------- */
insert_job: p01_frl_d_1639_00_mst_schd_cmd   job_type: CMD condition: blah blah
command: ${scriptdir}/Schedule.sh -m RUN -s 1639 -f 1 -j -v TCF_MSCHD_DLY.sql
start_times: "12:05"
description: Master Schedule Control\: Script

/* ----------------- p01_frl_d_1640_10_chk_prev_run_cmd ----------------- */
insert_job: "p01_frl_d_1640_10_chk_prev_run_cmd"   job_type: CMD
command: ${scriptdir}/Schedule.sh -m RUN -s 1639 -f 1 -j -v TCF_MSCHD_DLY.sql
start_times: "13:05"
description: "Blah blah"
"""


def sanitise(s):
    return s.replace('"', "").strip()


class TreeToJson(Transformer):

    def jil(self, s):
        sub_command, object_name = s[0:2]
        attributes = s[-1]
        # print(attributes)
        attributes.update({sub_command.value: sanitise(object_name.value)})
        return attributes

    def pairs(self, s: List[lark.Token]):
        _ = {}
        for i in s:
            attribute, value = i.children
            _.update({attribute.value: sanitise(value.value)})
        return _


with open("jil.lark", 'r') as grammar:
    parser = Lark(grammar, parser='lalr')
    tree = parser.parse(text)
    # print(tree.pretty(indent_str="    "))
    a: lark.Tree = TreeToJson().transform(tree)
    print(json.dumps(a.children, indent=4))
```

**Output:**

```
[
    {
        "job_type": "CMD condition: blah blah",
        "command": "${scriptdir}/Schedule.sh -m RUN -s 1639 -f 1 -j -v TCF_MSCHD_DLY.sql",
        "start_times": "12:05",
        "description": "Master Schedule Control\\: Script",
        "insert_job": "p01_frl_d_1639_00_mst_schd_cmd"
    },
    {
        "job_type": "CMD",
        "command": "${scriptdir}/Schedule.sh -m RUN -s 1639 -f 1 -j -v TCF_MSCHD_DLY.sql",
        "start_times": "13:05",
        "description": "Blah blah",
        "insert_job": "p01_frl_d_1640_10_chk_prev_run_cmd"
    }
]
```

**Expected Output:**
```
[
    {
        "job_type": "CMD",
        "condition": "blah blah",
        "command": "${scriptdir}/Schedule.sh -m RUN -s 1639 -f 1 -j -v TCF_MSCHD_DLY.sql",
        "start_times": "12:05",
        "description": "Master Schedule Control\\: Script",
        "insert_job": "p01_frl_d_1639_00_mst_schd_cmd"
    },
    {
        "job_type": "CMD",
        "command": "${scriptdir}/Schedule.sh -m RUN -s 1639 -f 1 -j -v TCF_MSCHD_DLY.sql",
        "start_times": "13:05",
        "description": "Blah blah",
        "insert_job": "p01_frl_d_1640_10_chk_prev_run_cmd"
    }
]
```

Explain what you're trying to do, and what is obstructing your progress.

I am trying to get the above given *Expected Output* where `"condition": "blah blah"` is also matched as an attribute statement (key:value pair).

**Comment by erezsh** [comment]
Well, according to the grammar you gave, both ways are legal parsings.

How do you know, as a human, that ..
```
job_type: CMD condition: blah blah
```

.. is one pair and not two? To me, it's not obvious.

Once you can articulate the distinction, try to apply it to the grammar.

**Comment by sukujgrg** [comment]
- If a word succeed by a `:` and a `string` with zero or more empty spaces, it's a pair. So, in this case, it's two pairs.
- If a colon is escaped with (eg: `10\:05`) or inside quotes (eg: `"10:05"`), should not treat it as a pair delimiter.

My idea was, if I do `pair+`, it will match all such pairs. But that's not working.
