### ISSUE TITLE
Be able to re-raise specific user exceptions

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#882]
**Suggestion**
Instead of [re-raising every exception found during visiting as a `VisitorError`](https://github.com/lark-parser/lark/blob/6cc9d42dc0b697996a9dffbc3e9f71bdf4d6e3c6/lark/visitors.py#L109-L110), what about whitelisting specific exceptions and let it go up the stack?

For example, say I want to whitelist `MyException` and not let it be re-raised as a `VisitorError`. Maybe I would do something like this:

```py
...   # Define transformer or something
parser = lark.Lark(
    grammar,
    ...,  # All the other options
    whitelist_exceptions=[MyException],
)

try:
    parser.parse(doc)
except MyException:
    ...  # Do the stuff
```

**Describe alternatives you've considered**
Subclassing `Transformer` or `Visitor` and implementing it. But that seems a bit hacky.

**Additional context**
This way, I can let "real" `LarkErrors` that signify a mistake in my `Transformer` flow normally yet let the exceptions I want to raise in my `Transformer` flow out uncaught.

**Comment by erezsh** [comment]
The main reason for raising a VisitError is that when using the internal transformer (`Lark(..., transformer=...)`), the parser needs to know if the error happened inside the transformer or elsewhere.

But you can just catch `VisitError` outside, an re-raise it as you like..

See this example:

```python
from lark import Lark, Transformer
from lark.visitors import VisitError

tree = Lark('start: "a"').parse('a')

class T(Transformer):
	def start(self, x):
		raise KeyError("Original Exception")

t = T()
try:
	print( t.transform(tree))
except VisitError as e:
	raise e.orig_exc
```

**Comment by ThatXliner** [comment]
>	raise e.orig_exc

What's `e.orig_exc`? Is it built-in Python's `Exception`? Does it return `VisitError` if there wasn't any other exceptions?

**Comment by ThatXliner** [comment]
[Nevermind](https://github.com/lark-parser/lark/blob/6cc9d42dc0b697996a9dffbc3e9f71bdf4d6e3c6/lark/exceptions.py#L239)

**Comment by ThatXliner** [comment]
Hey, that's not in the documentation.
