### ISSUE TITLE
range literal with unicode escape sequence in legacy Python

### ISSUE THREAD

**Issue by tsangwpx** [lark-parser/lark#890]
This issue is related to legacy Python < 3.3.
I created this because my PR #889 tests encounter [errors](https://github.com/tsangwpx/lark/runs/2507499919?check_suite_focus=true) when run against `pypy2` target. 
Someone may find this useful unless Python 2 support is explicitly dropped.

```
g = _Lark(r"""start: A+
              A: "\u0061".."\u0063"
              """)
g.parse('abcdefu')
```

Expected output:
Some exception raise.

Actual output:
`parse()` succeeded.

The reason is that `re` package does not support unicode escape sequence before 3.3.

The regex character set given by `PrepareLiterals.range` is equally `[u0061-u0063]` or `[0-u]`.

https://github.com/lark-parser/lark/blob/6348538eb65207414a4bd7f014201306e84d2917/lark/load_grammar.py#L469-L470

**Comment by MegaIng** [comment]
While that might be true, this isn't the reason you get the error message you saw: That is because pypy2 correctly (I think) rejects `\U` escape sequences in none-unicode literals. You need to add a `u` in test

**Comment by tsangwpx** [comment]
The code snippet is modified version of the following test case
https://github.com/lark-parser/lark/blob/6348538eb65207414a4bd7f014201306e84d2917/tests/test_parser.py#L1085-L1089

Probably the issue is confined to the test case only.

The raw unicode string convert the escape sequence to a single character in Python 2 while raw string in Python 3 keep they unchanged.

In Python 2,
```
>>> print(ur'\u0061\U00000061')
aa
```

In Python 3,
```
>>> print(r'\u0061\U00000061')
\u0061\U00000061
```

I think `re` is happy to accept those raw strings in Python 2 and Python 3.3 or later. No one is using version between 3.0 and 3.2.

**Comment by MegaIng** [comment]
Ok, I think I understand the problem now. I would just ignore this: We are dropping Python2.7 and <python3.6 . You can just add a skip clause wherever you need them in the tests for unicode in Python2.7

**Comment by tsangwpx** [comment]
It sounds good. The PR test case is skipped when python < 3.3.

Writing tests compatible with 2 and 3 is complicated because `ur`  flags are required but invalid syntax in Python 3.  The same test cases would be written twice: one file for Python2 and other file for Python 3.

**Comment by erezsh** [comment]
Lark is now 3.6+
