### ISSUE TITLE
Trouble Ignoring Comments

### ISSUE THREAD

**Issue by jhhcs** [lark-parser/lark#896]
Hey! I am writing a PowerShell parser and I ran into some trouble ignoring comments. I have boiled it down to a minimal non-working example, which is the following. Note that this is, of course, not capable of parsing PowerShell - it is only meant to illustrate the issue, and give a little context.
```python
from lark import Lark

parser = Lark(R"""
WHITESPACE : /([\u0020\u00A0\u1680\u2000-\u200A\u202F\u205F\u3000\u0009\u000B\u000C]|`[\r\n])+/
SL_COMMENT : /#[^\r\n]+/
DL_COMMENT : /<#(>|#*[^#>]+)*#+>/
_ENDL      : /([;\r\n])+/
endl       : _ENDL
script     : _ENDL? (statement endl)* statement endl?
statement  : command argument*
command    : token
argument   : token
token      : /([^\s{}();,|&$`\u0022\u201C\u201D\u201E\u0027\u2018\u2019\u201A\u201B]|`.)+/

%ignore WHITESPACE
%ignore SL_COMMENT
%ignore DL_COMMENT
""", start='script')

print(parser.parse("""
# comment
test one two # ignore me
""").pretty())
```
when I run this script, it usually parses `# comment` or `# ignore me` as parts of a command. Interestingly, this does not appear to be deterministic, i.e. it will sometimes actually ignore one of them, but I have not had a single execution where it successfully ignored both, and most of the time it ignores neither.

My goal is, if it wasn't obvious, to have it actually ignore all comments. I know I am likely doing something wrong, i.e. I have some misconception about how `%ignore` works - I am hoping someone can explain to me how this should be done.

**Comment by ThatXliner** [comment]
What do you get when you set the ambiguity to `explicit`?

**Comment by erezsh** [comment]
Your `token` regex allows `#`, which is probably not what you intended.

Try this:

```lark
...
SL_COMMENT : /#[^\r\n]+\n/
...
token      : /([^#\s{}();,|&$`\u0022\u201C\u201D\u201E\u0027\u2018\u2019\u201A\u201B]|`.)+/
...
```

**Comment by jhhcs** [comment]
Unfortunately, the fact that `token` allows `#` is correct and intentional. A hashtag can be part of a token. I am transcribing the PowerShell language specification from MS, and this is precisely how they define their `generic-token`. I believe that the reason why this works for _them_ is because they parse PowerShell in two steps. In the first step, the separate whitespace, comments, and code tokens. It is in the second parsing step where they parse the actual tokens.

I had hoped that the `%ignore` directive would be able to get rid of the comments even though `token` is able to match it. And, as a matter of fact:
```python
from lark import Lark

parser = Lark(R"""
WHITESPACE: /[\r\n\s]+/
COMMENT: /#[^\r\n]+/
%ignore WHITESPACE
%ignore COMMENT
token: /[^\s]+/
start: token*
""")

print(parser.parse("""
# comment
test one two # ignore me
""").pretty())
```
This much simpler language will have all comments stripped, even though `token` would also allow `#`. Because of the above example, I had found renewed hope that my mistake was somewhere else, and I could manage to fix the PowerShell parser after all. I think it would help me a lot to understand how exactly `%ignore` works, i.e. when these patterns are matched and consequently stripped.

**Comment by MegaIng** [comment]
@jhhcs But how is it determinate in the actual language whether `#` is part of a token or start of a comment? You need to clearly formulate that and then implement it.

**Comment by jhhcs** [comment]
Dear @MegaIng: Your comment actually helped me find something I was unaware of, namely that you can [use a custom lexer in Lark](https://lark-parser.readthedocs.io/en/latest/examples/advanced/custom_lexer.html). This might very well solve my problem, because PowerShell's parser solves the ambiguity by separating comments out during tokenization. However, I am still very curious as to why the comments are correctly stripped in my second example, but not in the first one I gave.

**Comment by MegaIng** [comment]
@jhhcs I don't know. The amazing thing is that there is a somewhat surprising fact hidden here:

```
WHITESPACE : / +/
SL_COMMENT : /#[^\r\n]+/
_ENDL      : /([;\r\n])+/
endl       : _ENDL
script     : _ENDL? (statement endl)* statement endl?
statement  : token*
token      : /[a-z#]+/

%ignore WHITESPACE
%ignore SL_COMMENT
```

Behaves like the grammar you showed off, e.g. Sometimes the comments are tokens and sometimes not.

But if you change `script` to:

```
script     : _ENDL? (statement _ENDL)* statement _ENDL?
```

It always behaves correctly. Maybe @erezsh has an answer here?

**Comment by erezsh** [comment]
No idea. Might be related to Issue #595 .

**Comment by jhhcs** [comment]
Could you tell me how `%ignore` is _intended_ to work? As in, at what point during parsing are `%ignore` patterns matched, and consequently, ignored?

**Comment by erezsh** [comment]
@jhhcs In Lark's version of Earley, ignores are scanned immediately after the rest of the tokens are scanned (among those that the parser thinks might be there). If any are found, they are simply skipped over, by carrying all the pending matches into the next iteration. This way, the parser can consider all the variations of the parse, and always find a solution, if one exists.
