### ISSUE TITLE
Syntax parse error when rule is re-using

### ISSUE THREAD

**Issue by seimit** [lark-parser/lark#899]
**What is your question?**
Are there limitation when a rule is re-used? 

Try to be accurate and concise.
I'm re-using rules a lot, but in one particular case I got an error, which looks strange for me.

**If you're having trouble with your code or grammar**
Provide a small script that encapsulates your issue.
```
import logging
from lark import Lark, logger

logger.setLevel(logging.DEBUG)

test = '''first_level_block 
            { 
                    -- comment --
                    second_level_block 
                   { 
                    -- comment --
                    } 
            }
      '''

test_grammar = '''
%import common.WS
%ignore WS

%import common.NEWLINE
%ignore NEWLINE

comment: OPEN_CMT (data)* CLOSE_CMT
OPEN_CMT : "--"
data : "comment"
CLOSE_CMT: "--"

start : "first_level_block" OPEN_BLOCK (comment | second_level_block)* CLOSE_BLOCK

OPEN_BLOCK : "{"
CLOSE_BLOCK : "}"

second_level_block : "second_level_block" OPEN_SECOND_BLOCK (comment)* CLOSE_SECOND_BLOCK 
OPEN_SECOND_BLOCK : "{"
CLOSE_SECOND_BLOCK : "}"

'''

p = Lark(test_grammar, parser='lalr', debug=True)
p.parse(test)

```

Explain what you're trying to do, and what is obstructing your progress.
I want once any rule is defined, to be possible to use it everywhere.
In this example, if the second "{-- comment --}" line is removed, there is no error during parsing. But when I add it inside the second block, parsing failed with:
lark.exceptions.UnexpectedToken: Unexpected token Token('CLOSE_BLOCK', '}') at line 5, column 21.
Expected one of:
        * OPEN_CMT
        * CLOSE_SECOND_BLOCK

Regards!

**Comment by MegaIng** [comment]
The problem here is overlapping terminals `CLOSE_SECOND_BLOCK` and `CLOSE_BLOCK`. You really try to avoid having Terminals that can match the same sequence. If you replace `CLOSE_SECOND_BLOCK` with `CLOSE_BLOCK` (and same for the open), the grammar will work correctly.

When using `parser='lalr'`, the lexer has to guess which terminal you want to parse (it doesn't backtrack/try all possbilites like `parser='earley')`. When using the standard (i.e. `lexer='contextual'`) the Lexer tries it's best to resolve conflicting terminals to the correct one, but sometimes that still fails.

**Comment by seimit** [comment]
Hello MegaIng,
Thanks for the detail explanation!
This will solve my problem with the syntax error, but the reason to use different Terminals is the semantic parser. If I resolve the syntax parse error with using same terminals, I can not recognize when the first and second block are open/closed.
Regards!

**Comment by MegaIng** [comment]
@seimit Well, yes you can: they will be inside `second_level_block` rules. I would suggest not using named terminals at all:

```
comment: "--" (data)* "--"
data : "comment"

start : "first_level_block" "{" (comment | second_level_block)* "}"

second_level_block : "second_level_block" "{" (comment)* "}"
```

Will create a tree like this:

```
start
  comment
    data
  second_level_block
    comment
      data
```

meaing that the second level data is in a seperate rule. Look at the [json tutorial](https://github.com/lark-parser/lark/blob/master/docs/json_tutorial.md) on an example with how to best continue with such a tree.
