### ISSUE TITLE
Extending rule definitions to the next line by using the OR operator

### ISSUE THREAD

**Issue by seimit** [lark-parser/lark#900]
**Describe the bug**
According the documentation:
"Rule definitions can be extended to the next line by using the OR operator (signified by a pipe: | )."
And the example is:
```
<name> : <items-to-match> [-> <alias> ]
| ...
```
However, when I'm trying to use this in my code, I got an error.

A clear and concise description of what the bug is, and what you expected to happen.
I expect extending the rules in multiple lines to work as described in the documentation.

**To Reproduce**

Provide a short script that reproduces the erroneous behavior.

```
import logging
from lark import Lark, logger

logger.setLevel(logging.DEBUG)

test = '''
        first_rule second_rule third_rule
      '''

test_grammar = '''

//start : first_rule second_rule third_rule // This works as expected
start : first_rule 
        | second_rule 
        | third_rule

first_rule : "first_rule"
second_rule : "second_rule"
third_rule : "third_rule"

%import common.WS
%ignore WS

'''
p = Lark(test_grammar, parser='lalr', debug=True)
p.parse(test)
```
I got the following error:
lark.exceptions.UnexpectedToken: Unexpected token Token('SECOND_RULE', 'second_rule') at line 3, column 9.
Expected one of:
        * $END
Previous tokens: [Token('FIRST_RULE', 'first_rule')]

**Comment by MegaIng** [comment]
Yes. This is an `OR`, not a concatenation. `a|b` matches if and only if `a` or `b` matches, like normal regex. There is currently no way to extend concatenation over multiple lines.

**Comment by seimit** [comment]
Thanks!
I thought that "rule extending" in the documentation is really the "extend concatenation over multiple lines".
Otherwise the ```OR``` works as expected.
