### ISSUE TITLE
Infer variable types from context

### ISSUE THREAD

**Issue by JJJGGGG** [lark-parser/lark#904]
I have the following code:

```py
from lark import Lark, Transformer, v_args
@v_args(inline=True)    # Affects the signatures of the methods
class T(Transformer):
  def si(self, n1, n2, n3):
    if(n1):
      return n2
    return n3
  def number(self, n):
    return float(n)
  def eq(self, n1, n2): 
    print(n1 == n2)
    return n1 == n2
  def ge(self, n1, n2):
    return n1 > n2
  def boolean(self, n):
    return bool(n)

grammar = r"""
ins: n -> number
| "Si(" n_cond "," n "," n ")" -> si


n_cond: n -> number
       | cond -> boolean

cond: NUMBER "==" NUMBER -> eq
      | NUMBER ">" NUMBER -> ge
n: NUMBER -> number

%import common.NUMBER
%import common.WS_INLINE

%ignore WS_INLINE
"""

p = Lark(grammar, start="ins", parser="lalr", transformer=T(), lexer="contextual")

print(p.parse("Si(0 == 1, 2, 3)"))
```

So basically, it is a parser that parses a function ```Si(n1, n2, n3)``` (similar to excel IF function, ```if n1 then n2 else n3```), where n1 can be a number or a boolean expression. My question is on these lines of the grammar definition:

```py
...
n_cond: n -> number
       | cond -> boolean
...
```
If i remove the ```number``` or ```boolean``` functions, the boolean returned by ```cond``` is interpreted as another thing than boolean and the parsing returns 2. So is there a way to avoid to write a type declaration function every time, it being inferred from the previous variable type?

**Comment by erezsh** [comment]
I can't tell exactly what you mean, because you didn't include everything, like that's `cond`, or which input isn't working as you expect. 

This isn't really Lark-related anyway, but I'll do my best to answer.

**Comment by JJJGGGG** [comment]
I tried to make a minimal reproductible example and all I could reduce it to was this:
```py
from lark import Lark, Transformer, v_args
@v_args(inline=True)    # Affects the signatures of the methods
class T(Transformer):
  def si(self, n1, n2, n3):
    if(n1):
      return n2
    return n3
  def eq(self, n1, n2): 
    print(n1 == n2)
    return n1 == n2
  def boolean(self, n):
    return bool(n)
  def number(self, n):
    return float(n)

grammar = r"""
ins: "Si(" n_cond "," n "," n ")" -> si

n_cond: n 
        | cond

cond: NUMBER "==" NUMBER -> eq

n: NUMBER -> number

%import common.NUMBER
%import common.WS_INLINE

%ignore WS_INLINE
"""

p = Lark(grammar, start="ins", parser="lalr", transformer=T(), lexer="contextual")

print(p.parse("Si(0 == 1, 2, 3)"))
```
This code should print 3, but prints 2. If I print n1 in the si function at the beginning of T, this shows:
```
Tree('n_cond', [False])
```
I suppose the n1 is treated as True only because it is an object, but it should evaluate to False because it bears a False value, doesn't it?

And I think the same issue happens with this code:

```
from lark import Lark
grammar = r"""
start: NUMBER

%import common.NUMBER
%import common.WS_INLINE

%ignore WS_INLINE
"""

p = Lark(grammar, start="start", parser="lalr", lexer="contextual")

print(p.parse("1"))
```
Here, it isn't 1 that is printed, but 
```
Tree('start', [Token('NUMBER', '1')])
```

Why doesn't Lark flatten outputs, but rather lets the whole Tree? Or better: how could I make Lark ignore the Tree (just make the parsing AND compiling)? Am I using the wrong tool?

**Comment by erezsh** [comment]
> Am I using the wrong tool?

Well, you're using the right tool wrong.

`Tree` objects are always True, but adding this to the transformer would work:

```python
  def n_cond(self, n):
    return n
```

But in this case, you can do an ever simpler change instead, and define `n_cond` like this:

```lark
?n_cond: n 
        | cond
```

Either one is fine.
