### ISSUE TITLE
Why do the docs say that terminals have to be upper case but when I have lowercase terminals I have not issues?

### ISSUE THREAD

**Issue by brando90** [lark-parser/lark#933]
**Describe the bug**

I recently had a bug where the parser told me that my terminals were recrusive (detected by the use of uppercase). 

'''
lark.exceptions.GrammarError: Recursion in terminal 'LAMBDA_EXP' (recursion is only allowed in rules, not terminals)
'''

But when I removed the recursion and changed the name to a lower case I got not bug. Isn't this a bug?

**To Reproduce**

Initial grammar with bug:
```
LAMBDA_EXP : IDENT
    | "λ" IDENT ":" SIMPLE_TYPE "." LAMBDA_EXP
    | LAMBDA_EXP LAMBDA_EXP
    // | "(" LAMBDA_EXP LAMBDA_EXP ")"

SIMPLE_TYPE : IDENT
    | SIMPLE_TYPE "→" SIMPLE_TYPE  // "→"

IDENT : /[A-Za-z0-9_]+/

%import common.WS
%ignore WS

// %import common.ESCAPED_STRING
// %import common.SIGNED_NUMBER

```
corrected grammar with no bug (but I believe it should be throwing a bug due incorrect use of lowercase):
```
term : ident
    | "λ" ident ":" type "." term
    | term term
    // | "(" term term ")"

type : ident
    | type "→" type  // "→"

ident : /[A-Za-z0-9_]+/

%import common.WS
%ignore WS

// %import common.ESCAPED_STRING
// %import common.SIGNED_NUMBER
```

**Comment by MegaIng** [comment]
Why would that be incorrect use?

**Comment by brando90** [comment]
> Why would that be incorrect use?

because the docs say that terminals are uppercased. So when I do a non-terminal with a upper case I get recursion errors. But it seems inconsistent to not throw me errors when my terminals are lower case.

I am just basing what I read https://lark-parser.readthedocs.io/en/latest/grammar.html and the docs. I am fine with letting the user define rules terminals with whatever case we want and then having lark detect terminals automatically by seeing if they point to a constant or regex etc.

**Comment by MegaIng** [comment]
But if you write them lowercase, they aren't terminals. The case defines if they are terminals or non terminals.

You can btw. make `IDENT` a Terminal without any problems.

**Comment by erezsh** [comment]
When you write

```lark
ident : /[A-Za-z0-9_]+/
```

You define a rule called `ident`, which matches one anonymous terminal, in this case a regexp.

Most terminal definitions can be turned into rules and still work the same way. But that's not always the case! Also, the resulting tree will look different.
