### ISSUE TITLE
How to use all special characters and store them as is in the grammar rules of the parser?

### ISSUE THREAD

**Issue by brando90** [lark-parser/lark#939]
**Describe the bug**

Not 100% if its a bug but I was trying to match a rule with the given rules but I noticed that one of the rules in the parser has a strange anon symbol instead of my symbol:
```
rule
Out[9]: Rule(NonTerminal('type'), [NonTerminal('type'), Terminal('→'), NonTerminal('type')], None, RuleOptions(False, False, None, None))
rules
Out[10]: 
[Rule(NonTerminal('type'), [NonTerminal('type'), Terminal('__ANON_0'), NonTerminal('type')], None, RuleOptions(True, False, None, None)),
 Rule(NonTerminal('type'), [Terminal('T')], None, RuleOptions(True, False, None, None))]
```
which makes me unable to find a rule. Is this expected? How to have parser detect that type of character and store it properly?

**To Reproduce**

Use this grammar to reproduce:
```
from lark import Lark
grammar = r"
type : type "→" type  // "→"
    | /[A-Za-z0-9_]+/

// ignore tokens
IGNORE_TOKENS : "(" | ")"
%import common.WS

%ignore WS
%ignore IGNORE_TOKENS"
"
parser = Lark(grammar, 'type', keep_all_tokens=True)
ast = parser.parse('T → T')
rule = Rule(NonTerminal('type'), [NonTerminal('type'), Terminal('→'), NonTerminal('type')], None, RuleOptions(False, False, None, None))
parser.rules.index(rule)
```

**Comment by brando90** [comment]
actually it didn't get fixed when I switched to `->`...?
```
type : type "->" type  // "->"
    	| "T" 
// ignore tokens
IGNORE_TOKENS : "(" | ")"
%import common.WS
%ignore WS
%ignore IGNORE_TOKENS
// %import common.ESCAPED_STRING
// %import common.SIGNED_NUMBER
parser.rules
Out[7]: 
[Rule(NonTerminal('type'), [NonTerminal('type'), Terminal('__ANON_0'), NonTerminal('type')], None, RuleOptions(True, False, None, None)),
 Rule(NonTerminal('type'), [Terminal('T')], None, RuleOptions(True, False, None, None))]
```

**Comment by brando90** [comment]
why is this terminal `Terminal('__ANON_0')` showing up?

**Comment by erezsh** [comment]
It's a terminal without a name. Probably `/[A-Za-z0-9_]+/`. But anyway, if you want every terminal to have the right name, you have to name them yourself.

**Comment by brando90** [comment]
> It's a terminal without a name. Probably `->` or `/[A-Za-z0-9_]+/`. But anyway, if you want every terminal to have the right name, you have to name them yourself.

but why does this one appear correctly though?

```
[Rule(NonTerminal('term'), [Terminal('Λ'), NonTerminal('term'), Terminal('COLON'), NonTerminal('type'), Terminal('DOT'), NonTerminal('term')], None, RuleOptions(True, False, None, None)),
```

**Comment by brando90** [comment]
ok I see my code works if I change stuff as follow:
```
                sym = Terminal(child.type)  # e.g. token.type "COMMA" in Token('COMMA', ','), token.value = ',' (check)
                # sym = Terminal(child.value)  # e.g. token.type "COMMA" in Token('COMMA', ','), token.value = ',' (check)
```
why do tokens have two names? Why not use the value as the name e.g. `->` or `,` or `→`?

**Comment by erezsh** [comment]
We do, if the name is a unicode id

```python
if value and is_id_continue(value) and is_id_start(value[0]) and value.upper() not in self.term_set:
    term_name = value.upper()
```

What you suggest might work. And maybe it's more useable than `ANON_x`, so it's worth considering.

**Comment by erezsh** [comment]
@MegaIng What do you think, why not use the terminal value as its type, instead of autogenerating a generic one?

**Comment by MegaIng** [comment]
Potential downsides:

- Breaking change (we dont care right now)
- Bad idea with unicode in 2.7 (dont care either)
- potentially harder to type for the end user (but they are providing the grammar, so what do we care)
- Need to change a few places accross the code base, e.g. all is terminal checks
- Confusing for long regex

But this is the third time we get an issue for this, and this is certaintly a permanent fix. I would do it.

**Comment by erezsh** [comment]
It's breaking, but it's not like anyone relies on terminal names being `_ANON_x`. Or at least, they shouldn't have.

Why would it matter on 2.7?

**Comment by MegaIng** [comment]
> Why would it matter on 2.7?

It intoduces unicode to places in the codebase that didn't have it till now, that might make problems. But we since we are dropping 2.7 support anyway right now, we dont have to care.

**Comment by erezsh** [comment]
I looked into it. We depend on terminal names for use as regex groups. So anything that isn't a valid ID would fail. Of course, we can translate between the "safe name" and the "value name" before creating the token, but my feeling is that it's not worth the trouble.

Btw, the relevant information is available in `Lark.terminals`, so you can do the translation yourself if you want, before you begin working with the tree.
