### ISSUE TITLE
Link leads to 404 page in JSON tutorial.

### ISSUE THREAD

**Issue by MystPi** [lark-parser/lark#941]
**Examples link doesn't work**

The link at the bottom of the [JSON tutorial](https://github.com/lark-parser/lark/blob/master/docs/json_tutorial.md) leads to the 404 page.

**To Reproduce**

Just go to the tutorial and click the [link](https://github.com/lark-parser/lark/blob/master/docs/examples) at the very bottom of the page. I thought it might be a good idea to report this so people don't get confused.

**Comment by MegaIng** [comment]
Not from [read the docs](https://lark-parser.readthedocs.io/en/latest/json_tutorial.html). Not really sure there is something we can do to fix this. The example folder on github is https://github.com/lark-parser/lark/tree/master/examples.

**Comment by erezsh** [comment]
It works now. Thanks for reporting it!

**Comment by MystPi** [comment]
No problem!
