### ISSUE TITLE
Using lark to search lines of source code?

### ISSUE THREAD

**Issue by just1ngray** [lark-parser/lark#943]
### Can/should I use lark to match text?
Specifically, I am trying to analyze how various functionalities are used in a set of source code files. I.e., what arguments are passed to a given function, or what kind of regular expressions are used?

#### Ex 1: Find arguments passed to the `my_function` function. Ans: [None, None, "abc"] for each line respectively.
```
function foo():
    bar()
    result = my_function("abc") // comment
```

#### Ex 2: What regular expressions are found in this snippet? Ans: %$
```javascript
    ...
    value = parseFloat(value, 10) / (/%$/.test(value) ? 100 : 1);
    ...
```

I've been using regular expressions + additional logic to handle this so far. But as my project grows, accuracy and maintainability is suffering. I figured I might be able to write a grammar in lark to handle most of the work.

I've used lark in other aspects of my project without any issues, but I keep getting difficult errors and would really appreciate some help in the matter. I figure the grammar for Ex 1 should look something like this:
```
start   : [JUNK] "my_function(" ARG ")" [JUNK]
JUNK    : /.+/
ARG     : /[^ ]+/
```

In my mind, the above grammar should be able to handle `my_function("abc")`, in reality:
```
Traceback (most recent call last):
  File "...sample.py", line 80, in <module>
    print parser.parse('my_function("abc")')
  File "...Library/Python/2.7/lib/python/site-packages/lark/lark.py", line 561, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "...Library/Python/2.7/lib/python/site-packages/lark/parser_frontends.py", line 107, in parse
    return self.parser.parse(stream, start, **kw)
  File "...Library/Python/2.7/lib/python/site-packages/lark/parsers/earley.py", line 306, in parse
    raise UnexpectedEOF(expected_terminals, state=frozenset(i.s for i in to_scan))
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
        * __ANON_0
        * RPAR
        * __ANON_0
        * RPAR
```

Am I totally misguided? Am I missing something here?
Either way, thanks for the awesome project - it's working splendidly in other parts of my project.

**Comment by MegaIng** [comment]
Lark isn't really that good at searching in a text. It would be better if you can define a full grammar for everything (If the text might contain error, you can try to play around with error callbacks). Otherwise [pyparsing](https://github.com/pyparsing/pyparsing) has [scanString](https://pythonhosted.org/pyparsing/pyparsing.ParserElement-class.html#scanString), which might be a better fit.

Although @erezsh: Shouldn't it be somewhat easy to build a search function the uses some kind of cached (contextual) lexer to try to parse at a lot of places and sees how much progress it does? Might be worth adding to lark, since this isn't the first time we get this request.

**Comment by ThatXliner** [comment]
If you're trying to search for Python code, you're probably better off with something like [Red Baron](https://redbaron.readthedocs.io/en/latest/)

**Comment by erezsh** [comment]
Lark might be able to do it, if you use `parser="earley"` and `lexer="dynamic_complete"`.

But it would be very inefficient!

You're better off starting you parse at different points in the text. Like

```python
for i in range(text):
   try:
        res = lark_instance.parse(text[i:])
		// do something with result
   except LarkError:
       pass
```

And if that's too slow, you can find all the likely points with a regexp, and then use Lark to validate your findings. But that's just a thought. Lark definitely wasn't designed for that.

**Comment by erezsh** [comment]
@MegaIng I'd be willing to consider such a PR if it works well, but I'm not sure it would be as simple as you suggest.

**Comment by just1ngray** [comment]
Thanks everyone for your assistance. It seems my current solution (regex + additional logic) is better than anything lark is meant to provide.

I’ll close this since my question has been answered. 😄
