### ISSUE TITLE
String Parsing Error

### ISSUE THREAD

**Issue by MystPi** [lark-parser/lark#946]
This is [most of] my grammar:
```lark
?start : tag*

tag : NAME attr? ("{" value* "}")?
eval : "%" "{" /.+?(?=})/? "}"
attr : "(" key_value ("," key_value)* ")"
key_value : NAME ":" STRING
        
?value : tag
       | eval
       | STRING
               
_STRING_INNER: /.*?/
_STRING_ESC_INNER: _STRING_INNER /(?<!\\)(\\\\)*?/

STRING : "\"" _STRING_ESC_INNER "\""
```
And I'm trying to parse ```p {"Hello"}```.
It works if I use:
```lark
%import common.ESCAPED_STRING -> STRING
```
Instead of:
```lark
_STRING_INNER: /.*?/
_STRING_ESC_INNER: _STRING_INNER /(?<!\\)(\\\\)*?/

STRING : "\"" _STRING_ESC_INNER "\""
```

But I can't use the included strings because I want them to be multi-line.
This is the error:
```
lark.exceptions.UnexpectedCharacters: No terminal matches '"' in the current parser context, at line 1 col 5

p {"Hello"}
    ^
Expected one of: 
	* NAME
	* STRING
	* RBRACE
	* PERCENT
```
Anything I should do?

**Comment by MegaIng** [comment]
That grammar works for me (when adding ignore WS and a definition for NAME). Can you provide a full small python script and what version of lark you are using?

**Comment by MystPi** [comment]
I'm pretty sure my version is 0.11.3. As for the program, it can be found [here](https://github.com/MystPi/marker/blob/main/marker.py).

**Comment by MystPi** [comment]
Ahh, I found the issue! I needed a raw string for the escaped quote! Thanks for your help anyway. 😄
