### ISSUE TITLE
Parsing a long input (50+ characters or so) brings the parser to a halt

### ISSUE THREAD

**Issue by richard-jones** [lark-parser/lark#951]
I am writing a small DSL for a documentation task, and have really been enjoying playing with Lark.  I have never written a lexer before, so I'm very much new to the whole thing, apologies in advance if I'm making an obvious mistake here.

I have devised a grammar for my DSL, and when I pass it a long-ish token, it brings my programme to a halt.  I have also tried this in the Lark IDE and it crashes the browser window.  I presume that my grammar defines a horribly inefficient algorithm, but I am unsure how to approach optimising it.

Here is the grammar:

```
start: context
     | link entity
     | pointer link entity 
     | link register entity
     | pointer link register entity
     | context link entity
     | noswitch context link entity

context: CONTEXT -> context
link: LINK -> link
entity: ENTITY -> entity
noswitch: NOSWITCH -> noswitch
register: REGISTER -> register
pointer: POINTER -> pointer

CONTEXT: PREFIX ":" TYPE
LINK: " "* "->" " "* 
    | " "* SYMBOL " "+
ENTITY: PREFIX ":" TYPE
NOSWITCH: " "* "!" " "*
REGISTER: " "* "$" " "*
POINTER: " "* "^" " "*

PREFIX: SYMBOL
TYPE: SYMBOL

LOWER: ("a".."z")+
UPPER: ("A".."Z")+
NUMBER: ("0".."9")+
SYMBOL: (LOWER | UPPER | NUMBER)+
```

Some examples of legal terms in this grammar would be

```
Thing:Feature
isA Thing:Feature
Thing:Feature -> Other:Whatsit
!Thing:Feature isA Other:Whatsit
```

This all works well, except that I hit this token, and everything stopped working:

`APIOutgoingCommonJournalApplication:Model->Seamless:Library`

After some experimentation in the IDE, I found that if I enter a shorter token, like `APIOutgoingCommonApplication:Model->Seamless:Library` then everything works fine, maybe a little laggy.  But add a couple more characters to the first term and everything grinds to a halt.

I have tried executing this with both Earley and LALR with similar results.

Any help or pointers you could give me would be gratefully received.

**Comment by erezsh** [comment]
It seems that you've managed to confuse the Earley parser by using nested repetition inside the terminals.

If you redefine SYMBOL like this, it should work much better:

```lark
LOWER: ("a".."z")
UPPER: ("A".."Z")
NUMBER: ("0".."9")
SYMBOL: (LOWER | UPPER | NUMBER)+
```

I could not reproduce this issue with LALR.

P.S. It's generally advised to use `%ignore` to deal with whitespace, rather than writing them into the terminals.

**Comment by erezsh** [comment]
For future reference, this is a bug in the Python re module.

To reproduce:

```python
import re
re.match('(a+)+x', 'a'*30)
```

This will cause both Earley and LALR to "freeze" while the regex runs its course.

A possible solution to avoid this (other than writing better regexes :) is to use the optional `regex` module, which doesn't seem to suffer from this problem.

**Comment by richard-jones** [comment]
Great spot, thank you so much!  This works perfectly.  I made a few other modifications and added in the `&ignore " "` for the whitespace, and everything is rosy.

For reference/interest, here is the updated and working version in full

```
start: noswitch? context (link entity)?
       | pointer? link register? entity

context: ENTITY -> context
link: LINK -> link
entity: ENTITY -> entity
noswitch: NOSWITCH -> noswitch
register: REGISTER -> register
pointer: POINTER -> pointer

%ignore " "
LINK: "->"
    | SYMBOL
ENTITY: SYMBOL ":" SYMBOL
NOSWITCH: "!"
REGISTER: "$"
POINTER: "^"

LOWER: ("a".."z")
UPPER: ("A".."Z")
NUMBER: ("0".."9")
SYMBOL: (LOWER | UPPER | NUMBER)+
```

Thanks again for your help, and all your work on Lark!

**Comment by erezsh** [comment]
The aliases you're using aren't necessary.

These two forms are completely equivalent:

```lark
context: ENTITY -> context
```

```lark
context: ENTITY
```

Same goes for the rest of the aliases.

The rest looks fine (though the definition of LINK seems a little fishy).

Happy to help!
