### ISSUE TITLE
Lark not acting deterministically on this grammar...

### ISSUE THREAD

**Issue by enjoysmath** [lark-parser/lark#953]
```
from lark import Lark, Transformer
from expression import *


math_grammar = r"""
    ?expr: paren                             -> parentheses
               | prop
               | prop_list                       -> and_props
               | add                                 -> add_op
               | mul                                 -> mul_op
               | expr_list              
               | var                                  -> variable
               | ESCAPED_STRING  -> string
               | SIGNED_NUMBER   -> integer

    prop:  typing                         -> typing_prop
             | implies                         -> implies_prop
             
    prop_list: prop ("," prop)+

    implies: prop "=>" prop
                  |  prop "⇒" prop
                  
    add: expr ("+" expr)+
    mul: expr expr+
    ?typing: expr ":" expr
    ?expr_list : expr ("," expr)+
    paren: "(" expr ")"
    
    string : ESCAPED_STRING
    
    ?var: LATIN_VAR   
         | GREEK_VAR    
    LATIN_VAR: /[a-zA-Z]/
    GREEK_VAR: /α|β|Γ|γ|Δ|δ|ε|ζ|η|Θ|θ|ι|κ|Λ|λ|μ|ν|Ξ|ξ|Π|π|ρ|Σ|σ|ς|τ|Υ|υ|Φ|φ|χ|Ψ|ψ|Ω|ω/
    
    %import common.ESCAPED_STRING
    %import common.SIGNED_NUMBER
    %import common.WS
    %ignore WS
    """

class TreeToMath(Transformer):
    def parentheses(self, tree):
        return Parentheses(tree[0].children[0])
            
    def string(self, tree):
        return String(tree[0][1:-1])
            
    def integer(self, tree):
        return int(tree[0])
    
    def variable(self, tree):
        return Var(tree[0])
    
    def typing_prop(self, tree):
        return TypingProp(*tree[0].children)
            
    def implies_prop(self, tree):
        return ImpliesProp(*tree[0].children)
        
    def and_props(self, tree):
        return And(*tree[0].children)
    
    def mul_op(self, tree):
        return Mul(*tree[0].children)
    
    #list = list
    #null = lambda self, _: None
    #true = lambda self, _: True
    #false = lambda self, _: False

math_parser = Lark(math_grammar, start='expr', lexer='standard')

if __name__ == '__main__':
    while True:
        text = input("text=")
        tree = math_parser.parse(text)
        expr = TreeToMath().transform(tree)
        print(repr(expr))
        print(str(expr))

```

[expression.zip](https://github.com/lark-parser/lark/files/6912115/expression.zip)

`expression.py` included in that zip is what I'm transforming the parse tree into and is the only other dependency needed to exhibit the issue.

Try running the above code listing and typing in `a:b:c`.  It will print out `(a:b):c`.  Try running again, and entering that it will sometimes print out `a:(b:c)`.    Keep re-running and entering that to see that it changes around.

Anyway, I can't use my code like this unless it acts deterministically on the user's input.  

So what can I specify in the grammar to correct the problem?

**Comment by MegaIng** [comment]
While we try to avoid nondeterministic behavior, I would strongly suggest you redesign your entire grammar to avoid all ambiguities, following the examples set by the [calc](https://github.com/lark-parser/lark/blob/master/examples/calc.py) and the [python](https://github.com/lark-parser/lark/blob/master/examples/advanced/python3.lark) grammars. You need to clearly define precedence and associativity of all operators to prevent ambiguities in your grammar.

As example, your current grammar would allow `ab+c` to be parsed as `(ab)+c` or as `a(b+c)`, which is certainly not what you want. While Lark tries to be  deterministic for the same output, it might not be correct for different inputs.

**Comment by erezsh** [comment]
It's a known bug #595 and #81 

Unless if you feel your situation is unique, I will close it as duplicate.
