### ISSUE TITLE
propagate_positions doesn't work with all kinds of `tree_class`

### ISSUE THREAD

**Issue by BlankSpruce** [lark-parser/lark#955]
Consider this snippet:
```python
from lark import Lark, Meta

# just for the sake of demonstration
class MyTree:
    def __init__(self, data, children):
        self.data = data
        self.children = children
        self.meta = Meta()

parser = Lark.open(
    grammar_filename="foobar.lark",
    propagate_positions=True,
    tree_class=MyTree
)
```

Due to the `isinstance(res, Tree)` in implementation of [`PropagatePositions.__call__`](https://github.com/lark-parser/lark/blob/7ee1409128c378c7e77bfac8018fe46485f4bf77/lark/parse_tree_builder.py#L33):
```python
class PropagatePositions:
    ...

    def __call__(self, children):
        res = self.node_builder(children)

        if isinstance(res, Tree):
            ...
            # algorithm impl
            ...

        return res
```
when `MyTree` is not derived from `Tree` (and it might be so for some reason) `PropagatePositions` won't do anything useful. Currently the available workarounds I'm aware of are:
- do it yourself with `transformer` supplied to parser but only when grammar has no inlined terminals
- monkey patching `PropagatePositions.__call__` with alternative implementation aware of `MyTree`

I'm not sure what would be the best way forward since PropagatePositions in some cases would have to be aware of `tree_class` layout. For instance (general idea since I'm not allowed to provide concrete example):
```python
class MyTree:
    # let's say you don't need all the details of Meta and you'd like to have all the data flat in MyTree
    def __init__(self, data, children, start=None, end=None)
        self.data = data
        self.children = children
        self.start = start
        self.end = end

class MyPropagatePositions:
     ...
     def __call__(self, children):
         ...
         if isinstance(res, MyTree):
              ...
              # just start position part
              if isinstance(child, MyTree):
                  res.start = child.start
              elif isinstance(child, Token):
                  res.start = child.pos_in_stream
```

This in turn would require yet another option to `Lark` in case user would like to roll out their own implementation. The alternative solution would be requiring that `MyTree` derives from `lark.Tree` but it might be too limiting.

**Comment by BlankSpruce** [comment]
I wasn't aware it's part of the API since I didn't see it documented. I'm fine with your clarification.

Without disclosing code I'm not allowed to disclose it might be hard to give a convincing example of when it might be limiting but I'll try something different: consider the following based on example above:
```python
class MyTree:
    __slots__ = {"data", "children", "column_begin", "column_end"}

    def __init__(self, data, children, column_begin=None, column_end=None)
        self.data = data
        self.children = children
        self.column_begin = column_begin
        self.column_end = column_end
```
I kind of need some meta information but I don't need it all and at the same time I'd like to still limit memory and attribute access overhead related to `Tree.meta`.

**Comment by BlankSpruce** [comment]
Of course we can close the issue at that since completely custom `Tree` might be a feature you don't want to support. Documentation update about inheritance from `lark.Tree` would be much appreciated.

**Comment by MegaIng** [comment]
But the Tree class you presented is not compatible with `PropagatePositions`. If you need different attributes, you need to role a custom implementation.

**Comment by BlankSpruce** [comment]
Yes, of course, the second and third example are completely incompatible with PropagePositions. For the first example I wasn't aware that inheritance is "the way".

**Comment by erezsh** [comment]
The parser expects certain behaviors from the tree class. PropagatePositions expects a meta attribute.

Giving the users complete freedom isn't the best idea, probably.

I'll take your comment about mentioning it in the documentation. I'll also add a subclass test with a proper error, to help prevent future confusion.
