### ISSUE TITLE
Anonymous token changes reconstruction

### ISSUE THREAD

**Issue by plannigan** [lark-parser/lark#957]
**Describe the bug**

If I use an anonymous token as part of a rule, reconstructing the original content produces a slightly different result. However, using a named terminal produces the expected result.

**To Reproduce**

```python
from lark import Lark
from lark.reconstruct import Reconstructor

content = """FOO [ "some", "sequence", "of", "values" ]"""

terminal_parser = Lark("""start: name WS_INLINE array
name: WORD
value: WORD
instruction: name WS_INLINE array
array: "[" WS_INLINE? _quoted_term{value} WS_INLINE? ( COMMA WS_INLINE? _quoted_term{value} WS_INLINE? )* "]"
_quoted_term{term}: SINGLE_OR_DOUBLE_QUOTE term SINGLE_OR_DOUBLE_QUOTE
SINGLE_OR_DOUBLE_QUOTE: /['"]/
COMMA: ","
%import common.WORD
%import common.WS_INLINE
    """)

anon_parser = Lark("""start: name WS_INLINE array
name: WORD
value: WORD
instruction: name WS_INLINE array
array: "[" WS_INLINE? _quoted_term{value} WS_INLINE? ( "," WS_INLINE? _quoted_term{value} WS_INLINE? )* "]"
_quoted_term{term}: SINGLE_OR_DOUBLE_QUOTE term SINGLE_OR_DOUBLE_QUOTE
SINGLE_OR_DOUBLE_QUOTE: /['"]/
%import common.WORD
%import common.WS_INLINE
    """)

new_anon_content = Reconstructor(anon_parser).reconstruct(anon_parser.parse(content))
new_terminal_content = Reconstructor(terminal_parser).reconstruct(terminal_parser.parse(content))

print(content)
print(new_anon_content)
print(new_anon_content == content)
print(new_terminal_content)
print(new_terminal_content == content)
```

Running this produces
```
FOO [ "some", "sequence", "of", "values" ]
FOO [ "some" ,"sequence" ,"of", "values" ]
False
FOO [ "some", "sequence", "of", "values" ]
True
```
Note that the commas are shifted to the right of the white space when the grammar does not user a named terminal. There does seem to be some variance between runs on how many and which commas get shifted.

This uses `lark`  0.11.3 & python 3.9.0.

**Comment by erezsh** [comment]
My guess is that the different between COMMA and _COMMA changes the matching order of the different derivations. Since both are syntactically valid, which one gets chosen is a matter of chance. Perhaps we can introduce a way to explicitly prefer a certain order.

But perhaps @MegaIng will have a better insight.

**Comment by MegaIng** [comment]
You are not throwing away `WS_INLINE`. That means that the actual children are somewhat like this:

with terminal
```
Tree('array', [WS_INLINE, value, COMMA, WS_INLINE, value, COMMA, WS_INLINE])
```

and without

```
Tree('array', [WS_INLINE, value, WS_INLINE, value, WS_INLINE])
```

Notice how the WS_INLINE stays in place, but the COMMA can be inserted to either side of it. This is ambiguous and might therefore change depending on PYHASHSEED. However, there is not such ambiguity in the first case. There is currently not really a solution to fixing this.


@erezsh A way to explicitly prefer a matching certain order would be to filter out unwanted rules when generating the reconstruction rules in `TreeMatcher`. Those unwanted rules would be those that have to same expansion when excluding thrown away rules. The facility is mostly already there I think. I will see if I can hack something together.

**Comment by plannigan** [comment]
Ok. I understand the ambiguity now. Unfortunately, I am trying to write a grammar for something that already exists & need to write things back without these type of odd changes. Giving it a name does appear resolve my immediate issue.
