### ISSUE TITLE
Using the LALR file cache on Python 2.7 fails with "unbound method exists() must be called with FS instance as first argument (got str instance instead)"

### ISSUE THREAD

**Issue by antoniotejada** [lark-parser/lark#977]
I'm using Lark for epycc https://github.com/antoniotejada/epycc on Python 2.7 and I found that when using the LALR with cache=True:
```Python
parser = lark.Lark.open(grammar_filepath, keep_all_tokens="True", 
    lexer="standard", parser="lalr", cache=True)
```
fails with 
```Python
Exception has occurred: TypeError
unbound method exists() must be called with FS instance as first argument (got str instance instead)
        File "C:\Python27\Lib\site-packages\lark\lark.py", line 276, in __init__
        if FS.exists(cache_fn):
        File "C:\Python27\Lib\site-packages\lark\lark.py", line 501, in open
        return cls(f, **options)
                ...
```
The problem is in utils.FS that doesn't declare "exists" as @staticmethod the same way it's done for "open"

An easy workaround is:
```Python
setattr(lark.utils.FS, 'exists', staticmethod(os.path.exists))
parser = lark.Lark.open(grammar_filepath, keep_all_tokens="True", 
    lexer="standard", parser="lalr", cache=True)
```

**Comment by erezsh** [comment]
Thanks for the catch. We'll merge the fix soon.

Just curious, in what context are you using Lark with Python 2.7?

I ask because we are planning to drop support for Python 2 soon.

**Comment by antoniotejada** [comment]
Thanks for the quick turnaround, Erez.

Coincidentally I read https://github.com/lark-parser/lark/pull/925 and https://github.com/lark-parser/lark/pull/925/commits/eb453241464a2461f9642f6810ac966a4c7e77b7 little after submitting my bug.

The short story is that I don't think I have a solid customer story for you to keep 2.7 support, this is just for my pet projects and I may not even be a returning customer and switch away from Lark at some point :-)

The long story is that I have a bunch of 2.7 code and I cannot be bothered switching to Python 3 unless something I care about gets fixed like GIL/multithread, interpreter reinitialization, speed/JIT. I don't even upgrade packages if they just work.

I picked Lark for [epycc](https://github.com/antoniotejada/epycc), after writing my own unfinished top down parser, because of the Earley promise of dealing with ambiguous grammars (which in the end didn't work for the C99 ambiguities), the 2.7 support, the speed charts in the docs, and the fact that I could easily switch from Earley to LALR and even standalone (being able to quickly prototype changes with the online IDE is super helpful too).

Even if [epycc](https://github.com/antoniotejada/epycc) gains traction I probably wouldn't switch to 3 either, just take patches from Python 3 people and keep both working.

To me Python 3 might as well be called Slytherin, it's a different language from Python and I'm not going to use one over the other just because someone wakes up one day and says so :-)

**Comment by MegaIng** [comment]
@antoniotejada Did you manage to parse C with lark now? Because that is certainly possible, although slightly painful because of the need to add a (Post-)Lexer hack. Did you manage to add that?

(IMO, the fact that more and more libraries are switching to just Python3 is reason enough to switch over. EOL was almost a year ago, and the point at which everyone said "Please switch over, it will only get harder to switch the more you wait" was like 10 years ago)

**Comment by antoniotejada** [comment]
> @antoniotejada Did you manage to parse C with lark now? Because that is certainly possible, although slightly painful because of the need to add a (Post-)Lexer hack. Did you manage to add that?

@MegaIng Sure, I expect to be able to parse C99 with Lark LALR and the lexer hack, since people have been doing that forever with yacc/bison, although I haven't done that yet.

For the time being I've been using Lark's standard lexer (which fails for suffixed ints due to Python's-not-returning-the-longest-alternative-regexp issue) and I'm upgrading it right now to my custom Python re-based lexer that does priority and longest string match, with Lark's LALR parser.

I wrote a DFA-based one too , but I need to clean it up and see if it's any faster than my re-hacked longest match priority lexer, https://github.com/antoniotejada/epycc/blob/master/grammar.py#L1132


Nevertheless the hope I had using Lark that was with Earley I would be able to take the full phrase and lexical grammar verbatim from the C99 spec, and get the ambiguous trees and don't need the lexer hack (or even a lexer, for that matter). Unfortunately that's not possible since I verified Lark's Earley doesn't return multiple trees for C99's typedef_name vs. identifier ambiguity.

Lark's Earley "context" lexer also fails in an interesting way and I had to switch the "standard" lexer, see this comment https://github.com/antoniotejada/epycc/blob/master/epycc.py#L2019

> (IMO, the fact that more and more libraries are switching to just Python3 is reason enough to switch over. EOL was almost a year ago, and the point at which everyone said "Please switch over, it will only get harder to switch the more you wait" was like 10 years ago)

I still have Windows XP on one of my machines ¯\_(ツ)_/¯


Wow, thanks a bunch for taking the time to create that gist! I do think I need a bit more due to the standard lexer not returning the longest match (I believe another option you support is to use regexp package instead of re, which I think it does allow it, but I'm having fun with my custom lexer).

**Comment by MegaIng** [comment]
> but I'm having fun with my custom lexer

That is reason enough.

Also note that you could alternatively add it as a requirement for the suffix to have the next character not be alphanumeric.

Also, you are the third person in the last few days to come across that issue. I think I am going to provide a PR.

(`return` as identifier for a call vs `return` as a statement is something that could also be fixed by priorities. Also, adding a negative  look ahead will certainly be faster than whatever else you can do in pure python, but might create large problems with the rest of lark.)

**Comment by antoniotejada** [comment]
> That is reason enough. Otherwise, you would probably be using pycparser

Spot on, I also wanted to generate the parser from the spec directly to make sure nothing was being missed.

> (return as identifier for a call vs return as a statement is something that could also be fixed by priorities. 

Interestingly the return as identifier only happens with Earley + context lexer (which doesn't support priorities, AFAIK), with the LALR parser the context lexer has no issues.

> Edit: The suffix problem is solvable by just moving the longest option first. Use INT_SIZE_SUFFIX: "ll" | "LL" |"l" | "L" instead.

@MegaIng Moving the longest first does indeed work! then I may go with your transformer idea.

**Comment by erezsh** [comment]
> not possible since I verified Lark's Earley doesn't return multiple trees for C99's typedef_name vs. identifier ambiguity.
> 
> Lark's Earley "context" lexer also fails in an interesting way and I had to switch the "standard" lexer, see this comment

Too bad you didn't open a bug! Perhaps we could fix it, or suggest a workaround.

That said, it's true the Earley implementation isn't perfect about returning every possible ambiguity. But you should be able to at least make it choose the right parse tree.

**Comment by antoniotejada** [comment]
> > not possible since I verified Lark's Earley doesn't return multiple trees for C99's typedef_name vs. identifier ambiguity.
> > Lark's Earley "context" lexer also fails in an interesting way and I had to switch the "standard" lexer, see this comment
> 
> Too bad you didn't open a bug! Perhaps we could fix it, or suggest a workaround.

Point taken :-), I just did a quick try and indeed I'm seeing both trees as it should, but I've simplified the grammar since
https://gist.github.com/antoniotejada/4148e9eff50b1f3ea18c5cb73c60dd63
I think back at the time the grammar had several ambiguities and it showed one of those but not the other or something.
 
> That said, it's true the Earley implementation isn't perfect about returning every possible ambiguity. But you should be able to at least make it choose the right parse tree.

For this ambiguity (typedef vs. identifier) I think the only solution is to get all the trees and choose after the fact, once you know if something is a typedef or not (see @MegaIng gist), so I don't think you can help it choose the right one before the fact.
