### ISSUE TITLE
`*.whl` is missing since release 0.11.2 on PyPI

### ISSUE THREAD

**Issue by michael-k** [lark-parser/lark#981]
There's only the `*.tar.gz` [available on PyPI](https://pypi.org/project/lark-parser/#files).  0.11.1 and before had both the `*.tar.gz` and the `*.whl` [available on PyPI](https://pypi.org/project/lark-parser/0.11.1/#files).

It would be nice if the `*.whl` could be uploaded to PyPI again.

**Comment by erezsh** [comment]
Sorry about that! Try now.

**Comment by michael-k** [comment]
(Still missing for >0.11.1,<0.12, but 0.12.0 is good enough for me :slightly_smiling_face:)
