### ISSUE TITLE
Accessing token string or tree.data transparently

### ISSUE THREAD

**Issue by antoniotejada** [lark-parser/lark#986]
It would be nice if there was a way so when traversing a tree you don't need to know if a child is a token or a tree in order to decide the alternative path to take, eg given the grammar rule

```lark
postfix_expression:  primary_expression
|  postfix_expression "[" expression "]"
|  "(" type_name ")" "{" initializer_list "}"
```
I have to do
```python
if (is_tree(node.children[0]) and (node.children[0].data == "postfix_expression"):
   <do treey stuff>
elif (is_token(node.children[0]) and (node.children[0].value == "(")):
   <do tokeny stuff>
```

Token already compares to string transparently without .value (ie. token.value == token), but it would be nice if tree can compare to string transparently too without .data, then the code would become
```python
if (node.children[0] == "postfix_expression"):
   treey stuff
elif (node.children[0] == "("):
   tokeny stuff
```
A slightly worse option is to add a .data field to token that contains the token string, so you can still handle trees and tokens transparently.

Let me know if there already exists a better way of doing this.

**Comment by erezsh** [comment]
@antoniotejada Is there a specific reason that you want the `(` token in your tree? In Lark we recommend to discard punctuation.

Also, you can do `tree_or_token == "my_token_value"`, and it will return true if it's `Token(SOME_TYPE, "my_token"value")` but False if it's a tree.

However, you should really need to. Maybe take a step back and try to describe what you're trying to solve.

**Comment by antoniotejada** [comment]
> @antoniotejada Is there a specific reason that you want the `(` token in your tree? In Lark we recommend to discard punctuation.

I'm not sure which tokens are punctuation for you and which are not, but in C '(' is definitely needed to tell grammar productions apart and generate one or another code, eg
```lark
postfix_expression:  primary_expression
  |  postfix_expression "[" expression "]"
  |  postfix_expression "(" argument_expression_list? ")"
```
the first is array selection, the second is function call. You could say that in this specific case you can tell the difference without hooking on [ and ( and looking if there's a next production and which one it is, but that just complicates the code unnecessarily, from checking a single token you change to having to check if there's a production following and which one it is, and without any tangible benefits that I can see.

Another example:
```lark
postfix_expression:  primary_expression
  |  postfix_expression "." identifier
  |  postfix_expression "->" identifier
```
Maybe you could claim that "." is punctuation and "->" is not, but that seems pretty arbitrary to me and again I can't see the benefits of removing one.

> Also, you can do `tree_or_token == "my_token_value"`, and it will return true if it's `Token(SOME_TYPE, "my_token"value")` but False if it's a tree.

Right, but the problem is that then you need to be very careful to defer any children[0].data checks (which are not valid if children[0] is a token) after you've done all the token checks, which is not maintainable.

> However, imho you shouldn't have to. Maybe take a step back and try to describe what you're trying to solve.

@erezsh The way I'm doing things right now is using Lark to generate the tree, and then traversing the tree manually:
```python
tree = parser.parse(source)
generate_ir(tree)
```
(you can see the full code here https://github.com/antoniotejada/epycc/blob/3467ab77be8eebdee36a83e74cf571f45bcfe07b/epycc.py#L2627 )

I could use Lark's Interpreter or Transformer approach, but at this moment I rather make the code generation independent from Lark as much as possible, so I'm using Lark as an "AST" producer and my code generator consumes the tree and generates code. If I ever switch to another non-Lark parser I just need to generate a tree with nodes that have .children and .value attributes, since that's everything I use from Lark.

In addition, and for the same reason, I want to modify the grammar as little as possible, so I don't want to put markers like "!" or "?" or such to tag which tokens to preserve and which tokens to remove.

**Comment by erezsh** [comment]
The Lark way of doing this is with aliases:

```lark
?postfix_expression:  primary_expression              // use ? to discard this option
  |  postfix_expression "[" expression "]"    -> array_get
  |  postfix_expression "(" argument_expression_list? ")"   -> func_call
```

Similarly,

```lark
?postfix_expression:  primary_expression  // discarded
  |  postfix_expression "." identifier    -> get_attr
  |  postfix_expression "->" identifier   -> get_ptr
```

In this case, both `.` and `->` are punctuation, and are unnecessary in the tree.

If you want to do it another way, you have every right to, and Lark won't stand in your way.

But it to me, it seems silly to not take advantage of Lark's full abilities, and then complain when the result is a little awkward.

**Comment by MegaIng** [comment]
If you really want to make the Tree nodes compare equal to string based on the data attribute, you can just defined your own custom subclass:

```
class TreeEqString(Tree):
    def __eq__(self, other):
       if isinstance(other, str):
            return self.data == other
        else:
            return super(TreeEqString, self).__eq__(self, other)

and then create the parser with

```

parser=Lark(..., tree_class=TreeEqStr)
```

However, I also agree with @erezsh that you should probably use Lark abilities (like aliases) instead.

**Comment by antoniotejada** [comment]
@MegaIng Thanks but if I have to fix it myself I rather monkey patch at import time.

```python
import lark
# Monkey patch lark trees so they can compare to strings, see 
# https://github.com/lark-parser/lark/issues/986
old_lark_tree_eq = lark.Tree.__eq__ 
lark.Tree.__eq__ = lambda self, other: (self.data == other) if isinstance(other, str) else old_lark_tree_eq(self, other)
```

Interestingly, because lark.Tree.__eq__ is currently silently swallowing the AttributeError, I found that I was already comparing against strings in a few places (but it was against token strings, not rule names, so it was ok).
