### ISSUE TITLE
Strange lexer behaviour

### ISSUE THREAD

**Issue by cbobed** [lark-parser/lark#988]
**Describe the bug**

I have found an incoherent behaviour in the lexer in a quite particular case. 
I'm writing a grammar to write a pseudo query language mixing words/tokens with AND, OR, quotes, and parenthesis. The main idea is that the AND and OR operators apply to just one token/quoted string, unless they are within a parenthesis expression, where we will expand the operands to all the tokens leftwise or rightwise. 
For example, 
A B AND C => the operands of AND would be "B" and "C"
while (A B AND C) => the operands of AND would be "A B"  and "C"

I've defined WORD as /\S*[^)]/ to avoid collisions with the ending parenthesis in case there is no space to define the token properly. Depending on whether I'm within a parenthesis or not and, if inside, whether there are one or more tokens, the regular expression is evaluated differently. 

**To Reproduce**

The grammar and behaviour: 

`from lark import Lark

parser = Lark(r"""

    start: expr+
    
    expr: expr OP_OR and_expr
        | and_expr
        
    and_expr: and_expr OP_AND operand
        | operand
        
    operand: WORD
        | QUOTED_EXPR
        | par_expr
        
    par_expr: PAR_OPEN broaden_expr PAR_CLOSE
    
    broaden_expr: broaden_expr OP_OR broaden_and_expr
        | broaden_and_expr 
    
    broaden_and_expr: broaden_and_expr OP_AND broaden_operand
        | broaden_operand
        
    broaden_operand: WORD+       
        | QUOTED_EXPR
        | par_expr
    
    OP_OR.10: "OR"
    OP_AND.10: "AND"
    OP_QUOTES.10: "\""
    PAR_OPEN.10: "("
    PAR_CLOSE.10: ")"
    QUOTED_EXPR.10: /\".*?\"/                           // to make the regular expression greedy
    WORD: /\S*[^)]/             
    
    %import common.WS                                   // imports from terminal library
    %ignore WS
    """, parser="lalr")`

Then, with the following inputs: 
query='(operand AND whatever)' :: OK 
query='(operand AND whatever dfa)' :: OK 
query='(operand AND whatever dfa )' :: OK 
query='(operand) AND (whatever)' :: *NOK* => parses operand) and whatever) as the tokens
query='(operand ) AND (whatever )' :: OK => distinguishes the ) token
query='(operand) AND (whatever dfa)' :: *NOK* => parses operand) as token
query='(operand ) AND (whatever dfa) :: OK => dfa and ) are parsed as different tokens

It seems that the + applied to WORD in broaden_operand affects the way the regex used for defining words is evaluated.

BTW, for my purposes I've solved it by changing the regex to directly /[^)\s]/+ but I thought that the behaviour should be notified to see whether it was the way the regex evaluation should work.

**Comment by erezsh** [comment]
Your definition of WORD is simply incorrect, because it allows `)` -

do `re.match('\S', ')')`, and see that it matches.

**Comment by erezsh** [comment]
If you want alphanumeric characters, you should use `[^\W]` instead. `\S` will include a lot of bug-worthy characters.

**Comment by cbobed** [comment]
Please, re-read my definition: 
\S*[^)] => kleene-star of anything but spaces (0 or more), ending with any character that is not an ')'

re.match('\S*[^)]','(exp)') => matches '(exp', given that I have also the priorities set so '(' has more priority, should parse '(', then 'exp', and finally ')'

**Comment by cbobed** [comment]
> If you want alphanumeric characters, you should use `[^\W]` instead. `\S` will include a lot of bug-worthy characters.

I'm afraid that I'm using \S on purpose as I precisely would like to include any character but the spaces ... and [^\W] woudl give me anything but the alphanumeric ones, though

**Comment by erezsh** [comment]
Well, it's still incorrect.

```python
>>> re.match('\S*[^)]', 'whatever)')
<re.Match object; span=(0, 8), match='whatever'>
>>> re.match('\S*[^)]', 'whatever) ')
<re.Match object; span=(0, 10), match='whatever) '>
```

**Comment by cbobed** [comment]
No, because I've stated the pragma ignore WS ... I was reporting the strange behavior of the lexer int his particular scenario, but I'm sorry if I've offended anyone, I close the bug.

**Comment by erezsh** [comment]
Yes, I understand what you're reporting. Do you understand why I think you're wrong?

Okay, maybe try to create a much smaller example, that demonstrates a bug in your eyes.

**Comment by erezsh** [comment]
I'll explain more clearly: Because `\S*[^)]` can match `foo) `, that's what the lexer returns. That makes it skip the `)` symbol for other options, by design. If you used a terminal that *doesn't* allow `foo)`, it would work.

**Comment by erezsh** [comment]
Maybe even `\S*[^)\s]` might be good enough.

**Comment by cbobed** [comment]
Yes, I completely understand why do you think I'm wrong. However, I'm not reporting a problem with the regex, but with the different behaviour that lark in this situation has: it's exactly the same regex, which depending where it does appear, detects one thing or another. Note that I don't actually care that there is an intermediate ')' in a consecutive stream of chars, that's why I've focused on anything but ')'. 

More detailed examples (same grammar applies): 

'people in the Internet' is correctly parsed as **different tokens** due to the previous tokenizing (ignore WS): people, in, the, Internet

'people in the (Internet)' is correctly parsed as people, in, the, (, Internet, )

'(Internet)' => (, Internet, )

(Internet) AND (WWW) => NOK, broken 
(Internet ) AND (WWW) => (, Internet, ), AND, (, WWW, )

all of this with the same regex. As I've mentioned above, I've changed my regex and I've made my grammar work, **but** I thought that this difference in the behaviour of **lark** depending on where the regex was applied was not consistent. 

I'm open to share more exampes.

**Comment by cbobed** [comment]
> I'll explain more clearly: Because `\S*[^)]` can match `foo) `, that's what the lexer returns. That makes it skip the `)` symbol for other options, by design. If you used a terminal that _doesn't_ allow `foo) `, it would work.

Take a look on the other examples ... I'm aware of what you are saying, but I'm completely ignoring the white spaces, and that's the behaviour I'm witnessing with the rest of the tokens. But such behaviour changes under this particular condition, that's why I considered it a bug (it doesn't happen with other parsers). That said, I was trying to contribute, I wasn't aware of the possible toxicity. 

Best,

**Comment by cbobed** [comment]
> Maybe even `\S*[^)\s]` might be good enough.

Please, take a look at the bug report :: BTW paragraph

**Comment by erezsh** [comment]
Okay, I think I understand your point now. You're probably experiencing the effects of the contextual lexer, which only matches a subset of the terminals that is expected by the grammar at that point.

Perhaps if you init Lark as `Lark(..., parser='lalr', lexer='standard')`, you will get the behavior that you expect.

**Comment by cbobed** [comment]
I've tested the last examples with both lexers and I'm afraid it doesn't tokenize it properly. I'll take a look at the inner details of the contextualized lexer though, I'd like to know how the lexicalization is narrowed. 

That's what I was finding strange, you were right about the regex at low level, but once you have got rid of all the spaces and witnessing the different behaviour (sometimes it split the string perfectly xxx) => xxx and ), sometimes not ...) was the bug I was reporting. Fortunately, my code was solved with the change of regex (quite similar to what you proposed, in fact). Thx !! :)

**Comment by MegaIng** [comment]
@cbobed What @erezsh was trying to tell you was that `%ignore WS` does not do what you expected it to do. It does not actually prevent all other terminals from matching a WS, but tells the lexer to always try to parse `WS` last and if that is the only thing that matches to skip to the end of the Terminal. This means that `"(operand) AND (whatever)"` gets tokenized as:

```
Token('PAR_OPEN', '(')
Token('WORD', 'operand) ')
Token('OP_AND', 'AND')
Token('WS', ' ')
Token('PAR_OPEN', '(')
Token('WORD', 'whatever')
Token('PAR_CLOSE', ')')
```

Notice how the first `WORD` token contains the `') '`. This is because that is the longest possible match that single regex allows. It does not take into account that the last character would also match the ignored `WS` token. This is by design. (Otherwise it would be impossible to parse strings correctly for example)

**Comment by cbobed** [comment]
@MegaIng Thanks for the comment. 

That's what I found very confusing. When I stated explicitly to ignore the WS, I was expecting the lexer to do some kind of two passes: first strip out all the WS to actually ignore them, and then apply the regex to the resulting string parts (we would not have "tokens" yet) to detect the language tokens appropriately. 

What I don't follow is your comment "Otherwise it would be impossible to ...", the lexer could get rid of the \s chars (you can innerly modified the automaton to do so, or process the input in two stages) and afterwards could pass the regexes automaton on each string part. Why would it be impossible to parse? I mean, of course, it would modify the meaning of the written regex, but the user has explicitly stated to ignore/get rid of all WSs in the input. 

I ack that it's the expected behaviour, so this issue wouldn't be labelled as a bug, but as a suggestion (IDK whether to include this behaviour in the lexer or to clarify the %ignore WS behaviour in the documentation). 

Thank you very much for the insights

**Comment by erezsh** [comment]
@cbobed You're welcome to write a paragraph to your past self, explaining whatever information you think is missing from the documentation.

**Comment by cbobed** [comment]
Sure, I think (especially for people that had previous experience with other parser tools) that this would help in order to specify where the %ignore directive applies (bear in mind that in lark there is not so much separation between the lexer and the grammar parser as rules and terminal definitions are not so isolated from one each other as in other parsing tools). 

Thank you! 

----------------------------
%ignore

All occurrences of the terminal will be ignored, and won't be part of the parse. **Note that %ignore affects complete tokens at grammar parsing, not affecting the way your regexps will be matched (e.g., ignoring WS - short for White Spaces - would not prevent the lexer to consider them to tokenize the input). **

Using the %ignore directive results in a cleaner grammar.

It's especially important for the LALR(1) algorithm, because adding whitespace (or comments, or other extranous elements) explicitly in the grammar, harms its predictive abilities, which are based on a lookahead of 1.

Syntax:

%ignore <TERMINAL>
------------------------------

**Comment by MegaIng** [comment]
> What I don't follow is your comment "Otherwise it would be impossible to ...", 

If you have a Python style string you want to keep the Whitespace. You don't actually want to ignore all Whitespace in the following example:

```
def hello () :
    print ( "Hello World" )
```

While lots of those WS are to be ignored, not all (especially the intend and the space between Hello and World) are to be thrown away and are supposed to go into some kind of Token.

**Comment by cbobed** [comment]
Yeah, I see ... I was thinking about the actual meaning/implication of "ignoring the whitespaces" at tokenizing time, which in this case would limit (I was assuming implicitly this loss of expressivity if %ignore WS was working at char level, but now the behaviour of the directive in lark is clearer to me - it's ignore at grammar level). 

Thank you @MegaIng !
